# Import libraries

In [1]:
import os
import glob
import json
import time
import gc
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report

import lightgbm as lgb
import optuna

print("LightGBM version:", lgb.__version__)
print("Optuna version:", optuna.__version__)

LightGBM version: 4.6.0
Optuna version: 4.8.0

# Config

In [2]:
RANDOM_STATE = 42
INPUT_ROOT = "/opt/spark/workspace/input/data"
OUTPUT_DIR = "/opt/spark/workspace/output/lgbm_experiment"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# PICKUP_COL = "tpep_pickup_datetime"
# DROPOFF_COL = "tpep_dropoff_datetime"

TARGET_PROCESSING_DATE_HOUR = pd.Timestamp("2025-01-15 12:00:00")
PREVIOUS_BATCH_OFFSET = pd.Timedelta(hours=12)

HISTORY_OFFSETS = [
    pd.Timedelta(days=1),
    pd.Timedelta(days=7),
    pd.Timedelta(days=14),
]

# Sampling
MIN_ROWS_PER_GROUP = 100
TARGET_SAMPLE_PER_GROUP = 10_000

# Nếu True: mỗi processing_date_hour trong nhóm label = 0 lấy tối đa TARGET_SAMPLE_PER_GROUP dòng
# Nếu False: lấy toàn bộ rồi sample tổng
SAMPLE_EACH_COMPARISON_BATCH = True

# Train / valid / test split
TEST_SIZE = 0.15
VALID_SIZE = 0.15
VALID_SIZE_FROM_TRAIN = VALID_SIZE / (1 - TEST_SIZE)

# Optuna tuning
N_TRIALS = 100

# LightGBM
N_ESTIMATORS_MAX = 2000
EARLY_STOPPING_ROUNDS = 100

# Data Loading

In [3]:
parquet_files = glob.glob(f"{INPUT_ROOT}/**/*.parquet", recursive=True)
print("Found parquet files:")
for f in parquet_files:
    print(f)

Found parquet files:
/opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet

In [4]:
DATA_PATH = "/opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet"
print("Using:", DATA_PATH)

Using: /opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet

In [5]:
df_raw = pd.read_parquet(DATA_PATH)
print(df_raw.shape)
display(df_raw.head())
print(df_raw.dtypes)

(3326978, 22)

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,cbd_congestion_fee,date_hour,processing_date_hour
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,...,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,...,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,...,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0,2025-01-01 01:00:00,2025-01-01 12:00:00
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,...,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,...,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00

vendorid                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
ratecodeid                      float64
store_and_fwd_flag       string[python]
pulocationid                      int32
dolocationid                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
cbd_congestion_fee              float64
date_hour                datetime64[us]
processing_date_hour     datetime64[us]
dtype: object

# Data Pre-processing

In [8]:
print("Min tpep_pickup_datetime:", df_raw["tpep_pickup_datetime"].min())
print("Max tpep_pickup_datetime:", df_raw["tpep_pickup_datetime"].max())
print("Min tpep_dropoff_datetime :", df_raw["tpep_dropoff_datetime"].min())
print("Max tpep_dropoff_datetime :", df_raw["tpep_dropoff_datetime"].max())

Min tpep_pickup_datetime: 2024-12-31 23:25:38
Max tpep_pickup_datetime: 2025-01-31 23:44:00
Min tpep_dropoff_datetime : 2024-12-31 23:55:13
Max tpep_dropoff_datetime : 2025-01-31 23:44:59

In [7]:
print("After datetime parsing:", df_raw.shape)
print("Min date_hour :", df_raw["date_hour"].min())
print("Max date_hour :", df_raw["date_hour"].max())
print("Min processing_date_hour:", df_raw["processing_date_hour"].min())
print("Max processing_date_hour:", df_raw["processing_date_hour"].max())

After datetime parsing: (3326978, 22)
Min date_hour : 2025-01-01 00:00:00
Max date_hour : 2025-01-31 23:00:00
Min processing_date_hour: 2025-01-01 12:00:00
Max processing_date_hour: 2025-02-01 00:00:00

In [9]:
print(df_raw.shape)
display(df_raw.head())
print(df_raw.dtypes)

(3326978, 22)

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,cbd_congestion_fee,date_hour,processing_date_hour
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,...,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,...,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,...,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0,2025-01-01 01:00:00,2025-01-01 12:00:00
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,...,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,...,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0,2025-01-01 00:00:00,2025-01-01 12:00:00

vendorid                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
ratecodeid                      float64
store_and_fwd_flag       string[python]
pulocationid                      int32
dolocationid                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
cbd_congestion_fee              float64
date_hour                datetime64[us]
processing_date_hour     datetime64[us]
dtype: object

In [10]:
processing_counts = (
    df_raw
    .groupby("processing_date_hour", as_index=False)
    .size()
    .rename(columns={"size": "row_count"})
    .sort_values("processing_date_hour")
    .reset_index(drop=True)
)

display(processing_counts.head())
display(processing_counts.tail())

  processing_date_hour  row_count
0  2025-01-01 12:00:00      36464
1  2025-01-02 00:00:00      45227
2  2025-01-02 12:00:00      19740
3  2025-01-03 00:00:00      61896
4  2025-01-03 12:00:00      21563

   processing_date_hour  row_count
57  2025-01-30 00:00:00      87625
58  2025-01-30 12:00:00      32929
59  2025-01-31 00:00:00      94242
60  2025-01-31 12:00:00      31944
61  2025-02-01 00:00:00      93156

In [11]:
target_processing_hour = pd.to_datetime(TARGET_PROCESSING_DATE_HOUR)
comparison_processing_hours = []
comparison_processing_hours.append(
    target_processing_hour - PREVIOUS_BATCH_OFFSET
)

comparison_processing_hours.extend([
    target_processing_hour - offset
    for offset in HISTORY_OFFSETS
])

target_count = int(
    (df_raw["processing_date_hour"] == target_processing_hour).sum()
)

print("Target processing hour, label = 1:")
print("-", target_processing_hour, "| rows:", target_count)

print("\nComparison processing hours, label = 0:")
for h in comparison_processing_hours:
    cnt = int((df_raw["processing_date_hour"] == h).sum())
    print("-", h, "| rows:", cnt)

Target processing hour, label = 1:
- 2025-01-15 12:00:00 | rows: 32738

Comparison processing hours, label = 0:
- 2025-01-15 00:00:00 | rows: 86467
- 2025-01-14 12:00:00 | rows: 30435
- 2025-01-08 12:00:00 | rows: 28758
- 2025-01-01 12:00:00 | rows: 36464

In [12]:
def sample_by_processing_hour(
    source_df,
    processing_hour,
    label,
    max_rows,
    random_state
):
    part = source_df[source_df["processing_date_hour"] == processing_hour].copy()

    if len(part) == 0:
        return part

    if len(part) > max_rows:
        part = part.sample(max_rows, random_state=random_state)

    part["label"] = label

    return part

In [13]:
positive_df = sample_by_processing_hour(
    source_df=df_raw,
    processing_hour=target_processing_hour,
    label=1,
    max_rows=TARGET_SAMPLE_PER_GROUP,
    random_state=RANDOM_STATE
)

print("Positive sample:")
print("Processing hour:", target_processing_hour)
print("Rows:", len(positive_df))

display(
    positive_df[[
        "date_hour",
        "processing_date_hour",
        "label"
    ]].head()
)

if len(positive_df) < MIN_ROWS_PER_GROUP:
    raise ValueError(
        f"Positive sample quá ít: {len(positive_df)} rows. "
        f"Cần tối thiểu {MIN_ROWS_PER_GROUP} rows."
    )

Positive sample:
Processing hour: 2025-01-15 12:00:00
Rows: 10000

                  date_hour processing_date_hour  label
1248923 2025-01-15 10:00:00  2025-01-15 12:00:00      1
1253056 2025-01-15 09:00:00  2025-01-15 12:00:00      1
1239600 2025-01-15 06:00:00  2025-01-15 12:00:00      1
1236295 2025-01-15 00:00:00  2025-01-15 12:00:00      1
1234755 2025-01-15 00:00:00  2025-01-15 12:00:00      1

In [14]:
negative_parts = []

for i, compare_hour in enumerate(comparison_processing_hours):
    part = sample_by_processing_hour(
        source_df=df_raw,
        processing_hour=compare_hour,
        label=0,
        max_rows=TARGET_SAMPLE_PER_GROUP,
        random_state=RANDOM_STATE + i + 100
    )

    print("Comparison hour:", compare_hour, "| rows:", len(part))

    if len(part) >= MIN_ROWS_PER_GROUP:
        negative_parts.append(part)
    else:
        print("Skipped because rows < MIN_ROWS_PER_GROUP")

if len(negative_parts) == 0:
    raise ValueError("Không có đủ dữ liệu đã có để tạo label = 0.")

negative_df = pd.concat(negative_parts, axis=0)

print("\nNegative sample total rows:", len(negative_df))

display(
    negative_df.groupby("processing_date_hour")
    .size()
    .reset_index(name="row_count")
    .sort_values("processing_date_hour")
)

Comparison hour: 2025-01-15 00:00:00 | rows: 10000
Comparison hour: 2025-01-14 12:00:00 | rows: 10000
Comparison hour: 2025-01-08 12:00:00 | rows: 10000
Comparison hour: 2025-01-01 12:00:00 | rows: 10000

Negative sample total rows: 40000

  processing_date_hour  row_count
0  2025-01-01 12:00:00      10000
1  2025-01-08 12:00:00      10000
2  2025-01-14 12:00:00      10000
3  2025-01-15 00:00:00      10000

In [15]:
work_df = pd.concat([positive_df, negative_df], axis=0)
work_df = work_df.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)

print("Work dataset shape:", work_df.shape)

print("\nLabel count:")
print(work_df["label"].value_counts())

print("\nLabel ratio:")
print(work_df["label"].value_counts(normalize=True))

print("\nRows by label and source_processing_date_hour:")
display(
    work_df.groupby(["label", "processing_date_hour"])
    .size()
    .reset_index(name="row_count")
    .sort_values(["label", "processing_date_hour"])
)

Work dataset shape: (50000, 23)

Label count:
label
0    40000
1    10000
Name: count, dtype: int64

Label ratio:
label
0    0.8
1    0.2
Name: proportion, dtype: float64

Rows by label and source_processing_date_hour:

   label processing_date_hour  row_count
0      0  2025-01-01 12:00:00      10000
1      0  2025-01-08 12:00:00      10000
2      0  2025-01-14 12:00:00      10000
3      0  2025-01-15 00:00:00      10000
4      1  2025-01-15 12:00:00      10000

In [16]:
work_df.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,...,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,cbd_congestion_fee,date_hour,processing_date_hour,label
0,1,2025-01-08 08:43:22,2025-01-08 09:00:22,NaN,1.90,99.0,<NA>,158,100,0,...,0.00,0.0,1.0,23.01,NaN,NaN,0.75,2025-01-08 09:00:00,2025-01-08 12:00:00,0
1,2,2025-01-15 08:48:11,2025-01-15 08:59:42,1.0,2.01,1.0,N,144,234,1,...,3.51,0.0,1.0,21.06,2.5,0.0,0.75,2025-01-15 09:00:00,2025-01-15 12:00:00,1
2,2,2025-01-15 09:12:03,2025-01-15 09:32:43,6.0,2.52,1.0,N,107,161,1,...,4.77,0.0,1.0,28.62,2.5,0.0,0.75,2025-01-15 09:00:00,2025-01-15 12:00:00,1
3,2,2025-01-14 15:06:00,2025-01-14 15:18:00,NaN,4.63,99.0,<NA>,78,208,0,...,0.00,0.0,1.0,19.64,NaN,NaN,0.00,2025-01-14 15:00:00,2025-01-15 00:00:00,0
4,2,2025-01-08 09:22:58,2025-01-08 09:42:08,1.0,1.96,1.0,N,90,163,1,...,4.49,0.0,1.0,26.94,2.5,0.0,0.75,2025-01-08 09:00:00,2025-01-08 12:00:00,0

In [17]:
EXCLUDE_COLS = [
    "label",
    "date_hour",
    "processing_date_hour",
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
]

print("Columns to drop from model:")
for c in EXCLUDE_COLS:
    if c in work_df.columns:
        print("-", c)

Columns to drop from model:
- label
- date_hour
- processing_date_hour
- tpep_pickup_datetime
- tpep_dropoff_datetime

In [18]:
CATEGORICAL_COLS = [
    "VendorID",
    "RatecodeID",
    "store_and_fwd_flag",
    "PULocationID",
    "DOLocationID",
    "payment_type",
]

NUMERIC_COLS = [
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "Airport_fee",
    "cbd_congestion_fee",
]

CATEGORICAL_COLS = [c for c in CATEGORICAL_COLS if c in work_df.columns]
NUMERIC_COLS = [c for c in NUMERIC_COLS if c in work_df.columns]

print("Categorical columns:", CATEGORICAL_COLS)
print("Numeric columns:", NUMERIC_COLS)

Categorical columns: ['store_and_fwd_flag', 'payment_type']
Numeric columns: ['passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'cbd_congestion_fee']

## Encoding

In [19]:
class TaxiFeatureEncoder:
    def __init__(self, categorical_cols, numeric_cols, exclude_cols):
        self.categorical_cols = list(categorical_cols)
        self.numeric_cols = list(numeric_cols)
        self.exclude_cols = set(exclude_cols)

        self.category_maps_ = {}
        self.numeric_output_cols_ = []
        self.output_cols_ = []

    def _remove_excluded_columns(self, input_df):
        data = input_df.copy()

        cols_to_drop = [
            col for col in self.exclude_cols
            if col in data.columns
        ]

        if cols_to_drop:
            data = data.drop(columns=cols_to_drop)

        return data

    def fit(self, input_df):
        data = self._remove_excluded_columns(input_df)

        # Numeric: giữ các numeric_cols có trong data
        self.numeric_output_cols_ = [
            col for col in self.numeric_cols
            if col in data.columns
        ]

        self.category_maps_ = {}

        for col in self.categorical_cols:
            if col in data.columns:
                values = data[col].astype("string")

                # Chỉ lấy category từ giá trị không null
                categories = sorted(
                    values.dropna().unique().tolist()
                )

                self.category_maps_[col] = categories

        transformed = self.transform(input_df)
        self.output_cols_ = transformed.columns.tolist()

        return self

    def transform(self, input_df):
        data = self._remove_excluded_columns(input_df)
        out = pd.DataFrame(index=data.index)

        # Numeric: giữ NaN, không fill, không tạo __isnull
        for col in self.numeric_output_cols_:
            if col in data.columns:
                out[col] = pd.to_numeric(data[col], errors="coerce")

        # Categorical: giữ null là missing, không fill "__MISSING__"
        for col, categories in self.category_maps_.items():
            if col in data.columns:
                values = data[col].astype("string")

                out[col] = pd.Categorical(
                    values,
                    categories=categories
                )

        # Replace inf thành NaN để LightGBM xử lý
        out = out.replace([np.inf, -np.inf], np.nan)

        # Đảm bảo thứ tự cột giống lúc fit
        if self.output_cols_:
            for col in self.output_cols_:
                if col not in out.columns:
                    if col in self.category_maps_:
                        out[col] = pd.Categorical(
                            [pd.NA] * len(out),
                            categories=self.category_maps_[col]
                        )
                    else:
                        out[col] = np.nan

            out = out[self.output_cols_]

        return out

In [20]:
y = work_df["label"].astype(int)
X_raw = work_df.drop(columns=["label"], errors="ignore")
n_total = len(work_df)
n_test = int(round(TEST_SIZE * n_total))
n_valid = int(round(VALID_SIZE * n_total))

X_train_valid_raw, X_test_raw, y_train_valid, y_test = train_test_split(
    X_raw,
    y,
    test_size=n_test,
    random_state=RANDOM_STATE,
    stratify=y
)

X_train_raw, X_valid_raw, y_train, y_valid = train_test_split(
    X_train_valid_raw,
    y_train_valid,
    test_size=n_valid,
    random_state=RANDOM_STATE,
    stratify=y_train_valid
)

print("Train raw:", X_train_raw.shape, "| positive rate:", y_train.mean())
print("Valid raw:", X_valid_raw.shape, "| positive rate:", y_valid.mean())
print("Test raw :", X_test_raw.shape, "| positive rate:", y_test.mean())

Train raw: (35000, 22) | positive rate: 0.2
Valid raw: (7500, 22) | positive rate: 0.2
Test raw : (7500, 22) | positive rate: 0.2

In [21]:
encoder = TaxiFeatureEncoder(
    categorical_cols=CATEGORICAL_COLS,
    numeric_cols=NUMERIC_COLS,
    exclude_cols=EXCLUDE_COLS
)

encoder.fit(X_train_raw)

X_train = encoder.transform(X_train_raw)
X_valid = encoder.transform(X_valid_raw)
X_test = encoder.transform(X_test_raw)

print("X_train:", X_train.shape)
print("X_valid:", X_valid.shape)
print("X_test :", X_test.shape)

print("Feature columns:")
print(X_train.columns.tolist())

X_train: (35000, 13)
X_valid: (7500, 13)
X_test : (7500, 13)
Feature columns:
['passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'cbd_congestion_fee', 'store_and_fwd_flag', 'payment_type']

In [22]:
missing_summary = (
    X_train
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(missing_summary[missing_summary > 0])

passenger_count         5459
congestion_surcharge    5459
store_and_fwd_flag      5459
dtype: int64

In [23]:
baseline_params = {
    "objective": "binary",
    "metric": "auc",
    "boosting_type": "gbdt",

    # Số cây tối đa, early stopping sẽ tự chọn best_iteration
    "n_estimators": N_ESTIMATORS_MAX,

    # Baseline core params
    "learning_rate": 0.05,
    "num_leaves": 31,
    "max_depth": -1,
    "min_child_samples": 20,

    # Baseline không dùng subsampling
    "subsample": 1.0,
    "subsample_freq": 0,
    "colsample_bytree": 1.0,

    # Regularization gần như tắt
    "reg_alpha": 1e-8,
    "reg_lambda": 1e-8,
    "min_split_gain": 0.0,

    # Binning mặc định
    "max_bin": 255,

    # Native missing handling
    "use_missing": True,
    "zero_as_missing": False,

    # Reproducibility / resource
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
    "verbosity": -1,
}

baseline_model = lgb.LGBMClassifier(**baseline_params)

baseline_model.fit(
    X_train,
    y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric="auc",
    callbacks=[
        lgb.early_stopping(
            stopping_rounds=EARLY_STOPPING_ROUNDS,
            verbose=True
        ),
        lgb.log_evaluation(period=50)
    ]
)

baseline_valid_pred = baseline_model.predict_proba(X_valid)[:, 1]
baseline_test_pred = baseline_model.predict_proba(X_test)[:, 1]

baseline_valid_auc = roc_auc_score(y_valid, baseline_valid_pred)
baseline_test_auc = roc_auc_score(y_test, baseline_test_pred)

print("Baseline valid AUC:", baseline_valid_auc)
print("Baseline test AUC :", baseline_test_auc)
print("Baseline best iteration:", baseline_model.best_iteration_)

Training until validation scores don't improve for 100 rounds
[50]	valid_0's auc: 0.690735
[100]	valid_0's auc: 0.690314
Early stopping, best iteration is:
[30]	valid_0's auc: 0.69221
Baseline valid AUC: 0.6922103888888889
Baseline test AUC : 0.6830474444444445
Baseline best iteration: 30

In [24]:
def suggest_lgbm_params(trial):
    # LightGBM leaf-wise tree:
    # Nếu max_depth được set, nên giữ num_leaves <= 2^max_depth
    max_depth = trial.suggest_categorical(
        "max_depth",
        [-1, 4, 5, 6, 7, 8, 10, 12]
    )

    if max_depth == -1:
        num_leaves_upper = 256
    else:
        num_leaves_upper = min(256, 2 ** max_depth)

    params = {
        "objective": "binary",
        "metric": "auc",
        "boosting_type": "gbdt",
        "verbosity": -1,
        "random_state": RANDOM_STATE,
        "n_jobs": -1,

        # Native missing handling
        "use_missing": True,
        "zero_as_missing": False,

        # 1. Learning speed
        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.15,
            log=True
        ),

        # 2. Tree complexity
        "num_leaves": trial.suggest_int(
            "num_leaves",
            16,
            num_leaves_upper
        ),

        "max_depth": max_depth,

        # 3. Prevent overfitting in leaf-wise trees
        # LightGBM default = 20, nên search bắt đầu từ 10 để không loại baseline
        "min_child_samples": trial.suggest_int(
            "min_child_samples",
            10,
            1000,
            log=True
        ),

        # 4. Row bagging
        # subsample only works when subsample_freq > 0
        "subsample": trial.suggest_float(
            "subsample",
            0.7,
            1.0
        ),

        "subsample_freq": trial.suggest_int(
            "subsample_freq",
            0,
            10
        ),

        # 5. Feature sampling
        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.7,
            1.0
        ),

        # 6. Regularization
        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-8,
            10.0,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            1e-8,
            10.0,
            log=True
        ),

        # 7. Split control
        "min_split_gain": trial.suggest_float(
            "min_split_gain",
            0.0,
            1.0
        ),

        # 8. Histogram binning
        "max_bin": trial.suggest_categorical(
            "max_bin",
            [63, 127, 255]
        ),
    }

    return params

In [25]:
def objective(trial):
    params = suggest_lgbm_params(trial)

    model = lgb.LGBMClassifier(
        **params,
        n_estimators=N_ESTIMATORS_MAX
    )

    start_time = time.time()

    model.fit(
        X_train,
        y_train,
        eval_set=[(X_valid, y_valid)],
        eval_metric="auc",
        callbacks=[
            lgb.early_stopping(
                stopping_rounds=EARLY_STOPPING_ROUNDS,
                verbose=False
            )
        ]
    )

    valid_pred = model.predict_proba(X_valid)[:, 1]
    valid_auc = roc_auc_score(y_valid, valid_pred)

    elapsed = time.time() - start_time

    trial.set_user_attr("valid_auc", float(valid_auc))
    trial.set_user_attr("best_iteration", int(model.best_iteration_))
    trial.set_user_attr("elapsed_seconds", float(elapsed))

    return valid_auc

In [26]:
sampler = optuna.samplers.TPESampler(
    seed=RANDOM_STATE,
    n_startup_trials=10
)

pruner = optuna.pruners.MedianPruner(
    n_startup_trials=5,
    n_warmup_steps=50,
    interval_steps=10
)

study = optuna.create_study(
    direction="maximize",
    sampler=sampler,
    pruner=pruner
)

print("Optuna study created.")

[I 2026-05-03 22:50:27,956] A new study created in memory with name: no-name-3e869c8c-cb9f-4762-bfa5-98617bafd97d

Optuna study created.

In [27]:
study.enqueue_trial({
    "learning_rate": 0.05,
    "num_leaves": 31,
    "max_depth": -1,
    "min_child_samples": 20,
    "subsample": 1.0,
    "subsample_freq": 0,
    "colsample_bytree": 1.0,
    "reg_alpha": 1e-8,
    "reg_lambda": 1e-8,
    "min_split_gain": 0.0,
    "max_bin": 255,
})

study.optimize(
    objective,
    n_trials=N_TRIALS,
    show_progress_bar=True
)

print("Best validation AUC:", study.best_value)
print("Best params:")
print(study.best_params)

Best trial: 0. Best value: 0.69221:   1%|          | 1/100 [00:00<00:50,  1.98it/s]

[I 2026-05-03 22:50:30,605] Trial 0 finished with value: 0.6922103888888889 and parameters: {'max_depth': -1, 'learning_rate': 0.05, 'num_leaves': 31, 'min_child_samples': 20, 'subsample': 1.0, 'subsample_freq': 0, 'colsample_bytree': 1.0, 'reg_alpha': 1e-08, 'reg_lambda': 1e-08, 'min_split_gain': 0.0, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   2%|▏         | 2/100 [00:00<00:46,  2.12it/s]

[I 2026-05-03 22:50:31,055] Trial 1 finished with value: 0.6852301666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.05092911283433821, 'num_leaves': 16, 'min_child_samples': 257, 'subsample': 0.7061753482887407, 'subsample_freq': 10, 'colsample_bytree': 0.9497327922401265, 'reg_alpha': 8.148018307012941e-07, 'reg_lambda': 4.329370014459266e-07, 'min_split_gain': 0.18340450985343382, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   3%|▎         | 3/100 [00:01<01:09,  1.39it/s]

[I 2026-05-03 22:50:32,070] Trial 2 finished with value: 0.6885951111111113 and parameters: {'max_depth': 10, 'learning_rate': 0.04025192252635066, 'num_leaves': 158, 'min_child_samples': 12, 'subsample': 0.8822634555704315, 'subsample_freq': 1, 'colsample_bytree': 0.7195154778955838, 'reg_alpha': 3.4671276804481113, 'reg_lambda': 4.905556676028774, 'min_split_gain': 0.8083973481164611, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   4%|▍         | 4/100 [00:02<01:01,  1.57it/s]

[I 2026-05-03 22:50:32,584] Trial 3 finished with value: 0.6904389444444443 and parameters: {'max_depth': 7, 'learning_rate': 0.04089285700048085, 'num_leaves': 77, 'min_child_samples': 22, 'subsample': 0.9908753883293675, 'subsample_freq': 8, 'colsample_bytree': 0.9818496824692567, 'reg_alpha': 1.1309571585271483, 'reg_lambda': 0.002404915432737351, 'min_split_gain': 0.9218742350231168, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   5%|▌         | 5/100 [00:06<03:02,  1.92s/it]

[I 2026-05-03 22:50:36,778] Trial 4 finished with value: 0.6835213888888889 and parameters: {'max_depth': 6, 'learning_rate': 0.08779238696445962, 'num_leaves': 19, 'min_child_samples': 941, 'subsample': 0.9316734307889972, 'subsample_freq': 2, 'colsample_bytree': 0.7016566351370807, 'reg_alpha': 0.2183498289760726, 'reg_lambda': 0.022999378190815954, 'min_split_gain': 0.7290071680409873, 'max_bin': 63}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   6%|▌         | 6/100 [00:07<02:19,  1.48s/it]

[I 2026-05-03 22:50:37,399] Trial 5 finished with value: 0.6859893888888889 and parameters: {'max_depth': 4, 'learning_rate': 0.05621157696543969, 'num_leaves': 16, 'min_child_samples': 592, 'subsample': 0.8416644775485848, 'subsample_freq': 1, 'colsample_bytree': 0.9139734361668985, 'reg_alpha': 0.0703178263660987, 'reg_lambda': 0.0011258869313624912, 'min_split_gain': 0.770967179954561, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   7%|▋         | 7/100 [00:08<02:09,  1.39s/it]

[I 2026-05-03 22:50:38,604] Trial 6 finished with value: 0.6893807222222224 and parameters: {'max_depth': 10, 'learning_rate': 0.030384197380564082, 'num_leaves': 198, 'min_child_samples': 28, 'subsample': 0.7230939729486379, 'subsample_freq': 3, 'colsample_bytree': 0.7483663861762013, 'reg_alpha': 2.3295866619309256, 'reg_lambda': 0.18753546777666233, 'min_split_gain': 0.6334037565104235, 'max_bin': 63}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   8%|▊         | 8/100 [00:09<01:42,  1.11s/it]

[I 2026-05-03 22:50:39,114] Trial 7 finished with value: 0.6883662222222222 and parameters: {'max_depth': 6, 'learning_rate': 0.0916347113121937, 'num_leaves': 58, 'min_child_samples': 10, 'subsample': 0.8532241907732697, 'subsample_freq': 4, 'colsample_bytree': 0.7666323431412191, 'reg_alpha': 1.1989147575590843e-07, 'reg_lambda': 1.0927895733904103e-05, 'min_split_gain': 0.9429097039125192, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:   9%|▉         | 9/100 [00:09<01:35,  1.05s/it]

[I 2026-05-03 22:50:40,043] Trial 8 finished with value: 0.6873204444444445 and parameters: {'max_depth': 4, 'learning_rate': 0.05210786568543147, 'num_leaves': 16, 'min_child_samples': 99, 'subsample': 0.7154436253749967, 'subsample_freq': 3, 'colsample_bytree': 0.9724797657899962, 'reg_alpha': 1.4323759352560882e-06, 'reg_lambda': 2.0139739500176936e-07, 'min_split_gain': 0.489452760277563, 'max_bin': 63}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  10%|█         | 10/100 [00:10<01:32,  1.03s/it]

[I 2026-05-03 22:50:41,023] Trial 9 finished with value: 0.6850517777777777 and parameters: {'max_depth': -1, 'learning_rate': 0.09602669100781164, 'num_leaves': 93, 'min_child_samples': 23, 'subsample': 0.7122325424664291, 'subsample_freq': 6, 'colsample_bytree': 0.9032693085526847, 'reg_alpha': 1.4102316596654226e-08, 'reg_lambda': 0.0004062913017826356, 'min_split_gain': 0.22649577519793795, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  11%|█         | 11/100 [00:12<01:36,  1.08s/it]

[I 2026-05-03 22:50:42,216] Trial 10 finished with value: 0.6883516111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.01393442615437794, 'num_leaves': 25, 'min_child_samples': 70, 'subsample': 0.995156085765876, 'subsample_freq': 0, 'colsample_bytree': 0.8268253975058423, 'reg_alpha': 3.4046778781905594e-05, 'reg_lambda': 2.042213320965466e-08, 'min_split_gain': 0.01231116956493733, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  12%|█▏        | 12/100 [00:12<01:28,  1.00s/it]

[I 2026-05-03 22:50:43,043] Trial 11 finished with value: 0.6887353888888889 and parameters: {'max_depth': 7, 'learning_rate': 0.022433516328694402, 'num_leaves': 70, 'min_child_samples': 47, 'subsample': 0.9905356938643037, 'subsample_freq': 7, 'colsample_bytree': 0.9994385955746448, 'reg_alpha': 0.003329393993130799, 'reg_lambda': 1.8169614068531696e-05, 'min_split_gain': 0.4217869903194965, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  13%|█▎        | 13/100 [00:13<01:28,  1.02s/it]

[I 2026-05-03 22:50:44,095] Trial 12 finished with value: 0.6921140555555556 and parameters: {'max_depth': -1, 'learning_rate': 0.0210290366456854, 'num_leaves': 115, 'min_child_samples': 23, 'subsample': 0.9377926329723484, 'subsample_freq': 9, 'colsample_bytree': 0.8542668769519566, 'reg_alpha': 0.00025544641400772333, 'reg_lambda': 0.014260522558352596, 'min_split_gain': 0.973391102890388, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  14%|█▍        | 14/100 [00:15<01:45,  1.23s/it]

[I 2026-05-03 22:50:45,819] Trial 13 finished with value: 0.6864937222222222 and parameters: {'max_depth': -1, 'learning_rate': 0.015201636795255503, 'num_leaves': 254, 'min_child_samples': 121, 'subsample': 0.9344307908849546, 'subsample_freq': 10, 'colsample_bytree': 0.8248094400752193, 'reg_alpha': 0.0001009671365256525, 'reg_lambda': 0.207705330035993, 'min_split_gain': 0.3287835375844916, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  15%|█▌        | 15/100 [00:16<01:45,  1.24s/it]

[I 2026-05-03 22:50:47,075] Trial 14 finished with value: 0.6903668333333334 and parameters: {'max_depth': -1, 'learning_rate': 0.02836189689274007, 'num_leaves': 126, 'min_child_samples': 39, 'subsample': 0.9393861906781806, 'subsample_freq': 8, 'colsample_bytree': 0.8780494705961787, 'reg_alpha': 0.0015683536799578973, 'reg_lambda': 4.250010638564734e-05, 'min_split_gain': 0.04298515947264633, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  16%|█▌        | 16/100 [00:18<02:00,  1.43s/it]

[I 2026-05-03 22:50:48,961] Trial 15 finished with value: 0.6912236666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.010036139963278122, 'num_leaves': 123, 'min_child_samples': 16, 'subsample': 0.8969866818911938, 'subsample_freq': 5, 'colsample_bytree': 0.8024650284806476, 'reg_alpha': 1.1126306238481883e-05, 'reg_lambda': 1.2060066914814705e-08, 'min_split_gain': 0.6089582803996045, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  17%|█▋        | 17/100 [00:19<01:48,  1.31s/it]

[I 2026-05-03 22:50:49,984] Trial 16 finished with value: 0.6878327777777777 and parameters: {'max_depth': 12, 'learning_rate': 0.020117656951502628, 'num_leaves': 170, 'min_child_samples': 199, 'subsample': 0.799453395510975, 'subsample_freq': 9, 'colsample_bytree': 0.9323267155840407, 'reg_alpha': 0.010832982403604384, 'reg_lambda': 1.3780751104367926e-06, 'min_split_gain': 0.15163044391225766, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  18%|█▊        | 18/100 [00:20<01:29,  1.09s/it]

[I 2026-05-03 22:50:50,553] Trial 17 finished with value: 0.6883014999999999 and parameters: {'max_depth': -1, 'learning_rate': 0.1354082264549953, 'num_leaves': 102, 'min_child_samples': 44, 'subsample': 0.9592607700132496, 'subsample_freq': 5, 'colsample_bytree': 0.8736007532764493, 'reg_alpha': 2.4479787631280804e-08, 'reg_lambda': 0.0074686473836630555, 'min_split_gain': 0.36942622888282683, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  19%|█▉        | 19/100 [00:22<01:44,  1.29s/it]

[I 2026-05-03 22:50:52,309] Trial 18 finished with value: 0.688644 and parameters: {'max_depth': -1, 'learning_rate': 0.02727738685120232, 'num_leaves': 213, 'min_child_samples': 16, 'subsample': 0.9583192655987517, 'subsample_freq': 7, 'colsample_bytree': 0.85520576956422, 'reg_alpha': 0.0005101688516272654, 'reg_lambda': 2.994609981054048, 'min_split_gain': 0.6037304511210528, 'max_bin': 127}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  20%|██        | 20/100 [00:22<01:20,  1.01s/it]

[I 2026-05-03 22:50:52,654] Trial 19 finished with value: 0.6881645 and parameters: {'max_depth': 5, 'learning_rate': 0.06540358868799205, 'num_leaves': 23, 'min_child_samples': 69, 'subsample': 0.9070687761182827, 'subsample_freq': 0, 'colsample_bytree': 0.7857389586552314, 'reg_alpha': 5.193094367691932e-06, 'reg_lambda': 0.06972306107285572, 'min_split_gain': 0.8624808991805706, 'max_bin': 63}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  21%|██        | 21/100 [00:24<01:40,  1.27s/it]

[I 2026-05-03 22:50:54,557] Trial 20 finished with value: 0.6916487222222222 and parameters: {'max_depth': 12, 'learning_rate': 0.01722080311351532, 'num_leaves': 45, 'min_child_samples': 30, 'subsample': 0.7797079479364939, 'subsample_freq': 4, 'colsample_bytree': 0.9490397793386667, 'reg_alpha': 2.60131684454089e-07, 'reg_lambda': 0.00010146063710346217, 'min_split_gain': 0.2735722787864484, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  22%|██▏       | 22/100 [00:26<01:47,  1.38s/it]

[I 2026-05-03 22:50:56,198] Trial 21 finished with value: 0.6895810555555555 and parameters: {'max_depth': 12, 'learning_rate': 0.01886870525738644, 'num_leaves': 53, 'min_child_samples': 32, 'subsample': 0.7730530034803582, 'subsample_freq': 4, 'colsample_bytree': 0.9622072840443873, 'reg_alpha': 1.3069729182700093e-07, 'reg_lambda': 3.548525072653717e-05, 'min_split_gain': 0.2915359111397561, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  23%|██▎       | 23/100 [00:27<01:47,  1.40s/it]

[I 2026-05-03 22:50:57,619] Trial 22 finished with value: 0.6909695 and parameters: {'max_depth': 12, 'learning_rate': 0.010875147170511542, 'num_leaves': 47, 'min_child_samples': 17, 'subsample': 0.7989375207795804, 'subsample_freq': 6, 'colsample_bytree': 0.9399335215681107, 'reg_alpha': 1.6641647358723486e-07, 'reg_lambda': 0.00020055972454003737, 'min_split_gain': 0.11014272280738556, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  24%|██▍       | 24/100 [00:29<01:56,  1.53s/it]

[I 2026-05-03 22:50:59,462] Trial 23 finished with value: 0.6879772222222222 and parameters: {'max_depth': 8, 'learning_rate': 0.013984874644558946, 'num_leaves': 88, 'min_child_samples': 58, 'subsample': 0.7496471073190015, 'subsample_freq': 2, 'colsample_bytree': 0.9972932991360461, 'reg_alpha': 1.2771150099274702e-08, 'reg_lambda': 0.649962405425226, 'min_split_gain': 0.2578442554594261, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 0. Best value: 0.69221:  25%|██▌       | 25/100 [00:31<01:59,  1.59s/it]

[I 2026-05-03 22:51:01,198] Trial 24 finished with value: 0.6876916111111111 and parameters: {'max_depth': -1, 'learning_rate': 0.03372059068763727, 'num_leaves': 109, 'min_child_samples': 26, 'subsample': 0.8351376958639053, 'subsample_freq': 4, 'colsample_bytree': 0.9080585357771302, 'reg_alpha': 8.275319575959534e-07, 'reg_lambda': 2.87330440716545e-06, 'min_split_gain': 0.10381827650143609, 'max_bin': 255}. Best is trial 0 with value: 0.6922103888888889.

Best trial: 25. Best value: 0.695001:  26%|██▌       | 26/100 [00:32<01:47,  1.45s/it]

[I 2026-05-03 22:51:02,306] Trial 25 finished with value: 0.6950005555555555 and parameters: {'max_depth': 12, 'learning_rate': 0.023873294595159376, 'num_leaves': 41, 'min_child_samples': 13, 'subsample': 0.9713274276033085, 'subsample_freq': 6, 'colsample_bytree': 0.8805614664467682, 'reg_alpha': 9.826986721484363e-05, 'reg_lambda': 0.007732030487042723, 'min_split_gain': 0.3960708725009974, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  27%|██▋       | 27/100 [00:33<01:48,  1.49s/it]

[I 2026-05-03 22:51:03,896] Trial 26 finished with value: 0.6932588333333334 and parameters: {'max_depth': -1, 'learning_rate': 0.02335019466961151, 'num_leaves': 144, 'min_child_samples': 10, 'subsample': 0.969121052282018, 'subsample_freq': 9, 'colsample_bytree': 0.8423772771585686, 'reg_alpha': 0.00011785860112565301, 'reg_lambda': 0.006602413117983696, 'min_split_gain': 0.5135157733466249, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  28%|██▊       | 28/100 [00:35<02:00,  1.68s/it]

[I 2026-05-03 22:51:06,007] Trial 27 finished with value: 0.6905830555555557 and parameters: {'max_depth': 12, 'learning_rate': 0.024921386550579766, 'num_leaves': 154, 'min_child_samples': 11, 'subsample': 0.9659665287836239, 'subsample_freq': 7, 'colsample_bytree': 0.8223488371268255, 'reg_alpha': 4.169288835501848e-05, 'reg_lambda': 0.0024405242839977788, 'min_split_gain': 0.4768716160587092, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  29%|██▉       | 29/100 [00:40<03:07,  2.64s/it]

[I 2026-05-03 22:51:10,898] Trial 28 finished with value: 0.6933741666666666 and parameters: {'max_depth': -1, 'learning_rate': 0.03584874430193938, 'num_leaves': 142, 'min_child_samples': 14, 'subsample': 0.973052313312315, 'subsample_freq': 8, 'colsample_bytree': 0.8828905408011507, 'reg_alpha': 0.022844629257339055, 'reg_lambda': 0.0007911882056050648, 'min_split_gain': 0.5507267327001316, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  30%|███       | 30/100 [00:42<02:40,  2.29s/it]

[I 2026-05-03 22:51:12,374] Trial 29 finished with value: 0.6925520555555555 and parameters: {'max_depth': -1, 'learning_rate': 0.03474624201284442, 'num_leaves': 142, 'min_child_samples': 14, 'subsample': 0.9686382529480293, 'subsample_freq': 9, 'colsample_bytree': 0.8819903934074635, 'reg_alpha': 0.023629282734257216, 'reg_lambda': 0.0005096213965759378, 'min_split_gain': 0.5538326471886973, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  31%|███       | 31/100 [00:43<02:15,  1.97s/it]

[I 2026-05-03 22:51:13,594] Trial 30 finished with value: 0.6875179444444445 and parameters: {'max_depth': 10, 'learning_rate': 0.04210015351707103, 'num_leaves': 181, 'min_child_samples': 10, 'subsample': 0.912688301523686, 'subsample_freq': 8, 'colsample_bytree': 0.8447482118696168, 'reg_alpha': 0.0010818638482766004, 'reg_lambda': 0.03907925352379099, 'min_split_gain': 0.6958868054377629, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  32%|███▏      | 32/100 [00:44<02:01,  1.78s/it]

[I 2026-05-03 22:51:14,933] Trial 31 finished with value: 0.690683611111111 and parameters: {'max_depth': -1, 'learning_rate': 0.03700422199978623, 'num_leaves': 138, 'min_child_samples': 14, 'subsample': 0.9779831797123506, 'subsample_freq': 10, 'colsample_bytree': 0.8860343063841145, 'reg_alpha': 0.05520119532180494, 'reg_lambda': 0.0007385822930916294, 'min_split_gain': 0.5482028572907589, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  33%|███▎      | 33/100 [00:46<01:55,  1.73s/it]

[I 2026-05-03 22:51:16,536] Trial 32 finished with value: 0.6922061111111112 and parameters: {'max_depth': -1, 'learning_rate': 0.03461572904439954, 'num_leaves': 143, 'min_child_samples': 14, 'subsample': 0.9679477859356271, 'subsample_freq': 9, 'colsample_bytree': 0.890464148943329, 'reg_alpha': 0.006124087732106705, 'reg_lambda': 0.0047830878304978616, 'min_split_gain': 0.4167117555872408, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  34%|███▍      | 34/100 [00:48<02:00,  1.82s/it]

[I 2026-05-03 22:51:18,588] Trial 33 finished with value: 0.687935 and parameters: {'max_depth': -1, 'learning_rate': 0.025626797962751875, 'num_leaves': 184, 'min_child_samples': 18, 'subsample': 0.8779727630447269, 'subsample_freq': 9, 'colsample_bytree': 0.8622300316191311, 'reg_alpha': 0.022767127084451895, 'reg_lambda': 0.00015228736158059768, 'min_split_gain': 0.5400538688094889, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  35%|███▌      | 35/100 [00:49<01:33,  1.43s/it]

[I 2026-05-03 22:51:19,101] Trial 34 finished with value: 0.6942806666666667 and parameters: {'max_depth': 7, 'learning_rate': 0.04761949748284444, 'num_leaves': 36, 'min_child_samples': 13, 'subsample': 0.9513651026741974, 'subsample_freq': 8, 'colsample_bytree': 0.8980417962515277, 'reg_alpha': 0.4047382258531885, 'reg_lambda': 0.001798880935407828, 'min_split_gain': 0.41479783285685207, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  36%|███▌      | 36/100 [00:49<01:17,  1.21s/it]

[I 2026-05-03 22:51:19,791] Trial 35 finished with value: 0.6933215555555555 and parameters: {'max_depth': 7, 'learning_rate': 0.044024207535332954, 'num_leaves': 33, 'min_child_samples': 10, 'subsample': 0.9478508327331655, 'subsample_freq': 6, 'colsample_bytree': 0.9271234871416891, 'reg_alpha': 0.2773250793580993, 'reg_lambda': 0.00242044127957167, 'min_split_gain': 0.43787141910712457, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  37%|███▋      | 37/100 [00:50<01:04,  1.02s/it]

[I 2026-05-03 22:51:20,385] Trial 36 finished with value: 0.6936291666666665 and parameters: {'max_depth': 7, 'learning_rate': 0.06470159313642707, 'num_leaves': 34, 'min_child_samples': 19, 'subsample': 0.9460211414748029, 'subsample_freq': 6, 'colsample_bytree': 0.927653210069452, 'reg_alpha': 0.7572698742159839, 'reg_lambda': 0.0014082450902683323, 'min_split_gain': 0.4236207438538384, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  38%|███▊      | 38/100 [00:50<00:56,  1.09it/s]

[I 2026-05-03 22:51:21,039] Trial 37 finished with value: 0.693599111111111 and parameters: {'max_depth': 7, 'learning_rate': 0.06533174585214709, 'num_leaves': 37, 'min_child_samples': 20, 'subsample': 0.9212453217573073, 'subsample_freq': 7, 'colsample_bytree': 0.9186215275752391, 'reg_alpha': 0.7831636865747019, 'reg_lambda': 0.001706284405824746, 'min_split_gain': 0.3852529906106596, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  39%|███▉      | 39/100 [00:51<00:49,  1.23it/s]

[I 2026-05-03 22:51:21,623] Trial 38 finished with value: 0.6932284444444444 and parameters: {'max_depth': 7, 'learning_rate': 0.06966891460676024, 'num_leaves': 36, 'min_child_samples': 20, 'subsample': 0.9189961338514198, 'subsample_freq': 7, 'colsample_bytree': 0.9124185378897511, 'reg_alpha': 1.0706652255831004, 'reg_lambda': 0.1263516744832683, 'min_split_gain': 0.38377863381562066, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  40%|████      | 40/100 [00:52<00:43,  1.37it/s]

[I 2026-05-03 22:51:22,155] Trial 39 finished with value: 0.6877858333333333 and parameters: {'max_depth': 7, 'learning_rate': 0.0788963385503626, 'num_leaves': 39, 'min_child_samples': 408, 'subsample': 0.8767698795980459, 'subsample_freq': 6, 'colsample_bytree': 0.9608039583148689, 'reg_alpha': 5.580490489714628, 'reg_lambda': 0.020221627212330312, 'min_split_gain': 0.333296526718678, 'max_bin': 63}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  41%|████      | 41/100 [00:52<00:43,  1.34it/s]

[I 2026-05-03 22:51:22,932] Trial 40 finished with value: 0.6898256666666667 and parameters: {'max_depth': 7, 'learning_rate': 0.05740447029690518, 'num_leaves': 64, 'min_child_samples': 33, 'subsample': 0.8944964045867988, 'subsample_freq': 5, 'colsample_bytree': 0.9254388678475389, 'reg_alpha': 0.3203997247107323, 'reg_lambda': 0.5245914850427532, 'min_split_gain': 0.4643816139645186, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  42%|████▏     | 42/100 [00:53<00:40,  1.43it/s]

[I 2026-05-03 22:51:23,534] Trial 41 finished with value: 0.6926332777777777 and parameters: {'max_depth': 7, 'learning_rate': 0.047370982031769544, 'num_leaves': 28, 'min_child_samples': 21, 'subsample': 0.9996165594278378, 'subsample_freq': 8, 'colsample_bytree': 0.9007697933638878, 'reg_alpha': 1.472616356243649, 'reg_lambda': 0.0013851789363442512, 'min_split_gain': 0.6739113360977769, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  43%|████▎     | 43/100 [00:53<00:34,  1.67it/s]

[I 2026-05-03 22:51:23,896] Trial 42 finished with value: 0.6928143888888889 and parameters: {'max_depth': 7, 'learning_rate': 0.11367734319990742, 'num_leaves': 46, 'min_child_samples': 13, 'subsample': 0.9820648939486992, 'subsample_freq': 7, 'colsample_bytree': 0.8936995579312726, 'reg_alpha': 0.11448342789937119, 'reg_lambda': 0.0012326208343175764, 'min_split_gain': 0.38523627344316785, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  44%|████▍     | 44/100 [00:54<00:33,  1.67it/s]

[I 2026-05-03 22:51:24,493] Trial 43 finished with value: 0.6903338888888889 and parameters: {'max_depth': 6, 'learning_rate': 0.06032851655172586, 'num_leaves': 33, 'min_child_samples': 18, 'subsample': 0.9215053700439196, 'subsample_freq': 6, 'colsample_bytree': 0.9201568635498932, 'reg_alpha': 0.8185148356244345, 'reg_lambda': 7.640311486380622e-05, 'min_split_gain': 0.32496297051635337, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  45%|████▌     | 45/100 [00:54<00:28,  1.96it/s]

[I 2026-05-03 22:51:24,794] Trial 44 finished with value: 0.6883793333333333 and parameters: {'max_depth': 4, 'learning_rate': 0.0758542322280498, 'num_leaves': 16, 'min_child_samples': 12, 'subsample': 0.9527176510974767, 'subsample_freq': 8, 'colsample_bytree': 0.8714236069632172, 'reg_alpha': 5.621699298343312, 'reg_lambda': 0.0004756869725905262, 'min_split_gain': 0.4562843312113419, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  46%|████▌     | 46/100 [00:55<00:29,  1.84it/s]

[I 2026-05-03 22:51:25,419] Trial 45 finished with value: 0.6940965 and parameters: {'max_depth': 7, 'learning_rate': 0.04879054210116902, 'num_leaves': 40, 'min_child_samples': 26, 'subsample': 0.9449701767175871, 'subsample_freq': 7, 'colsample_bytree': 0.9382104808695064, 'reg_alpha': 0.43692150782609845, 'reg_lambda': 0.012025607272512753, 'min_split_gain': 0.5128528218014107, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  47%|████▋     | 47/100 [00:56<00:37,  1.43it/s]

[I 2026-05-03 22:51:26,488] Trial 46 finished with value: 0.6920267222222223 and parameters: {'max_depth': 7, 'learning_rate': 0.05183608167882942, 'num_leaves': 41, 'min_child_samples': 26, 'subsample': 0.9483974722154682, 'subsample_freq': 7, 'colsample_bytree': 0.947776534109109, 'reg_alpha': 0.5875118731310924, 'reg_lambda': 0.012186012701034834, 'min_split_gain': 0.22101711174959873, 'max_bin': 63}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  48%|████▊     | 48/100 [00:56<00:31,  1.67it/s]

[I 2026-05-03 22:51:26,850] Trial 47 finished with value: 0.6885472777777777 and parameters: {'max_depth': 7, 'learning_rate': 0.10250290311960598, 'num_leaves': 55, 'min_child_samples': 174, 'subsample': 0.922870755791129, 'subsample_freq': 6, 'colsample_bytree': 0.9802222052702235, 'reg_alpha': 8.848734404073916, 'reg_lambda': 0.04707975363360303, 'min_split_gain': 0.40085065860886343, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  49%|████▉     | 49/100 [00:57<00:29,  1.72it/s]

[I 2026-05-03 22:51:27,386] Trial 48 finished with value: 0.6929912777777778 and parameters: {'max_depth': 7, 'learning_rate': 0.0830979547480311, 'num_leaves': 24, 'min_child_samples': 36, 'subsample': 0.9337026652095017, 'subsample_freq': 5, 'colsample_bytree': 0.9627096265733566, 'reg_alpha': 2.975708273009046, 'reg_lambda': 0.004054871761699071, 'min_split_gain': 0.508220094971201, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  50%|█████     | 50/100 [00:58<00:33,  1.49it/s]

[I 2026-05-03 22:51:28,275] Trial 49 finished with value: 0.6892306111111111 and parameters: {'max_depth': 7, 'learning_rate': 0.046304234036296896, 'num_leaves': 52, 'min_child_samples': 23, 'subsample': 0.8624231248254847, 'subsample_freq': 7, 'colsample_bytree': 0.7285814544595519, 'reg_alpha': 0.11610267214144838, 'reg_lambda': 0.00024625172579273837, 'min_split_gain': 0.34946476158448586, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 25. Best value: 0.695001:  51%|█████     | 51/100 [00:58<00:30,  1.60it/s]

[I 2026-05-03 22:51:28,783] Trial 50 finished with value: 0.6915101666666668 and parameters: {'max_depth': 5, 'learning_rate': 0.06513949233090709, 'num_leaves': 20, 'min_child_samples': 50, 'subsample': 0.8987189761963945, 'subsample_freq': 6, 'colsample_bytree': 0.9390734318932291, 'reg_alpha': 0.4223336431539401, 'reg_lambda': 0.013619263941218868, 'min_split_gain': 0.587766470962813, 'max_bin': 127}. Best is trial 25 with value: 0.6950005555555555.

Best trial: 51. Best value: 0.69623:  52%|█████▏    | 52/100 [00:59<00:29,  1.63it/s]

[I 2026-05-03 22:51:29,370] Trial 51 finished with value: 0.6962298333333333 and parameters: {'max_depth': 10, 'learning_rate': 0.051083723788855104, 'num_leaves': 81, 'min_child_samples': 15, 'subsample': 0.9813181710870581, 'subsample_freq': 8, 'colsample_bytree': 0.9129016411695934, 'reg_alpha': 0.05506488949139064, 'reg_lambda': 0.0016046179629749745, 'min_split_gain': 0.6541180611548333, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  53%|█████▎    | 53/100 [00:59<00:27,  1.70it/s]

[I 2026-05-03 22:51:29,901] Trial 52 finished with value: 0.693899888888889 and parameters: {'max_depth': 10, 'learning_rate': 0.055358605026924385, 'num_leaves': 81, 'min_child_samples': 19, 'subsample': 0.9823465475273792, 'subsample_freq': 8, 'colsample_bytree': 0.901933055936774, 'reg_alpha': 0.13627458658387573, 'reg_lambda': 0.0016177500283212738, 'min_split_gain': 0.6412737562342468, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  54%|█████▍    | 54/100 [01:00<00:28,  1.63it/s]

[I 2026-05-03 22:51:30,578] Trial 53 finished with value: 0.6927861111111111 and parameters: {'max_depth': 10, 'learning_rate': 0.051139344774391804, 'num_leaves': 79, 'min_child_samples': 26, 'subsample': 0.9850027608675135, 'subsample_freq': 8, 'colsample_bytree': 0.9045376778968307, 'reg_alpha': 0.063540047681201, 'reg_lambda': 0.0034020743051888383, 'min_split_gain': 0.7676260774238042, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  55%|█████▌    | 55/100 [01:01<00:32,  1.40it/s]

[I 2026-05-03 22:51:31,523] Trial 54 finished with value: 0.6850131111111111 and parameters: {'max_depth': 10, 'learning_rate': 0.040626468303364, 'num_leaves': 67, 'min_child_samples': 984, 'subsample': 0.9900772881170079, 'subsample_freq': 8, 'colsample_bytree': 0.8665007301277742, 'reg_alpha': 0.1360892635265224, 'reg_lambda': 0.02690717312723563, 'min_split_gain': 0.6540544181375648, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  56%|█████▌    | 56/100 [01:02<00:42,  1.04it/s]

[I 2026-05-03 22:51:33,059] Trial 55 finished with value: 0.6908992222222223 and parameters: {'max_depth': 10, 'learning_rate': 0.030539474308774656, 'num_leaves': 78, 'min_child_samples': 15, 'subsample': 0.9456595750911317, 'subsample_freq': 8, 'colsample_bytree': 0.900885789436639, 'reg_alpha': 2.519705752490752, 'reg_lambda': 0.007983859522879853, 'min_split_gain': 0.7107356503626786, 'max_bin': 63}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  57%|█████▋    | 57/100 [01:03<00:37,  1.14it/s]

[I 2026-05-03 22:51:33,754] Trial 56 finished with value: 0.6942408888888889 and parameters: {'max_depth': 10, 'learning_rate': 0.05621830736825666, 'num_leaves': 85, 'min_child_samples': 12, 'subsample': 0.9576504800010945, 'subsample_freq': 10, 'colsample_bytree': 0.9353711480565896, 'reg_alpha': 0.003360588719991032, 'reg_lambda': 0.000334515429390438, 'min_split_gain': 0.7737268227763877, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  58%|█████▊    | 58/100 [01:04<00:36,  1.15it/s]

[I 2026-05-03 22:51:34,608] Trial 57 finished with value: 0.6933880555555556 and parameters: {'max_depth': 10, 'learning_rate': 0.05473108030424833, 'num_leaves': 89, 'min_child_samples': 12, 'subsample': 0.9975476130685237, 'subsample_freq': 10, 'colsample_bytree': 0.9379762524413015, 'reg_alpha': 0.0026512470129401787, 'reg_lambda': 0.09863775687067572, 'min_split_gain': 0.7563936668428832, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  59%|█████▉    | 59/100 [01:05<00:32,  1.27it/s]

[I 2026-05-03 22:51:35,197] Trial 58 finished with value: 0.694443 and parameters: {'max_depth': 10, 'learning_rate': 0.07349284585295296, 'num_leaves': 70, 'min_child_samples': 12, 'subsample': 0.959399877945215, 'subsample_freq': 10, 'colsample_bytree': 0.894604511051871, 'reg_alpha': 0.0006432562373297272, 'reg_lambda': 2.288982589209679e-05, 'min_split_gain': 0.8740176634158812, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  60%|██████    | 60/100 [01:05<00:28,  1.41it/s]

[I 2026-05-03 22:51:35,722] Trial 59 finished with value: 0.6913307777777777 and parameters: {'max_depth': 10, 'learning_rate': 0.07225695555470663, 'num_leaves': 99, 'min_child_samples': 16, 'subsample': 0.9614650376497185, 'subsample_freq': 10, 'colsample_bytree': 0.9145384325582143, 'reg_alpha': 0.00046243571109689185, 'reg_lambda': 1.621630642746002e-05, 'min_split_gain': 0.8324446802153231, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  61%|██████    | 61/100 [01:06<00:29,  1.33it/s]

[I 2026-05-03 22:51:36,571] Trial 60 finished with value: 0.6952937222222222 and parameters: {'max_depth': 10, 'learning_rate': 0.047292424229303, 'num_leaves': 61, 'min_child_samples': 12, 'subsample': 0.9379839821626714, 'subsample_freq': 9, 'colsample_bytree': 0.8919689549271075, 'reg_alpha': 0.00019198257613025325, 'reg_lambda': 9.44551721217603e-06, 'min_split_gain': 0.9097597741269523, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  62%|██████▏   | 62/100 [01:07<00:29,  1.30it/s]

[I 2026-05-03 22:51:37,378] Trial 61 finished with value: 0.6944072777777778 and parameters: {'max_depth': 10, 'learning_rate': 0.049702842886172036, 'num_leaves': 70, 'min_child_samples': 12, 'subsample': 0.9396165702750005, 'subsample_freq': 9, 'colsample_bytree': 0.8922111453819406, 'reg_alpha': 6.800438284121235e-05, 'reg_lambda': 3.583224252013698e-06, 'min_split_gain': 0.8898929415823763, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  63%|██████▎   | 63/100 [01:08<00:29,  1.24it/s]

[I 2026-05-03 22:51:38,275] Trial 62 finished with value: 0.6945764999999999 and parameters: {'max_depth': 10, 'learning_rate': 0.04452845456799186, 'num_leaves': 61, 'min_child_samples': 12, 'subsample': 0.9578794448511495, 'subsample_freq': 10, 'colsample_bytree': 0.8580945732187625, 'reg_alpha': 0.00018843247936375134, 'reg_lambda': 1.4293196647178526e-06, 'min_split_gain': 0.9108007323349777, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  64%|██████▍   | 64/100 [01:09<00:29,  1.23it/s]

[I 2026-05-03 22:51:39,101] Trial 63 finished with value: 0.6933216666666666 and parameters: {'max_depth': 10, 'learning_rate': 0.039978651285604794, 'num_leaves': 61, 'min_child_samples': 10, 'subsample': 0.9325908679665446, 'subsample_freq': 9, 'colsample_bytree': 0.8314439471178129, 'reg_alpha': 1.2753262813599091e-05, 'reg_lambda': 4.392418287324076e-06, 'min_split_gain': 0.9878869509672681, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  65%|██████▌   | 65/100 [01:13<01:11,  2.05s/it]

[I 2026-05-03 22:51:44,029] Trial 64 finished with value: 0.694815888888889 and parameters: {'max_depth': 10, 'learning_rate': 0.03139587826779744, 'num_leaves': 72, 'min_child_samples': 11, 'subsample': 0.9762198398096188, 'subsample_freq': 10, 'colsample_bytree': 0.8564206528879452, 'reg_alpha': 0.00016738111444286832, 'reg_lambda': 2.8010608456875644e-07, 'min_split_gain': 0.900200105924674, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  66%|██████▌   | 66/100 [01:14<00:57,  1.68s/it]

[I 2026-05-03 22:51:44,862] Trial 65 finished with value: 0.6940135000000001 and parameters: {'max_depth': 10, 'learning_rate': 0.03116166064987516, 'num_leaves': 72, 'min_child_samples': 11, 'subsample': 0.9774796478077818, 'subsample_freq': 10, 'colsample_bytree': 0.8570785756107584, 'reg_alpha': 0.0001449454742559926, 'reg_lambda': 1.3317676324320996e-07, 'min_split_gain': 0.900721696252134, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  67%|██████▋   | 67/100 [01:15<00:49,  1.49s/it]

[I 2026-05-03 22:51:45,902] Trial 66 finished with value: 0.6937973888888889 and parameters: {'max_depth': 10, 'learning_rate': 0.027512948721689703, 'num_leaves': 98, 'min_child_samples': 15, 'subsample': 0.9904647908175541, 'subsample_freq': 9, 'colsample_bytree': 0.8355011959043653, 'reg_alpha': 4.9516027348581046e-05, 'reg_lambda': 4.369773623783908e-07, 'min_split_gain': 0.9381546269821338, 'max_bin': 63}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  68%|██████▊   | 68/100 [01:16<00:39,  1.23s/it]

[I 2026-05-03 22:51:46,513] Trial 67 finished with value: 0.6902612222222222 and parameters: {'max_depth': 10, 'learning_rate': 0.03843446154464165, 'num_leaves': 71, 'min_child_samples': 91, 'subsample': 0.9594029387019093, 'subsample_freq': 10, 'colsample_bytree': 0.877377164381901, 'reg_alpha': 1.125971791316273e-05, 'reg_lambda': 8.094936065756097e-07, 'min_split_gain': 0.8900984957369882, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  69%|██████▉   | 69/100 [01:17<00:34,  1.13s/it]

[I 2026-05-03 22:51:47,405] Trial 68 finished with value: 0.6930377777777778 and parameters: {'max_depth': 8, 'learning_rate': 0.032203403326193154, 'num_leaves': 115, 'min_child_samples': 10, 'subsample': 0.9717598268936856, 'subsample_freq': 9, 'colsample_bytree': 0.8652680342682968, 'reg_alpha': 0.00023771797505581007, 'reg_lambda': 9.389016532851738e-08, 'min_split_gain': 0.8367849572062799, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  70%|███████   | 70/100 [01:18<00:34,  1.16s/it]

[I 2026-05-03 22:51:48,638] Trial 69 finished with value: 0.6930368333333333 and parameters: {'max_depth': 12, 'learning_rate': 0.021791631666204927, 'num_leaves': 53, 'min_child_samples': 12, 'subsample': 0.8330647811300513, 'subsample_freq': 10, 'colsample_bytree': 0.8135831361281334, 'reg_alpha': 0.0007586274541280837, 'reg_lambda': 7.496838469097193e-06, 'min_split_gain': 0.971563944792289, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  71%|███████   | 71/100 [01:19<00:29,  1.03s/it]

[I 2026-05-03 22:51:49,353] Trial 70 finished with value: 0.6947560555555556 and parameters: {'max_depth': 10, 'learning_rate': 0.04358977696027923, 'num_leaves': 61, 'min_child_samples': 16, 'subsample': 0.9409387966015764, 'subsample_freq': 9, 'colsample_bytree': 0.845551128208877, 'reg_alpha': 2.147531224459717e-05, 'reg_lambda': 1.59246547665905e-06, 'min_split_gain': 0.911145500054827, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  72%|███████▏  | 72/100 [01:19<00:25,  1.09it/s]

[I 2026-05-03 22:51:50,028] Trial 71 finished with value: 0.693592388888889 and parameters: {'max_depth': 10, 'learning_rate': 0.043650264879242305, 'num_leaves': 63, 'min_child_samples': 16, 'subsample': 0.9370983663244232, 'subsample_freq': 9, 'colsample_bytree': 0.8485463970518935, 'reg_alpha': 2.3706318570754733e-05, 'reg_lambda': 1.7385015197570392e-06, 'min_split_gain': 0.8639279747019181, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  73%|███████▎  | 73/100 [01:20<00:25,  1.06it/s]

[I 2026-05-03 22:51:51,036] Trial 72 finished with value: 0.6944581666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.0377209335487063, 'num_leaves': 74, 'min_child_samples': 11, 'subsample': 0.9639523402411795, 'subsample_freq': 10, 'colsample_bytree': 0.8890210004330963, 'reg_alpha': 7.106028514711512e-05, 'reg_lambda': 4.2996314560016646e-07, 'min_split_gain': 0.9047205523306321, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  74%|███████▍  | 74/100 [01:21<00:22,  1.17it/s]

[I 2026-05-03 22:51:51,687] Trial 73 finished with value: 0.6927562777777777 and parameters: {'max_depth': 10, 'learning_rate': 0.038051200778440285, 'num_leaves': 60, 'min_child_samples': 17, 'subsample': 0.9750612985787963, 'subsample_freq': 10, 'colsample_bytree': 0.7980322859371825, 'reg_alpha': 5.459196685428921e-06, 'reg_lambda': 3.502250901080536e-08, 'min_split_gain': 0.9551457736874439, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  75%|███████▌  | 75/100 [01:22<00:21,  1.18it/s]

[I 2026-05-03 22:51:52,505] Trial 74 finished with value: 0.6880484444444445 and parameters: {'max_depth': 6, 'learning_rate': 0.029460962671896993, 'num_leaves': 56, 'min_child_samples': 683, 'subsample': 0.9654222734675196, 'subsample_freq': 10, 'colsample_bytree': 0.8565185992777001, 'reg_alpha': 0.0001945548714903458, 'reg_lambda': 3.4706733331976977e-07, 'min_split_gain': 0.9239958093368336, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  76%|███████▌  | 76/100 [01:23<00:22,  1.07it/s]

[I 2026-05-03 22:51:53,646] Trial 75 finished with value: 0.6944239999999999 and parameters: {'max_depth': 10, 'learning_rate': 0.025697629761617883, 'num_leaves': 92, 'min_child_samples': 11, 'subsample': 0.9873219170500543, 'subsample_freq': 9, 'colsample_bytree': 0.8724065312719911, 'reg_alpha': 2.8638068531127437e-06, 'reg_lambda': 1.0263954065414286e-06, 'min_split_gain': 0.7916059718204472, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  77%|███████▋  | 77/100 [01:24<00:22,  1.04it/s]

[I 2026-05-03 22:51:54,657] Trial 76 finished with value: 0.6927303333333333 and parameters: {'max_depth': 12, 'learning_rate': 0.01827184767722973, 'num_leaves': 73, 'min_child_samples': 14, 'subsample': 0.9546140568529203, 'subsample_freq': 10, 'colsample_bytree': 0.8395226307545197, 'reg_alpha': 2.2309452501826837e-05, 'reg_lambda': 2.9656381785744948e-05, 'min_split_gain': 0.9993966097170807, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  78%|███████▊  | 78/100 [01:24<00:17,  1.29it/s]

[I 2026-05-03 22:51:55,003] Trial 77 finished with value: 0.6868672222222222 and parameters: {'max_depth': 4, 'learning_rate': 0.04216057948577149, 'num_leaves': 16, 'min_child_samples': 13, 'subsample': 0.9254330220600784, 'subsample_freq': 10, 'colsample_bytree': 0.8880951285149222, 'reg_alpha': 8.902829232220671e-05, 'reg_lambda': 6.311520064568857e-06, 'min_split_gain': 0.8224601492446113, 'max_bin': 255}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  79%|███████▉  | 79/100 [01:25<00:17,  1.21it/s]

[I 2026-05-03 22:51:55,951] Trial 78 finished with value: 0.6937776666666666 and parameters: {'max_depth': 10, 'learning_rate': 0.023537473181557054, 'num_leaves': 48, 'min_child_samples': 23, 'subsample': 0.9639757837946585, 'subsample_freq': 3, 'colsample_bytree': 0.8184167784628846, 'reg_alpha': 0.00033769442218896796, 'reg_lambda': 5.7785729938705115e-08, 'min_split_gain': 0.8625641342110246, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  80%|████████  | 80/100 [01:26<00:17,  1.14it/s]

[I 2026-05-03 22:51:56,956] Trial 79 finished with value: 0.6929725555555556 and parameters: {'max_depth': 10, 'learning_rate': 0.032772127387804786, 'num_leaves': 83, 'min_child_samples': 10, 'subsample': 0.9104381237675148, 'subsample_freq': 9, 'colsample_bytree': 0.8838208962344134, 'reg_alpha': 0.0010194752018608086, 'reg_lambda': 1.9309613315806875e-06, 'min_split_gain': 0.9248900654496494, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  81%|████████  | 81/100 [01:27<00:14,  1.30it/s]

[I 2026-05-03 22:51:57,477] Trial 80 finished with value: 0.6897426111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.04475274903007786, 'num_leaves': 27, 'min_child_samples': 17, 'subsample': 0.9757616870092036, 'subsample_freq': 10, 'colsample_bytree': 0.851137339516064, 'reg_alpha': 2.9606169421262146e-05, 'reg_lambda': 6.412592921027844e-07, 'min_split_gain': 0.9030585408689613, 'max_bin': 63}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  82%|████████▏ | 82/100 [01:28<00:15,  1.18it/s]

[I 2026-05-03 22:51:58,508] Trial 81 finished with value: 0.6945255 and parameters: {'max_depth': 10, 'learning_rate': 0.02558428802181338, 'num_leaves': 92, 'min_child_samples': 11, 'subsample': 0.9851289594745928, 'subsample_freq': 9, 'colsample_bytree': 0.863220324789867, 'reg_alpha': 2.1358960111558903e-06, 'reg_lambda': 2.209644641990461e-07, 'min_split_gain': 0.79922343609915, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  83%|████████▎ | 83/100 [01:29<00:13,  1.25it/s]

[I 2026-05-03 22:51:59,184] Trial 82 finished with value: 0.6921007222222223 and parameters: {'max_depth': 10, 'learning_rate': 0.036787315029257486, 'num_leaves': 106, 'min_child_samples': 11, 'subsample': 0.9960420101917127, 'subsample_freq': 9, 'colsample_bytree': 0.86633696964337, 'reg_alpha': 4.864223259036068e-07, 'reg_lambda': 4.2314631615083275e-07, 'min_split_gain': 0.9539565663409539, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  84%|████████▍ | 84/100 [01:29<00:11,  1.36it/s]

[I 2026-05-03 22:51:59,768] Trial 83 finished with value: 0.6939452222222222 and parameters: {'max_depth': 10, 'learning_rate': 0.06016809676136928, 'num_leaves': 67, 'min_child_samples': 14, 'subsample': 0.9823152141333107, 'subsample_freq': 10, 'colsample_bytree': 0.877187792307495, 'reg_alpha': 1.670173024868472e-06, 'reg_lambda': 1.8395034544918685e-07, 'min_split_gain': 0.8545123582300346, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  85%|████████▌ | 85/100 [01:31<00:14,  1.07it/s]

[I 2026-05-03 22:52:01,179] Trial 84 finished with value: 0.6936354444444444 and parameters: {'max_depth': 10, 'learning_rate': 0.02050113927751686, 'num_leaves': 75, 'min_child_samples': 13, 'subsample': 0.9694754960177197, 'subsample_freq': 9, 'colsample_bytree': 0.8479140942210186, 'reg_alpha': 0.00011346538336261098, 'reg_lambda': 2.6067452637654815e-07, 'min_split_gain': 0.8075155495372794, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  86%|████████▌ | 86/100 [01:31<00:12,  1.08it/s]

[I 2026-05-03 22:52:02,072] Trial 85 finished with value: 0.6944334444444444 and parameters: {'max_depth': 8, 'learning_rate': 0.03488146491182301, 'num_leaves': 238, 'min_child_samples': 11, 'subsample': 0.9543114960806943, 'subsample_freq': 9, 'colsample_bytree': 0.8938050746291375, 'reg_alpha': 6.764164260688379e-06, 'reg_lambda': 2.4796430287120906e-06, 'min_split_gain': 0.7347263460681632, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  87%|████████▋ | 87/100 [01:33<00:15,  1.16s/it]

[I 2026-05-03 22:52:03,790] Trial 86 finished with value: 0.6917908888888888 and parameters: {'max_depth': 12, 'learning_rate': 0.024271400311623715, 'num_leaves': 95, 'min_child_samples': 15, 'subsample': 0.9393357134557356, 'subsample_freq': 10, 'colsample_bytree': 0.860343394883034, 'reg_alpha': 0.0004291074689691055, 'reg_lambda': 1.1518393023954725e-06, 'min_split_gain': 0.882084423787171, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  88%|████████▊ | 88/100 [01:34<00:13,  1.13s/it]

[I 2026-05-03 22:52:04,844] Trial 87 finished with value: 0.6910616111111111 and parameters: {'max_depth': 10, 'learning_rate': 0.029252372250539282, 'num_leaves': 129, 'min_child_samples': 10, 'subsample': 0.9621970643785067, 'subsample_freq': 9, 'colsample_bytree': 0.9100913191322062, 'reg_alpha': 5.374335883075645e-05, 'reg_lambda': 1.160333058697866e-05, 'min_split_gain': 0.9095530294416592, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  89%|████████▉ | 89/100 [01:35<00:11,  1.04s/it]

[I 2026-05-03 22:52:05,678] Trial 88 finished with value: 0.6877376111111111 and parameters: {'max_depth': 10, 'learning_rate': 0.026718240751460016, 'num_leaves': 49, 'min_child_samples': 344, 'subsample': 0.9999889064636913, 'subsample_freq': 10, 'colsample_bytree': 0.8724231774538485, 'reg_alpha': 0.001981491848246586, 'reg_lambda': 1.3207101958749978e-08, 'min_split_gain': 0.9648572099467151, 'max_bin': 255}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  90%|█████████ | 90/100 [01:35<00:08,  1.22it/s]

[I 2026-05-03 22:52:05,987] Trial 89 finished with value: 0.6921518333333332 and parameters: {'max_depth': 6, 'learning_rate': 0.0960065639479674, 'num_leaves': 59, 'min_child_samples': 21, 'subsample': 0.9905985765647773, 'subsample_freq': 8, 'colsample_bytree': 0.8417179512744256, 'reg_alpha': 0.00017231700604905653, 'reg_lambda': 2.3648322978850294e-05, 'min_split_gain': 0.9344490107026988, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  91%|█████████ | 91/100 [01:36<00:06,  1.34it/s]

[I 2026-05-03 22:52:06,553] Trial 90 finished with value: 0.687699 and parameters: {'max_depth': 4, 'learning_rate': 0.1291187133703456, 'num_leaves': 16, 'min_child_samples': 18, 'subsample': 0.9276464640979567, 'subsample_freq': 9, 'colsample_bytree': 0.8817515839398313, 'reg_alpha': 1.6525171999883847e-05, 'reg_lambda': 9.86544613000355e-05, 'min_split_gain': 0.790794927626349, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  92%|█████████▏| 92/100 [01:37<00:05,  1.36it/s]

[I 2026-05-03 22:52:07,258] Trial 91 finished with value: 0.6928682777777777 and parameters: {'max_depth': 8, 'learning_rate': 0.03479309558263771, 'num_leaves': 228, 'min_child_samples': 11, 'subsample': 0.9492300666623101, 'subsample_freq': 9, 'colsample_bytree': 0.8919889254843993, 'reg_alpha': 1.449773141894971e-06, 'reg_lambda': 2.8430945331599367e-06, 'min_split_gain': 0.7265434631342835, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  93%|█████████▎| 93/100 [01:38<00:05,  1.29it/s]

[I 2026-05-03 22:52:08,124] Trial 92 finished with value: 0.6915686666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.04136486908222589, 'num_leaves': 246, 'min_child_samples': 13, 'subsample': 0.9533917831012954, 'subsample_freq': 10, 'colsample_bytree': 0.8955629221120223, 'reg_alpha': 3.7042175239526374e-06, 'reg_lambda': 4.925991788599509e-05, 'min_split_gain': 0.8537012588294148, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  94%|█████████▍| 94/100 [01:39<00:05,  1.11it/s]

[I 2026-05-03 22:52:09,322] Trial 93 finished with value: 0.6903311111111111 and parameters: {'max_depth': 8, 'learning_rate': 0.03383676187061303, 'num_leaves': 84, 'min_child_samples': 12, 'subsample': 0.7366525801509392, 'subsample_freq': 9, 'colsample_bytree': 0.8684782338351743, 'reg_alpha': 9.34779232555123e-06, 'reg_lambda': 5.956286535867103e-07, 'min_split_gain': 0.6837520522028363, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  95%|█████████▌| 95/100 [01:40<00:04,  1.03it/s]

[I 2026-05-03 22:52:10,456] Trial 94 finished with value: 0.6959813888888889 and parameters: {'max_depth': 10, 'learning_rate': 0.016343214178901538, 'num_leaves': 43, 'min_child_samples': 16, 'subsample': 0.9791312689635862, 'subsample_freq': 10, 'colsample_bytree': 0.9194112948956275, 'reg_alpha': 8.5649751626081e-05, 'reg_lambda': 5.887127922563277e-06, 'min_split_gain': 0.7562440789499024, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  96%|█████████▌| 96/100 [01:41<00:04,  1.15s/it]

[I 2026-05-03 22:52:12,024] Trial 95 finished with value: 0.6952436111111111 and parameters: {'max_depth': 10, 'learning_rate': 0.01377306769082823, 'num_leaves': 43, 'min_child_samples': 16, 'subsample': 0.9802683793188522, 'subsample_freq': 10, 'colsample_bytree': 0.9195598391757979, 'reg_alpha': 4.077187839254863e-08, 'reg_lambda': 6.575086444330911e-06, 'min_split_gain': 0.8033031002688124, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  97%|█████████▋| 97/100 [01:43<00:03,  1.33s/it]

[I 2026-05-03 22:52:13,783] Trial 96 finished with value: 0.6954216111111111 and parameters: {'max_depth': 10, 'learning_rate': 0.0120310331457248, 'num_leaves': 42, 'min_child_samples': 15, 'subsample': 0.9780099884239288, 'subsample_freq': 10, 'colsample_bytree': 0.9243824605519603, 'reg_alpha': 2.6328120705297625e-08, 'reg_lambda': 5.2161024574228e-06, 'min_split_gain': 0.7511142736483196, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  98%|█████████▊| 98/100 [01:48<00:05,  2.52s/it]

[I 2026-05-03 22:52:19,061] Trial 97 finished with value: 0.6953241666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.012118583748508096, 'num_leaves': 41, 'min_child_samples': 23, 'subsample': 0.9821873382386296, 'subsample_freq': 10, 'colsample_bytree': 0.9256934171827934, 'reg_alpha': 6.393963861742749e-08, 'reg_lambda': 5.895538715355359e-06, 'min_split_gain': 0.752147973755216, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623:  99%|█████████▉| 99/100 [01:50<00:02,  2.15s/it]

[I 2026-05-03 22:52:20,353] Trial 98 finished with value: 0.6940182777777778 and parameters: {'max_depth': 10, 'learning_rate': 0.011291441160486979, 'num_leaves': 44, 'min_child_samples': 30, 'subsample': 0.9775528987924498, 'subsample_freq': 10, 'colsample_bytree': 0.9203049816153436, 'reg_alpha': 4.7176503219201906e-08, 'reg_lambda': 7.946346509894711e-06, 'min_split_gain': 0.7463130681798622, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.

Best trial: 51. Best value: 0.69623: 100%|██████████| 100/100 [01:51<00:00,  1.12s/it]

[I 2026-05-03 22:52:21,875] Trial 99 finished with value: 0.6942389444444445 and parameters: {'max_depth': 10, 'learning_rate': 0.01272573582568805, 'num_leaves': 32, 'min_child_samples': 20, 'subsample': 0.9716433243361913, 'subsample_freq': 10, 'colsample_bytree': 0.9470671785824655, 'reg_alpha': 5.506290357144771e-08, 'reg_lambda': 1.3392273809089784e-05, 'min_split_gain': 0.6999204572952995, 'max_bin': 127}. Best is trial 51 with value: 0.6962298333333333.
Best validation AUC: 0.6962298333333333
Best params:
{'max_depth': 10, 'learning_rate': 0.051083723788855104, 'num_leaves': 81, 'min_child_samples': 15, 'subsample': 0.9813181710870581, 'subsample_freq': 8, 'colsample_bytree': 0.9129016411695934, 'reg_alpha': 0.05506488949139064, 'reg_lambda': 0.0016046179629749745, 'min_split_gain': 0.6541180611548333, 'max_bin': 127}

In [28]:
baseline_search_params = {
    "learning_rate": 0.05,
    "num_leaves": 31,
    "max_depth": -1,
    "min_child_samples": 20,
    "subsample": 1.0,
    "subsample_freq": 0,
    "colsample_bytree": 1.0,
    "reg_alpha": 1e-8,
    "reg_lambda": 1e-8,
    "min_split_gain": 0.0,
    "max_bin": 255,
}

if study.best_value >= baseline_valid_auc:
    selected_params = study.best_params
    selected_param_source = "optuna"
    selected_valid_auc = study.best_value
else:
    selected_params = baseline_search_params
    selected_param_source = "baseline"
    selected_valid_auc = baseline_valid_auc

print("Selected param source:", selected_param_source)
print("Selected validation AUC:", selected_valid_auc)
print("Selected params:")
print(selected_params)

Selected param source: optuna
Selected validation AUC: 0.6962298333333333
Selected params:
{'max_depth': 10, 'learning_rate': 0.051083723788855104, 'num_leaves': 81, 'min_child_samples': 15, 'subsample': 0.9813181710870581, 'subsample_freq': 8, 'colsample_bytree': 0.9129016411695934, 'reg_alpha': 0.05506488949139064, 'reg_lambda': 0.0016046179629749745, 'min_split_gain': 0.6541180611548333, 'max_bin': 127}

In [29]:
final_model = lgb.LGBMClassifier(
    objective="binary",
    metric="auc",
    boosting_type="gbdt",
    verbosity=-1,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    n_estimators=N_ESTIMATORS_MAX,
    use_missing=True,
    zero_as_missing=False,
    **selected_params
)

final_model.fit(
    X_train,
    y_train,
    eval_set=[(X_valid, y_valid)],
    eval_metric="auc",
    callbacks=[
        lgb.early_stopping(
            stopping_rounds=EARLY_STOPPING_ROUNDS,
            verbose=True
        ),
        lgb.log_evaluation(period=50)
    ]
)

final_valid_pred = final_model.predict_proba(X_valid)[:, 1]
final_test_pred = final_model.predict_proba(X_test)[:, 1]

final_valid_auc = roc_auc_score(y_valid, final_valid_pred)
final_test_auc = roc_auc_score(y_test, final_test_pred)

print("Selected param source:", selected_param_source)
print("Final valid AUC:", final_valid_auc)
print("Final test AUC :", final_test_auc)
print("Final best iteration:", final_model.best_iteration_)

Training until validation scores don't improve for 100 rounds
[50]	valid_0's auc: 0.695392
[100]	valid_0's auc: 0.692439
Early stopping, best iteration is:
[33]	valid_0's auc: 0.69623
Selected param source: optuna
Final valid AUC: 0.6962298333333333
Final test AUC : 0.6840723333333334
Final best iteration: 33

In [30]:
auc_summary_df = pd.DataFrame([
    {
        "case": "baseline",
        "valid_auc": float(baseline_valid_auc),
        "test_auc": float(baseline_test_auc),
        "param_source": "baseline"
    },
    {
        "case": "optuna_best",
        "valid_auc": float(study.best_value),
        "test_auc": None,
        "param_source": "optuna"
    },
    {
        "case": "final_selected",
        "valid_auc": float(final_valid_auc),
        "test_auc": float(final_test_auc),
        "param_source": selected_param_source
    },
])

display(auc_summary_df)

             case  valid_auc  test_auc param_source
0        baseline    0.69221  0.683047     baseline
1     optuna_best    0.69623       NaN       optuna
2  final_selected    0.69623  0.684072       optuna

In [31]:
trials_df = study.trials_dataframe()

display(
    trials_df.sort_values("value", ascending=False).head(10)
)

trials_path = f"{OUTPUT_DIR}/optuna_lgbm_trials.csv"
trials_df.to_csv(trials_path, index=False)

print("Saved:", trials_path)

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_learning_rate,params_max_bin,params_max_depth,params_min_child_samples,...,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,params_subsample_freq,user_attrs_best_iteration,user_attrs_elapsed_seconds,user_attrs_valid_auc,system_attrs_fixed_params,state
51,51,0.696230,2026-05-03 22:51:28.789399,2026-05-03 22:51:29.370573,0 days 00:00:00.581174,0.912902,0.051084,127,10,15,...,81,5.506489e-02,1.604618e-03,0.981318,8,33,0.552788,0.696230,NaN,COMPLETE
94,94,0.695981,2026-05-03 22:52:09.327709,2026-05-03 22:52:10.456189,0 days 00:00:01.128480,0.919411,0.016343,127,10,16,...,43,8.564975e-05,5.887128e-06,0.979131,10,147,1.096291,0.695981,NaN,COMPLETE
96,96,0.695422,2026-05-03 22:52:12.029930,2026-05-03 22:52:13.783568,0 days 00:00:01.753638,0.924382,0.012031,127,10,15,...,42,2.632812e-08,5.216102e-06,0.978010,10,174,1.722038,0.695422,NaN,COMPLETE
97,97,0.695324,2026-05-03 22:52:13.789617,2026-05-03 22:52:19.061402,0 days 00:00:05.271785,0.925693,0.012119,127,10,23,...,41,6.393964e-08,5.895539e-06,0.982187,10,172,5.239044,0.695324,NaN,COMPLETE
60,60,0.695294,2026-05-03 22:51:35.727895,2026-05-03 22:51:36.571750,0 days 00:00:00.843855,0.891969,0.047292,127,10,12,...,61,1.919826e-04,9.445517e-06,0.937984,9,29,0.815329,0.695294,NaN,COMPLETE
95,95,0.695244,2026-05-03 22:52:10.461974,2026-05-03 22:52:12.024314,0 days 00:00:01.562340,0.919560,0.013773,127,10,16,...,43,4.077188e-08,6.575086e-06,0.980268,10,169,1.528755,0.695244,NaN,COMPLETE
25,25,0.695001,2026-05-03 22:51:01.204223,2026-05-03 22:51:02.306297,0 days 00:00:01.102074,0.880561,0.023873,127,12,13,...,41,9.826987e-05,7.732030e-03,0.971327,6,72,1.074792,0.695001,NaN,COMPLETE
64,64,0.694816,2026-05-03 22:51:39.107603,2026-05-03 22:51:44.029606,0 days 00:00:04.922003,0.856421,0.031396,127,10,11,...,72,1.673811e-04,2.801061e-07,0.976220,10,45,4.892325,0.694816,NaN,COMPLETE
70,70,0.694756,2026-05-03 22:51:48.642925,2026-05-03 22:51:49.353757,0 days 00:00:00.710832,0.845551,0.043590,127,10,16,...,61,2.147531e-05,1.592465e-06,0.940939,9,24,0.681539,0.694756,NaN,COMPLETE
62,62,0.694576,2026-05-03 22:51:37.384279,2026-05-03 22:51:38.275204,0 days 00:00:00.890925,0.858095,0.044528,127,10,12,...,61,1.884325e-04,1.429320e-06,0.957879,10,45,0.859759,0.694576,NaN,COMPLETE

Saved: /opt/spark/workspace/output/lgbm_experiment/optuna_lgbm_trials.csv

In [ ]:
from optuna.importance import get_param_importances

param_importance = get_param_importances(study)

param_importance_df = pd.DataFrame({
    "parameter": list(param_importance.keys()),
    "importance": list(param_importance.values())
}).sort_values("importance", ascending=False)

display(param_importance_df)

param_importance_path = f"{OUTPUT_DIR}/optuna_param_importance.csv"
param_importance_df.to_csv(param_importance_path, index=False)

print("Saved:", param_importance_path)

In [ ]:
best_config = {
    "model": "LightGBM",
    "task": "tlc_yellow_taxi_current_batch_vs_existing_batches",
    "target_processing_date_hour": str(TARGET_PROCESSING_DATE_HOUR),
    "comparison_processing_date_hours": [
        str(h) for h in comparison_processing_hours
    ],
    "metric": "auc",

    "baseline_valid_auc": float(baseline_valid_auc),
    "baseline_test_auc": float(baseline_test_auc),

    "optuna_best_valid_auc": float(study.best_value),
    "optuna_best_params": study.best_params,

    "selected_param_source": selected_param_source,
    "selected_valid_auc": float(selected_valid_auc),
    "selected_params": selected_params,

    "final_valid_auc": float(final_valid_auc),
    "final_test_auc": float(final_test_auc),
    "final_best_iteration": int(final_model.best_iteration_),

    "fixed_training_config": {
        "n_estimators_max": N_ESTIMATORS_MAX,
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "random_state": RANDOM_STATE,
        "target_sample_per_group": TARGET_SAMPLE_PER_GROUP,
        "min_rows_per_group": MIN_ROWS_PER_GROUP,
        "previous_batch_offset": str(PREVIOUS_BATCH_OFFSET),
        "history_offsets": [str(x) for x in HISTORY_OFFSETS],
        "use_missing": True,
        "zero_as_missing": False,
        "no_isnull_features": True,
        "no_trip_duration_min": True,
    },

    "tuned_parameter_groups": {
        "tree_complexity": [
            "num_leaves",
            "max_depth",
            "min_child_samples"
        ],
        "learning_process": [
            "learning_rate",
            "n_estimators_with_early_stopping"
        ],
        "sampling": [
            "subsample",
            "subsample_freq",
            "colsample_bytree"
        ],
        "regularization": [
            "reg_alpha",
            "reg_lambda",
            "min_split_gain"
        ],
        "binning": [
            "max_bin"
        ]
    }
}

best_params_path = f"{OUTPUT_DIR}/best_lgbm_params.json"

with open(best_params_path, "w") as f:
    json.dump(best_config, f, indent=2, default=str)

print("Saved:", best_params_path)
display(best_config)

In [ ]:
X_final_train = pd.concat([X_train, X_valid], axis=0)
y_final_train = pd.concat([y_train, y_valid], axis=0)

print("Final train:", X_final_train.shape)
print("Final test :", X_test.shape)

In [ ]:
threshold = 0.2
final_test_label_pred = (final_test_pred >= threshold).astype(int)

print(classification_report(y_test, final_test_label_pred))

In [ ]:
importance_df = pd.DataFrame({
    "feature": X_final_train.columns,
    "importance": final_model.feature_importances_
}).sort_values("importance", ascending=False)

display(importance_df.head(30))

importance_path = f"{OUTPUT_DIR}/final_lgbm_feature_importance.csv"
importance_df.to_csv(importance_path, index=False)

print("Saved:", importance_path)

In [ ]:
import matplotlib.pyplot as plt

top_n = 20
plot_df = importance_df.head(top_n).sort_values("importance")

plt.figure(figsize=(8, 6))
plt.barh(plot_df["feature"], plot_df["importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top LightGBM Feature Importance")
plt.show()

In [ ]:
import shap

SHAP_SAMPLE_SIZE = min(3000, len(X_test))
# SHAP_SAMPLE_SIZE = len(X_test)
X_shap = X_test.sample(
    SHAP_SAMPLE_SIZE,
    random_state=RANDOM_STATE
)

explainer = shap.TreeExplainer(final_model)
shap_values = explainer.shap_values(X_shap)

if isinstance(shap_values, list):
    shap_values_to_plot = shap_values[1]
else:
    shap_values_to_plot = shap_values

shap.summary_plot(
    shap_values_to_plot,
    X_shap,
    max_display=20
)

In [ ]:
shap.summary_plot(
    shap_values_to_plot,
    X_shap,
    plot_type="bar",
    max_display=20
)

In [ ]:
# Tỷ lệ bản ghi label = 1 bị giả lập bất thường
# 0.30 nghĩa là 30% bản ghi trong batch target sẽ bị chỉnh bất thường
ANOMALY_FRACTION = 0.30

# Seed để kết quả tái lập được
ANOMALY_RANDOM_STATE = 2025

print("Synthetic anomaly fraction:", ANOMALY_FRACTION)

In [ ]:
print("Positive target rows:", len(positive_df))
print("Negative history rows:", len(negative_df))

print("Target processing hour:")
print(positive_df["processing_date_hour"].value_counts())

print("History processing hours:")
display(
    negative_df["processing_date_hour"]
    .value_counts()
    .sort_index()
)

In [ ]:
def inject_synthetic_anomalies(
    target_df,
    anomaly_fraction=0.30,
    random_state=42
):
    """
    Giả lập bất thường trên dữ liệu target label = 1.
    
    Lưu ý:
    - Chỉ chỉnh dữ liệu target.
    - Không chỉnh dữ liệu lịch sử.
    - Cột synthetic_anomaly chỉ dùng để kiểm tra, không đưa vào model.
    """
    data = target_df.copy()
    rng = np.random.default_rng(random_state)

    data["synthetic_anomaly"] = 0

    n_rows = len(data)
    n_anomaly = int(n_rows * anomaly_fraction)

    if n_anomaly <= 0:
        return data

    anomaly_indices = rng.choice(
        data.index.to_numpy(),
        size=n_anomaly,
        replace=False
    )

    data.loc[anomaly_indices, "synthetic_anomaly"] = 1

    # Chia nhóm anomaly thành nhiều kiểu khác nhau
    anomaly_groups = np.array_split(anomaly_indices, 5)

    # 1. Fare / total amount tăng bất thường
    rows = anomaly_groups[0]
    if len(rows) > 0:
        if "fare_amount" in data.columns:
            multiplier = rng.uniform(3, 8, size=len(rows))
            data.loc[rows, "fare_amount"] = (
                pd.to_numeric(data.loc[rows, "fare_amount"], errors="coerce")
                .fillna(0)
                * multiplier
            )

        if "tip_amount" in data.columns:
            data.loc[rows, "tip_amount"] = rng.uniform(20, 100, size=len(rows))

        if "total_amount" in data.columns:
            base_fare = (
                pd.to_numeric(data.loc[rows, "fare_amount"], errors="coerce")
                .fillna(0)
            )
            data.loc[rows, "total_amount"] = base_fare + rng.uniform(50, 150, size=len(rows))

    # 2. Trip distance rất lớn
    rows = anomaly_groups[1]
    if len(rows) > 0 and "trip_distance" in data.columns:
        data.loc[rows, "trip_distance"] = rng.uniform(80, 180, size=len(rows))

        if "total_amount" in data.columns:
            data.loc[rows, "total_amount"] = rng.uniform(200, 500, size=len(rows))

    # 3. Passenger count bất thường hoặc missing
    rows = anomaly_groups[2]
    if len(rows) > 0 and "passenger_count" in data.columns:
        half = len(rows) // 2
        rows_high = rows[:half]
        rows_null = rows[half:]

        if len(rows_high) > 0:
            data.loc[rows_high, "passenger_count"] = rng.integers(8, 15, size=len(rows_high))

        if len(rows_null) > 0:
            data.loc[rows_null, "passenger_count"] = np.nan

    # 4. Category lạ trong payment_type / store_and_fwd_flag
    rows = anomaly_groups[3]
    if len(rows) > 0:
        if "payment_type" in data.columns:
            data.loc[rows, "payment_type"] = 99

        if "store_and_fwd_flag" in data.columns:
            data.loc[rows, "store_and_fwd_flag"] = "ANOM"

    # 5. Location ID bất thường
    rows = anomaly_groups[4]
    if len(rows) > 0:
        if "PULocationID" in data.columns:
            data.loc[rows, "PULocationID"] = 999

        if "DOLocationID" in data.columns:
            data.loc[rows, "DOLocationID"] = 999

    return data

In [ ]:
abnormal_positive_df = inject_synthetic_anomalies(
    target_df=positive_df,
    anomaly_fraction=ANOMALY_FRACTION,
    random_state=ANOMALY_RANDOM_STATE
)

print("Abnormal positive shape:", abnormal_positive_df.shape)
print("Synthetic anomaly counts:")
print(abnormal_positive_df["synthetic_anomaly"].value_counts())

display(
    abnormal_positive_df[
        [
            "processing_date_hour",
            "label",
            "synthetic_anomaly",
            "trip_distance",
            "fare_amount",
            "tip_amount",
            "total_amount",
            "passenger_count",
            "payment_type",
            "PULocationID",
            "DOLocationID",
        ]
    ].head(20)
)

In [ ]:
# Lịch sử giữ nguyên, thêm synthetic_anomaly = 0 để dễ phân tích
normal_negative_df = negative_df.copy()
normal_negative_df["synthetic_anomaly"] = 0

abnormal_work_df = pd.concat(
    [abnormal_positive_df, normal_negative_df],
    axis=0
)

abnormal_work_df = abnormal_work_df.sample(
    frac=1,
    random_state=RANDOM_STATE
).reset_index(drop=True)

print("Abnormal work dataset shape:", abnormal_work_df.shape)
print(abnormal_work_df["label"].value_counts())
print(abnormal_work_df["label"].value_counts(normalize=True))

display(
    abnormal_work_df.groupby(["label", "synthetic_anomaly"])
    .size()
    .reset_index(name="row_count")
)

In [ ]:
compare_cols = [
    "trip_distance",
    "fare_amount",
    "tip_amount",
    "total_amount",
    "passenger_count",
]

compare_cols = [c for c in compare_cols if c in abnormal_work_df.columns]

normal_target_stats = positive_df[compare_cols].describe().T
abnormal_target_stats = abnormal_positive_df[compare_cols].describe().T
history_stats = negative_df[compare_cols].describe().T

summary_stats = pd.concat(
    {
        "normal_target": normal_target_stats[["mean", "50%", "max"]],
        "abnormal_target": abnormal_target_stats[["mean", "50%", "max"]],
        "history": history_stats[["mean", "50%", "max"]],
    },
    axis=1
)

display(summary_stats)

In [ ]:
y_abnormal = abnormal_work_df["label"].astype(int)
X_abnormal_raw = abnormal_work_df.drop(columns=["label", "synthetic_anomaly"], errors="ignore")

n_abn_total = len(abnormal_work_df)
n_abn_test = int(round(TEST_SIZE * n_abn_total))
n_anb_valid = int(round(VALID_SIZE * n_abn_total))

X_ab_train_valid_raw, X_ab_test_raw, y_ab_train_valid, y_ab_test = train_test_split(
    X_abnormal_raw,
    y_abnormal,
    test_size=n_abn_test,
    random_state=RANDOM_STATE,
    stratify=y_abnormal
)

X_ab_train_raw, X_ab_valid_raw, y_ab_train, y_ab_valid = train_test_split(
    X_ab_train_valid_raw,
    y_ab_train_valid,
    test_size=n_anb_valid,
    random_state=RANDOM_STATE,
    stratify=y_ab_train_valid
)

print("Abnormal train raw:", X_ab_train_raw.shape, "| positive rate:", y_ab_train.mean())
print("Abnormal valid raw:", X_ab_valid_raw.shape, "| positive rate:", y_ab_valid.mean())
print("Abnormal test raw :", X_ab_test_raw.shape, "| positive rate:", y_ab_test.mean())

In [ ]:
abnormal_encoder = TaxiFeatureEncoder(
    categorical_cols=CATEGORICAL_COLS,
    numeric_cols=NUMERIC_COLS,
    exclude_cols=EXCLUDE_COLS
)

abnormal_encoder.fit(X_ab_train_raw)

X_ab_train = abnormal_encoder.transform(X_ab_train_raw)
X_ab_valid = abnormal_encoder.transform(X_ab_valid_raw)
X_ab_test = abnormal_encoder.transform(X_ab_test_raw)

print("X_ab_train:", X_ab_train.shape)
print("X_ab_valid:", X_ab_valid.shape)
print("X_ab_test :", X_ab_test.shape)

print("Features used by model:")
print(X_ab_train.columns.tolist())

if "synthetic_anomaly" in X_ab_train.columns:
    raise ValueError("synthetic_anomaly bị đưa vào model. Cần loại bỏ ngay.")
else:
    print("OK: synthetic_anomaly is NOT used as a model feature.")

In [ ]:
abnormal_model = lgb.LGBMClassifier(
    objective="binary",
    metric="auc",
    boosting_type="gbdt",
    verbosity=-1,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    n_estimators=N_ESTIMATORS_MAX,
    **study.best_params
)

abnormal_model.fit(
    X_ab_train,
    y_ab_train,
    eval_set=[(X_ab_valid, y_ab_valid)],
    eval_metric="auc",
    callbacks=[
        lgb.early_stopping(
            stopping_rounds=EARLY_STOPPING_ROUNDS,
            verbose=True
        ),
        lgb.log_evaluation(period=50)
    ]
)

ab_valid_pred = abnormal_model.predict_proba(X_ab_valid)[:, 1]
ab_test_pred = abnormal_model.predict_proba(X_ab_test)[:, 1]

abnormal_valid_auc = roc_auc_score(y_ab_valid, ab_valid_pred)
abnormal_test_auc = roc_auc_score(y_ab_test, ab_test_pred)

print("Abnormal valid AUC:", abnormal_valid_auc)
print("Abnormal test AUC :", abnormal_test_auc)
print("Best iteration:", abnormal_model.best_iteration_)

In [ ]:
comparison_rows = []

# Các biến này được tạo ở phần notebook trước
# baseline_test_auc: baseline LightGBM bình thường
# final_test_auc: model sau Optuna trên dữ liệu bình thường

if "baseline_test_auc" in globals():
    comparison_rows.append({
        "case": "Normal data - baseline LightGBM",
        "test_auc": float(baseline_test_auc)
    })

if "final_test_auc" in globals():
    comparison_rows.append({
        "case": "Normal data - tuned LightGBM",
        "test_auc": float(final_test_auc)
    })

comparison_rows.append({
    "case": f"Synthetic anomaly data - tuned LightGBM, anomaly_fraction={ANOMALY_FRACTION}",
    "test_auc": float(abnormal_test_auc)
})

auc_comparison_df = pd.DataFrame(comparison_rows)

display(auc_comparison_df)

In [ ]:
score_analysis_df = X_ab_test_raw.copy()
score_analysis_df["true_label"] = y_ab_test.values
score_analysis_df["pred_score"] = ab_test_pred

if "synthetic_anomaly" not in score_analysis_df.columns:
    score_analysis_df["synthetic_anomaly"] = 0

display(
    score_analysis_df.groupby(["true_label", "synthetic_anomaly"])["pred_score"]
    .agg(["count", "mean", "median", "min", "max"])
    .reset_index()
)

In [ ]:
ab_importance_df = pd.DataFrame({
    "feature": X_ab_train.columns,
    "importance": abnormal_model.feature_importances_
}).sort_values("importance", ascending=False)

display(ab_importance_df.head(30))

ab_importance_path = f"{OUTPUT_DIR}/abnormal_lgbm_feature_importance.csv"
ab_importance_df.to_csv(ab_importance_path, index=False)

print("Saved:", ab_importance_path)

In [ ]:
import matplotlib.pyplot as plt

top_n = 20
plot_df = ab_importance_df.head(top_n).sort_values("importance")

plt.figure(figsize=(8, 6))
plt.barh(plot_df["feature"], plot_df["importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top LightGBM Feature Importance - Synthetic Anomaly Case")
plt.show()

In [ ]:
import shap

SHAP_SAMPLE_SIZE = len(X_ab_test)

X_ab_shap = X_ab_test.sample(
    SHAP_SAMPLE_SIZE,
    random_state=RANDOM_STATE
)

ab_explainer = shap.TreeExplainer(abnormal_model)
ab_shap_values = ab_explainer.shap_values(X_ab_shap)

if isinstance(ab_shap_values, list):
    ab_shap_values_to_plot = ab_shap_values[1]
else:
    ab_shap_values_to_plot = ab_shap_values

shap.summary_plot(
    ab_shap_values_to_plot,
    X_ab_shap,
    max_display=20
)

In [ ]:
shap.summary_plot(
    shap_values_to_plot,
    X_shap,
    plot_type="bar",
    max_display=20
)

In [ ]:
def run_synthetic_anomaly_experiment(
    anomaly_fraction,
    random_state=42
):
    # 1. Inject anomaly vào target
    temp_positive = inject_synthetic_anomalies(
        target_df=positive_df,
        anomaly_fraction=anomaly_fraction,
        random_state=random_state
    )

    # 2. History giữ nguyên
    temp_negative = negative_df.copy()
    temp_negative["synthetic_anomaly"] = 0

    # 3. Gộp dataset
    temp_work_df = pd.concat([temp_positive, temp_negative], axis=0)
    temp_work_df = temp_work_df.sample(
        frac=1,
        random_state=random_state
    ).reset_index(drop=True)

    # 4. Split
    y_temp = temp_work_df["label"].astype(int)
    X_temp_raw = temp_work_df.drop(columns=["label", "synthetic_anomaly"], errors="ignore")
    
    n_temp_total = len(temp_work_df)
    n_temp_test = int(round(TEST_SIZE * n_temp_total))
    n_temp_valid = int(round(VALID_SIZE * n_temp_total))
    
    X_temp_train_valid_raw, X_temp_test_raw, y_temp_train_valid, y_temp_test = train_test_split(
        X_temp_raw,
        y_temp,
        test_size=n_temp_test,
        random_state=random_state,
        stratify=y_temp
    )

    X_temp_train_raw, X_temp_valid_raw, y_temp_train, y_temp_valid = train_test_split(
        X_temp_train_valid_raw,
        y_temp_train_valid,
        test_size=n_temp_valid,
        random_state=random_state,
        stratify=y_temp_train_valid
    )

    # 5. Encode
    temp_encoder = TaxiFeatureEncoder(
        categorical_cols=CATEGORICAL_COLS,
        numeric_cols=NUMERIC_COLS,
        exclude_cols=EXCLUDE_COLS
    )

    temp_encoder.fit(X_temp_train_raw)

    X_temp_train = temp_encoder.transform(X_temp_train_raw)
    X_temp_valid = temp_encoder.transform(X_temp_valid_raw)
    X_temp_test = temp_encoder.transform(X_temp_test_raw)

    # 6. Train bằng best params, không tuning lại
    temp_model = lgb.LGBMClassifier(
        objective="binary",
        metric="auc",
        boosting_type="gbdt",
        verbosity=-1,
        random_state=random_state,
        n_jobs=-1,
        n_estimators=N_ESTIMATORS_MAX,
        **study.best_params
    )

    temp_model.fit(
        X_temp_train,
        y_temp_train,
        eval_set=[(X_temp_valid, y_temp_valid)],
        eval_metric="auc",
        callbacks=[
            lgb.early_stopping(
                stopping_rounds=EARLY_STOPPING_ROUNDS,
                verbose=False
            )
        ]
    )

    valid_pred = temp_model.predict_proba(X_temp_valid)[:, 1]
    test_pred = temp_model.predict_proba(X_temp_test)[:, 1]

    valid_auc = roc_auc_score(y_temp_valid, valid_pred)
    test_auc = roc_auc_score(y_temp_test, test_pred)

    result = {
        "anomaly_fraction": anomaly_fraction,
        "valid_auc": float(valid_auc),
        "test_auc": float(test_auc),
        "best_iteration": int(temp_model.best_iteration_),
        "n_rows": int(len(temp_work_df)),
        "n_positive": int((temp_work_df["label"] == 1).sum()),
        "n_negative": int((temp_work_df["label"] == 0).sum()),
        "n_synthetic_anomaly": int(temp_work_df["synthetic_anomaly"].sum()),
    }

    return result

In [ ]:
ANOMALY_LEVELS = [0.0, 0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90,1]

sweep_results = []

for frac in ANOMALY_LEVELS:
    print("Running anomaly_fraction =", frac)

    result = run_synthetic_anomaly_experiment(
        anomaly_fraction=frac,
        random_state=ANOMALY_RANDOM_STATE
    )

    sweep_results.append(result)

sweep_df = pd.DataFrame(sweep_results)

display(sweep_df)

In [ ]:
plt.figure(figsize=(7, 5))
plt.plot(
    sweep_df["anomaly_fraction"],
    sweep_df["test_auc"],
    marker="o"
)
plt.xlabel("Synthetic anomaly fraction")
plt.ylabel("Test AUC")
plt.title("AUC vs Synthetic Anomaly Fraction")
plt.grid(True)
plt.show()

In [ ]:
BATCH_START = pd.Timestamp("2025-01-16 12:00:00")
BATCH_END = pd.Timestamp("2025-01-31 12:00:00")

TARGET_BATCH_LIST = pd.date_range(
    start=BATCH_START,
    end=BATCH_END,
    freq="12h"
).tolist()

print("Number of target batches:", len(TARGET_BATCH_LIST))
print("First target batch:", TARGET_BATCH_LIST[0])
print("Last target batch :", TARGET_BATCH_LIST[-1])

TARGET_BATCH_LIST[:5], TARGET_BATCH_LIST[-5:]

In [ ]:
if "selected_params" in globals():
    MODEL_PARAMS = selected_params
    PARAM_SOURCE = "selected_params"
elif "study" in globals():
    MODEL_PARAMS = study.best_params
    PARAM_SOURCE = "study.best_params"
else:
    raise ValueError("Không tìm thấy selected_params hoặc study.best_params.")

print("Using params from:", PARAM_SOURCE)
print(MODEL_PARAMS)

In [ ]:
EXCLUDE_COLS = [
    "label",
    "date_hour",
    "processing_date_hour",
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
]

print("Exclude columns:")
for col in EXCLUDE_COLS:
    print("-", col)

In [ ]:
def sample_by_processing_hour(
    source_df,
    processing_hour,
    label,
    max_rows,
    random_state
):
    part = source_df[source_df["processing_date_hour"] == processing_hour].copy()

    if len(part) == 0:
        return part

    if len(part) > max_rows:
        part = part.sample(max_rows, random_state=random_state)

    part["label"] = label
    # part["source_processing_date_hour"] = processing_hour

    return part

In [ ]:
def get_comparison_processing_hours(target_processing_hour):
    comparison_hours = [
        target_processing_hour - PREVIOUS_BATCH_OFFSET,
    ]

    comparison_hours += [
        target_processing_hour - offset
        for offset in HISTORY_OFFSETS
    ]

    # Loại trùng và sắp xếp
    comparison_hours = sorted(list(set(comparison_hours)))

    return comparison_hours

In [ ]:
def build_dataset_for_target_batch(
    source_df,
    target_processing_hour,
    min_rows_per_group=MIN_ROWS_PER_GROUP,
    max_rows_per_group=TARGET_SAMPLE_PER_GROUP,
    random_state=RANDOM_STATE
):
    # 1. Positive sample: target batch
    positive_df = sample_by_processing_hour(
        source_df=source_df,
        processing_hour=target_processing_hour,
        label=1,
        max_rows=max_rows_per_group,
        random_state=random_state
    )

    if len(positive_df) < min_rows_per_group:
        return None, {
            "status": "skipped",
            "reason": "positive_rows_too_few",
            "target_processing_hour": str(target_processing_hour),
            "positive_rows": len(positive_df),
        }

    # 2. Negative sample: all comparison batches
    comparison_hours = get_comparison_processing_hours(target_processing_hour)

    negative_parts = []
    negative_info = []

    for i, compare_hour in enumerate(comparison_hours):
        part = sample_by_processing_hour(
            source_df=source_df,
            processing_hour=compare_hour,
            label=0,
            max_rows=max_rows_per_group,
            random_state=random_state + i + 100
        )

        negative_info.append({
            "comparison_hour": str(compare_hour),
            "rows": len(part)
        })

        if len(part) >= min_rows_per_group:
            negative_parts.append(part)

    if len(negative_parts) == 0:
        return None, {
            "status": "skipped",
            "reason": "negative_rows_too_few",
            "target_processing_hour": str(target_processing_hour),
            "positive_rows": len(positive_df),
            "negative_info": negative_info,
        }

    negative_df = pd.concat(negative_parts, axis=0)

    # 3. Gộp positive + negative
    work_df = pd.concat([positive_df, negative_df], axis=0)
    work_df = work_df.sample(frac=1, random_state=random_state).reset_index(drop=True)

    meta = {
        "status": "ok",
        "target_processing_hour": str(target_processing_hour),
        "positive_rows": int((work_df["label"] == 1).sum()),
        "negative_rows": int((work_df["label"] == 0).sum()),
        "total_rows": int(len(work_df)),
        "comparison_hours": [str(h) for h in comparison_hours],
        "negative_info": negative_info,
    }

    return work_df, meta

In [ ]:
def train_evaluate_one_batch(
    batch_df,
    model_params,
    random_state=RANDOM_STATE
):
    y = batch_df["label"].astype(int)
    X_raw = batch_df.drop(columns=["label"], errors="ignore")

    n_temp_total = len(batch_df)
    n_temp_test = int(round(TEST_SIZE * n_temp_total))
    n_temp_valid = int(round(VALID_SIZE * n_temp_total))
    
    X_train_valid_raw, X_test_raw, y_train_valid, y_test = train_test_split(
        X_raw,
        y,
        test_size=n_temp_test,
        random_state=random_state,
        stratify=y
    )

    X_train_raw, X_valid_raw, y_train, y_valid = train_test_split(
        X_train_valid_raw,
        y_train_valid,
        test_size=n_temp_valid,
        random_state=random_state,
        stratify=y_train_valid
    )

    encoder = TaxiFeatureEncoder(
        categorical_cols=CATEGORICAL_COLS,
        numeric_cols=NUMERIC_COLS,
        exclude_cols=EXCLUDE_COLS
    )

    encoder.fit(X_train_raw)

    X_train = encoder.transform(X_train_raw)
    X_valid = encoder.transform(X_valid_raw)
    X_test = encoder.transform(X_test_raw)

    model = lgb.LGBMClassifier(
        objective="binary",
        metric="auc",
        boosting_type="gbdt",
        verbosity=-1,
        random_state=random_state,
        n_jobs=-1,
        n_estimators=N_ESTIMATORS_MAX,
        use_missing=True,
        zero_as_missing=False,
        **model_params
    )

    model.fit(
        X_train,
        y_train,
        eval_set=[(X_valid, y_valid)],
        eval_metric="auc",
        callbacks=[
            lgb.early_stopping(
                stopping_rounds=EARLY_STOPPING_ROUNDS,
                verbose=False
            )
        ]
    )

    valid_pred = model.predict_proba(X_valid)[:, 1]
    test_pred = model.predict_proba(X_test)[:, 1]

    valid_auc = roc_auc_score(y_valid, valid_pred)
    test_auc = roc_auc_score(y_test, test_pred)

    result = {
        "valid_auc": float(valid_auc),
        "test_auc": float(test_auc),
        "best_iteration": int(model.best_iteration_),
        "n_train": int(len(X_train)),
        "n_valid": int(len(X_valid)),
        "n_test": int(len(X_test)),
        "positive_rate_train": float(y_train.mean()),
        "positive_rate_valid": float(y_valid.mean()),
        "positive_rate_test": float(y_test.mean()),
    }

    artifacts = {
        "model": model,
        "encoder": encoder,
        "X_train": X_train,
        "X_valid": X_valid,
        "X_test": X_test,
        "X_test_raw": X_test_raw,
        "y_train": y_train,
        "y_valid": y_valid,
        "y_test": y_test,
        "test_pred": test_pred,
    }

    return result, artifacts

In [ ]:
def compute_lgbm_shap_top_features(
    model,
    X_data,
    target_processing_hour,
    top_n=10,
    sample_size=1000,
    random_state=RANDOM_STATE
):
    if len(X_data) > sample_size:
        X_shap = X_data.sample(sample_size, random_state=random_state)
    else:
        X_shap = X_data.copy()

    # LightGBM native SHAP contributions
    # Output shape = n_rows x (n_features + 1)
    # Cột cuối là expected value / bias term
    shap_contrib = model.booster_.predict(
        X_shap,
        pred_contrib=True
    )

    shap_values = shap_contrib[:, :-1]

    mean_abs_shap = np.abs(shap_values).mean(axis=0)

    shap_df = pd.DataFrame({
        "target_processing_date_hour": target_processing_hour,
        "feature": X_shap.columns,
        "mean_abs_shap": mean_abs_shap
    }).sort_values("mean_abs_shap", ascending=False)

    shap_df["rank"] = range(1, len(shap_df) + 1)

    return shap_df.head(top_n), shap_df

In [ ]:
batch_auc_results = []
batch_shap_top_results = []
batch_shap_all_results = []
batch_run_logs = []

for idx, target_hour in enumerate(TARGET_BATCH_LIST):
    print("=" * 100)
    print(f"[{idx + 1}/{len(TARGET_BATCH_LIST)}] Running target batch:", target_hour)

    batch_df, meta = build_dataset_for_target_batch(
        source_df=df_raw,
        target_processing_hour=target_hour,
        min_rows_per_group=MIN_ROWS_PER_GROUP,
        max_rows_per_group=TARGET_SAMPLE_PER_GROUP,
        random_state=RANDOM_STATE + idx
    )

    batch_run_logs.append(meta)

    if batch_df is None:
        print("Skipped:", meta["reason"])
        continue

    print("Rows:", meta["total_rows"])
    print("Positive rows:", meta["positive_rows"])
    print("Negative rows:", meta["negative_rows"])
    print("Comparison hours:", meta["comparison_hours"])

    try:
        eval_result, artifacts = train_evaluate_one_batch(
            batch_df=batch_df,
            model_params=MODEL_PARAMS,
            random_state=RANDOM_STATE + idx
        )

        result_row = {
            "target_processing_date_hour": target_hour,
            "target_processing_date_hour_str": str(target_hour),
            "valid_auc": eval_result["valid_auc"],
            "test_auc": eval_result["test_auc"],
            "best_iteration": eval_result["best_iteration"],
            "total_rows": meta["total_rows"],
            "positive_rows": meta["positive_rows"],
            "negative_rows": meta["negative_rows"],
            "n_train": eval_result["n_train"],
            "n_valid": eval_result["n_valid"],
            "n_test": eval_result["n_test"],
            "positive_rate_test": eval_result["positive_rate_test"],
            "comparison_hours": " | ".join(meta["comparison_hours"]),
        }

        batch_auc_results.append(result_row)

        print("Valid AUC:", eval_result["valid_auc"])
        print("Test AUC :", eval_result["test_auc"])
        print("Best iteration:", eval_result["best_iteration"])

        shap_top_df, shap_all_df = compute_lgbm_shap_top_features(
            model=artifacts["model"],
            X_data=artifacts["X_test"],
            target_processing_hour=str(target_hour),
            top_n=10,
            sample_size=1000,
            random_state=RANDOM_STATE + idx
        )

        batch_shap_top_results.append(shap_top_df)
        batch_shap_all_results.append(shap_all_df)

        print("Top SHAP features:")
        display(shap_top_df[["rank", "feature", "mean_abs_shap"]])

        # Dọn nhẹ bộ nhớ
        del artifacts
        gc.collect()

    except Exception as e:
        print("Failed target batch:", target_hour)
        print("Error:", repr(e))

        batch_run_logs.append({
            "status": "failed",
            "target_processing_hour": str(target_hour),
            "error": repr(e)
        })

In [ ]:
auc_series_df = pd.DataFrame(batch_auc_results)

auc_series_df = auc_series_df.sort_values("target_processing_date_hour").reset_index(drop=True)

display(auc_series_df)

auc_series_path = f"{OUTPUT_DIR}/batch_auc_series.csv"
auc_series_df.to_csv(auc_series_path, index=False)

print("Saved:", auc_series_path)

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(14, 5))

plt.plot(
    auc_series_df["target_processing_date_hour"],
    auc_series_df["test_auc"],
    marker="o",
    label="Test AUC"
)

plt.axhline(
    0.5,
    linestyle="--",
    label="AUC = 0.5"
)

plt.xlabel("Target processing_date_hour")
plt.ylabel("Test AUC")
plt.title("Batch-level Test AUC over Time")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

In [ ]:
# Số điểm lịch sử tối thiểu trước khi bắt đầu đánh giá bất thường
MIN_HISTORY_POINTS = 20

# Số điểm gần nhất dùng làm lịch sử.
# Nếu đặt None: dùng toàn bộ lịch sử trước đó.
# Nếu đặt 12: chỉ dùng 12 batch gần nhất.
ROLLING_WINDOW = None

# Mức báo động thống kê.
# Đây không phải threshold AUC, mà là mức p-value.
ALPHA = 0.05

print("MIN_HISTORY_POINTS:", MIN_HISTORY_POINTS)
print("ROLLING_WINDOW:", ROLLING_WINDOW)
print("ALPHA:", ALPHA)

In [ ]:
def add_empirical_auc_anomaly_score(
    auc_df,
    auc_col="test_auc",
    time_col="target_processing_date_hour",
    min_history_points=6,
    rolling_window=None,
    alpha=0.05
):
    """
    Tính anomaly score cho chuỗi AUC bằng empirical p-value.

    Ý tưởng:
    - Với mỗi điểm AUC hiện tại, lấy các AUC trước đó làm lịch sử.
    - Tính p-value một phía phía trên:
        p = (số điểm lịch sử >= AUC hiện tại + 1) / (số điểm lịch sử + 1)
    - p càng nhỏ => AUC hiện tại càng hiếm/cao bất thường so với lịch sử.

    Không dùng threshold AUC cố định.
    """

    data = auc_df.copy()
    data = data.sort_values(time_col).reset_index(drop=True)

    p_values = []
    percentile_ranks = []
    history_means = []
    history_medians = []
    history_q95s = []
    history_sizes = []
    anomaly_flags = []
    anomaly_reasons = []

    for i, row in data.iterrows():
        current_auc = row[auc_col]

        # Chỉ dùng dữ liệu quá khứ
        history = data.loc[:i-1, auc_col].dropna()

        if rolling_window is not None:
            history = history.tail(rolling_window)

        history_size = len(history)
        history_sizes.append(history_size)

        if history_size < min_history_points or pd.isna(current_auc):
            p_values.append(np.nan)
            percentile_ranks.append(np.nan)
            history_means.append(np.nan)
            history_medians.append(np.nan)
            history_q95s.append(np.nan)
            anomaly_flags.append(False)
            anomaly_reasons.append("warmup_not_enough_history")
            continue

        # Empirical p-value phía trên
        # +1 smoothing để tránh p-value = 0 khi điểm hiện tại lớn hơn toàn bộ lịch sử
        p_value = (np.sum(history >= current_auc) + 1) / (history_size + 1)

        # Percentile rank: tỷ lệ lịch sử <= current_auc
        percentile_rank = (np.sum(history <= current_auc) + 1) / (history_size + 1)

        history_mean = history.mean()
        history_median = history.median()
        history_q95 = history.quantile(1 - alpha)

        is_anomaly = p_value <= alpha

        p_values.append(float(p_value))
        percentile_ranks.append(float(percentile_rank))
        history_means.append(float(history_mean))
        history_medians.append(float(history_median))
        history_q95s.append(float(history_q95))
        anomaly_flags.append(bool(is_anomaly))

        if is_anomaly:
            anomaly_reasons.append(
                f"auc_is_in_top_{int(alpha * 100)}pct_tail_of_history"
            )
        else:
            anomaly_reasons.append("normal_vs_history")

    data["history_size"] = history_sizes
    data["history_auc_mean"] = history_means
    data["history_auc_median"] = history_medians
    data[f"history_auc_q{int((1-alpha)*100)}"] = history_q95s
    data["auc_empirical_p_value"] = p_values
    data["auc_percentile_rank"] = percentile_ranks
    data["is_auc_anomaly"] = anomaly_flags
    data["auc_anomaly_reason"] = anomaly_reasons

    return data

In [ ]:
auc_monitoring_df = add_empirical_auc_anomaly_score(
    auc_df=auc_series_df,
    auc_col="test_auc",
    time_col="target_processing_date_hour",
    min_history_points=MIN_HISTORY_POINTS,
    rolling_window=ROLLING_WINDOW,
    alpha=ALPHA
)

display(auc_monitoring_df)

In [ ]:
auc_anomaly_batches_df = auc_monitoring_df[
    auc_monitoring_df["is_auc_anomaly"] == True
].copy()

print("Number of AUC anomaly batches:", len(auc_anomaly_batches_df))

display(
    auc_anomaly_batches_df[
        [
            "target_processing_date_hour",
            "test_auc",
            "history_size",
            "history_auc_mean",
            "history_auc_median",
            f"history_auc_q{int((1-ALPHA)*100)}",
            "auc_empirical_p_value",
            "auc_percentile_rank",
            "auc_anomaly_reason",
        ]
    ]
)

In [ ]:
import matplotlib.pyplot as plt

q_col = f"history_auc_q{int((1-ALPHA)*100)}"

plt.figure(figsize=(14, 5))

plt.plot(
    auc_monitoring_df["target_processing_date_hour"],
    auc_monitoring_df["test_auc"],
    marker="o",
    label="Test AUC"
)

plt.plot(
    auc_monitoring_df["target_processing_date_hour"],
    auc_monitoring_df[q_col],
    marker="x",
    linestyle="--",
    label=f"Dynamic historical q{int((1-ALPHA)*100)}"
)

# Đánh dấu anomaly
anomaly_points = auc_monitoring_df[auc_monitoring_df["is_auc_anomaly"] == True]

plt.scatter(
    anomaly_points["target_processing_date_hour"],
    anomaly_points["test_auc"],
    s=120,
    marker="X",
    label="AUC anomaly"
)

plt.axhline(
    0.5,
    linestyle=":",
    label="AUC = 0.5"
)

plt.xlabel("Target processing_date_hour")
plt.ylabel("Test AUC")
plt.title("Dynamic AUC Monitoring using Empirical Historical Distribution")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(14, 5))

plt.plot(
    auc_monitoring_df["target_processing_date_hour"],
    auc_monitoring_df["auc_empirical_p_value"],
    marker="o",
    label="Empirical p-value"
)

plt.axhline(
    ALPHA,
    linestyle="--",
    label=f"alpha = {ALPHA}"
)

plt.xlabel("Target processing_date_hour")
plt.ylabel("Empirical p-value")
plt.title("AUC Empirical p-value over Time")
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()