# SynapseML LightGBM — Clean & Cluster-Optimized Notebook

Notebook này dùng để phát hiện **data drift/anomaly theo batch** bằng cách:

- `label = 1`: batch hiện tại cần kiểm tra.
- `label = 0`: các batch lịch sử dùng để so sánh.
- Train **SynapseML LightGBM** để phân biệt 2 nhóm dữ liệu.
- Dùng **AUC** để đo mức độ khác nhau giữa batch hiện tại và lịch sử.

Thiết kế vẫn giữ các tối ưu chính của notebook cũ:

1. Không dùng `orderBy(rand()).limit()` trên toàn bộ batch lớn.
2. Sampling theo `processing_date_hour` bằng candidate sampling trước, rồi mới random sort + limit.
3. Spark split theo label bằng hash/window để gần giống `train_test_split(..., stratify=y)`.
4. Cache/persist các DataFrame dùng lại nhiều lần.
5. SynapseML profile tối ưu cho cụm `2 executors x 6 cores`, `task.cpus = 3`, `numTasks = 4`, `numThreads = 3`.
6. Không bật SHAP trong Optuna vì rất nặng; chỉ bật ở final model nếu cần.

## 1. Import libraries

In [1]:
import os
import json
import math
import random
import time
import gc
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
from sklearn.metrics import roc_auc_score, classification_report

from IPython.display import display

from pyspark import StorageLevel
from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from pyspark.sql.types import StructType, StructField, DoubleType, LongType
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.functions import vector_to_array

from synapse.ml.lightgbm import LightGBMClassifier

print("Optuna version:", optuna.__version__)

Optuna version: 4.8.0

## 2. Configuration

Bạn chỉ cần sửa các biến trong cell này khi đổi dữ liệu, batch target hoặc cấu hình cluster.

In [2]:
# ============================================================
# Reproducibility
# ============================================================
RANDOM_STATE = 42

# ============================================================
# Input / output
# ============================================================
# Silver parquet đã clean từ Bronze -> Silver.
DATA_PATH = "/opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet"

# Nơi lưu CSV kết quả: Optuna trials, feature importance, AUC monitoring, ...
OUTPUT_DIR = "/opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# Target batch cần kiểm tra
# ============================================================
# Batch hiện tại sẽ được gán label = 1.
TARGET_PROCESSING_DATE_HOUR = pd.Timestamp("2025-01-15 12:00:00")

# Vì pipeline của bạn xử lý 12h/lần, batch liền trước là target - 12h.
PREVIOUS_BATCH_OFFSET = pd.Timedelta(hours=12)

# Các batch lịch sử bổ sung được gán label = 0.
# Bạn có thể thêm/bớt offset tùy dữ liệu thực tế.
HISTORY_OFFSETS = [
    pd.Timedelta(days=1),
    pd.Timedelta(days=7),
    pd.Timedelta(days=14),
]

# ============================================================
# Sampling theo từng processing_date_hour
# ============================================================
# Mỗi batch chỉ lấy tối đa số dòng này để LightGBM chạy nhanh hơn.
TARGET_SAMPLE_PER_GROUP = 10_000
MIN_ROWS_PER_GROUP = 100

# Sampling candidate lấy dư một chút trước khi limit.
# Ví dụ cần 10,000 dòng, candidate sẽ khoảng 16,000 dòng nếu batch đủ lớn.
# OVERSAMPLE_FACTOR = 1.6

# ============================================================
# Train / validation / test split
# ============================================================
TEST_SIZE = 0.15
VALID_SIZE = 0.15

# ============================================================
# Optuna / LightGBM
# ============================================================
RUN_OPTUNA = True
N_TRIALS = 100
# DEBUG_TRIAL_ERRORS = False

# SynapseML LightGBM sẽ train tối đa N_ESTIMATORS_MAX vòng.
# earlyStoppingRound sẽ dừng sớm nếu validation AUC không cải thiện.
N_ESTIMATORS_MAX = 2000
EARLY_STOPPING_ROUNDS = 100

# SHAP rất nặng trong SynapseML.
# Khuyến nghị: Optuna luôn không dùng SHAP; final model mới bật nếu cần giải thích.
RUN_FINAL_SHAP = True
SHAP_SAMPLE_SIZE = 3000

# ============================================================
# Optional experiments / monitoring
# ============================================================
RUN_SYNTHETIC_EXPERIMENTS = False
RUN_BATCH_MONITORING = False
RUN_BATCH_SHAP = False

# Batch monitoring range: chỉ dùng khi RUN_BATCH_MONITORING=True.
# BATCH_START = pd.Timestamp("2025-01-20 00:00:00")
# BATCH_END = pd.Timestamp("2025-01-31 12:00:00")
# BATCH_FREQ = "12h"

# Empirical p-value config cho chuỗi AUC.
# MIN_HISTORY_POINTS = 20
# ROLLING_WINDOW = None
# ALPHA = 0.05

# ============================================================
# SynapseML LightGBM cluster profile
# ------------------------------------------------------------
# Profile cho cụm 2 workers, mỗi worker 6 cores / khoảng 12-14GB RAM:
# spark.executor.instances = 2
# spark.executor.cores     = 6
# spark.task.cpus          = 3
# available task slots     = 2 * floor(6/3) = 4
# => LightGBM numTasks=4, numThreads=3, data repartition(4)
# ============================================================
LGBM_NUM_TASKS = 4
LGBM_NUM_THREADS = 3
LGBM_NUM_PARTITIONS = 4

# Spark preprocessing/shuffle profile.
# 4 task slots * 3 waves = 12 partitions.
SPARK_SQL_SHUFFLE_PARTITIONS = 12
SPARK_DEFAULT_PARALLELISM = 12

# Khi chạy nhiều Optuna trials trong notebook, không cố định port để tránh lỗi port busy.
USE_FIXED_PORTS = False

print("DATA_PATH:", DATA_PATH)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("TARGET_PROCESSING_DATE_HOUR:", TARGET_PROCESSING_DATE_HOUR)
print("TARGET_SAMPLE_PER_GROUP:", TARGET_SAMPLE_PER_GROUP)
print("RUN_OPTUNA:", RUN_OPTUNA, "| N_TRIALS:", N_TRIALS)
print("SynapseML profile:", {
    "numTasks": LGBM_NUM_TASKS,
    "numThreads": LGBM_NUM_THREADS,
    "partitions": LGBM_NUM_PARTITIONS,
    "shuffle_partitions": SPARK_SQL_SHUFFLE_PARTITIONS,
})

DATA_PATH: /opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet
OUTPUT_DIR: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata
TARGET_PROCESSING_DATE_HOUR: 2025-01-15 12:00:00
TARGET_SAMPLE_PER_GROUP: 10000
RUN_OPTUNA: True | N_TRIALS: 100
SynapseML profile: {'numTasks': 4, 'numThreads': 3, 'partitions': 4, 'shuffle_partitions': 12}

## 3. Start Spark session

Cell này tạo Spark session theo profile đã tối ưu. Nếu bạn chạy trong môi trường đã có Spark session, vẫn có thể giữ cell này; Spark sẽ trả về session hiện tại nếu tồn tại.

In [3]:
spark = (
    SparkSession.builder
    .appName("SynapseML LightGBM Batch Drift Detection - Clean")
    .master("spark://spark-master:7077")
    .config("spark.executor.instances", "2")
    .config("spark.executor.cores", "6")
    .config("spark.executor.memory", "10g")
    .config("spark.task.cpus", str(LGBM_NUM_THREADS))
    .config("spark.sql.shuffle.partitions", str(SPARK_SQL_SHUFFLE_PARTITIONS))
    .config("spark.default.parallelism", str(SPARK_DEFAULT_PARALLELISM))
    .config("spark.dynamicAllocation.enabled", "false")
    # .config("spark.speculation", "false")
    # .config("spark.scheduler.mode", "FIFO")
    # .config("spark.python.worker.reuse", "true")
    # .config("spark.executorEnv.OMP_NUM_THREADS", str(LGBM_NUM_THREADS))
    # .config("spark.executorEnv.MKL_NUM_THREADS", "1")
    # .config("spark.executorEnv.OPENBLAS_NUM_THREADS", "1")
    # .config("spark.executorEnv.NUMEXPR_NUM_THREADS", "1")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

conf = spark.sparkContext.getConf()


def get_conf_int(key, default):
    """Đọc Spark conf dạng int; nếu thiếu hoặc lỗi thì dùng default."""
    try:
        return int(conf.get(key, str(default)))
    except Exception:
        return int(default)


executor_instances = get_conf_int("spark.executor.instances", 2)
executor_cores = get_conf_int("spark.executor.cores", 6)
task_cpus = get_conf_int("spark.task.cpus", LGBM_NUM_THREADS)
available_task_slots = executor_instances * (executor_cores // task_cpus)

print("Spark application:", spark.sparkContext.appName)
print("Spark master:", spark.sparkContext.master)
print("executor.instances:", executor_instances)
print("executor.cores:", executor_cores)
print("spark.task.cpus:", task_cpus)
print("Available Spark task slots:", available_task_slots)
print("Expected SynapseML numTasks:", LGBM_NUM_TASKS)
print("spark.sql.shuffle.partitions:", conf.get("spark.sql.shuffle.partitions"))
print("spark.default.parallelism:", conf.get("spark.default.parallelism"))

if available_task_slots < LGBM_NUM_TASKS:
    raise ValueError(
        f"Spark chỉ có {available_task_slots} task slots nhưng LGBM_NUM_TASKS={LGBM_NUM_TASKS}. "
        "Hãy giảm LGBM_NUM_TASKS, giảm spark.task.cpus hoặc tăng executor cores."
    )

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/03 20:39:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Spark application: SynapseML LightGBM Batch Drift Detection - Clean
Spark master: spark://spark-master:7077
executor.instances: 2
executor.cores: 6
spark.task.cpus: 3
Available Spark task slots: 4
Expected SynapseML numTasks: 4
spark.sql.shuffle.partitions: 12
spark.default.parallelism: 12

## 4. Load Silver data

Ở đây ta normalize tên cột về lowercase để khớp với job Silver mới của bạn. Các cột thời gian được cast về timestamp để filter batch ổn định hơn.

In [5]:
df_raw = spark.read.parquet(DATA_PATH)
print("Raw row count:", df_raw.count())
df_raw.printSchema()
df_raw.show(5, truncate=False)

Raw row count: 3326978
root
 |-- vendorid: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: double (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- ratecodeid: double (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- pulocationid: integer (nullable = true)
 |-- dolocationid: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)
 |-- date_hour: timestamp_ntz (nullable = true)
 |-- processing_date_hour: timestamp_ntz (nullable = true)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+-------------------+--------------------+
|vendorid|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|ratecodeid|store_and_fwd_flag|pulocationid|dolocationid|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|cbd_congestion_fee|date_hour          |processing_date_hour|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+-------------------+--------------------+
|1       |2025-01-01 00:18:38 |2025-01-01 00:26:59  |1.0            |1.6          |1.0       |N                 |229         |237         |1           |10.0       |3.5  |0.5    |3.0       |0.0         |1.0                  |18.0        |2.5                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
|1       |2025-01-01 00:32:40 |2025-01-01 00:35:13  |1.0            |0.5          |1.0       |N                 |236         |237         |1           |5.1        |3.5  |0.5    |2.02      |0.0         |1.0                  |12.12       |2.5                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
|1       |2025-01-01 00:44:04 |2025-01-01 00:46:01  |1.0            |0.6          |1.0       |N                 |141         |141         |1           |5.1        |3.5  |0.5    |2.0       |0.0         |1.0                  |12.1        |2.5                 |0.0        |0.0               |2025-01-01 01:00:00|2025-01-01 12:00:00 |
|2       |2025-01-01 00:14:27 |2025-01-01 00:20:01  |3.0            |0.52         |1.0       |N                 |244         |244         |2           |7.2        |1.0  |0.5    |0.0       |0.0         |1.0                  |9.7         |0.0                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
|2       |2025-01-01 00:21:34 |2025-01-01 00:25:06  |3.0            |0.66         |1.0       |N                 |244         |116         |2           |5.8        |1.0  |0.5    |0.0       |0.0         |1.0                  |8.3         |0.0                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+-------------------+--------------------+
only showing top 5 rows

## 5. Basic overview and cache source data

Ta cache `df_raw` vì các bước sau sẽ filter nhiều lần theo `processing_date_hour`.

In [6]:
# Tổng quan range dữ liệu.
df_raw.select(
    F.count("*").alias("row_count"),
    F.min("date_hour").alias("min_date_hour"),
    F.max("date_hour").alias("max_date_hour"),
    F.min("processing_date_hour").alias("min_processing_date_hour"),
    F.max("processing_date_hour").alias("max_processing_date_hour"),
).show(truncate=False)

# Repartition theo processing_date_hour giúp các thao tác filter/sample theo batch hiệu quả hơn.
df_raw = (
    df_raw
    .repartition(SPARK_SQL_SHUFFLE_PARTITIONS, "processing_date_hour")
    .persist(StorageLevel.MEMORY_AND_DISK)
)

cached_rows = df_raw.count()
print("Cached df_raw rows:", cached_rows)

processing_counts = (
    df_raw
    .groupBy("processing_date_hour")
    .count()
    .withColumnRenamed("count", "row_count")
    .orderBy("processing_date_hour")
)

print("First processing_date_hour values:")
processing_counts.show(10, truncate=False)

print("Last processing_date_hour values:")
processing_counts.orderBy(F.desc("processing_date_hour")).show(10, truncate=False)

+---------+-------------------+-------------------+------------------------+------------------------+
|row_count|min_date_hour      |max_date_hour      |min_processing_date_hour|max_processing_date_hour|
+---------+-------------------+-------------------+------------------------+------------------------+
|3326978  |2025-01-01 00:00:00|2025-01-31 23:00:00|2025-01-01 12:00:00     |2025-02-01 00:00:00     |
+---------+-------------------+-------------------+------------------------+------------------------+

Cached df_raw rows: 3326978
First processing_date_hour values:

+--------------------+---------+
|processing_date_hour|row_count|
+--------------------+---------+
|2025-01-01 12:00:00 |36464    |
|2025-01-02 00:00:00 |45227    |
|2025-01-02 12:00:00 |19740    |
|2025-01-03 00:00:00 |61896    |
|2025-01-03 12:00:00 |21563    |
|2025-01-04 00:00:00 |66523    |
|2025-01-04 12:00:00 |22995    |
|2025-01-05 00:00:00 |71531    |
|2025-01-05 12:00:00 |25047    |
|2025-01-06 00:00:00 |53406    |
+--------------------+---------+
only showing top 10 rows

Last processing_date_hour values:
+--------------------+---------+
|processing_date_hour|row_count|
+--------------------+---------+
|2025-02-01 00:00:00 |93156    |
|2025-01-31 12:00:00 |31944    |
|2025-01-31 00:00:00 |94242    |
|2025-01-30 12:00:00 |32929    |
|2025-01-30 00:00:00 |87625    |
|2025-01-29 12:00:00 |28139    |
|2025-01-29 00:00:00 |81639    |
|2025-01-28 12:00:00 |27793    |
|2025-01-28 00:00:00 |64075    |
|2025-01-27 12:00:00 |26096    |
+--------------------+---------+
only showing top 10 rows

## 6. Define target and comparison batches

- Target batch: `label = 1`.
- Comparison/history batches: `label = 0`.

In [7]:
def filter_processing_hour(source_df, processing_hour):
    """
    Lọc dữ liệu theo processing_date_hour.
    Cột processing_date_hour đã là timestamp chuẩn nên không cần format/cast lại.
    """
    return source_df.filter(
        F.col("processing_date_hour") == F.lit(processing_hour.to_pydatetime())
    )


def get_comparison_processing_hours(target_processing_hour):
    """
    Tạo danh sách các batch lịch sử để so sánh với target batch.
    """
    target_processing_hour = pd.Timestamp(target_processing_hour)

    comparison_hours = [target_processing_hour - PREVIOUS_BATCH_OFFSET]
    comparison_hours += [
        target_processing_hour - offset
        for offset in HISTORY_OFFSETS
    ]

    return sorted(set(comparison_hours))


# Target batch: label = 1
target_processing_hour = pd.Timestamp(TARGET_PROCESSING_DATE_HOUR)

# Historical batches: label = 0
comparison_processing_hours = get_comparison_processing_hours(
    target_processing_hour
)

target_count = filter_processing_hour(
    df_raw,
    target_processing_hour
).count()

print("Target processing hour, label = 1:")
print(f"- {target_processing_hour} | rows: {target_count:,}")

print("\nComparison processing hours, label = 0:")
for processing_hour in comparison_processing_hours:
    row_count = filter_processing_hour(
        df_raw,
        processing_hour
    ).count()

    print(f"- {processing_hour} | rows: {row_count:,}")

Target processing hour, label = 1:
- 2025-01-15 12:00:00 | rows: 32,738

Comparison processing hours, label = 0:
- 2025-01-01 12:00:00 | rows: 36,464
- 2025-01-08 12:00:00 | rows: 28,758
- 2025-01-14 12:00:00 | rows: 30,435
- 2025-01-15 00:00:00 | rows: 86,467

## 7. Optimized sampling by processing hour

Đây là tối ưu quan trọng nhất so với cách `orderBy(rand()).limit()` trực tiếp trên toàn bộ batch.

In [8]:
def sample_by_processing_hour(
    source_df,
    processing_hour,
    label,
    max_rows,
    random_state,
):
    part = filter_processing_hour(source_df, processing_hour)

    part = part.withColumn("label", F.lit(float(label)))

    total_rows = part.count()

    # Nếu batch nhỏ hơn hoặc bằng max_rows, lấy toàn bộ.
    if total_rows <= max_rows:
        return part

    # Nếu batch lớn hơn max_rows, random rồi lấy đúng max_rows dòng.
    return (
        part
        .orderBy(F.rand(int(random_state)))
        .limit(int(max_rows))
    )

## 8. Build training dataset: target vs history

In [9]:
# ============================================================
# 1. Target batch: label = 1
# ============================================================

positive_df = sample_by_processing_hour(
    source_df=df_raw,
    processing_hour=target_processing_hour,
    label=1,
    max_rows=TARGET_SAMPLE_PER_GROUP,
    random_state=RANDOM_STATE,
)

positive_count = positive_df.count()

print("Positive sample:")
print(f"- processing_hour = {target_processing_hour}")
print(f"- rows = {positive_count:,}")


# ============================================================
# 2. Historical/comparison batches: label = 0
# ============================================================

negative_parts = []

for i, compare_hour in enumerate(comparison_processing_hours):
    negative_part = sample_by_processing_hour(
        source_df=df_raw,
        processing_hour=compare_hour,
        label=0,
        max_rows=TARGET_SAMPLE_PER_GROUP,
        random_state=RANDOM_STATE + i + 1,
    )

    row_count = negative_part.count()

    if row_count < MIN_ROWS_PER_GROUP:
        print(
            f"Skipped comparison hour {compare_hour} "
            f"because rows = {row_count:,} < {MIN_ROWS_PER_GROUP:,}"
        )
        continue

    print(f"Negative sample: {compare_hour} | rows = {row_count:,}")
    negative_parts.append(negative_part)


if not negative_parts:
    raise ValueError("Không có đủ dữ liệu lịch sử để tạo label = 0.")


# Gộp tất cả negative batches thành một DataFrame duy nhất.
negative_df = negative_parts[0]

for negative_part in negative_parts[1:]:
    negative_df = negative_df.unionByName(
        negative_part,
        allowMissingColumns=True,
    )


negative_count = negative_df.count()

print(f"\nNegative sample total rows: {negative_count:,}")

negative_df.groupBy("processing_date_hour") \
    .count() \
    .withColumnRenamed("count", "row_count") \
    .orderBy("processing_date_hour") \
    .show(truncate=False)

Positive sample:
- processing_hour = 2025-01-15 12:00:00
- rows = 10,000
Negative sample: 2025-01-01 12:00:00 | rows = 10,000
Negative sample: 2025-01-08 12:00:00 | rows = 10,000
Negative sample: 2025-01-14 12:00:00 | rows = 10,000
Negative sample: 2025-01-15 00:00:00 | rows = 10,000

Negative sample total rows: 40,000

[Stage 107:>(11 + 1) / 12][Stage 108:>(10 + 1) / 12][Stage 109:>(10 + 0) / 12]

+--------------------+---------+
|processing_date_hour|row_count|
+--------------------+---------+
|2025-01-01 12:00:00 |10000    |
|2025-01-08 12:00:00 |10000    |
|2025-01-14 12:00:00 |10000    |
|2025-01-15 00:00:00 |10000    |
+--------------------+---------+

In [10]:
# Gộp target batch label = 1 và history batches label = 0
work_df = positive_df.unionByName(
    negative_df,
    allowMissingColumns=True,
)

work_df = work_df.persist(StorageLevel.MEMORY_AND_DISK)

# Kích hoạt cache và kiểm tra kích thước dataset
row_count = work_df.count()
col_count = len(work_df.columns)

print("Work dataset shape:", (row_count, col_count))

# Kiểm tra số dòng theo từng label và từng processing batch
work_df.groupBy("label", "processing_date_hour") \
    .count() \
    .withColumnRenamed("count", "row_count") \
    .orderBy("label", "processing_date_hour") \
    .show(truncate=False)

Work dataset shape: (50000, 23)
+-----+--------------------+---------+
|label|processing_date_hour|row_count|
+-----+--------------------+---------+
|0.0  |2025-01-01 12:00:00 |10000    |
|0.0  |2025-01-08 12:00:00 |10000    |
|0.0  |2025-01-14 12:00:00 |10000    |
|0.0  |2025-01-15 00:00:00 |10000    |
|1.0  |2025-01-15 12:00:00 |10000    |
+-----+--------------------+---------+

## 9. Feature configuration

Không đưa các cột thời gian và label vào mô hình để tránh leakage. Mục tiêu là kiểm tra phân phối của các feature nghiệp vụ, không để mô hình học trực tiếp batch time.

In [11]:
# Không dùng các cột này làm feature.
EXCLUDE_COLS = [
    "label",
    "date_hour",
    "processing_date_hour",
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
]

# Categorical/code columns.
CATEGORICAL_COLS = [
    "vendorid",
    "ratecodeid",
    "store_and_fwd_flag",
    "payment_type",
]

# Numeric columns.
NUMERIC_COLS = [
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "pulocationid",
    "dolocationid",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee",
    "cbd_congestion_fee",
]

# Chỉ giữ cột thật sự tồn tại trong dataset.
CATEGORICAL_COLS = [c for c in CATEGORICAL_COLS if c in work_df.columns]
NUMERIC_COLS = [c for c in NUMERIC_COLS if c in work_df.columns]

print("Excluded columns:", [c for c in EXCLUDE_COLS if c in work_df.columns])
print("Categorical columns:", CATEGORICAL_COLS)
print("Numeric columns:", NUMERIC_COLS)

Excluded columns: ['label', 'date_hour', 'processing_date_hour', 'tpep_pickup_datetime', 'tpep_dropoff_datetime']
Categorical columns: ['vendorid', 'ratecodeid', 'store_and_fwd_flag', 'payment_type']
Numeric columns: ['passenger_count', 'trip_distance', 'fare_amount', 'pulocationid', 'dolocationid', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'cbd_congestion_fee']

In [20]:
# ============================================================
# Missing value summary for raw feature columns
# ============================================================

def build_missing_summary(input_df, feature_cols, numeric_cols):
    """
    Tính missing value cho các feature columns.

    Quy ước:
    - Numeric columns: missing nếu NULL hoặc NaN.
    - Non-numeric columns: missing nếu NULL.
    """

    # Chỉ giữ các cột thật sự tồn tại trong DataFrame
    existing_cols = [
        col for col in feature_cols
        if col in input_df.columns
    ]

    numeric_col_set = set(numeric_cols)

    total_rows = input_df.count()

    missing_exprs = []

    for col in existing_cols:
        if col in numeric_col_set:
            # Numeric: check cả NULL và NaN
            expr = F.sum(
                F.when(
                    F.col(col).isNull() | F.isnan(F.col(col).cast("double")),
                    1
                ).otherwise(0)
            ).alias(col)
        else:
            # Categorical/string: chỉ check NULL
            expr = F.sum(
                F.when(F.col(col).isNull(), 1).otherwise(0)
            ).alias(col)

        missing_exprs.append(expr)

    missing_row = input_df.select(missing_exprs).first().asDict()

    missing_summary_df = pd.DataFrame([
        {
            "column": col,
            "missing_count": int(missing_row[col]),
            "missing_rate_pct": (
                int(missing_row[col]) / total_rows * 100
                if total_rows > 0 else 0.0
            ),
        }
        for col in existing_cols
    ])

    missing_summary_df = missing_summary_df.sort_values(
        "missing_count",
        ascending=False,
    )

    return missing_summary_df


# Các cột raw feature cần kiểm tra missing
raw_feature_cols = CATEGORICAL_COLS + NUMERIC_COLS

missing_summary_df = build_missing_summary(
    input_df=work_df,
    feature_cols=raw_feature_cols,
    numeric_cols=NUMERIC_COLS,
)

display(missing_summary_df)

missing_path = f"{OUTPUT_DIR}/feature_missing_summary.csv"
missing_summary_df.to_csv(missing_path, index=False)

print("Saved:", missing_path)

                   column  missing_count  missing_rate_pct
4         passenger_count           7782            15.564
2      store_and_fwd_flag           7782            15.564
15   congestion_surcharge           7782            15.564
16            airport_fee           7782            15.564
1              ratecodeid              0             0.000
0                vendorid              0             0.000
6             fare_amount              0             0.000
7            pulocationid              0             0.000
3            payment_type              0             0.000
5           trip_distance              0             0.000
9                   extra              0             0.000
8            dolocationid              0             0.000
10                mta_tax              0             0.000
11             tip_amount              0             0.000
13  improvement_surcharge              0             0.000
12           tolls_amount              0             0.000
14           total_amount              0             0.000
17     cbd_congestion_fee              0             0.000

Saved: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/feature_missing_summary.csv

## 10. Stratified split utilities

Spark không có `train_test_split(..., stratify=y)` như sklearn. Vì vậy cell này tạo split gần tương đương:

- Tổng số dòng test ≈ `round(TEST_SIZE * total)`.
- Tổng số dòng validation ≈ `round(VALID_SIZE * total)`.
- Tỷ lệ label trong train/valid/test gần giống nhau.
- Dùng hash theo row id để random ổn định hơn `orderBy(rand())`.

In [14]:
# ============================================================
# Exact stratified train / valid / test split
# Gần giống logic train_test_split(stratify=y) của sklearn
# ============================================================

from pyspark.sql import Window
import pyspark.sql.functions as F
from pyspark.storagelevel import StorageLevel


def stratified_split_exact(
    input_df,
    label_col="label",
    test_size=TEST_SIZE,
    valid_size=VALID_SIZE,
    seed=RANDOM_STATE,
):
    """
    Chia dữ liệu thành train / valid / test có stratify theo label.

    Mục tiêu:
    - Giữ tỷ lệ label gần như chính xác trong từng split.
    - Số dòng valid/test ổn định hơn randomSplit().
    - Logic dễ hiểu hơn bản allocation phức tạp.

    Cách làm:
    1. Đếm số dòng của từng label.
    2. Với mỗi label, tính:
       - n_test_label  = round(test_size  * số dòng label đó)
       - n_valid_label = round(valid_size * số dòng label đó)
    3. Random thứ tự dữ liệu trong từng label.
    4. Lấy:
       - dòng 1 → n_test_label cho test
       - dòng tiếp theo → n_valid_label cho valid
       - phần còn lại cho train
    """
    # Ép label về double để thống nhất với SynapseML LightGBM
    base_df = input_df.withColumn(
        label_col,
        F.col(label_col).cast("double"),
    )

    # Đếm số dòng theo từng label và tính số dòng cần lấy cho test/valid
    label_count_df = (
        base_df
        .groupBy(label_col)
        .count()
        .withColumn("_n_test", F.round(F.col("count") * F.lit(test_size)).cast("long"))
        .withColumn("_n_valid", F.round(F.col("count") * F.lit(valid_size)).cast("long"))
        .drop("count")
    )

    labels = [row[label_col] for row in label_count_df.select(label_col).collect()]

    # Random thứ tự bên trong từng label
    window_by_label = Window.partitionBy(label_col).orderBy(F.rand(seed))

    split_df = (
        base_df
        .join(F.broadcast(label_count_df), on=label_col, how="left")
        .withColumn("_row_number", F.row_number().over(window_by_label))
        .withColumn(
            "_split",
            F.when(F.col("_row_number") <= F.col("_n_test"), F.lit("test"))
             .when(F.col("_row_number") <= F.col("_n_test") + F.col("_n_valid"), F.lit("valid"))
             .otherwise(F.lit("train"))
        )
        .drop("_row_number", "_n_test", "_n_valid")
    )

    train_df = split_df.filter(F.col("_split") == "train").drop("_split")
    valid_df = split_df.filter(F.col("_split") == "valid").drop("_split")
    test_df = split_df.filter(F.col("_split") == "test").drop("_split")

    return train_df, valid_df, test_df


def get_count_and_positive_rate(input_df, label_col="label"):
    """
    Trả về số dòng và tỷ lệ label = 1.
    """
    row = input_df.select(
        F.count("*").alias("row_count"),
        F.avg(F.col(label_col).cast("double")).alias("positive_rate"),
    ).first()

    return int(row["row_count"]), float(row["positive_rate"] or 0.0)


def print_split_report(train_df, valid_df, test_df, label_col="label"):
    """
    In báo cáo để kiểm tra kết quả split.
    """
    print("========== Split Report ==========")

    for split_name, split_df in [
        ("Train", train_df),
        ("Valid", valid_df),
        ("Test ", test_df),
    ]:
        row_count, positive_rate = get_count_and_positive_rate(
            split_df,
            label_col=label_col,
        )

        print(
            f"{split_name}: "
            f"rows={row_count:,} | "
            f"columns={len(split_df.columns)} | "
            f"positive_rate={positive_rate:.6f}"
        )

        split_df.groupBy(label_col) \
            .count() \
            .orderBy(label_col) \
            .show()

## 11. Feature pipeline

Cell này làm 3 việc:

1. Numeric columns → cast sang `double`.
2. String categorical columns → `StringIndexer`.
3. Ghép tất cả feature vào cột vector `features` để SynapseML LightGBM sử dụng.

In [16]:
class TaxiFeaturePipeline:
    """
    Feature pipeline cho Spark / SynapseML LightGBM.

    Mục tiêu:
    - Chuyển dữ liệu raw thành cột "features" để đưa vào LightGBM.
    - Giữ cách xử lý gần giống notebook LightGBM thường.
    - Không tự tạo thêm __isnull features.
    - Không fill missing numeric, vì LightGBM có thể xử lý missing value.
    - String categorical được encode bằng StringIndexer.
    - Numeric categorical được giữ dạng số và khai báo categoricalSlotIndexes.
    """

    def __init__(
        self,
        categorical_cols,
        numeric_cols,
        exclude_cols,
        label_col="label",
        features_col="features",
    ):
        self.categorical_cols = list(categorical_cols)
        self.numeric_cols = list(numeric_cols)
        self.exclude_cols = set(exclude_cols)
        self.label_col = label_col
        self.features_col = features_col

        # Các biến được xác định sau khi fit()
        self.numeric_feature_cols_ = []
        self.categorical_numeric_cols_ = []
        self.categorical_string_cols_ = []
        self.string_indexed_cols_ = []

        self.feature_cols_ = []
        self.categorical_slot_indexes_ = []

        self.string_indexer_model_ = None
        self.assembler_ = None

    def fit(self, train_df):
        """
        Fit pipeline trên train_df.

        Lưu ý:
        - Chỉ fit StringIndexer trên train set để tránh data leakage.
        - Valid/test chỉ transform bằng mapping đã học từ train.
        """

        available_cols = set(train_df.columns)
        schema_map = {
            field.name: field.dataType
            for field in train_df.schema.fields
        }

        categorical_set = set(self.categorical_cols)

        # ----------------------------------------------------
        # 1. Chọn numeric features
        # ----------------------------------------------------
        # Nếu một cột vừa nằm trong numeric_cols vừa nằm trong categorical_cols,
        # ưu tiên xem nó là categorical để tránh duplicate feature.
        self.numeric_feature_cols_ = [
            col
            for col in self.numeric_cols
            if col in available_cols
            and col not in self.exclude_cols
            and col not in categorical_set
        ]

        # ----------------------------------------------------
        # 2. Tách categorical thành:
        #    - string categorical: cần StringIndexer
        #    - numeric categorical: giữ dạng số, nhưng khai báo categoricalSlotIndexes
        # ----------------------------------------------------
        self.categorical_string_cols_ = []
        self.categorical_numeric_cols_ = []

        for col in self.categorical_cols:
            if col not in available_cols or col in self.exclude_cols:
                continue

            dtype = schema_map[col]

            if isinstance(dtype, T.StringType):
                self.categorical_string_cols_.append(col)
            else:
                self.categorical_numeric_cols_.append(col)

        # ----------------------------------------------------
        # 3. Fit StringIndexer cho các categorical dạng string
        # ----------------------------------------------------
        self.string_indexed_cols_ = [
            f"{col}__idx"
            for col in self.categorical_string_cols_
        ]

        if self.categorical_string_cols_:
            indexer = StringIndexer(
                inputCols=self.categorical_string_cols_,
                outputCols=self.string_indexed_cols_,
                handleInvalid="keep",
            )

            self.string_indexer_model_ = indexer.fit(train_df)
        else:
            self.string_indexer_model_ = None

        # ----------------------------------------------------
        # 4. Xác định thứ tự feature trong vector
        # ----------------------------------------------------
        self.feature_cols_ = (
            self.numeric_feature_cols_
            + self.categorical_numeric_cols_
            + self.string_indexed_cols_
        )

        if not self.feature_cols_:
            raise ValueError("Không có feature nào để đưa vào VectorAssembler.")

        # ----------------------------------------------------
        # 5. Xác định categorical slot indexes cho LightGBM
        # ----------------------------------------------------
        categorical_feature_cols = (
            self.categorical_numeric_cols_
            + self.string_indexed_cols_
        )

        self.categorical_slot_indexes_ = [
            self.feature_cols_.index(col)
            for col in categorical_feature_cols
        ]

        # ----------------------------------------------------
        # 6. Tạo VectorAssembler
        # ----------------------------------------------------
        self.assembler_ = VectorAssembler(
            inputCols=self.feature_cols_,
            outputCol=self.features_col,
            handleInvalid="keep",
        )

        return self

    def _clean_numeric_column(self, col_name):
        """
        Cast một cột sang double và chuyển NaN/inf thành null.

        Vì sao:
        - Spark ML vector dùng numeric/double.
        - LightGBM xử lý missing value tốt hơn là để inf.
        """

        x = F.col(col_name).cast("double")

        return (
            F.when(
                F.isnan(x)
                | (x == float("inf"))
                | (x == float("-inf")),
                F.lit(None).cast("double"),
            )
            .otherwise(x)
            .alias(col_name)
        )

    def transform(self, input_df):
        """
        Transform DataFrame thành DataFrame có cột features.

        Output:
        - Giữ các cột gốc cần thiết.
        - Thêm các cột indexed cho string categorical.
        - Thêm cột features.
        """

        if self.assembler_ is None:
            raise RuntimeError("Pipeline chưa được fit. Hãy gọi .fit(train_df) trước.")

        df = input_df

        # ----------------------------------------------------
        # 1. Cast numeric và numeric categorical sang double
        # ----------------------------------------------------
        cols_to_cast = set(
            self.numeric_feature_cols_
            + self.categorical_numeric_cols_
        )

        select_exprs = []

        for col in df.columns:
            if col in cols_to_cast:
                select_exprs.append(self._clean_numeric_column(col))
            else:
                select_exprs.append(F.col(col))

        df = df.select(*select_exprs)

        # ----------------------------------------------------
        # 2. Encode string categorical bằng StringIndexer model đã fit
        # ----------------------------------------------------
        if self.string_indexer_model_ is not None:
            df = self.string_indexer_model_.transform(df)

        # ----------------------------------------------------
        # 3. Ghép các feature thành vector features
        # ----------------------------------------------------
        df = self.assembler_.transform(df)

        return df

## 12. Split data and build features

In [15]:
# ============================================================
# Run exact stratified split
# ============================================================

train_df, valid_df, test_df = stratified_split_exact(
    input_df=work_df,
    label_col="label",
    test_size=TEST_SIZE,
    valid_size=VALID_SIZE,
    seed=RANDOM_STATE,
)

# Cache vì các DataFrame này sẽ dùng nhiều lần phía sau:
# feature pipeline, training, evaluation.
train_df = train_df.persist(StorageLevel.MEMORY_AND_DISK)
valid_df = valid_df.persist(StorageLevel.MEMORY_AND_DISK)
test_df = test_df.persist(StorageLevel.MEMORY_AND_DISK)

# Trigger cache
train_df.count()
valid_df.count()
test_df.count()

print_split_report(
    train_df=train_df,
    valid_df=valid_df,
    test_df=test_df,
    label_col="label",
)

26/05/03 21:39:28 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

========== Split Report ==========
Train: rows=35,000 | columns=23 | positive_rate=0.200000
+-----+-----+
|label|count|
+-----+-----+
|  0.0|28000|
|  1.0| 7000|
+-----+-----+

Valid: rows=7,500 | columns=23 | positive_rate=0.200000
+-----+-----+
|label|count|
+-----+-----+
|  0.0| 6000|
|  1.0| 1500|
+-----+-----+

Test : rows=7,500 | columns=23 | positive_rate=0.200000
+-----+-----+
|label|count|
+-----+-----+
|  0.0| 6000|
|  1.0| 1500|
+-----+-----+

In [18]:
# ============================================================
# Build feature vector for SynapseML LightGBM
# ============================================================

# Fit feature pipeline only on train set to avoid data leakage.
feature_pipeline = TaxiFeaturePipeline(
    categorical_cols=CATEGORICAL_COLS,
    numeric_cols=NUMERIC_COLS,
    exclude_cols=EXCLUDE_COLS,
    label_col="label",
    features_col="features",
)

feature_pipeline.fit(train_df)


# ============================================================
# Check selected features
# ============================================================

print("========== Feature Pipeline Summary ==========")
print("Numeric feature columns:")
print(feature_pipeline.numeric_feature_cols_)

print("\nCategorical numeric columns:")
print(feature_pipeline.categorical_numeric_cols_)

print("\nCategorical string columns:")
print(feature_pipeline.categorical_string_cols_)

print("\nString indexed columns:")
print(feature_pipeline.string_indexed_cols_)

print("\nFinal feature columns:")
print(feature_pipeline.feature_cols_)

print("\nCategorical slot indexes for LightGBM:")
print(feature_pipeline.categorical_slot_indexes_)

print("=============================================\n")


# ============================================================
# Transform train / valid / test into LightGBM input format
# ============================================================

train_features_df = (
    feature_pipeline
    .transform(train_df)
    .select("features", "label")
)

valid_features_df = (
    feature_pipeline
    .transform(valid_df)
    .select("features", "label")
)

test_features_df = (
    feature_pipeline
    .transform(test_df)
    .select("features", "label")
)

train_features_df = train_features_df.persist(StorageLevel.MEMORY_AND_DISK)
valid_features_df = valid_features_df.persist(StorageLevel.MEMORY_AND_DISK)
test_features_df = test_features_df.persist(StorageLevel.MEMORY_AND_DISK)


# Trigger cache and print row counts
train_feature_count = train_features_df.count()
valid_feature_count = valid_features_df.count()
test_feature_count = test_features_df.count()

print("Feature dataset rows:")
print(f"- Train: {train_feature_count:,}")
print(f"- Valid: {valid_feature_count:,}")
print(f"- Test : {test_feature_count:,}")


# ============================================================
# Quick sample check
# ============================================================

print("\nSample feature rows on train:")
train_features_df.show(5, truncate=False)

========== Feature Pipeline Summary ==========
Numeric feature columns:
['passenger_count', 'trip_distance', 'fare_amount', 'pulocationid', 'dolocationid', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'cbd_congestion_fee']

Categorical numeric columns:
['vendorid', 'ratecodeid', 'payment_type']

Categorical string columns:
['store_and_fwd_flag']

String indexed columns:
['store_and_fwd_flag__idx']

Final feature columns:
['passenger_count', 'trip_distance', 'fare_amount', 'pulocationid', 'dolocationid', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'cbd_congestion_fee', 'vendorid', 'ratecodeid', 'payment_type', 'store_and_fwd_flag__idx']

Categorical slot indexes for LightGBM:
[14, 15, 16, 17]
=============================================

Feature dataset rows:
- Train: 35,000
- Valid: 7,500
- Test : 7,500

Sample feature rows:
+----------------------------------------------------------------------------------+-----+
|features                                                                          |label|
+----------------------------------------------------------------------------------+-----+
|[1.0,9.85,38.7,132.0,196.0,0.0,0.5,0.0,0.0,1.0,41.95,0.0,1.75,0.0,2.0,1.0,2.0,0.0]|0.0  |
|[1.0,1.14,9.3,163.0,237.0,0.0,0.5,2.81,0.0,1.0,16.86,2.5,0.0,0.75,2.0,1.0,1.0,0.0]|0.0  |
|[1.0,2.6,15.6,236.0,161.0,3.25,0.5,4.05,0.0,1.0,24.4,2.5,0.0,0.75,1.0,1.0,1.0,0.0]|0.0  |
|[1.0,0.42,4.4,68.0,246.0,0.0,0.5,1.0,0.0,1.0,10.15,2.5,0.0,0.75,2.0,1.0,1.0,0.0]  |0.0  |
|[1.0,0.6,5.8,237.0,141.0,2.5,0.5,1.95,0.0,1.0,11.75,2.5,0.0,0.0,1.0,1.0,1.0,0.0]  |0.0  |
+----------------------------------------------------------------------------------+-----+
only showing top 5 rows

## 14. SynapseML LightGBM helper functions

Các hàm dưới đây giúp:

- Gộp train + valid cho SynapseML thông qua `validationIndicatorCol`.
- Chuẩn hóa params để tránh nhầm tên param giữa LightGBM Python và SynapseML.
- Train/evaluate AUC.

In [21]:
# ============================================================
# SynapseML LightGBM helper functions
# ============================================================

from synapse.ml.lightgbm import LightGBMClassifier
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.functions import vector_to_array
from pyspark.storagelevel import StorageLevel
import pyspark.sql.functions as F


# Evaluator dùng chung cho baseline, Optuna và final model
auc_evaluator = BinaryClassificationEvaluator(
    labelCol="label",
    rawPredictionCol="rawPrediction",
    metricName="areaUnderROC",
)


def build_lgbm_train_valid_df(
    train_features_df,
    valid_features_df,
    num_partitions=None,
    persist=True,
):
    """
    Gộp train + valid thành một DataFrame cho SynapseML LightGBM.

    Vì SynapseML LightGBM hỗ trợ early stopping bằng validationIndicatorCol:
    - is_validation = False  -> dòng train
    - is_validation = True   -> dòng validation

    Input:
    - train_features_df: DataFrame có cột features, label
    - valid_features_df: DataFrame có cột features, label

    Output:
    - DataFrame có cột features, label, is_validation
    """

    # Dữ liệu train
    train_part = (
        train_features_df
        .select(
            F.col("features"),
            F.col("label").cast("double").alias("label"),
        )
        .withColumn("is_validation", F.lit(False))
    )

    # Dữ liệu validation
    valid_part = (
        valid_features_df
        .select(
            F.col("features"),
            F.col("label").cast("double").alias("label"),
        )
        .withColumn("is_validation", F.lit(True))
    )

    # Gộp train + validation
    lgbm_train_df = train_part.unionByName(valid_part)

    # Với SynapseML LightGBM, số partition nên gần với số LightGBM tasks.
    # Ví dụ NUM_TASKS = 4 thì repartition(4) là hợp lý.
    if num_partitions is not None:
        lgbm_train_df = lgbm_train_df.repartition(int(num_partitions))

    # Cache vì DataFrame này có thể được dùng nhiều lần trong baseline/Optuna/final model.
    if persist:
        lgbm_train_df = lgbm_train_df.persist(StorageLevel.MEMORY_AND_DISK)
        lgbm_train_df.count()  # trigger cache

    return lgbm_train_df


def build_lgbm_params(overrides=None):
    """
    Tạo bộ tham số SynapseML LightGBM.

    overrides:
    - Dùng để truyền tham số từ baseline hoặc Optuna.
    - Ví dụ: {"learningRate": 0.05, "numLeaves": 31}

    Lưu ý:
    - Dùng tên tham số của SynapseML: learningRate, numLeaves, maxDepth...
    - Không dùng tên kiểu LightGBM Python: learning_rate, num_leaves...
    """

    params = {
        # Model objective / metric
        "objective": "binary",
        "metric": "auc",

        # Columns
        "featuresCol": "features",
        "labelCol": "label",
        "validationIndicatorCol": "is_validation",

        # Core LightGBM parameters
        "learningRate": 0.05,
        "numLeaves": 31,
        "maxDepth": -1,
        "minDataInLeaf": 20,
        "baggingFraction": 1.0,
        "baggingFreq": 0,
        "featureFraction": 1.0,
        "lambdaL1": 0.0,
        "lambdaL2": 0.0,
        "minGainToSplit": 0.0,
        "maxBin": 255,

        # Training control
        "numIterations": N_ESTIMATORS_MAX,
        "earlyStoppingRound": EARLY_STOPPING_ROUNDS,

        # Distributed LightGBM control
        "numTasks": LGBM_NUM_TASKS,
        "numThreads": LGBM_NUM_THREADS,
        "maxStreamingOMPThreads": LGBM_NUM_THREADS,

        # Stability/runtime options
        "timeout": 600,
        "useBarrierExecutionMode": True,
        "useSingleDatasetMode": True,
        "dataTransferMode": "streaming",
        "verbosity": -1,
    }

    if overrides:
        params.update(overrides)

    # Fixed ports giúp tránh conflict khi chạy notebook nhiều lần.
    # Nếu không dùng fixed ports thì để SynapseML tự chọn.
    if USE_FIXED_PORTS:
        params["driverListenPort"] = 12400
        params["defaultListenPort"] = 12401

    return params


def build_lgbm_classifier(
    params=None,
    categorical_slot_indexes=None,
    shap_col=None,
):
    """
    Tạo SynapseML LightGBMClassifier.

    categorical_slot_indexes:
    - Danh sách vị trí categorical features trong vector features.
    - Lấy từ feature_pipeline.categorical_slot_indexes_.

    shap_col:
    - Nếu truyền vào, SynapseML sẽ tạo thêm cột SHAP.
    - Chỉ bật khi cần giải thích final model vì transform sẽ chậm hơn.
    """

    lgbm_params = build_lgbm_params(params)

    if categorical_slot_indexes:
        lgbm_params["categoricalSlotIndexes"] = [
            int(x) for x in categorical_slot_indexes
        ]

    if shap_col:
        lgbm_params["featuresShapCol"] = shap_col

    return LightGBMClassifier(**lgbm_params)


def evaluate_auc(model, eval_df):
    """
    Tính AUC cho một DataFrame đã có features và label.

    Dùng cho:
    - baseline validation AUC
    - Optuna validation AUC
    - final test AUC
    """
    pred_df = model.transform(eval_df)
    auc = float(auc_evaluator.evaluate(pred_df))

    return auc


def predict_and_evaluate_auc(model, eval_df, persist_predictions=False):
    """
    Transform dữ liệu và tính AUC.

    Dùng khi bạn cần giữ lại prediction để:
    - tính classification report
    - lấy probability
    - phân tích lỗi
    - tính SHAP nếu model có bật featuresShapCol
    """
    pred_df = model.transform(eval_df)
    auc = float(auc_evaluator.evaluate(pred_df))

    keep_cols = [
        "features",
        "label",
        "rawPrediction",
        "probability",
        "prediction",
        "featuresShap",
    ]
    keep_cols = [col for col in keep_cols if col in pred_df.columns]
    pred_df = pred_df.select(*keep_cols)

    if persist_predictions:
        pred_df = pred_df.persist(StorageLevel.MEMORY_AND_DISK)
        pred_df.count()

    return auc, pred_df


def prediction_to_pandas(pred_df):
    """
    Chuyển prediction của Spark về pandas.

    Output gồm:
    - y_true: label thật
    - pred_score: xác suất model dự đoán label = 1

    Dùng để tính thêm metric ngoài Spark, ví dụ:
    - sklearn classification_report
    - confusion matrix
    - ROC curve
    """
    return (
        pred_df
        .select(
            F.col("label").cast("double").alias("y_true"),
            vector_to_array("probability")[1].cast("double").alias("pred_score"),
        )
        .toPandas()
    )


def get_best_iteration(model):
    """
    Lấy best iteration nếu SynapseML model expose thông tin này.

    Không phải version nào cũng expose giống nhau, nên hàm này thử nhiều tên method.
    Nếu không lấy được thì trả về None.
    """
    for attr in ["getBestIteration", "bestIteration", "best_iteration"]:
        try:
            value = getattr(model, attr)
            value = value() if callable(value) else value

            if value is not None:
                return int(value)
        except Exception:
            pass

    return None

## 15. Build reusable LightGBM train/eval DataFrames

DataFrame `lgbm_train_df` gồm cả train và validation, có cột `is_validation`. SynapseML LightGBM dùng cột này để early stopping.

In [22]:
lgbm_train_valid_df = build_lgbm_train_valid_df(
    train_features_df=train_features_df,
    valid_features_df=valid_features_df,
    num_partitions=LGBM_NUM_PARTITIONS,
    persist=True,
)

print("LightGBM train+valid rows:", lgbm_train_valid_df.count())

lgbm_train_valid_df.groupBy("is_validation", "label") \
    .count() \
    .orderBy("is_validation", "label") \
    .show()

LightGBM train+valid rows: 42500
+-------------+-----+-----+
|is_validation|label|count|
+-------------+-----+-----+
|        false|  0.0|28000|
|        false|  1.0| 7000|
|         true|  0.0| 6000|
|         true|  1.0| 1500|
+-------------+-----+-----+

## 16. Baseline SynapseML LightGBM

Baseline dùng params gần với LightGBM thường để có mốc so sánh với Optuna.

In [23]:
# ============================================================
# Baseline SynapseML LightGBM
# ============================================================

import time
import json
import gc


# Bộ tham số baseline, cố gắng khớp với LightGBM thường.
# Lưu ý:
# - Dùng tên tham số của SynapseML: learningRate, numLeaves, maxDepth...
# - Không dùng tên LightGBM Python như learning_rate, num_leaves.
baseline_params = {
    "learningRate": 0.05,
    "numLeaves": 31,
    "maxDepth": -1,
    "minDataInLeaf": 20,

    "baggingFraction": 1.0,
    "baggingFreq": 0,
    "featureFraction": 1.0,

    "lambdaL1": 1e-8,
    "lambdaL2": 1e-8,
    "minGainToSplit": 0.0,

    # 255 khớp LightGBM thường.
    # Nếu SynapseML/cluster hay lỗi native memory, có thể đổi về 127.
    "maxBin": 255,
}


def train_lgbm_baseline(
    params,
    train_valid_df,
    valid_df,
    test_df,
    categorical_slot_indexes,
    shap_col=None,
    keep_test_predictions=False,
):
    """
    Train baseline SynapseML LightGBM và đánh giá AUC trên valid/test.

    Input:
    - params:
        Bộ tham số LightGBM baseline hoặc Optuna.
    - train_valid_df:
        DataFrame đã gộp train + valid.
        Phải có cột:
        + features
        + label
        + is_validation
    - valid_df:
        DataFrame validation có features, label.
    - test_df:
        DataFrame test có features, label.
    - categorical_slot_indexes:
        Vị trí các categorical features trong vector features.
    - shap_col:
        Tên cột SHAP nếu muốn bật SHAP.
        Baseline thường để None cho nhanh.
    - keep_test_predictions:
        Nếu True, trả về thêm test prediction DataFrame.
        Nếu False, chỉ tính AUC để tiết kiệm memory.

    Output:
    - result: dict chứa valid_auc, test_auc, best_iteration, fit_seconds
    - model: SynapseML LightGBM model đã train
    - test_pred_df: prediction trên test nếu keep_test_predictions=True, ngược lại None
    """

    # Tạo estimator từ params.
    estimator = build_lgbm_classifier(
        params=params,
        categorical_slot_indexes=categorical_slot_indexes,
        shap_col=shap_col,
    )

    # Train model.
    start_time = time.time()
    model = estimator.fit(train_valid_df)
    fit_seconds = time.time() - start_time

    # Đánh giá AUC trên validation set.
    valid_auc = evaluate_auc(
        model=model,
        eval_df=valid_df,
    )

    # Đánh giá AUC trên test set.
    if keep_test_predictions:
        test_auc, test_pred_df = predict_and_evaluate_auc(
            model=model,
            eval_df=test_df,
            persist_predictions=True,
        )
    else:
        test_auc = evaluate_auc(
            model=model,
            eval_df=test_df,
        )
        test_pred_df = None

    result = {
        "valid_auc": float(valid_auc),
        "test_auc": float(test_auc),
        "best_iteration": get_best_iteration(model),
        "fit_seconds": float(fit_seconds),
    }

    return result, model, test_pred_df

In [24]:

# ============================================================
# Run baseline training
# ============================================================

baseline_result, baseline_model, baseline_test_pred_df = train_lgbm_baseline(
    params=baseline_params,
    train_valid_df=lgbm_train_valid_df,
    valid_df=valid_features_df,
    test_df=test_features_df,
    categorical_slot_indexes=feature_pipeline.categorical_slot_indexes_,
    shap_col=None,
    keep_test_predictions=False,
)

baseline_valid_auc = baseline_result["valid_auc"]
baseline_test_auc = baseline_result["test_auc"]

print("========== Baseline Result ==========")
print(json.dumps(baseline_result, indent=2, default=str))
print("=====================================")

gc.collect()

[LightGBM] [Info] Saving data reference to binary buffer

========== Baseline Result ==========
{
  "valid_auc": 0.6984680555555556,
  "test_auc": 0.7033878333333332,
  "best_iteration": null,
  "fit_seconds": 7.492920875549316
}
=====================================

695

## 17. Optuna tuning

Optuna chỉ tối ưu trên validation AUC. Không bật SHAP trong trial để tránh mỗi trial bị chậm quá nhiều.

In [25]:
# ============================================================
# Optuna tuning for SynapseML LightGBM
# ============================================================

import gc
import json
import optuna

from optuna.samplers import TPESampler
from optuna.pruners import NopPruner


def suggest_lgbm_params(trial):
    """
    Search space cho SynapseML LightGBM.

    Lưu ý:
    - Chỉ return các tham số cần tune.
    - Các tham số fixed như numTasks, numThreads, numIterations,
      earlyStoppingRound... sẽ được thêm trong build_lgbm_params().
    """

    params = {
        # Learning speed
        "learningRate": trial.suggest_float(
            "learningRate",
            0.01,
            0.20,
            log=True,
        ),

        # Tree complexity
        "numLeaves": trial.suggest_categorical(
            "numLeaves",
            [15, 31, 63, 127],
        ),
        "maxDepth": trial.suggest_categorical(
            "maxDepth",
            [-1, 4, 6, 8, 10, 12],
        ),
        "minDataInLeaf": trial.suggest_categorical(
            "minDataInLeaf",
            [10, 20, 50, 100, 200],
        ),

        # Row sampling
        "baggingFraction": trial.suggest_float(
            "baggingFraction",
            0.7,
            1.0,
        ),
        "baggingFreq": trial.suggest_categorical(
            "baggingFreq",
            [0, 1, 3, 5],
        ),

        # Feature sampling
        "featureFraction": trial.suggest_float(
            "featureFraction",
            0.7,
            1.0,
        ),

        # Regularization
        "lambdaL1": trial.suggest_float(
            "lambdaL1",
            1e-8,
            10.0,
            log=True,
        ),
        "lambdaL2": trial.suggest_float(
            "lambdaL2",
            1e-8,
            10.0,
            log=True,
        ),
        "minGainToSplit": trial.suggest_float(
            "minGainToSplit",
            0.0,
            1.0,
        ),

        # Histogram bins
        # 255 khớp LightGBM thường.
        # Nếu cluster hay lỗi native memory, 127 thường an toàn hơn.
        "maxBin": trial.suggest_categorical(
            "maxBin",
            [63, 127, 255],
        ),
    }

    return params


def objective(trial):
    """
    Optuna objective.

    Mục tiêu:
    - Train một SynapseML LightGBM model với params do Optuna đề xuất.
    - Tối ưu validation AUC.
    - Lưu thêm test AUC, best_iteration, fit_seconds để theo dõi.
    """

    params = suggest_lgbm_params(trial)

    try:
        result, model, _ = train_lgbm_baseline(
            params=params,
            train_valid_df=lgbm_train_valid_df,
            valid_df=valid_features_df,
            test_df=test_features_df,
            categorical_slot_indexes=feature_pipeline.categorical_slot_indexes_,
            shap_col=None,
            keep_test_predictions=False,
        )

        # Lưu thông tin phụ để xem lại sau khi tuning
        trial.set_user_attr("test_auc", result["test_auc"])
        trial.set_user_attr("best_iteration", result["best_iteration"])
        trial.set_user_attr("fit_seconds", result["fit_seconds"])

        return float(result["valid_auc"])

    except Exception as e:
        print(f"[Trial {trial.number}] failed: {repr(e)}")

        if DEBUG_TRIAL_ERRORS:
            raise

        # 0.5 tương đương random classifier cho AUC
        return 0.5

    finally:
        try:
            del model
        except Exception:
            pass

        gc.collect()


# ============================================================
# Create Optuna study
# ============================================================

# SynapseML LightGBM không expose intermediate validation AUC từng boosting round
# về Python như LightGBM thường, nên MedianPruner không thật sự hữu ích ở đây.
# Early stopping vẫn được xử lý bên trong LightGBM bằng earlyStoppingRound.
study = optuna.create_study(
    direction="maximize",
    sampler=TPESampler(seed=RANDOM_STATE),
    pruner=NopPruner(),
)


# Enqueue baseline để Optuna luôn chạy baseline trước.
# baseline_params là dict đã khai báo ở cell baseline.
study.enqueue_trial(baseline_params)


# ============================================================
# Run Optuna
# ============================================================

if RUN_OPTUNA:
    study.optimize(
        objective,
        n_trials=N_TRIALS,
        show_progress_bar=True,
        gc_after_trial=True,
    )
else:
    # Nếu không muốn tuning lâu, chỉ chạy baseline trial đã enqueue.
    study.optimize(
        objective,
        n_trials=1,
        show_progress_bar=True,
        gc_after_trial=True,
    )


# ============================================================
# Optuna result
# ============================================================

print("========== Optuna Best Result ==========")
print("Best validation AUC:", study.best_value)

print("\nBest params:")
print(json.dumps(study.best_params, indent=2, default=str))

best_trial = study.best_trial

print("\nBest trial extra info:")
print("Trial number    :", best_trial.number)
print("Test AUC        :", best_trial.user_attrs.get("test_auc"))
print("Best iteration  :", best_trial.user_attrs.get("best_iteration"))
print("Fit seconds     :", best_trial.user_attrs.get("fit_seconds"))
print("========================================")

[I 2026-05-03 22:16:49,064] A new study created in memory with name: no-name-a8e1f003-907d-4a4e-a57e-ad413c0a58b3
  0%|          | 0/100 [00:00<?, ?it/s]

[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   1%|          | 1/100 [00:09<15:22,  9.32s/it]

[I 2026-05-03 22:16:58,263] Trial 0 finished with value: 0.6984766111111109 and parameters: {'learningRate': 0.05, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 1.0, 'baggingFreq': 0, 'featureFraction': 1.0, 'lambdaL1': 1e-08, 'lambdaL2': 1e-08, 'minGainToSplit': 0.0, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   2%|▏         | 2/100 [00:18<15:27,  9.46s/it]

[I 2026-05-03 22:17:07,806] Trial 1 finished with value: 0.6930141111111112 and parameters: {'learningRate': 0.030710573677773714, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.7912726728878613, 'baggingFreq': 5, 'featureFraction': 0.7418481581956126, 'lambdaL1': 4.258943089524393e-06, 'lambdaL2': 1.9826980964985924e-05, 'minGainToSplit': 0.45606998421703593, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   3%|▎         | 3/100 [00:27<14:40,  9.08s/it]

[I 2026-05-03 22:17:16,463] Trial 2 finished with value: 0.6921765555555555 and parameters: {'learningRate': 0.05898602410432694, 'numLeaves': 31, 'maxDepth': 4, 'minDataInLeaf': 200, 'baggingFraction': 0.777633994480005, 'baggingFreq': 0, 'featureFraction': 0.7554563366576581, 'lambdaL1': 5.324289357128436, 'lambdaL2': 0.09466630153726856, 'minGainToSplit': 0.9394989415641891, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:17:23 WARN DAGScheduler: Broadcasting large task binary with size 1309.1 KiB
26/05/03 22:17:24 WARN DAGScheduler: Broadcasting large task binary with size 1309.1 KiB
Best trial: 0. Best value: 0.698477:   4%|▍         | 4/100 [00:36<14:41,  9.18s/it]

[I 2026-05-03 22:17:25,793] Trial 3 finished with value: 0.6923636666666667 and parameters: {'learningRate': 0.01303561122512888, 'numLeaves': 127, 'maxDepth': 4, 'minDataInLeaf': 50, 'baggingFraction': 0.7016566351370807, 'baggingFreq': 0, 'featureFraction': 0.7222133955202271, 'lambdaL1': 1.683416412018213e-05, 'lambdaL2': 1.1036250149900698e-07, 'minGainToSplit': 0.8631034258755935, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   5%|▌         | 5/100 [00:46<14:31,  9.17s/it]

[I 2026-05-03 22:17:34,956] Trial 4 finished with value: 0.6957816111111108 and parameters: {'learningRate': 0.02538617845650057, 'numLeaves': 127, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.7094287557060203, 'baggingFreq': 5, 'featureFraction': 0.7747876687446624, 'lambdaL1': 4.9368087974032924e-05, 'lambdaL2': 0.06308995924905789, 'minGainToSplit': 0.22879816549162246, 'maxBin': 127}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   6%|▌         | 6/100 [00:53<13:27,  8.59s/it]

[I 2026-05-03 22:17:42,425] Trial 5 finished with value: 0.6944266111111109 and parameters: {'learningRate': 0.16201847221720986, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 200, 'baggingFraction': 0.7020856391593572, 'baggingFreq': 0, 'featureFraction': 0.8012845514210883, 'lambdaL1': 3.0632845126552133, 'lambdaL2': 8.106369361161699e-06, 'minGainToSplit': 0.5187906217433661, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   7%|▋         | 7/100 [01:00<12:42,  8.20s/it]

[I 2026-05-03 22:17:49,806] Trial 6 finished with value: 0.6931263333333333 and parameters: {'learningRate': 0.17871985357940612, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.9016406642217636, 'baggingFreq': 0, 'featureFraction': 0.8896917491780738, 'lambdaL1': 0.005032310118297565, 'lambdaL2': 0.000663700518115767, 'minGainToSplit': 0.0902897700544083, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:17:58 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/05/03 22:18:00 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
Best trial: 0. Best value: 0.698477:   8%|▊         | 8/100 [01:12<14:21,  9.36s/it]

[I 2026-05-03 22:18:01,651] Trial 7 finished with value: 0.6983037222222221 and parameters: {'learningRate': 0.011299251679907115, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.7773824883145466, 'baggingFreq': 1, 'featureFraction': 0.7725556872701355, 'lambdaL1': 6.885332382888648e-08, 'lambdaL2': 1.188343025435737, 'minGainToSplit': 0.9004180571633305, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:   9%|▉         | 9/100 [01:20<13:31,  8.92s/it]

[I 2026-05-03 22:18:09,576] Trial 8 finished with value: 0.6984436111111111 and parameters: {'learningRate': 0.08800150788211335, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.8955883778507802, 'baggingFreq': 1, 'featureFraction': 0.9239474215354072, 'lambdaL1': 0.007025804993039185, 'lambdaL2': 0.4395524392287042, 'minGainToSplit': 0.6576128923003434, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  10%|█         | 10/100 [01:28<13:05,  8.73s/it]

[I 2026-05-03 22:18:17,917] Trial 9 finished with value: 0.6913300555555556 and parameters: {'learningRate': 0.022132793664325537, 'numLeaves': 31, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.9821375753058743, 'baggingFreq': 0, 'featureFraction': 0.9784955687763176, 'lambdaL1': 7.139327996351564e-05, 'lambdaL2': 5.010641965202524, 'minGainToSplit': 0.9636199770892528, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  11%|█         | 11/100 [01:37<12:55,  8.71s/it]

[I 2026-05-03 22:18:26,574] Trial 10 finished with value: 0.6955732222222222 and parameters: {'learningRate': 0.06889556861408848, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 0.995156085765876, 'baggingFreq': 3, 'featureFraction': 0.9918969421053334, 'lambdaL1': 1.2534333684621333e-08, 'lambdaL2': 2.042213320965466e-08, 'minGainToSplit': 0.01231116956493733, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  12%|█▏        | 12/100 [01:45<12:23,  8.45s/it]

[I 2026-05-03 22:18:34,442] Trial 11 finished with value: 0.6978097777777775 and parameters: {'learningRate': 0.09383875912675972, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 20, 'baggingFraction': 0.9095612924208469, 'baggingFreq': 1, 'featureFraction': 0.9193559643266661, 'lambdaL1': 0.01256529038856324, 'lambdaL2': 0.0009294716775490714, 'minGainToSplit': 0.629555350459485, 'maxBin': 127}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  13%|█▎        | 13/100 [01:52<11:48,  8.15s/it]

[I 2026-05-03 22:18:41,880] Trial 12 finished with value: 0.6964208888888886 and parameters: {'learningRate': 0.10091557450479278, 'numLeaves': 15, 'maxDepth': -1, 'minDataInLeaf': 200, 'baggingFraction': 0.931578875128058, 'baggingFreq': 1, 'featureFraction': 0.9430335889765121, 'lambdaL1': 0.022637714731709807, 'lambdaL2': 1.6577334316362836e-06, 'minGainToSplit': 0.6952690808831975, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  14%|█▍        | 14/100 [02:00<11:37,  8.11s/it]

[I 2026-05-03 22:18:49,891] Trial 13 finished with value: 0.692808388888889 and parameters: {'learningRate': 0.046266910877374286, 'numLeaves': 15, 'maxDepth': 8, 'minDataInLeaf': 50, 'baggingFraction': 0.839801329937587, 'baggingFreq': 3, 'featureFraction': 0.8370643110464486, 'lambdaL1': 5.385659685389981e-07, 'lambdaL2': 0.0107649396580961, 'minGainToSplit': 0.3287835375844916, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  15%|█▌        | 15/100 [02:08<11:20,  8.00s/it]

[I 2026-05-03 22:18:57,654] Trial 14 finished with value: 0.6920362777777775 and parameters: {'learningRate': 0.10305080157845938, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 0.9460564310075372, 'baggingFreq': 1, 'featureFraction': 0.9413351195739358, 'lambdaL1': 0.0010710735454245116, 'lambdaL2': 0.00010523193963449515, 'minGainToSplit': 0.7166447132582263, 'maxBin': 127}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:19:04 WARN DAGScheduler: Broadcasting large task binary with size 1057.4 KiB
26/05/03 22:19:05 WARN DAGScheduler: Broadcasting large task binary with size 1057.4 KiB
Best trial: 0. Best value: 0.698477:  16%|█▌        | 16/100 [02:17<11:39,  8.33s/it]

[I 2026-05-03 22:19:06,745] Trial 15 finished with value: 0.6973291111111112 and parameters: {'learningRate': 0.034877767539036104, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.8649343096487292, 'baggingFreq': 1, 'featureFraction': 0.8822183292765754, 'lambdaL1': 0.0960337691463074, 'lambdaL2': 8.309024139321242e-07, 'minGainToSplit': 0.2662890013604836, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  17%|█▋        | 17/100 [02:26<11:34,  8.36s/it]

[I 2026-05-03 22:19:15,189] Trial 16 finished with value: 0.6953461666666666 and parameters: {'learningRate': 0.06814314508565371, 'numLeaves': 63, 'maxDepth': 8, 'minDataInLeaf': 200, 'baggingFraction': 0.9550725368382506, 'baggingFreq': 3, 'featureFraction': 0.9992744579586503, 'lambdaL1': 0.21252429567751777, 'lambdaL2': 0.018314061164103737, 'minGainToSplit': 0.4327456111804914, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:19:22 WARN DAGScheduler: Broadcasting large task binary with size 1253.4 KiB
26/05/03 22:19:23 WARN DAGScheduler: Broadcasting large task binary with size 1253.4 KiB
Best trial: 0. Best value: 0.698477:  18%|█▊        | 18/100 [02:35<11:43,  8.57s/it]

[I 2026-05-03 22:19:24,247] Trial 17 finished with value: 0.6936822222222222 and parameters: {'learningRate': 0.04491698722790464, 'numLeaves': 127, 'maxDepth': 10, 'minDataInLeaf': 20, 'baggingFraction': 0.861446185630293, 'baggingFreq': 5, 'featureFraction': 0.963850238766421, 'lambdaL1': 9.212857307336059e-07, 'lambdaL2': 0.7576147072741423, 'minGainToSplit': 0.5613955293597556, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  19%|█▉        | 19/100 [02:42<11:02,  8.18s/it]

[I 2026-05-03 22:19:31,507] Trial 18 finished with value: 0.6925827222222222 and parameters: {'learningRate': 0.13117815704838395, 'numLeaves': 31, 'maxDepth': 6, 'minDataInLeaf': 50, 'baggingFraction': 0.8123544223539447, 'baggingFreq': 1, 'featureFraction': 0.898843799971821, 'lambdaL1': 0.0005949384547515614, 'lambdaL2': 0.002884412348945533, 'minGainToSplit': 0.7961223145108114, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:19:39 WARN DAGScheduler: Broadcasting large task binary with size 1558.5 KiB
26/05/03 22:19:40 WARN DAGScheduler: Broadcasting large task binary with size 1558.5 KiB
Best trial: 0. Best value: 0.698477:  20%|██        | 20/100 [02:52<11:39,  8.75s/it]

[I 2026-05-03 22:19:41,583] Trial 19 finished with value: 0.6959302222222223 and parameters: {'learningRate': 0.017521461079681434, 'numLeaves': 15, 'maxDepth': -1, 'minDataInLeaf': 10, 'baggingFraction': 0.8895675391464223, 'baggingFreq': 0, 'featureFraction': 0.8514142828285605, 'lambdaL1': 0.00026120720108298876, 'lambdaL2': 1.5325207755717412e-08, 'minGainToSplit': 0.13831913237043555, 'maxBin': 127}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  21%|██        | 21/100 [03:00<11:16,  8.56s/it]

[I 2026-05-03 22:19:49,703] Trial 20 finished with value: 0.6958115555555555 and parameters: {'learningRate': 0.05669734327061269, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 100, 'baggingFraction': 0.9692961841714417, 'baggingFreq': 0, 'featureFraction': 0.9460278014493306, 'lambdaL1': 0.70835084318821, 'lambdaL2': 8.535170455607742e-05, 'minGainToSplit': 0.372381491009686, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:19:58 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/05/03 22:19:59 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
Best trial: 0. Best value: 0.698477:  22%|██▏       | 22/100 [03:12<12:18,  9.46s/it]

[I 2026-05-03 22:20:01,235] Trial 21 finished with value: 0.6974125000000001 and parameters: {'learningRate': 0.010302631309335607, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.7480728858095436, 'baggingFreq': 1, 'featureFraction': 0.8130755544240803, 'lambdaL1': 1.120976378531883e-08, 'lambdaL2': 8.321569492301686, 'minGainToSplit': 0.8306123833810541, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  23%|██▎       | 23/100 [03:20<11:44,  9.15s/it]

[I 2026-05-03 22:20:09,699] Trial 22 finished with value: 0.6979995555555556 and parameters: {'learningRate': 0.03741216079921653, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.8185580127739943, 'baggingFreq': 1, 'featureFraction': 0.8632874428676431, 'lambdaL1': 9.62172018279007e-08, 'lambdaL2': 0.4093270953374342, 'minGainToSplit': 0.7037397984098509, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  24%|██▍       | 24/100 [03:28<11:12,  8.84s/it]

[I 2026-05-03 22:20:17,824] Trial 23 finished with value: 0.6971712222222223 and parameters: {'learningRate': 0.08160194617020398, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.7618281201060162, 'baggingFreq': 1, 'featureFraction': 0.9237973539756348, 'lambdaL1': 1.0114233126713548e-07, 'lambdaL2': 0.649962405425226, 'minGainToSplit': 0.5750492605761146, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:20:24 WARN DAGScheduler: Broadcasting large task binary with size 1435.4 KiB
26/05/03 22:20:25 WARN DAGScheduler: Broadcasting large task binary with size 1435.4 KiB
Best trial: 0. Best value: 0.698477:  25%|██▌       | 25/100 [03:37<11:02,  8.84s/it]

[I 2026-05-03 22:20:26,655] Trial 24 finished with value: 0.6956629444444443 and parameters: {'learningRate': 0.017497052191459816, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 100, 'baggingFraction': 0.928037055762482, 'baggingFreq': 1, 'featureFraction': 0.7013164312600516, 'lambdaL1': 5.99090474789645e-08, 'lambdaL2': 3.0204582257943557, 'minGainToSplit': 0.9883930611985802, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  26%|██▌       | 26/100 [03:45<10:22,  8.42s/it]

[I 2026-05-03 22:20:34,080] Trial 25 finished with value: 0.6962038888888888 and parameters: {'learningRate': 0.14275465271791404, 'numLeaves': 31, 'maxDepth': 10, 'minDataInLeaf': 200, 'baggingFraction': 0.7328107001069475, 'baggingFreq': 1, 'featureFraction': 0.8206001345903948, 'lambdaL1': 6.26890138434218e-07, 'lambdaL2': 0.17510515746904026, 'minGainToSplit': 0.8785620420160659, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  27%|██▋       | 27/100 [03:52<09:55,  8.16s/it]

[I 2026-05-03 22:20:41,637] Trial 26 finished with value: 0.6932283888888887 and parameters: {'learningRate': 0.12056890086878222, 'numLeaves': 127, 'maxDepth': 8, 'minDataInLeaf': 20, 'baggingFraction': 0.8806388064632406, 'baggingFreq': 5, 'featureFraction': 0.9677358171978858, 'lambdaL1': 4.829576338298943e-06, 'lambdaL2': 0.015722265406419748, 'minGainToSplit': 0.7678974270924446, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  28%|██▊       | 28/100 [04:00<09:44,  8.12s/it]

[I 2026-05-03 22:20:49,681] Trial 27 finished with value: 0.6954793888888888 and parameters: {'learningRate': 0.04961047327120771, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 100, 'baggingFraction': 0.8335602271086741, 'baggingFreq': 3, 'featureFraction': 0.7914318309058351, 'lambdaL1': 0.002344735454798909, 'lambdaL2': 2.86333363892965e-07, 'minGainToSplit': 0.6214742337504001, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  29%|██▉       | 29/100 [04:08<09:28,  8.01s/it]

[I 2026-05-03 22:20:57,406] Trial 28 finished with value: 0.695962611111111 and parameters: {'learningRate': 0.07599850914529215, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.7856170443209335, 'baggingFreq': 1, 'featureFraction': 0.9148197150021843, 'lambdaL1': 3.3876093713511496e-08, 'lambdaL2': 1.938732125801273, 'minGainToSplit': 0.8968503385330586, 'maxBin': 255}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698477:  30%|███       | 30/100 [04:17<09:32,  8.18s/it]

[I 2026-05-03 22:21:05,994] Trial 29 finished with value: 0.6980155555555556 and parameters: {'learningRate': 0.03213891014540883, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9979361021827199, 'baggingFreq': 5, 'featureFraction': 0.8716189915210998, 'lambdaL1': 4.58836154091207e-06, 'lambdaL2': 0.003075786932067291, 'minGainToSplit': 0.45486989156168034, 'maxBin': 127}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:21:13 WARN DAGScheduler: Broadcasting large task binary with size 1372.6 KiB
26/05/03 22:21:14 WARN DAGScheduler: Broadcasting large task binary with size 1372.6 KiB
Best trial: 0. Best value: 0.698477:  31%|███       | 31/100 [04:26<09:52,  8.59s/it]

[I 2026-05-03 22:21:15,527] Trial 30 finished with value: 0.6958874999999999 and parameters: {'learningRate': 0.02671798539408663, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.8057144594342076, 'baggingFreq': 0, 'featureFraction': 0.7579049852731836, 'lambdaL1': 3.152357450499791e-07, 'lambdaL2': 1.8188496859630268e-05, 'minGainToSplit': 0.0026679612772813055, 'maxBin': 63}. Best is trial 0 with value: 0.6984766111111109.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:21:22 WARN DAGScheduler: Broadcasting large task binary with size 1116.8 KiB
26/05/03 22:21:23 WARN DAGScheduler: Broadcasting large task binary with size 1116.8 KiB
Best trial: 31. Best value: 0.699697:  32%|███▏      | 32/100 [04:35<09:55,  8.76s/it]

[I 2026-05-03 22:21:24,683] Trial 31 finished with value: 0.6996974999999999 and parameters: {'learningRate': 0.03237943493347231, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9966817696185324, 'baggingFreq': 5, 'featureFraction': 0.872006621963079, 'lambdaL1': 1.7132068531836293e-06, 'lambdaL2': 0.0038469072044054974, 'minGainToSplit': 0.43866936320626015, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  33%|███▎      | 33/100 [04:44<09:53,  8.85s/it]

[I 2026-05-03 22:21:33,768] Trial 32 finished with value: 0.6936428333333332 and parameters: {'learningRate': 0.017231905780555175, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9700683539903037, 'baggingFreq': 5, 'featureFraction': 0.8348898511546103, 'lambdaL1': 1.0339270418978393e-08, 'lambdaL2': 0.05745845828595084, 'minGainToSplit': 0.20732948272509247, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:21:41 WARN DAGScheduler: Broadcasting large task binary with size 1545.5 KiB
26/05/03 22:21:42 WARN DAGScheduler: Broadcasting large task binary with size 1545.5 KiB
Best trial: 31. Best value: 0.699697:  34%|███▍      | 34/100 [04:54<10:09,  9.23s/it]

[I 2026-05-03 22:21:43,886] Trial 33 finished with value: 0.6962174444444444 and parameters: {'learningRate': 0.011100719627591838, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9229692707987934, 'baggingFreq': 5, 'featureFraction': 0.9025353212381289, 'lambdaL1': 2.0027142431085094e-07, 'lambdaL2': 0.20666429678565335, 'minGainToSplit': 0.38200819612491954, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:21:51 WARN DAGScheduler: Broadcasting large task binary with size 1833.1 KiB
26/05/03 22:21:53 WARN DAGScheduler: Broadcasting large task binary with size 1833.1 KiB
Best trial: 31. Best value: 0.699697:  35%|███▌      | 35/100 [05:05<10:27,  9.65s/it]

[I 2026-05-03 22:21:54,494] Trial 34 finished with value: 0.6955267222222222 and parameters: {'learningRate': 0.014632388584975823, 'numLeaves': 15, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.9472749917015081, 'baggingFreq': 5, 'featureFraction': 0.723984415676405, 'lambdaL1': 1.7742523492040027e-05, 'lambdaL2': 0.00011415089366609801, 'minGainToSplit': 0.5028387709574468, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:22:00 WARN DAGScheduler: Broadcasting large task binary with size 1018.9 KiB
26/05/03 22:22:01 WARN DAGScheduler: Broadcasting large task binary with size 1018.9 KiB
Best trial: 31. Best value: 0.699697:  36%|███▌      | 36/100 [05:13<09:48,  9.20s/it]

[I 2026-05-03 22:22:02,639] Trial 35 finished with value: 0.6950842222222222 and parameters: {'learningRate': 0.05654424512310123, 'numLeaves': 127, 'maxDepth': 6, 'minDataInLeaf': 50, 'baggingFraction': 0.9786753885035404, 'baggingFreq': 0, 'featureFraction': 0.7778276688867263, 'lambdaL1': 1.0179015053831868e-06, 'lambdaL2': 0.042271141982564285, 'minGainToSplit': 0.2942433985257292, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  37%|███▋      | 37/100 [05:21<09:22,  8.92s/it]

[I 2026-05-03 22:22:10,920] Trial 36 finished with value: 0.696948111111111 and parameters: {'learningRate': 0.039579293498765364, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.999855631713629, 'baggingFreq': 5, 'featureFraction': 0.8569832906999896, 'lambdaL1': 2.045696693439181e-06, 'lambdaL2': 1.2118485815182092, 'minGainToSplit': 0.17315233777134648, 'maxBin': 255}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  38%|███▊      | 38/100 [05:30<08:59,  8.70s/it]

[I 2026-05-03 22:22:19,119] Trial 37 finished with value: 0.6934954444444444 and parameters: {'learningRate': 0.02824275794281584, 'numLeaves': 31, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.723503237131314, 'baggingFreq': 0, 'featureFraction': 0.7565883426684039, 'lambdaL1': 0.0001803307562436218, 'lambdaL2': 0.0038850240039502455, 'minGainToSplit': 0.925971357778018, 'maxBin': 63}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:22:26 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
26/05/03 22:22:28 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
Best trial: 31. Best value: 0.699697:  39%|███▉      | 39/100 [05:40<09:15,  9.10s/it]

[I 2026-05-03 22:22:29,158] Trial 38 finished with value: 0.6944124999999998 and parameters: {'learningRate': 0.02234726440282245, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 20, 'baggingFraction': 0.9587448154671665, 'baggingFreq': 1, 'featureFraction': 0.9777069804335334, 'lambdaL1': 4.02992964964698e-08, 'lambdaL2': 6.176937150244691e-06, 'minGainToSplit': 0.7500761540623417, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:22:35 WARN DAGScheduler: Broadcasting large task binary with size 1081.9 KiB
26/05/03 22:22:37 WARN DAGScheduler: Broadcasting large task binary with size 1081.9 KiB
Best trial: 31. Best value: 0.699697:  40%|████      | 40/100 [05:49<09:03,  9.05s/it]

[I 2026-05-03 22:22:38,103] Trial 39 finished with value: 0.6953615 and parameters: {'learningRate': 0.022039778337567997, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 100, 'baggingFraction': 0.7754415599526833, 'baggingFreq': 0, 'featureFraction': 0.8729553089061497, 'lambdaL1': 2.3751364670172596e-08, 'lambdaL2': 0.0003713514598639652, 'minGainToSplit': 0.6422089922261308, 'maxBin': 255}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:22:47 WARN DAGScheduler: Broadcasting large task binary with size 3.4 MiB
26/05/03 22:22:48 WARN DAGScheduler: Broadcasting large task binary with size 3.4 MiB
Best trial: 31. Best value: 0.699697:  41%|████      | 41/100 [06:00<09:42,  9.87s/it]

[I 2026-05-03 22:22:49,862] Trial 40 finished with value: 0.69702 and parameters: {'learningRate': 0.012784343882029777, 'numLeaves': 127, 'maxDepth': -1, 'minDataInLeaf': 200, 'baggingFraction': 0.9106658956941265, 'baggingFreq': 5, 'featureFraction': 0.9343794092756642, 'lambdaL1': 2.3518212335021518e-05, 'lambdaL2': 0.15712491906950446, 'minGainToSplit': 0.8338013900133172, 'maxBin': 63}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  42%|████▏     | 42/100 [06:09<09:06,  9.42s/it]

[I 2026-05-03 22:22:58,227] Trial 41 finished with value: 0.6961824444444444 and parameters: {'learningRate': 0.03182944139874867, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9890751370131267, 'baggingFreq': 5, 'featureFraction': 0.8798799414377101, 'lambdaL1': 8.119500479548846e-06, 'lambdaL2': 0.0018405840334951402, 'minGainToSplit': 0.45892299675557946, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  43%|████▎     | 43/100 [06:17<08:43,  9.18s/it]

[I 2026-05-03 22:23:06,852] Trial 42 finished with value: 0.6961393333333332 and parameters: {'learningRate': 0.03171698680887658, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9806106981879235, 'baggingFreq': 5, 'featureFraction': 0.8357578288213866, 'lambdaL1': 2.5513518940996035e-06, 'lambdaL2': 0.00711376451891768, 'minGainToSplit': 0.44477540570044377, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:23:13 WARN DAGScheduler: Broadcasting large task binary with size 1174.0 KiB
26/05/03 22:23:15 WARN DAGScheduler: Broadcasting large task binary with size 1174.0 KiB
Best trial: 31. Best value: 0.699697:  44%|████▍     | 44/100 [06:27<08:34,  9.19s/it]

[I 2026-05-03 22:23:16,063] Trial 43 finished with value: 0.6981525 and parameters: {'learningRate': 0.04119329733578581, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9987533729758977, 'baggingFreq': 5, 'featureFraction': 0.901930969170216, 'lambdaL1': 1.5480864028084562e-07, 'lambdaL2': 0.0008997026337622481, 'minGainToSplit': 0.08019240847651998, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  45%|████▌     | 45/100 [06:35<08:11,  8.93s/it]

[I 2026-05-03 22:23:24,397] Trial 44 finished with value: 0.6983835555555556 and parameters: {'learningRate': 0.051271985396671424, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9396803195771182, 'baggingFreq': 5, 'featureFraction': 0.8919609568749256, 'lambdaL1': 2.4643821382200223e-07, 'lambdaL2': 0.00022489635293422293, 'minGainToSplit': 0.06981465311520198, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  46%|████▌     | 46/100 [06:43<07:46,  8.63s/it]

[I 2026-05-03 22:23:32,322] Trial 45 finished with value: 0.696506111111111 and parameters: {'learningRate': 0.051374576884890964, 'numLeaves': 15, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.8972436957093495, 'baggingFreq': 3, 'featureFraction': 0.9623173679326278, 'lambdaL1': 0.012510329888331116, 'lambdaL2': 1.2108214426759514e-07, 'minGainToSplit': 0.05048993666751703, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  47%|████▋     | 47/100 [06:50<07:18,  8.27s/it]

[I 2026-05-03 22:23:39,750] Trial 46 finished with value: 0.6914838333333333 and parameters: {'learningRate': 0.19094537749467186, 'numLeaves': 31, 'maxDepth': 8, 'minDataInLeaf': 50, 'baggingFraction': 0.8753238945593311, 'baggingFreq': 1, 'featureFraction': 0.8917511393596284, 'lambdaL1': 2.9105040545739206e-07, 'lambdaL2': 0.03374076945503366, 'minGainToSplit': 0.1041295922198397, 'maxBin': 255}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  48%|████▊     | 48/100 [06:58<07:06,  8.20s/it]

[I 2026-05-03 22:23:47,790] Trial 47 finished with value: 0.6946774444444445 and parameters: {'learningRate': 0.06926221258574271, 'numLeaves': 15, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.9121328544098951, 'baggingFreq': 0, 'featureFraction': 0.9091016854961349, 'lambdaL1': 6.369470040577541e-05, 'lambdaL2': 4.670145030976934e-06, 'minGainToSplit': 0.23821099122341927, 'maxBin': 127}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  49%|████▉     | 49/100 [07:06<06:55,  8.15s/it]

[I 2026-05-03 22:23:55,824] Trial 48 finished with value: 0.6968693333333329 and parameters: {'learningRate': 0.08766321886952878, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 200, 'baggingFraction': 0.9347708841596802, 'baggingFreq': 5, 'featureFraction': 0.819809706377496, 'lambdaL1': 4.1807141742580034e-08, 'lambdaL2': 3.180537126040793e-08, 'minGainToSplit': 0.16079592294289752, 'maxBin': 63}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 31. Best value: 0.699697:  50%|█████     | 50/100 [07:15<06:47,  8.15s/it]

[I 2026-05-03 22:24:03,961] Trial 49 finished with value: 0.6978488333333335 and parameters: {'learningRate': 0.0637039320346464, 'numLeaves': 31, 'maxDepth': 6, 'minDataInLeaf': 20, 'baggingFraction': 0.9635627840279445, 'baggingFreq': 1, 'featureFraction': 0.9250619808249986, 'lambdaL1': 0.04342534492683085, 'lambdaL2': 1.0421247523421492e-06, 'minGainToSplit': 0.5489356345298816, 'maxBin': 255}. Best is trial 31 with value: 0.6996974999999999.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  51%|█████     | 51/100 [07:23<06:40,  8.17s/it]

[I 2026-05-03 22:24:12,186] Trial 50 finished with value: 0.6998178333333331 and parameters: {'learningRate': 0.10961641773565604, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9373824334980544, 'baggingFreq': 3, 'featureFraction': 0.9875373536399997, 'lambdaL1': 0.0025313158457515843, 'lambdaL2': 4.206340310924732e-05, 'minGainToSplit': 0.07054667038582645, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  52%|█████▏    | 52/100 [07:30<06:25,  8.02s/it]

[I 2026-05-03 22:24:19,870] Trial 51 finished with value: 0.6974959444444443 and parameters: {'learningRate': 0.11213654814247011, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9404749320363308, 'baggingFreq': 3, 'featureFraction': 0.989514714930132, 'lambdaL1': 0.004658877130683061, 'lambdaL2': 4.7778447363058445e-05, 'minGainToSplit': 0.04329884048708961, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  53%|█████▎    | 53/100 [07:39<06:21,  8.12s/it]

[I 2026-05-03 22:24:28,224] Trial 52 finished with value: 0.69958 and parameters: {'learningRate': 0.09960481467099155, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8465624488540235, 'baggingFreq': 3, 'featureFraction': 0.9581771747694339, 'lambdaL1': 0.001616727757895995, 'lambdaL2': 0.0003040085824687593, 'minGainToSplit': 0.12002874220853678, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  54%|█████▍    | 54/100 [07:46<06:03,  7.91s/it]

[I 2026-05-03 22:24:35,629] Trial 53 finished with value: 0.6951159444444444 and parameters: {'learningRate': 0.0974543280447241, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8489074612475552, 'baggingFreq': 3, 'featureFraction': 0.9489115010921234, 'lambdaL1': 0.0014205593195700265, 'lambdaL2': 0.0002857423546667166, 'minGainToSplit': 0.0964028047567886, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  55%|█████▌    | 55/100 [07:53<05:47,  7.71s/it]

[I 2026-05-03 22:24:42,888] Trial 54 finished with value: 0.6958044444444443 and parameters: {'learningRate': 0.14407282340397534, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8659926169776399, 'baggingFreq': 3, 'featureFraction': 0.9800526658712042, 'lambdaL1': 0.0005422630038989457, 'lambdaL2': 3.359650945352104e-05, 'minGainToSplit': 0.04498533813359825, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  56%|█████▌    | 56/100 [08:01<05:42,  7.77s/it]

[I 2026-05-03 22:24:50,804] Trial 55 finished with value: 0.696724111111111 and parameters: {'learningRate': 0.11006431705390483, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9215640618888028, 'baggingFreq': 3, 'featureFraction': 0.9576564969650596, 'lambdaL1': 0.006151758854019683, 'lambdaL2': 0.00015455967695178485, 'minGainToSplit': 0.1426100170238388, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  57%|█████▋    | 57/100 [08:09<05:27,  7.62s/it]

[I 2026-05-03 22:24:58,075] Trial 56 finished with value: 0.6954792777777778 and parameters: {'learningRate': 0.15943022883990837, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9536192411423392, 'baggingFreq': 3, 'featureFraction': 0.9969328375913815, 'lambdaL1': 0.027679410902924025, 'lambdaL2': 1.4729587933712197e-05, 'minGainToSplit': 0.2132391402069617, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  58%|█████▊    | 58/100 [08:16<05:22,  7.68s/it]

[I 2026-05-03 22:25:05,887] Trial 57 finished with value: 0.6971854999999999 and parameters: {'learningRate': 0.08103531783752171, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9730275348817465, 'baggingFreq': 3, 'featureFraction': 0.9325108993728262, 'lambdaL1': 0.15903936028546742, 'lambdaL2': 0.00041632369286252724, 'minGainToSplit': 0.0015587382580053155, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  59%|█████▉    | 59/100 [08:24<05:14,  7.68s/it]

[I 2026-05-03 22:25:13,569] Trial 58 finished with value: 0.6966642777777778 and parameters: {'learningRate': 0.09184743016806567, 'numLeaves': 15, 'maxDepth': -1, 'minDataInLeaf': 10, 'baggingFraction': 0.8943999411493027, 'baggingFreq': 3, 'featureFraction': 0.9831873150260553, 'lambdaL1': 0.002562511724322795, 'lambdaL2': 2.0562949172442155e-06, 'minGainToSplit': 0.11862552944884536, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  60%|██████    | 60/100 [08:32<05:13,  7.83s/it]

[I 2026-05-03 22:25:21,737] Trial 59 finished with value: 0.6974632777777777 and parameters: {'learningRate': 0.05125363995610364, 'numLeaves': 15, 'maxDepth': 10, 'minDataInLeaf': 200, 'baggingFraction': 0.8297189525348233, 'baggingFreq': 3, 'featureFraction': 0.9741336317872291, 'lambdaL1': 0.00022705320913154355, 'lambdaL2': 0.0012172260022418608, 'minGainToSplit': 0.07945215035250669, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  61%|██████    | 61/100 [08:40<05:06,  7.86s/it]

[I 2026-05-03 22:25:29,664] Trial 60 finished with value: 0.696846388888889 and parameters: {'learningRate': 0.06098075774220364, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 50, 'baggingFraction': 0.8854206987068848, 'baggingFreq': 0, 'featureFraction': 0.9547598932497363, 'lambdaL1': 0.0006698042831675349, 'lambdaL2': 4.9860064839517036e-05, 'minGainToSplit': 0.3153341616734258, 'maxBin': 255}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  62%|██████▏   | 62/100 [08:48<04:55,  7.77s/it]

[I 2026-05-03 22:25:37,230] Trial 61 finished with value: 0.6946839444444445 and parameters: {'learningRate': 0.12824734506040025, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.8509237607380198, 'baggingFreq': 1, 'featureFraction': 0.9884436529237526, 'lambdaL1': 0.008436988610166268, 'lambdaL2': 0.007880726298972364, 'minGainToSplit': 0.6670439483955339, 'maxBin': 63}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:25:43 WARN DAGScheduler: Broadcasting large task binary with size 1351.7 KiB
26/05/03 22:25:44 WARN DAGScheduler: Broadcasting large task binary with size 1351.7 KiB
Best trial: 50. Best value: 0.699818:  63%|██████▎   | 63/100 [08:56<04:54,  7.95s/it]

[I 2026-05-03 22:25:45,606] Trial 62 finished with value: 0.695476611111111 and parameters: {'learningRate': 0.06798889735564703, 'numLeaves': 127, 'maxDepth': 8, 'minDataInLeaf': 20, 'baggingFraction': 0.9863442092274021, 'baggingFreq': 1, 'featureFraction': 0.9720205861674751, 'lambdaL1': 7.786445064342001e-08, 'lambdaL2': 9.853489486327351, 'minGainToSplit': 0.04869398679732896, 'maxBin': 63}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:25:52 WARN DAGScheduler: Broadcasting large task binary with size 1306.6 KiB
26/05/03 22:25:53 WARN DAGScheduler: Broadcasting large task binary with size 1306.6 KiB
Best trial: 50. Best value: 0.699818:  64%|██████▍   | 64/100 [09:05<05:00,  8.34s/it]

[I 2026-05-03 22:25:54,863] Trial 63 finished with value: 0.6986467222222221 and parameters: {'learningRate': 0.044316284846280585, 'numLeaves': 31, 'maxDepth': 6, 'minDataInLeaf': 100, 'baggingFraction': 0.9039454335204622, 'baggingFreq': 3, 'featureFraction': 0.9328292463749808, 'lambdaL1': 2.4592294573749163e-08, 'lambdaL2': 3.1714394741762404, 'minGainToSplit': 0.3905341784308589, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:26:02 WARN DAGScheduler: Broadcasting large task binary with size 1686.1 KiB
26/05/03 22:26:03 WARN DAGScheduler: Broadcasting large task binary with size 1686.1 KiB
Best trial: 50. Best value: 0.699818:  65%|██████▌   | 65/100 [09:15<05:06,  8.76s/it]

[I 2026-05-03 22:26:04,585] Trial 64 finished with value: 0.6967361111111109 and parameters: {'learningRate': 0.0442600545604845, 'numLeaves': 31, 'maxDepth': 6, 'minDataInLeaf': 100, 'baggingFraction': 0.8701268019091551, 'baggingFreq': 3, 'featureFraction': 0.9372010494054636, 'lambdaL1': 2.14695353598636e-08, 'lambdaL2': 0.00022391400351353319, 'minGainToSplit': 0.3999812655861918, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 50. Best value: 0.699818:  66%|██████▌   | 66/100 [09:24<04:57,  8.75s/it]

[I 2026-05-03 22:26:13,297] Trial 65 finished with value: 0.6991216666666668 and parameters: {'learningRate': 0.03813572490505876, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9158367526149099, 'baggingFreq': 3, 'featureFraction': 0.914042583735651, 'lambdaL1': 9.370996678470359, 'lambdaL2': 2.6026174150903563, 'minGainToSplit': 0.1896640473501566, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:26:20 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/03 22:26:21 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 50. Best value: 0.699818:  67%|██████▋   | 67/100 [09:33<04:57,  9.01s/it]

[I 2026-05-03 22:26:22,943] Trial 66 finished with value: 0.6990914444444444 and parameters: {'learningRate': 0.03963645426611407, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9018472035827673, 'baggingFreq': 3, 'featureFraction': 0.9999888072484616, 'lambdaL1': 2.236914028332983, 'lambdaL2': 3.683393592092365, 'minGainToSplit': 0.34474025977825207, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:26:29 WARN DAGScheduler: Broadcasting large task binary with size 1229.4 KiB
26/05/03 22:26:30 WARN DAGScheduler: Broadcasting large task binary with size 1229.4 KiB
Best trial: 50. Best value: 0.699818:  68%|██████▊   | 68/100 [09:42<04:46,  8.95s/it]

[I 2026-05-03 22:26:31,695] Trial 67 finished with value: 0.6978948333333331 and parameters: {'learningRate': 0.03547604492492642, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9079225689093993, 'baggingFreq': 3, 'featureFraction': 0.9984535863967005, 'lambdaL1': 4.101880070772983, 'lambdaL2': 4.082356895084282, 'minGainToSplit': 0.1878621039790664, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:26:39 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/03 22:26:40 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 50. Best value: 0.699818:  69%|██████▉   | 69/100 [09:53<04:51,  9.39s/it]

[I 2026-05-03 22:26:42,173] Trial 68 finished with value: 0.6988114444444444 and parameters: {'learningRate': 0.028697327403028355, 'numLeaves': 31, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8568769779412267, 'baggingFreq': 3, 'featureFraction': 0.949958849665405, 'lambdaL1': 8.192974173373095, 'lambdaL2': 1.5384432051705408, 'minGainToSplit': 0.3461588796548329, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:26:49 WARN DAGScheduler: Broadcasting large task binary with size 1707.8 KiB
26/05/03 22:26:51 WARN DAGScheduler: Broadcasting large task binary with size 1707.8 KiB
Best trial: 50. Best value: 0.699818:  70%|███████   | 70/100 [10:03<04:46,  9.54s/it]

[I 2026-05-03 22:26:52,049] Trial 69 finished with value: 0.6979747222222223 and parameters: {'learningRate': 0.024510203435362265, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8522175774477143, 'baggingFreq': 3, 'featureFraction': 0.9511550950380303, 'lambdaL1': 7.378816081621219, 'lambdaL2': 1.4440437989670571, 'minGainToSplit': 0.3451674816761216, 'maxBin': 127}. Best is trial 50 with value: 0.6998178333333331.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:26:59 WARN DAGScheduler: Broadcasting large task binary with size 1919.9 KiB
26/05/03 22:27:00 WARN DAGScheduler: Broadcasting large task binary with size 1919.9 KiB
Best trial: 70. Best value: 0.700372:  71%|███████   | 71/100 [10:12<04:39,  9.64s/it]

[I 2026-05-03 22:27:01,912] Trial 70 finished with value: 0.7003723888888888 and parameters: {'learningRate': 0.029407405650415247, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9195296684898796, 'baggingFreq': 3, 'featureFraction': 0.962528547679103, 'lambdaL1': 3.289131374938646, 'lambdaL2': 2.3724829054262764, 'minGainToSplit': 0.27941007159668, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:27:10 WARN DAGScheduler: Broadcasting large task binary with size 1984.2 KiB
26/05/03 22:27:11 WARN DAGScheduler: Broadcasting large task binary with size 1984.2 KiB
Best trial: 70. Best value: 0.700372:  72%|███████▏  | 72/100 [10:23<04:37,  9.90s/it]

[I 2026-05-03 22:27:12,431] Trial 71 finished with value: 0.6986798888888889 and parameters: {'learningRate': 0.028169667400095664, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9165159794526392, 'baggingFreq': 3, 'featureFraction': 0.9622076279315949, 'lambdaL1': 1.5315875563095132, 'lambdaL2': 2.2689781741511945, 'minGainToSplit': 0.2859510129009756, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:27:19 WARN DAGScheduler: Broadcasting large task binary with size 2044.3 KiB
26/05/03 22:27:20 WARN DAGScheduler: Broadcasting large task binary with size 2044.3 KiB
Best trial: 70. Best value: 0.700372:  73%|███████▎  | 73/100 [10:33<04:25,  9.85s/it]

[I 2026-05-03 22:27:22,150] Trial 72 finished with value: 0.6991411666666667 and parameters: {'learningRate': 0.029321408895434987, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.921210633008805, 'baggingFreq': 3, 'featureFraction': 0.9660468537558736, 'lambdaL1': 1.8739986888076747, 'lambdaL2': 0.7795258703873856, 'minGainToSplit': 0.25356684076965735, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:27:29 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/03 22:27:30 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 70. Best value: 0.700372:  74%|███████▍  | 74/100 [10:43<04:15,  9.83s/it]

[I 2026-05-03 22:27:31,951] Trial 73 finished with value: 0.6985694999999998 and parameters: {'learningRate': 0.024033461746826003, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9265596604392392, 'baggingFreq': 3, 'featureFraction': 0.9689116759386145, 'lambdaL1': 0.6025883868882884, 'lambdaL2': 6.211282568462214, 'minGainToSplit': 0.24591569309785144, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:27:39 WARN DAGScheduler: Broadcasting large task binary with size 1960.7 KiB
26/05/03 22:27:40 WARN DAGScheduler: Broadcasting large task binary with size 1960.7 KiB
Best trial: 70. Best value: 0.700372:  75%|███████▌  | 75/100 [10:52<04:03,  9.74s/it]

[I 2026-05-03 22:27:41,471] Trial 74 finished with value: 0.7001541666666665 and parameters: {'learningRate': 0.019803098717801813, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8886325770764986, 'baggingFreq': 3, 'featureFraction': 0.9849601605850986, 'lambdaL1': 2.1987689341583785, 'lambdaL2': 0.4932597684905057, 'minGainToSplit': 0.3531872581596653, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:27:48 WARN DAGScheduler: Broadcasting large task binary with size 2010.3 KiB
26/05/03 22:27:50 WARN DAGScheduler: Broadcasting large task binary with size 2010.3 KiB
Best trial: 70. Best value: 0.700372:  76%|███████▌  | 76/100 [11:02<03:52,  9.70s/it]

[I 2026-05-03 22:27:51,091] Trial 75 finished with value: 0.6992308333333334 and parameters: {'learningRate': 0.019448442184935952, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8889232187203262, 'baggingFreq': 3, 'featureFraction': 0.9841946774548561, 'lambdaL1': 1.7876059959603992, 'lambdaL2': 0.40894426467650513, 'minGainToSplit': 0.26760447668379916, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:27:58 WARN DAGScheduler: Broadcasting large task binary with size 2013.6 KiB
26/05/03 22:27:59 WARN DAGScheduler: Broadcasting large task binary with size 2013.6 KiB
Best trial: 70. Best value: 0.700372:  77%|███████▋  | 77/100 [11:11<03:40,  9.61s/it]

[I 2026-05-03 22:28:00,477] Trial 76 finished with value: 0.695320111111111 and parameters: {'learningRate': 0.018098717437397785, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8828132212797519, 'baggingFreq': 3, 'featureFraction': 0.9807665916154696, 'lambdaL1': 0.7814413543896166, 'lambdaL2': 0.42713613063733563, 'minGainToSplit': 0.2513319299569995, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:28:08 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/03 22:28:09 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 70. Best value: 0.700372:  78%|███████▊  | 78/100 [11:21<03:34,  9.76s/it]

[I 2026-05-03 22:28:10,607] Trial 77 finished with value: 0.6976693333333334 and parameters: {'learningRate': 0.019219691823794387, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8911265838993904, 'baggingFreq': 3, 'featureFraction': 0.9881944724131861, 'lambdaL1': 1.3474490654092217, 'lambdaL2': 0.6737727979203356, 'minGainToSplit': 0.2800567534929042, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:28:19 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
26/05/03 22:28:20 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
Best trial: 70. Best value: 0.700372:  79%|███████▉  | 79/100 [11:32<03:34, 10.21s/it]

[I 2026-05-03 22:28:21,852] Trial 78 finished with value: 0.6962603888888886 and parameters: {'learningRate': 0.015151697343427997, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8751362625331455, 'baggingFreq': 3, 'featureFraction': 0.942106781948102, 'lambdaL1': 0.39759462534323825, 'lambdaL2': 0.18174150449944373, 'minGainToSplit': 0.41890446406533277, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:28:29 WARN DAGScheduler: Broadcasting large task binary with size 1472.0 KiB
26/05/03 22:28:30 WARN DAGScheduler: Broadcasting large task binary with size 1472.0 KiB
Best trial: 70. Best value: 0.700372:  80%|████████  | 80/100 [11:43<03:24, 10.21s/it]

[I 2026-05-03 22:28:32,050] Trial 79 finished with value: 0.6975649444444444 and parameters: {'learningRate': 0.020122337475586952, 'numLeaves': 63, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.9195133823988196, 'baggingFreq': 3, 'featureFraction': 0.9667154299086326, 'lambdaL1': 3.9029652423889307, 'lambdaL2': 0.11117575136654884, 'minGainToSplit': 0.2165707117658476, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:28:39 WARN DAGScheduler: Broadcasting large task binary with size 1084.0 KiB
26/05/03 22:28:40 WARN DAGScheduler: Broadcasting large task binary with size 1084.0 KiB
Best trial: 70. Best value: 0.700372:  81%|████████  | 81/100 [11:52<03:06,  9.83s/it]

[I 2026-05-03 22:28:40,998] Trial 80 finished with value: 0.6984848333333334 and parameters: {'learningRate': 0.03346522643256592, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 10, 'baggingFraction': 0.8409060282250476, 'baggingFreq': 3, 'featureFraction': 0.9161359636451006, 'lambdaL1': 2.2340130213640075, 'lambdaL2': 0.3861656717656753, 'minGainToSplit': 0.3014892594389429, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:28:48 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/03 22:28:49 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 70. Best value: 0.700372:  82%|████████▏ | 82/100 [12:02<02:57,  9.87s/it]

[I 2026-05-03 22:28:50,972] Trial 81 finished with value: 0.6977195555555554 and parameters: {'learningRate': 0.030421682763810614, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9022473553945658, 'baggingFreq': 3, 'featureFraction': 0.9986313346839925, 'lambdaL1': 2.032205672611911, 'lambdaL2': 0.7531298630000393, 'minGainToSplit': 0.34989404611335073, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:28:57 WARN DAGScheduler: Broadcasting large task binary with size 1407.2 KiB
26/05/03 22:28:58 WARN DAGScheduler: Broadcasting large task binary with size 1407.2 KiB
Best trial: 70. Best value: 0.700372:  83%|████████▎ | 83/100 [12:10<02:41,  9.52s/it]

[I 2026-05-03 22:28:59,676] Trial 82 finished with value: 0.6978273888888888 and parameters: {'learningRate': 0.03920871180448758, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.933797447290632, 'baggingFreq': 3, 'featureFraction': 0.9850260157544086, 'lambdaL1': 0.30042918576301736, 'lambdaL2': 4.660684152199193, 'minGainToSplit': 0.26075824023387045, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:29:06 WARN DAGScheduler: Broadcasting large task binary with size 1367.4 KiB
26/05/03 22:29:07 WARN DAGScheduler: Broadcasting large task binary with size 1367.4 KiB
Best trial: 70. Best value: 0.700372:  84%|████████▍ | 84/100 [12:19<02:30,  9.38s/it]

[I 2026-05-03 22:29:08,718] Trial 83 finished with value: 0.6966437777777778 and parameters: {'learningRate': 0.03550615094663117, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9454769990835228, 'baggingFreq': 3, 'featureFraction': 0.9735043921466848, 'lambdaL1': 0.9965641299626427, 'lambdaL2': 0.25917953308207153, 'minGainToSplit': 0.47905828831506625, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:29:16 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/03 22:29:17 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 70. Best value: 0.700372:  85%|████████▌ | 85/100 [12:30<02:24,  9.66s/it]

[I 2026-05-03 22:29:19,037] Trial 84 finished with value: 0.6986477777777778 and parameters: {'learningRate': 0.025834681590700872, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.9002813569827107, 'baggingFreq': 3, 'featureFraction': 0.9594861824467517, 'lambdaL1': 2.587699097283155, 'lambdaL2': 0.9955398363003077, 'minGainToSplit': 0.19622774426085915, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:29:27 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
26/05/03 22:29:29 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
Best trial: 70. Best value: 0.700372:  86%|████████▌ | 86/100 [12:41<02:22, 10.15s/it]

[I 2026-05-03 22:29:30,338] Trial 85 finished with value: 0.6975203333333333 and parameters: {'learningRate': 0.015986266943737424, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.914436907235676, 'baggingFreq': 3, 'featureFraction': 0.9924973626755633, 'lambdaL1': 0.09179635682331372, 'lambdaL2': 2.3664586773908183, 'minGainToSplit': 0.13254197072587118, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:29:39 WARN DAGScheduler: Broadcasting large task binary with size 3.3 MiB
26/05/03 22:29:41 WARN DAGScheduler: Broadcasting large task binary with size 3.3 MiB
Best trial: 70. Best value: 0.700372:  87%|████████▋ | 87/100 [12:53<02:19, 10.73s/it]

[I 2026-05-03 22:29:42,431] Trial 86 finished with value: 0.6990992777777778 and parameters: {'learningRate': 0.013361056423491774, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8872778708544706, 'baggingFreq': 3, 'featureFraction': 0.9768071064632332, 'lambdaL1': 5.819708482292807, 'lambdaL2': 0.08321400972590501, 'minGainToSplit': 0.3229424890289151, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:29:51 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
26/05/03 22:29:52 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
Best trial: 70. Best value: 0.700372:  88%|████████▊ | 88/100 [13:05<02:11, 10.99s/it]

[I 2026-05-03 22:29:54,028] Trial 87 finished with value: 0.6991741666666667 and parameters: {'learningRate': 0.01338316577028605, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8873142511033859, 'baggingFreq': 3, 'featureFraction': 0.9682737031186356, 'lambdaL1': 9.724424203516671, 'lambdaL2': 0.02288069291238029, 'minGainToSplit': 0.30986726579736523, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:30:02 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/05/03 22:30:03 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
Best trial: 70. Best value: 0.700372:  89%|████████▉ | 89/100 [13:15<02:00, 10.95s/it]

[I 2026-05-03 22:30:04,861] Trial 88 finished with value: 0.6959113333333332 and parameters: {'learningRate': 0.022306676387804165, 'numLeaves': 63, 'maxDepth': 8, 'minDataInLeaf': 10, 'baggingFraction': 0.8774142445930274, 'baggingFreq': 3, 'featureFraction': 0.9256972237096407, 'lambdaL1': 0.00013094212461525732, 'lambdaL2': 0.29169926433256343, 'minGainToSplit': 0.16364639469343736, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:30:14 WARN DAGScheduler: Broadcasting large task binary with size 3.5 MiB
26/05/03 22:30:16 WARN DAGScheduler: Broadcasting large task binary with size 3.5 MiB
Best trial: 70. Best value: 0.700372:  90%|█████████ | 90/100 [13:28<01:55, 11.58s/it]

[I 2026-05-03 22:30:17,947] Trial 89 finished with value: 0.6998602777777777 and parameters: {'learningRate': 0.01303873470542372, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.860537764119187, 'baggingFreq': 3, 'featureFraction': 0.9668789805124158, 'lambdaL1': 9.720502603434989, 'lambdaL2': 0.03174600446069962, 'minGainToSplit': 0.2687558588074373, 'maxBin': 127}. Best is trial 70 with value: 0.7003723888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:30:26 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/05/03 22:30:27 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
Best trial: 90. Best value: 0.700409:  91%|█████████ | 91/100 [13:39<01:42, 11.34s/it]

[I 2026-05-03 22:30:28,707] Trial 90 finished with value: 0.7004085555555555 and parameters: {'learningRate': 0.012609738383859002, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8280073555502637, 'baggingFreq': 3, 'featureFraction': 0.9651577070289638, 'lambdaL1': 4.216940990537675, 'lambdaL2': 0.00463248526766978, 'minGainToSplit': 0.3734377726398931, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:30:37 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
26/05/03 22:30:39 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
Best trial: 90. Best value: 0.700409:  92%|█████████▏| 92/100 [13:51<01:31, 11.40s/it]

[I 2026-05-03 22:30:40,264] Trial 91 finished with value: 0.6984736666666664 and parameters: {'learningRate': 0.0124464080925855, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8073838495573727, 'baggingFreq': 3, 'featureFraction': 0.9680500092571326, 'lambdaL1': 4.026231777266316, 'lambdaL2': 0.019744785264498146, 'minGainToSplit': 0.4108827594508785, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:30:49 WARN DAGScheduler: Broadcasting large task binary with size 3.2 MiB
26/05/03 22:30:51 WARN DAGScheduler: Broadcasting large task binary with size 3.2 MiB
Best trial: 90. Best value: 0.700409:  93%|█████████▎| 93/100 [14:03<01:21, 11.62s/it]

[I 2026-05-03 22:30:52,406] Trial 92 finished with value: 0.6989641111111111 and parameters: {'learningRate': 0.011021505099265578, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8285180173941252, 'baggingFreq': 3, 'featureFraction': 0.9548960586191718, 'lambdaL1': 9.991188104092746, 'lambdaL2': 0.004578134430211268, 'minGainToSplit': 0.3622095508021122, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:31:00 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
26/05/03 22:31:02 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
Best trial: 90. Best value: 0.700409:  94%|█████████▍| 94/100 [14:14<01:09, 11.52s/it]

[I 2026-05-03 22:31:03,668] Trial 93 finished with value: 0.6973602777777778 and parameters: {'learningRate': 0.01397674551194613, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8379437594051319, 'baggingFreq': 3, 'featureFraction': 0.9650454090271147, 'lambdaL1': 0.5494314531885028, 'lambdaL2': 0.03148556626880823, 'minGainToSplit': 0.2712418360273403, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:31:11 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
26/05/03 22:31:12 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
Best trial: 90. Best value: 0.700409:  95%|█████████▌| 95/100 [14:25<00:55, 11.19s/it]

[I 2026-05-03 22:31:14,079] Trial 94 finished with value: 0.6977811666666667 and parameters: {'learningRate': 0.012070981257121962, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 50, 'baggingFraction': 0.8164486354244439, 'baggingFreq': 3, 'featureFraction': 0.9837629620387415, 'lambdaL1': 1.1716532537371098, 'lambdaL2': 0.05946906979779817, 'minGainToSplit': 0.3121291105578937, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:31:23 WARN DAGScheduler: Broadcasting large task binary with size 3.5 MiB
26/05/03 22:31:24 WARN DAGScheduler: Broadcasting large task binary with size 3.5 MiB
Best trial: 90. Best value: 0.700409:  96%|█████████▌| 96/100 [14:37<00:45, 11.49s/it]

[I 2026-05-03 22:31:26,295] Trial 95 finished with value: 0.6993029444444442 and parameters: {'learningRate': 0.010285664047452332, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8622737810765045, 'baggingFreq': 3, 'featureFraction': 0.9450309808231429, 'lambdaL1': 4.903884990061098, 'lambdaL2': 0.0019910555835957982, 'minGainToSplit': 0.37263410340225733, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:31:33 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/03 22:31:35 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 90. Best value: 0.700409:  97%|█████████▋| 97/100 [14:47<00:33, 11.05s/it]

[I 2026-05-03 22:31:36,311] Trial 96 finished with value: 0.6981678888888888 and parameters: {'learningRate': 0.01609218535473633, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8600904612108885, 'baggingFreq': 3, 'featureFraction': 0.8445595591493714, 'lambdaL1': 5.864749028437392, 'lambdaL2': 0.0017776121502407992, 'minGainToSplit': 0.4750299921178392, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:31:46 WARN DAGScheduler: Broadcasting large task binary with size 3.2 MiB
26/05/03 22:31:48 WARN DAGScheduler: Broadcasting large task binary with size 3.2 MiB
Best trial: 90. Best value: 0.700409:  98%|█████████▊| 98/100 [15:01<00:23, 11.86s/it]

[I 2026-05-03 22:31:50,052] Trial 97 finished with value: 0.6980222777777777 and parameters: {'learningRate': 0.010351780050481636, 'numLeaves': 127, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.8438359896462344, 'baggingFreq': 3, 'featureFraction': 0.9466467530159951, 'lambdaL1': 3.2962890988794973, 'lambdaL2': 0.012282267965249343, 'minGainToSplit': 0.37369381906543064, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:31:59 WARN DAGScheduler: Broadcasting large task binary with size 4.3 MiB
26/05/03 22:32:01 WARN DAGScheduler: Broadcasting large task binary with size 4.3 MiB
Best trial: 90. Best value: 0.700409:  99%|█████████▉| 99/100 [15:13<00:12, 12.15s/it]

[I 2026-05-03 22:32:02,892] Trial 98 finished with value: 0.6968603888888888 and parameters: {'learningRate': 0.01174255213763655, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.8671659138507357, 'baggingFreq': 3, 'featureFraction': 0.9749796946581722, 'lambdaL1': 3.222773658707746e-05, 'lambdaL2': 0.0006310541606562118, 'minGainToSplit': 0.4388006113421846, 'maxBin': 127}. Best is trial 90 with value: 0.7004085555555555.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:32:13 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
26/05/03 22:32:15 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
Best trial: 99. Best value: 0.700986: 100%|██████████| 100/100 [15:27<00:00,  9.28s/it]

[I 2026-05-03 22:32:16,768] Trial 99 finished with value: 0.7009858888888889 and parameters: {'learningRate': 0.010259395566444143, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 10, 'baggingFraction': 0.7965161151921767, 'baggingFreq': 5, 'featureFraction': 0.9562031053637944, 'lambdaL1': 4.971067802769688, 'lambdaL2': 0.002484856335700491, 'minGainToSplit': 0.5373076515009603, 'maxBin': 127}. Best is trial 99 with value: 0.7009858888888889.
========== Optuna Best Result ==========
Best validation AUC: 0.7009858888888889

Best params:
{
  "learningRate": 0.010259395566444143,
  "numLeaves": 63,
  "maxDepth": 10,
  "minDataInLeaf": 10,
  "baggingFraction": 0.7965161151921767,
  "baggingFreq": 5,
  "featureFraction": 0.9562031053637944,
  "lambdaL1": 4.971067802769688,
  "lambdaL2": 0.002484856335700491,
  "minGainToSplit": 0.5373076515009603,
  "maxBin": 127
}

Best trial extra info:
Trial number    : 99
Test AUC        : 0.7062120555555556
Best iteration  : None
Fit seconds     : 10.456836938858032
========================================

In [26]:
# ============================================================
# Save and review Optuna tuning results
# ============================================================

from pathlib import Path
import pandas as pd

# Đảm bảo output directory tồn tại
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)


# ============================================================
# 1. Save all Optuna trials
# ============================================================

trials_df = study.trials_dataframe()

trials_path = f"{OUTPUT_DIR}/optuna_synapseml_lgbm_trials.csv"
trials_df.to_csv(trials_path, index=False)

print("Saved Optuna trials:", trials_path)


# ============================================================
# 2. Show top trials by validation AUC
# ============================================================

# value = validation AUC vì objective() return valid_auc
top_trials_df = (
    trials_df
    .dropna(subset=["value"])
    .sort_values("value", ascending=False)
    .head(10)
)

print("\nTop 10 trials by validation AUC:")
display(top_trials_df)


# ============================================================
# 3. Parameter importance
# ============================================================

try:
    from optuna.importance import get_param_importances

    complete_trials = [
        trial for trial in study.trials
        if trial.state == optuna.trial.TrialState.COMPLETE
        and trial.value is not None
    ]

    if len(complete_trials) < 2:
        print(
            "\nParam importance skipped: "
            "cần ít nhất 2 completed trials để tính importance."
        )
    else:
        param_importance = get_param_importances(study)

        param_importance_df = (
            pd.DataFrame(
                {
                    "parameter": list(param_importance.keys()),
                    "importance": list(param_importance.values()),
                }
            )
            .sort_values("importance", ascending=False)
        )

        param_importance_path = (
            f"{OUTPUT_DIR}/optuna_synapseml_param_importance.csv"
        )

        param_importance_df.to_csv(param_importance_path, index=False)

        print("\nSaved parameter importance:", param_importance_path)
        display(param_importance_df)

except Exception as e:
    print("\nParam importance skipped:", repr(e))

Saved Optuna trials: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/optuna_synapseml_lgbm_trials.csv

Top 10 trials by validation AUC:

,number,value,datetime_start,datetime_complete,duration,params_baggingFraction,params_baggingFreq,params_featureFraction,params_lambdaL1,params_lambdaL2,...,params_maxBin,params_maxDepth,params_minDataInLeaf,params_minGainToSplit,params_numLeaves,user_attrs_best_iteration,user_attrs_fit_seconds,user_attrs_test_auc,system_attrs_fixed_params,state
99,99,0.700986,2026-05-03 22:32:03.009173,2026-05-03 22:32:16.768096,0 days 00:00:13.758923,0.796516,5,0.956203,4.971068,0.002485,...,127,10,10,0.537308,63,None,10.456837,0.706212,NaN,COMPLETE
90,90,0.700409,2026-05-03 22:30:18.064409,2026-05-03 22:30:28.707429,0 days 00:00:10.643020,0.828007,3,0.965158,4.216941,0.004632,...,127,6,10,0.373438,63,None,7.794500,0.707812,NaN,COMPLETE
70,70,0.700372,2026-05-03 22:26:52.169156,2026-05-03 22:27:01.912247,0 days 00:00:09.743091,0.919530,3,0.962529,3.289131,2.372483,...,127,6,10,0.279410,63,None,7.267786,0.703507,NaN,COMPLETE
74,74,0.700154,2026-05-03 22:27:32.073774,2026-05-03 22:27:41.470931,0 days 00:00:09.397157,0.888633,3,0.984960,2.198769,0.493260,...,127,6,10,0.353187,63,None,7.006494,0.705568,NaN,COMPLETE
89,89,0.699860,2026-05-03 22:30:05.006740,2026-05-03 22:30:17.947284,0 days 00:00:12.940544,0.860538,3,0.966879,9.720503,0.031746,...,127,6,10,0.268756,63,None,9.538091,0.706056,NaN,COMPLETE
50,50,0.699818,2026-05-03 22:24:04.082980,2026-05-03 22:24:12.185860,0 days 00:00:08.102880,0.937382,3,0.987537,0.002531,0.000042,...,127,6,10,0.070547,15,None,6.006586,0.699735,NaN,COMPLETE
31,31,0.699697,2026-05-03 22:21:15.650330,2026-05-03 22:21:24.682979,0 days 00:00:09.032649,0.996682,5,0.872007,0.000002,0.003847,...,127,6,10,0.438669,15,None,6.521441,0.706532,NaN,COMPLETE
52,52,0.699580,2026-05-03 22:24:19.988390,2026-05-03 22:24:28.224497,0 days 00:00:08.236107,0.846562,3,0.958177,0.001617,0.000304,...,127,6,10,0.120029,15,None,6.070747,0.693454,NaN,COMPLETE
95,95,0.699303,2026-05-03 22:31:14.199014,2026-05-03 22:31:26.295019,0 days 00:00:12.096005,0.862274,3,0.945031,4.903885,0.001991,...,127,6,10,0.372634,63,None,8.944494,0.706565,NaN,COMPLETE
75,75,0.699231,2026-05-03 22:27:41.586716,2026-05-03 22:27:51.091713,0 days 00:00:09.504997,0.888923,3,0.984195,1.787606,0.408944,...,127,6,10,0.267604,63,None,6.942793,0.707149,NaN,COMPLETE

Saved parameter importance: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/optuna_synapseml_param_importance.csv

          parameter  importance
0       baggingFreq    0.206275
1            maxBin    0.205810
2    minGainToSplit    0.111753
3          lambdaL1    0.102091
4      learningRate    0.097535
5   featureFraction    0.079994
6     minDataInLeaf    0.072549
7          maxDepth    0.071765
8   baggingFraction    0.044810
9         numLeaves    0.006105
10         lambdaL2    0.001313

## 18. Select best params and train final model

Nếu Optuna tốt hơn baseline theo validation AUC thì dùng Optuna; ngược lại giữ baseline.

In [27]:
# ============================================================
# Select best parameters: Optuna vs Baseline
# ============================================================

# Nếu Optuna tốt hơn hoặc bằng baseline trên validation AUC,
# dùng best params từ Optuna.
# Ngược lại, quay về baseline params.
if float(study.best_value) >= float(baseline_valid_auc):
    selected_params = dict(study.best_params)
    selected_param_source = "optuna"
    selected_valid_auc = float(study.best_value)
else:
    selected_params = dict(baseline_params)
    selected_param_source = "baseline"
    selected_valid_auc = float(baseline_valid_auc)


# Build full SynapseML params:
# - selected_params chỉ chứa model params cần tune
# - build_lgbm_params() sẽ thêm các fixed params như:
#   numIterations, earlyStoppingRound, numTasks, numThreads, timeout...
selected_lgbm_params = build_lgbm_params(selected_params)


print("========== Selected LightGBM Parameters ==========")
print("Selected param source:", selected_param_source)
print("Selected validation AUC:", selected_valid_auc)

print("\nSelected tunable params:")
print(json.dumps(selected_params, indent=2, default=str))

print("\nSelected full SynapseML params:")
print(json.dumps(selected_lgbm_params, indent=2, default=str))

print("==================================================")

========== Selected LightGBM Parameters ==========
Selected param source: optuna
Selected validation AUC: 0.7009858888888889

Selected tunable params:
{
  "learningRate": 0.010259395566444143,
  "numLeaves": 63,
  "maxDepth": 10,
  "minDataInLeaf": 10,
  "baggingFraction": 0.7965161151921767,
  "baggingFreq": 5,
  "featureFraction": 0.9562031053637944,
  "lambdaL1": 4.971067802769688,
  "lambdaL2": 0.002484856335700491,
  "minGainToSplit": 0.5373076515009603,
  "maxBin": 127
}

Selected full SynapseML params:
{
  "objective": "binary",
  "metric": "auc",
  "featuresCol": "features",
  "labelCol": "label",
  "validationIndicatorCol": "is_validation",
  "learningRate": 0.010259395566444143,
  "numLeaves": 63,
  "maxDepth": 10,
  "minDataInLeaf": 10,
  "baggingFraction": 0.7965161151921767,
  "baggingFreq": 5,
  "featureFraction": 0.9562031053637944,
  "lambdaL1": 4.971067802769688,
  "lambdaL2": 0.002484856335700491,
  "minGainToSplit": 0.5373076515009603,
  "maxBin": 127,
  "numIterations": 2000,
  "earlyStoppingRound": 100,
  "numTasks": 4,
  "numThreads": 3,
  "maxStreamingOMPThreads": 3,
  "timeout": 600,
  "useBarrierExecutionMode": true,
  "useSingleDatasetMode": true,
  "dataTransferMode": "streaming",
  "verbosity": -1
}
==================================================

In [28]:
# ============================================================
# Train final SynapseML LightGBM model
# ============================================================

final_shap_col = "featuresShap" if RUN_FINAL_SHAP else None

final_result, final_model, final_test_pred_df = train_lgbm_baseline(
    params=selected_params,
    train_valid_df=lgbm_train_valid_df,
    valid_df=valid_features_df,
    test_df=test_features_df,
    categorical_slot_indexes=feature_pipeline.categorical_slot_indexes_,
    shap_col=final_shap_col,
    keep_test_predictions=True,
)

final_valid_auc = final_result["valid_auc"]
final_test_auc = final_result["test_auc"]
final_best_iteration = final_result["best_iteration"]

print("========== Final Model Result ==========")
print(json.dumps(final_result, indent=2, default=str))

print("\nRUN_FINAL_SHAP:", RUN_FINAL_SHAP)
print("Final prediction columns:")
print(final_test_pred_df.columns)
print("========================================")

[LightGBM] [Info] Saving data reference to binary buffer

26/05/03 22:33:13 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
26/05/03 22:33:14 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
26/05/03 22:33:16 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB
26/05/03 22:34:15 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB

========== Final Model Result ==========
{
  "valid_auc": 0.7009984444444446,
  "test_auc": 0.7062029444444446,
  "best_iteration": null,
  "fit_seconds": 10.467931032180786
}

RUN_FINAL_SHAP: True
Final prediction columns:
['features', 'label', 'rawPrediction', 'probability', 'prediction', 'featuresShap']
========================================

In [29]:
# ============================================================
# Save AUC summary
# ============================================================

from pathlib import Path
import pandas as pd

Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

# Lấy test AUC của best Optuna trial nếu có
optuna_best_test_auc = study.best_trial.user_attrs.get("test_auc")

auc_summary_df = pd.DataFrame([
    {
        "case": "baseline",
        "valid_auc": float(baseline_valid_auc),
        "test_auc": float(baseline_test_auc),
        "param_source": "baseline",
    },
    {
        "case": "optuna_best",
        "valid_auc": float(study.best_value),
        "test_auc": (
            float(optuna_best_test_auc)
            if optuna_best_test_auc is not None
            else None
        ),
        "param_source": "optuna",
    },
    {
        "case": "final_selected",
        "valid_auc": float(final_valid_auc),
        "test_auc": float(final_test_auc),
        "param_source": selected_param_source,
    },
])

auc_summary_path = f"{OUTPUT_DIR}/auc_summary.csv"
auc_summary_df.to_csv(auc_summary_path, index=False)

print("Saved AUC summary:", auc_summary_path)
display(auc_summary_df)

Saved AUC summary: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/auc_summary.csv

             case  valid_auc  test_auc param_source
0        baseline   0.698468  0.703388     baseline
1     optuna_best   0.700986  0.706212       optuna
2  final_selected   0.700998  0.706203       optuna

In [30]:
# ============================================================
# Save best SynapseML LightGBM configuration
# ============================================================

from pathlib import Path
import json

Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

# Full params dùng để train SynapseML LightGBM.
# selected_params chỉ là tunable params, còn build_lgbm_params()
# sẽ bổ sung fixed params như numIterations, numTasks, numThreads...
selected_lgbm_params = build_lgbm_params(selected_params)

# Lấy test AUC của best Optuna trial nếu có
optuna_best_test_auc = study.best_trial.user_attrs.get("test_auc")
optuna_best_iteration = study.best_trial.user_attrs.get("best_iteration")
optuna_fit_seconds = study.best_trial.user_attrs.get("fit_seconds")

# Trong TaxiFeaturePipeline phiên bản mới,
# categorical features gồm:
# - categorical numeric columns
# - string columns sau khi StringIndexer
categorical_feature_cols = (
    feature_pipeline.categorical_numeric_cols_
    + feature_pipeline.string_indexed_cols_
)

best_config = {
    "model": "SynapseML LightGBM",
    "task": "current_batch_vs_historical_batches",
    "target_processing_date_hour": str(TARGET_PROCESSING_DATE_HOUR),
    "comparison_processing_date_hours": [
        str(h) for h in comparison_processing_hours
    ],

    # Main metric
    "metric": "auc",

    # Baseline result
    "baseline": {
        "valid_auc": float(baseline_valid_auc),
        "test_auc": float(baseline_test_auc),
        "params": baseline_params,
    },

    # Optuna result
    "optuna_best": {
        "valid_auc": float(study.best_value),
        "test_auc": (
            float(optuna_best_test_auc)
            if optuna_best_test_auc is not None
            else None
        ),
        "best_iteration": (
            int(optuna_best_iteration)
            if optuna_best_iteration is not None
            else None
        ),
        "fit_seconds": (
            float(optuna_fit_seconds)
            if optuna_fit_seconds is not None
            else None
        ),
        "params": study.best_params,
    },

    # Final selected result
    "final_selected": {
        "selected_param_source": selected_param_source,
        "selected_valid_auc": float(selected_valid_auc),
        "selected_tunable_params": selected_params,
        "selected_full_lgbm_params": selected_lgbm_params,
        "final_valid_auc": float(final_valid_auc),
        "final_test_auc": float(final_test_auc),
        "final_best_iteration": (
            int(final_best_iteration)
            if final_best_iteration is not None
            else None
        ),
    },

    # Feature information
    "features": {
        "numeric_feature_cols": feature_pipeline.numeric_feature_cols_,
        "categorical_numeric_cols": feature_pipeline.categorical_numeric_cols_,
        "categorical_string_cols": feature_pipeline.categorical_string_cols_,
        "string_indexed_cols": feature_pipeline.string_indexed_cols_,
        "final_feature_cols": feature_pipeline.feature_cols_,
        "categorical_feature_cols": categorical_feature_cols,
        "categorical_slot_indexes": feature_pipeline.categorical_slot_indexes_,
    },

    # Fixed experiment config
    "fixed_training_config": {
        "random_state": RANDOM_STATE,
        "target_sample_per_group": TARGET_SAMPLE_PER_GROUP,
        "min_rows_per_group": MIN_ROWS_PER_GROUP,
        "previous_batch_offset": str(PREVIOUS_BATCH_OFFSET),
        "history_offsets": [
            str(offset) for offset in HISTORY_OFFSETS
        ],
        "n_estimators_max": N_ESTIMATORS_MAX,
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "lgbm_num_tasks": LGBM_NUM_TASKS,
        "lgbm_num_threads": LGBM_NUM_THREADS,
        "spark_sql_shuffle_partitions": SPARK_SQL_SHUFFLE_PARTITIONS,
        "run_optuna": RUN_OPTUNA,
        "n_trials": N_TRIALS,
        "run_final_shap": RUN_FINAL_SHAP,
        "use_fixed_ports": USE_FIXED_PORTS,
    },
}

best_config_path = f"{OUTPUT_DIR}/best_synapseml_lightgbm_config.json"

with open(best_config_path, "w", encoding="utf-8") as f:
    json.dump(
        best_config,
        f,
        indent=2,
        ensure_ascii=False,
        default=str,
    )

print("Saved best config:", best_config_path)

Saved best config: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/best_synapseml_lightgbm_config.json

## 19. Classification report on test set

AUC là metric chính cho drift detection. Classification report chỉ để xem thêm tại một threshold cụ thể.

In [ ]:
THRESHOLD = 0.5

score_pdf = extract_probability_label_df(final_test_pred_df)
score_pdf["y_pred"] = (score_pdf["pred_score"] >= THRESHOLD).astype(int)

print("Test AUC from Spark:", final_test_auc)
print("Test AUC from pandas:", roc_auc_score(score_pdf["y_true"], score_pdf["pred_score"]))
print("Threshold:", THRESHOLD)
print(classification_report(score_pdf["y_true"], score_pdf["y_pred"], digits=4))

score_path = f"{OUTPUT_DIR}/final_test_predictions_scores.csv"
score_pdf.to_csv(score_path, index=False)
print("Saved:", score_path)

## 20. Feature importance and optional SHAP

- Native feature importance nhẹ hơn SHAP.
- SHAP trong SynapseML nặng hơn nhiều, nên chỉ bật bằng `RUN_FINAL_SHAP=True`.

In [ ]:
def get_synapseml_feature_importance_df(model, feature_cols):
    """Đọc feature importance từ SynapseML model nếu version hiện tại hỗ trợ."""
    importances = None

    # SynapseML versions khác nhau có thể expose importance khác nhau.
    for expr in [
        "model.getFeatureImportances()",
        "model.getLightGBMBooster().getFeatureImportances()",
    ]:
        try:
            importances = eval(expr)
            break
        except Exception:
            pass

    if importances is None:
        print("Could not read native feature_importances from SynapseML model.")
        return pd.DataFrame({"feature": feature_cols, "importance": np.nan})

    importances = list(importances)
    n = min(len(importances), len(feature_cols))

    if len(importances) != len(feature_cols):
        print("Warning: importance length mismatch:", len(importances), len(feature_cols))

    return pd.DataFrame({
        "feature": feature_cols[:n],
        "importance": importances[:n],
    }).sort_values("importance", ascending=False)


importance_df = get_synapseml_feature_importance_df(final_model, feature_pipeline.feature_cols_)
importance_path = f"{OUTPUT_DIR}/final_synapseml_feature_importance.csv"
importance_df.to_csv(importance_path, index=False)

print("Saved:", importance_path)
display(importance_df.head(30))

In [ ]:
import matplotlib.pyplot as plt

plot_df = importance_df.dropna().head(20).sort_values("importance")

if len(plot_df) > 0:
    plt.figure(figsize=(8, 6))
    plt.barh(plot_df["feature"], plot_df["importance"])
    plt.xlabel("Importance")
    plt.ylabel("Feature")
    plt.title("Top SynapseML LightGBM Feature Importance")
    plt.show()
else:
    print("Native feature importance not available or empty.")

In [ ]:
def compute_top_shap_from_predictions(pred_df, feature_cols, shap_col="featuresShap", top_n=20, sample_size=None, seed=42):
    """Tính mean(|SHAP|) cho từng feature từ prediction DataFrame."""
    if shap_col not in pred_df.columns:
        raise ValueError(
            f"Column {shap_col!r} không tồn tại. "
            "Hãy bật RUN_FINAL_SHAP=True hoặc estimator phải có featuresShapCol."
        )

    shap_source_df = pred_df

    if sample_size is not None:
        total = pred_df.count()
        if total > sample_size:
            frac = min(1.0, float(sample_size) / float(total) * 1.5)
            shap_source_df = pred_df.sample(False, frac, seed=seed).limit(int(sample_size))

    shap_df = shap_source_df.withColumn("shap_array", vector_to_array(shap_col))
    shap_size = shap_df.select(F.size("shap_array").alias("shap_size")).first()["shap_size"]

    shap_long_df = shap_df.select(
        F.posexplode("shap_array").alias("feature_index", "shap_value")
    )

    # Một số version có bias/base value ở cuối vector SHAP. Nếu có, bỏ phần đó.
    if shap_size == len(feature_cols) + 1:
        shap_long_df = shap_long_df.filter(F.col("feature_index") < len(feature_cols))

    feature_mapping_df = spark.createDataFrame(
        [(i, name) for i, name in enumerate(feature_cols)],
        ["feature_index", "feature"],
    )

    shap_all_df = (
        shap_long_df
        .groupBy("feature_index")
        .agg(F.avg(F.abs("shap_value")).alias("mean_abs_shap"))
        .join(F.broadcast(feature_mapping_df), on="feature_index", how="left")
        .orderBy(F.desc("mean_abs_shap"))
    )

    return shap_all_df.limit(top_n), shap_all_df


if RUN_FINAL_SHAP and final_test_pred_df is not None and "featuresShap" in final_test_pred_df.columns:
    shap_top_df_spark, shap_all_df_spark = compute_top_shap_from_predictions(
        pred_df=final_test_pred_df,
        feature_cols=feature_pipeline.feature_cols_,
        shap_col="featuresShap",
        top_n=20,
        sample_size=SHAP_SAMPLE_SIZE,
        seed=RANDOM_STATE,
    )

    shap_top_pdf = shap_top_df_spark.toPandas()
    shap_path = f"{OUTPUT_DIR}/final_synapseml_shap_top_features.csv"
    shap_top_pdf.to_csv(shap_path, index=False)

    print("Saved:", shap_path)
    display(shap_top_pdf)
else:
    shap_top_pdf = pd.DataFrame(columns=["feature_index", "mean_abs_shap", "feature"])
    print("Final SHAP skipped. Set RUN_FINAL_SHAP=True to compute SynapseML featuresShap.")

In [ ]:
if len(shap_top_pdf) > 0:
    plot_df = shap_top_pdf.sort_values("mean_abs_shap")

    plt.figure(figsize=(8, 6))
    plt.barh(plot_df["feature"], plot_df["mean_abs_shap"])
    plt.xlabel("Mean absolute SHAP value")
    plt.ylabel("Feature")
    plt.title("Top SynapseML SHAP Features")
    plt.show()
else:
    print("No SHAP plot because SHAP was skipped or unavailable.")

## 21. Optional: Synthetic anomaly experiment

Phần này chỉ chạy khi `RUN_SYNTHETIC_EXPERIMENTS=True`. Mục tiêu là kiểm tra detector có nhạy hơn khi ta cố tình inject anomaly vào target batch hay không.

In [ ]:
ANOMALY_LEVELS = [0.0, 0.05, 0.10, 0.20, 0.30, 0.50, 0.75]
ANOMALY_RANDOM_STATE = 2025


def inject_synthetic_anomalies_spark(target_df, anomaly_fraction=0.30, random_state=42):
    """
    Inject anomaly đơn giản vào một phần target rows.

    Đây chỉ là synthetic test, không dùng để clean dữ liệu thật.
    """
    data = (
        target_df
        .withColumn("_r_anom", F.rand(int(random_state)))
        .withColumn("synthetic_anomaly", (F.col("_r_anom") < float(anomaly_fraction)).cast("int"))
        .withColumn("_anom_group", (F.rand(int(random_state) + 1) * 5).cast("int"))
    )

    is_anom = F.col("synthetic_anomaly") == 1

    if "trip_distance" in data.columns:
        data = data.withColumn(
            "trip_distance",
            F.when(is_anom & (F.col("_anom_group") == 0), F.col("trip_distance") * F.lit(5.0))
             .otherwise(F.col("trip_distance"))
        )

    if "total_amount" in data.columns:
        data = data.withColumn(
            "total_amount",
            F.when(is_anom & (F.col("_anom_group") == 1), F.col("total_amount") * F.lit(4.0))
             .otherwise(F.col("total_amount"))
        )

    if "fare_amount" in data.columns:
        data = data.withColumn(
            "fare_amount",
            F.when(is_anom & (F.col("_anom_group") == 2), F.col("fare_amount") * F.lit(4.0))
             .otherwise(F.col("fare_amount"))
        )

    if "store_and_fwd_flag" in data.columns:
        data = data.withColumn(
            "store_and_fwd_flag",
            F.when(is_anom & (F.col("_anom_group") == 3), F.lit("ANOM"))
             .otherwise(F.col("store_and_fwd_flag"))
        )

    for loc_col in ["pulocationid", "dolocationid"]:
        if loc_col in data.columns:
            data = data.withColumn(
                loc_col,
                F.when(is_anom & (F.col("_anom_group") == 4), F.lit(999))
                 .otherwise(F.col(loc_col))
            )

    return data.drop("_r_anom", "_anom_group")


def train_synapseml_on_work_df(batch_work_df, synapseml_params, random_state=42, shap_col=None, return_artifacts=False):
    """
    Train/evaluate trọn gói trên một work_df bất kỳ.

    Dùng cho:
    - Synthetic experiments.
    - Batch monitoring loop.
    """
    local_split_df = None
    local_lgbm_train_df = None
    local_train_features_df = None
    local_valid_features_df = None
    local_test_features_df = None
    local_test_pred_df = None

    try:
        local_train_raw_df, local_valid_raw_df, local_test_raw_df, local_split_df = stratified_split_sklearn_like_spark(
            input_df=batch_work_df,
            label_col="label",
            test_size=TEST_SIZE,
            valid_size=VALID_SIZE,
            seed=random_state,
            cache_result=True,
            return_split_df=True,
        )

        local_pipeline = SparkTaxiFeaturePipeline(
            categorical_cols=CATEGORICAL_COLS,
            numeric_cols=NUMERIC_COLS,
            exclude_cols=EXCLUDE_COLS,
            label_col="label",
        ).fit(local_train_raw_df)

        local_train_features_df = local_pipeline.transform(local_train_raw_df).select("features", "label").persist(StorageLevel.MEMORY_AND_DISK)
        local_valid_features_df = local_pipeline.transform(local_valid_raw_df).select("features", "label").persist(StorageLevel.MEMORY_AND_DISK)
        local_test_features_df = local_pipeline.transform(local_test_raw_df).select("features", "label").persist(StorageLevel.MEMORY_AND_DISK)

        local_train_features_df.count()
        local_valid_features_df.count()
        local_test_features_df.count()

        local_lgbm_train_df = build_lgbm_train_df(
            train_df=local_train_features_df,
            valid_df=local_valid_features_df,
            num_partitions=LGBM_NUM_PARTITIONS,
            persist=True,
        )

        estimator = build_synapseml_lgbm_classifier(
            synapseml_params=synapseml_params,
            categorical_slot_indexes=local_pipeline.categorical_slot_indexes_,
            shap_col=shap_col,
            validation_col="is_validation",
        )

        start = time.time()
        model = estimator.fit(local_lgbm_train_df)
        fit_seconds = time.time() - start

        valid_auc, _ = evaluate_auc(model, local_valid_features_df.select("features", "label"), return_predictions=False)
        test_auc, local_test_pred_df = evaluate_auc(
            model,
            local_test_features_df.select("features", "label"),
            return_predictions=return_artifacts,
            persist_predictions=return_artifacts,
        )

        result = {
            "valid_auc": float(valid_auc),
            "test_auc": float(test_auc),
            "best_iteration": safe_get_best_iteration(model),
            "fit_seconds": float(fit_seconds),
            "feature_count": len(local_pipeline.feature_cols_),
        }

        artifacts = None
        if return_artifacts:
            artifacts = {
                "model": model,
                "pipeline": local_pipeline,
                "test_pred_df": local_test_pred_df,
                "feature_cols": local_pipeline.feature_cols_,
            }

        return result, artifacts

    finally:
        if not return_artifacts:
            for obj in [
                local_test_pred_df,
                local_lgbm_train_df,
                local_train_features_df,
                local_valid_features_df,
                local_test_features_df,
                local_split_df,
            ]:
                try:
                    if obj is not None:
                        obj.unpersist()
                except Exception:
                    pass
        gc.collect()


if RUN_SYNTHETIC_EXPERIMENTS:
    synthetic_results = []

    for frac in ANOMALY_LEVELS:
        print("Running synthetic anomaly fraction:", frac)

        temp_positive = inject_synthetic_anomalies_spark(
            positive_df,
            anomaly_fraction=frac,
            random_state=ANOMALY_RANDOM_STATE,
        )

        temp_negative = negative_df.withColumn("synthetic_anomaly", F.lit(0))

        temp_work_df = (
            temp_positive
            .unionByName(temp_negative, allowMissingColumns=True)
            .repartition(SPARK_SQL_SHUFFLE_PARTITIONS)
            .persist(StorageLevel.MEMORY_AND_DISK)
        )
        temp_work_df.count()

        try:
            result, _ = train_synapseml_on_work_df(
                temp_work_df,
                synapseml_params=selected_synapseml_params,
                random_state=RANDOM_STATE,
                shap_col=None,
                return_artifacts=False,
            )

            result["anomaly_fraction"] = float(frac)
            result["n_rows"] = int(temp_work_df.count())
            result["n_synthetic_anomaly"] = int(temp_work_df.filter(F.col("synthetic_anomaly") == 1).count())
            synthetic_results.append(result)

            print(result)
        finally:
            temp_work_df.unpersist()

    synthetic_df = pd.DataFrame(synthetic_results)
    synthetic_path = f"{OUTPUT_DIR}/synthetic_anomaly_sweep.csv"
    synthetic_df.to_csv(synthetic_path, index=False)

    print("Saved:", synthetic_path)
    display(synthetic_df)
else:
    print("Synthetic experiments skipped. Set RUN_SYNTHETIC_EXPERIMENTS=True to run.")

## 22. Optional: Batch AUC monitoring

Phần này chạy nhiều target batches liên tiếp để tạo chuỗi AUC. Chỉ chạy khi `RUN_BATCH_MONITORING=True`.

In [ ]:
def build_dataset_for_target_batch_spark(
    source_df,
    target_processing_hour,
    min_rows_per_group=MIN_ROWS_PER_GROUP,
    max_rows_per_group=TARGET_SAMPLE_PER_GROUP,
    random_state=RANDOM_STATE,
):
    """Build work_df cho một target batch cụ thể."""
    positive = sample_by_processing_hour_spark(
        source_df=source_df,
        processing_hour=target_processing_hour,
        label=1,
        max_rows=max_rows_per_group,
        random_state=random_state,
        oversample_factor=OVERSAMPLE_FACTOR,
    )

    positive_rows = positive.count()
    if positive_rows < min_rows_per_group:
        return None, {
            "status": "skipped",
            "reason": "positive_rows_too_few",
            "target_processing_date_hour": str(target_processing_hour),
            "positive_rows": int(positive_rows),
        }

    comparison_hours = get_comparison_processing_hours(target_processing_hour)

    negative_parts = []
    negative_info = []

    for i, compare_hour in enumerate(comparison_hours):
        part = sample_by_processing_hour_spark(
            source_df=source_df,
            processing_hour=compare_hour,
            label=0,
            max_rows=max_rows_per_group,
            random_state=random_state + i + 100,
            oversample_factor=OVERSAMPLE_FACTOR,
        )

        rows = part.count()
        negative_info.append({"comparison_hour": str(compare_hour), "rows": int(rows)})

        if rows >= min_rows_per_group:
            negative_parts.append(part)

    if len(negative_parts) == 0:
        return None, {
            "status": "skipped",
            "reason": "negative_rows_too_few",
            "target_processing_date_hour": str(target_processing_hour),
            "positive_rows": int(positive_rows),
            "negative_info": negative_info,
        }

    negative = negative_parts[0]
    for p in negative_parts[1:]:
        negative = negative.unionByName(p, allowMissingColumns=True)

    work = positive.unionByName(negative, allowMissingColumns=True)
    work = work.repartition(SPARK_SQL_SHUFFLE_PARTITIONS).persist(StorageLevel.MEMORY_AND_DISK)
    work.count()

    label_counts = {
        float(r["label"]): int(r["count"])
        for r in work.groupBy("label").count().collect()
    }

    meta = {
        "status": "ok",
        "target_processing_date_hour": str(target_processing_hour),
        "positive_rows": int(label_counts.get(1.0, 0)),
        "negative_rows": int(label_counts.get(0.0, 0)),
        "total_rows": int(sum(label_counts.values())),
        "comparison_hours": [str(h) for h in comparison_hours],
        "negative_info": negative_info,
    }

    return work, meta

In [ ]:
if RUN_BATCH_MONITORING:
    target_batch_list = pd.date_range(start=BATCH_START, end=BATCH_END, freq=BATCH_FREQ).tolist()

    print("Number of target batches:", len(target_batch_list))
    print("First target batch:", target_batch_list[0])
    print("Last target batch :", target_batch_list[-1])

    batch_auc_results = []

    for i, batch_hour in enumerate(target_batch_list):
        print("\n" + "=" * 80)
        print(f"[{i+1}/{len(target_batch_list)}] Target batch: {batch_hour}")

        batch_df = None
        artifacts = None

        try:
            batch_df, meta = build_dataset_for_target_batch_spark(
                source_df=df_raw,
                target_processing_hour=batch_hour,
                random_state=RANDOM_STATE + i,
            )

            if meta.get("status") != "ok":
                print("Skipped:", meta)
                batch_auc_results.append(meta)
                continue

            need_shap = bool(RUN_BATCH_SHAP)
            result, artifacts = train_synapseml_on_work_df(
                batch_df,
                synapseml_params=selected_synapseml_params,
                random_state=RANDOM_STATE + i,
                shap_col=("featuresShap" if need_shap else None),
                return_artifacts=need_shap,
            )

            row = {**meta, **result}
            batch_auc_results.append(row)
            print("Result:", row)

            # Optional SHAP per batch nếu cần.
            if need_shap and artifacts is not None:
                shap_top_df_spark, _ = compute_top_shap_from_predictions(
                    artifacts["test_pred_df"],
                    feature_cols=artifacts["feature_cols"],
                    shap_col="featuresShap",
                    top_n=10,
                    sample_size=1000,
                    seed=RANDOM_STATE + i,
                )
                shap_top_pdf = shap_top_df_spark.toPandas()
                shap_top_pdf["target_processing_date_hour"] = str(batch_hour)
                display(shap_top_pdf)

        except Exception as e:
            print("Failed:", repr(e))
            batch_auc_results.append({
                "status": "failed",
                "target_processing_date_hour": str(batch_hour),
                "reason": repr(e),
            })

        finally:
            try:
                if batch_df is not None:
                    batch_df.unpersist()
            except Exception:
                pass
            gc.collect()

    auc_series_df = pd.DataFrame(batch_auc_results)
    auc_series_path = f"{OUTPUT_DIR}/batch_auc_series.csv"
    auc_series_df.to_csv(auc_series_path, index=False)

    print("Saved:", auc_series_path)
    display(auc_series_df)
else:
    auc_series_df = pd.DataFrame()
    print("Batch monitoring skipped. Set RUN_BATCH_MONITORING=True to run.")

## 23. Empirical p-value for AUC monitoring

Nếu đã có chuỗi AUC theo batch, ta dùng empirical p-value để xem AUC hiện tại có thuộc vùng cao bất thường so với lịch sử trước đó hay không.

In [ ]:
def add_empirical_auc_anomaly_score(
    auc_df,
    auc_col="test_auc",
    time_col="target_processing_date_hour",
    min_history_points=20,
    rolling_window=None,
    alpha=0.05,
):
    """
    Tính empirical p-value theo lịch sử trước thời điểm hiện tại.

    Công thức:
    p_value = (số AUC lịch sử >= AUC hiện tại + 1) / (số điểm lịch sử + 1)

    Nếu p_value <= alpha, AUC hiện tại nằm ở vùng cao bất thường so với lịch sử.
    """
    data = auc_df.copy()

    if data.empty or auc_col not in data.columns:
        return data

    data = data.sort_values(time_col).reset_index(drop=True)

    p_values = []
    percentile_ranks = []
    history_means = []
    history_medians = []
    history_qs = []
    history_sizes = []
    anomaly_flags = []
    anomaly_reasons = []

    for i, row in data.iterrows():
        current_auc = row.get(auc_col, np.nan)
        history = data.loc[:i-1, auc_col].dropna()

        if rolling_window is not None:
            history = history.tail(int(rolling_window))

        history_size = len(history)
        history_sizes.append(history_size)

        if history_size < min_history_points or pd.isna(current_auc):
            p_values.append(np.nan)
            percentile_ranks.append(np.nan)
            history_means.append(np.nan)
            history_medians.append(np.nan)
            history_qs.append(np.nan)
            anomaly_flags.append(False)
            anomaly_reasons.append("warmup_not_enough_history")
            continue

        p_value = (np.sum(history >= current_auc) + 1) / (history_size + 1)
        percentile_rank = (np.sum(history <= current_auc) + 1) / (history_size + 1)

        history_mean = history.mean()
        history_median = history.median()
        history_q = history.quantile(1 - alpha)

        is_anomaly = p_value <= alpha

        p_values.append(float(p_value))
        percentile_ranks.append(float(percentile_rank))
        history_means.append(float(history_mean))
        history_medians.append(float(history_median))
        history_qs.append(float(history_q))
        anomaly_flags.append(bool(is_anomaly))

        if is_anomaly:
            anomaly_reasons.append(f"auc_is_in_top_{int(alpha * 100)}pct_tail_of_history")
        else:
            anomaly_reasons.append("normal_vs_history")

    q_col = f"history_auc_q{int((1-alpha)*100)}"
    data["history_size"] = history_sizes
    data["history_auc_mean"] = history_means
    data["history_auc_median"] = history_medians
    data[q_col] = history_qs
    data["auc_empirical_p_value"] = p_values
    data["auc_percentile_rank"] = percentile_ranks
    data["is_auc_anomaly"] = anomaly_flags
    data["auc_anomaly_reason"] = anomaly_reasons

    return data


if len(auc_series_df) > 0:
    auc_monitoring_df = add_empirical_auc_anomaly_score(
        auc_series_df,
        auc_col="test_auc",
        time_col="target_processing_date_hour",
        min_history_points=MIN_HISTORY_POINTS,
        rolling_window=ROLLING_WINDOW,
        alpha=ALPHA,
    )

    auc_monitoring_path = f"{OUTPUT_DIR}/batch_auc_empirical_pvalue_monitoring.csv"
    auc_monitoring_df.to_csv(auc_monitoring_path, index=False)

    print("Saved:", auc_monitoring_path)
    display(auc_monitoring_df)
else:
    print("No AUC series available. Run batch monitoring first.")

In [ ]:
if "auc_monitoring_df" in globals() and len(auc_monitoring_df) > 0:
    plot_df = auc_monitoring_df.copy()
    plot_df["target_processing_date_hour"] = pd.to_datetime(plot_df["target_processing_date_hour"])
    plot_df = plot_df.sort_values("target_processing_date_hour")

    plt.figure(figsize=(12, 5))
    plt.plot(plot_df["target_processing_date_hour"], plot_df["test_auc"], marker="o", label="test_auc")

    q_col = f"history_auc_q{int((1-ALPHA)*100)}"
    if q_col in plot_df.columns:
        plt.plot(plot_df["target_processing_date_hour"], plot_df[q_col], linestyle="--", label=q_col)

    if "is_auc_anomaly" in plot_df.columns:
        anomalies = plot_df[plot_df["is_auc_anomaly"] == True]
        if len(anomalies) > 0:
            plt.scatter(anomalies["target_processing_date_hour"], anomalies["test_auc"], s=80, label="anomaly")

    plt.xlabel("target_processing_date_hour")
    plt.ylabel("AUC")
    plt.title("Batch AUC Monitoring")
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
else:
    print("No AUC monitoring plot.")

## 24. Cleanup

Chạy cell này sau khi đã lưu xong kết quả để giải phóng cache Spark.

In [ ]:
# Chỉ cleanup khi bạn đã hoàn tất train/evaluate/monitoring.
for obj_name in [
    "final_test_pred_df",
    "lgbm_train_df",
    "train_features_df",
    "valid_features_df",
    "test_features_df",
    "main_split_df",
    "work_df",
    "df_raw",
]:
    try:
        obj = globals().get(obj_name)
        if obj is not None:
            obj.unpersist()
            print("Unpersisted:", obj_name)
    except Exception as e:
        print("Skip cleanup for", obj_name, ":", repr(e))

gc.collect()
print("Cleanup completed.")