# SynapseML LightGBM — Clean & Cluster-Optimized Notebook + Best Iteration Export

Notebook này dùng để phát hiện **data drift/anomaly theo batch** bằng cách:

- `label = 1`: batch hiện tại cần kiểm tra.
- `label = 0`: các batch lịch sử dùng để so sánh.
- Train **SynapseML LightGBM** để phân biệt 2 nhóm dữ liệu.
- Dùng **AUC** để đo mức độ khác nhau giữa batch hiện tại và lịch sử.

Thiết kế vẫn giữ các tối ưu chính của notebook cũ:

1. Không dùng `orderBy(rand()).limit()` trên toàn bộ batch lớn.
2. Sampling theo `processing_date_hour` bằng candidate sampling trước, rồi mới random sort + limit.
3. Spark split theo label bằng hash/window để gần giống `train_test_split(..., stratify=y)`.
4. Cache/persist các DataFrame dùng lại nhiều lần.
5. SynapseML profile tối ưu cho cụm `2 executors x 6 cores`, `task.cpus = 3`, `numTasks = 4`, `numThreads = 3`.
6. Không bật SHAP trong Optuna vì rất nặng; chỉ bật ở final model nếu cần.

7. Lưu `best_iteration`, `best_iteration_source`, `booster_total_iterations` để dùng lại `numIterations` cố định trong production.

## 1. Import libraries

In [1]:
import os
import json
import math
import random
import time
import gc
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
from sklearn.metrics import roc_auc_score, classification_report

from IPython.display import display

from pyspark import StorageLevel
from pyspark.sql import SparkSession, Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from pyspark.sql.types import StructType, StructField, DoubleType, LongType
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.functions import vector_to_array

from synapse.ml.lightgbm import LightGBMClassifier

print("Optuna version:", optuna.__version__)

Optuna version: 4.8.0

## 2. Configuration

Bạn chỉ cần sửa các biến trong cell này khi đổi dữ liệu, batch target hoặc cấu hình cluster.

In [2]:
# ============================================================
# Reproducibility
# ============================================================
RANDOM_STATE = 42

# ============================================================
# Input / output
# ============================================================
# Silver parquet đã clean từ Bronze -> Silver.
DATA_PATH = "/opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet"

# Nơi lưu CSV kết quả: Optuna trials, feature importance, AUC monitoring, ...
OUTPUT_DIR = "/opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# Target batch cần kiểm tra
# ============================================================
# Batch hiện tại sẽ được gán label = 1.
TARGET_PROCESSING_DATE_HOUR = pd.Timestamp("2025-01-15 12:00:00")

# Vì pipeline của bạn xử lý 12h/lần, batch liền trước là target - 12h.
PREVIOUS_BATCH_OFFSET = pd.Timedelta(hours=12)

# Các batch lịch sử bổ sung được gán label = 0.
# Bạn có thể thêm/bớt offset tùy dữ liệu thực tế.
HISTORY_OFFSETS = [
    pd.Timedelta(days=1),
    pd.Timedelta(days=7),
    pd.Timedelta(days=14),
]

# ============================================================
# Sampling theo từng processing_date_hour
# ============================================================
# Mỗi batch chỉ lấy tối đa số dòng này để LightGBM chạy nhanh hơn.
TARGET_SAMPLE_PER_GROUP = 10_000
MIN_ROWS_PER_GROUP = 100

# Sampling candidate lấy dư một chút trước khi limit.
# Ví dụ cần 10,000 dòng, candidate sẽ khoảng 16,000 dòng nếu batch đủ lớn.
# OVERSAMPLE_FACTOR = 1.6

# ============================================================
# Train / validation / test split
# ============================================================
TEST_SIZE = 0.15
VALID_SIZE = 0.15

# ============================================================
# Optuna / LightGBM
# ============================================================
RUN_OPTUNA = True
N_TRIALS = 100
DEBUG_TRIAL_ERRORS = False

# SynapseML LightGBM sẽ train tối đa N_ESTIMATORS_MAX vòng.
# earlyStoppingRound sẽ dừng sớm nếu validation AUC không cải thiện.
N_ESTIMATORS_MAX = 2000
EARLY_STOPPING_ROUNDS = 100

# SHAP rất nặng trong SynapseML.
# Khuyến nghị: Optuna luôn không dùng SHAP; final model mới bật nếu cần giải thích.
RUN_FINAL_SHAP = True
SHAP_SAMPLE_SIZE = 3000

# ============================================================
# Optional experiments / monitoring
# ============================================================
RUN_SYNTHETIC_EXPERIMENTS = False
RUN_BATCH_MONITORING = False
RUN_BATCH_SHAP = False

# Batch monitoring range: chỉ dùng khi RUN_BATCH_MONITORING=True.
# BATCH_START = pd.Timestamp("2025-01-20 00:00:00")
# BATCH_END = pd.Timestamp("2025-01-31 12:00:00")
# BATCH_FREQ = "12h"

# Empirical p-value config cho chuỗi AUC.
# MIN_HISTORY_POINTS = 20
# ROLLING_WINDOW = None
# ALPHA = 0.05

# ============================================================
# SynapseML LightGBM cluster profile
# ------------------------------------------------------------
# Profile cho cụm 2 workers, mỗi worker 6 cores / khoảng 12-14GB RAM:
# spark.executor.instances = 2
# spark.executor.cores     = 6
# spark.task.cpus          = 3
# available task slots     = 2 * floor(6/3) = 4
# => LightGBM numTasks=4, numThreads=3, data repartition(4)
# ============================================================
LGBM_NUM_TASKS = 4
LGBM_NUM_THREADS = 3
LGBM_NUM_PARTITIONS = 4

# Spark preprocessing/shuffle profile.
# 4 task slots * 3 waves = 12 partitions.
SPARK_SQL_SHUFFLE_PARTITIONS = 12
SPARK_DEFAULT_PARALLELISM = 12

# Khi chạy nhiều Optuna trials trong notebook, không cố định port để tránh lỗi port busy.
USE_FIXED_PORTS = False

print("DATA_PATH:", DATA_PATH)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("TARGET_PROCESSING_DATE_HOUR:", TARGET_PROCESSING_DATE_HOUR)
print("TARGET_SAMPLE_PER_GROUP:", TARGET_SAMPLE_PER_GROUP)
print("RUN_OPTUNA:", RUN_OPTUNA, "| N_TRIALS:", N_TRIALS)
print("SynapseML profile:", {
    "numTasks": LGBM_NUM_TASKS,
    "numThreads": LGBM_NUM_THREADS,
    "partitions": LGBM_NUM_PARTITIONS,
    "shuffle_partitions": SPARK_SQL_SHUFFLE_PARTITIONS,
})

DATA_PATH: /opt/spark/workspace/input/data/silver_yellow_tripdata_2025-01.parquet
OUTPUT_DIR: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata
TARGET_PROCESSING_DATE_HOUR: 2025-01-15 12:00:00
TARGET_SAMPLE_PER_GROUP: 10000
RUN_OPTUNA: True | N_TRIALS: 100
SynapseML profile: {'numTasks': 4, 'numThreads': 3, 'partitions': 4, 'shuffle_partitions': 12}

## 3. Start Spark session

Cell này tạo Spark session theo profile đã tối ưu. Nếu bạn chạy trong môi trường đã có Spark session, vẫn có thể giữ cell này; Spark sẽ trả về session hiện tại nếu tồn tại.

In [3]:
spark = (
    SparkSession.builder
    .appName("SynapseML LightGBM Batch Drift Detection - Clean")
    .master("spark://spark-master:7077")
    .config("spark.executor.instances", "2")
    .config("spark.executor.cores", "6")
    .config("spark.executor.memory", "10g")
    .config("spark.task.cpus", str(LGBM_NUM_THREADS))
    .config("spark.sql.shuffle.partitions", str(SPARK_SQL_SHUFFLE_PARTITIONS))
    .config("spark.default.parallelism", str(SPARK_DEFAULT_PARALLELISM))
    .config("spark.dynamicAllocation.enabled", "false")
    # .config("spark.speculation", "false")
    # .config("spark.scheduler.mode", "FIFO")
    # .config("spark.python.worker.reuse", "true")
    # .config("spark.executorEnv.OMP_NUM_THREADS", str(LGBM_NUM_THREADS))
    # .config("spark.executorEnv.MKL_NUM_THREADS", "1")
    # .config("spark.executorEnv.OPENBLAS_NUM_THREADS", "1")
    # .config("spark.executorEnv.NUMEXPR_NUM_THREADS", "1")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

conf = spark.sparkContext.getConf()


def get_conf_int(key, default):
    """Đọc Spark conf dạng int; nếu thiếu hoặc lỗi thì dùng default."""
    try:
        return int(conf.get(key, str(default)))
    except Exception:
        return int(default)


executor_instances = get_conf_int("spark.executor.instances", 2)
executor_cores = get_conf_int("spark.executor.cores", 6)
task_cpus = get_conf_int("spark.task.cpus", LGBM_NUM_THREADS)
available_task_slots = executor_instances * (executor_cores // task_cpus)

print("Spark application:", spark.sparkContext.appName)
print("Spark master:", spark.sparkContext.master)
print("executor.instances:", executor_instances)
print("executor.cores:", executor_cores)
print("spark.task.cpus:", task_cpus)
print("Available Spark task slots:", available_task_slots)
print("Expected SynapseML numTasks:", LGBM_NUM_TASKS)
print("spark.sql.shuffle.partitions:", conf.get("spark.sql.shuffle.partitions"))
print("spark.default.parallelism:", conf.get("spark.default.parallelism"))

if available_task_slots < LGBM_NUM_TASKS:
    raise ValueError(
        f"Spark chỉ có {available_task_slots} task slots nhưng LGBM_NUM_TASKS={LGBM_NUM_TASKS}. "
        "Hãy giảm LGBM_NUM_TASKS, giảm spark.task.cpus hoặc tăng executor cores."
    )

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/05/05 23:19:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Spark application: SynapseML LightGBM Batch Drift Detection - Clean
Spark master: spark://spark-master:7077
executor.instances: 2
executor.cores: 6
spark.task.cpus: 3
Available Spark task slots: 4
Expected SynapseML numTasks: 4
spark.sql.shuffle.partitions: 12
spark.default.parallelism: 12

## 4. Load Silver data

Ở đây ta normalize tên cột về lowercase để khớp với job Silver mới của bạn. Các cột thời gian được cast về timestamp để filter batch ổn định hơn.

In [4]:
df_raw = spark.read.parquet(DATA_PATH)
print("Raw row count:", df_raw.count())
df_raw.printSchema()
df_raw.show(5, truncate=False)

Raw row count: 3326978
root
 |-- vendorid: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: double (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- ratecodeid: double (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- pulocationid: integer (nullable = true)
 |-- dolocationid: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)
 |-- date_hour: timestamp_ntz (nullable = true)
 |-- processing_date_hour: timestamp_ntz (nullable = true)

+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+-------------------+--------------------+
|vendorid|tpep_pickup_datetime|tpep_dropoff_datetime|passenger_count|trip_distance|ratecodeid|store_and_fwd_flag|pulocationid|dolocationid|payment_type|fare_amount|extra|mta_tax|tip_amount|tolls_amount|improvement_surcharge|total_amount|congestion_surcharge|airport_fee|cbd_congestion_fee|date_hour          |processing_date_hour|
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+-------------------+--------------------+
|1       |2025-01-01 00:18:38 |2025-01-01 00:26:59  |1.0            |1.6          |1.0       |N                 |229         |237         |1           |10.0       |3.5  |0.5    |3.0       |0.0         |1.0                  |18.0        |2.5                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
|1       |2025-01-01 00:32:40 |2025-01-01 00:35:13  |1.0            |0.5          |1.0       |N                 |236         |237         |1           |5.1        |3.5  |0.5    |2.02      |0.0         |1.0                  |12.12       |2.5                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
|1       |2025-01-01 00:44:04 |2025-01-01 00:46:01  |1.0            |0.6          |1.0       |N                 |141         |141         |1           |5.1        |3.5  |0.5    |2.0       |0.0         |1.0                  |12.1        |2.5                 |0.0        |0.0               |2025-01-01 01:00:00|2025-01-01 12:00:00 |
|2       |2025-01-01 00:14:27 |2025-01-01 00:20:01  |3.0            |0.52         |1.0       |N                 |244         |244         |2           |7.2        |1.0  |0.5    |0.0       |0.0         |1.0                  |9.7         |0.0                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
|2       |2025-01-01 00:21:34 |2025-01-01 00:25:06  |3.0            |0.66         |1.0       |N                 |244         |116         |2           |5.8        |1.0  |0.5    |0.0       |0.0         |1.0                  |8.3         |0.0                 |0.0        |0.0               |2025-01-01 00:00:00|2025-01-01 12:00:00 |
+--------+--------------------+---------------------+---------------+-------------+----------+------------------+------------+------------+------------+-----------+-----+-------+----------+------------+---------------------+------------+--------------------+-----------+------------------+-------------------+--------------------+
only showing top 5 rows

## 5. Basic overview and cache source data

Ta cache `df_raw` vì các bước sau sẽ filter nhiều lần theo `processing_date_hour`.

In [5]:
# Tổng quan range dữ liệu.
df_raw.select(
    F.count("*").alias("row_count"),
    F.min("date_hour").alias("min_date_hour"),
    F.max("date_hour").alias("max_date_hour"),
    F.min("processing_date_hour").alias("min_processing_date_hour"),
    F.max("processing_date_hour").alias("max_processing_date_hour"),
).show(truncate=False)

# Repartition theo processing_date_hour giúp các thao tác filter/sample theo batch hiệu quả hơn.
df_raw = (
    df_raw
    .repartition(SPARK_SQL_SHUFFLE_PARTITIONS, "processing_date_hour")
    .persist(StorageLevel.MEMORY_AND_DISK)
)

cached_rows = df_raw.count()
print("Cached df_raw rows:", cached_rows)

processing_counts = (
    df_raw
    .groupBy("processing_date_hour")
    .count()
    .withColumnRenamed("count", "row_count")
    .orderBy("processing_date_hour")
)

print("First processing_date_hour values:")
processing_counts.show(10, truncate=False)

print("Last processing_date_hour values:")
processing_counts.orderBy(F.desc("processing_date_hour")).show(10, truncate=False)

+---------+-------------------+-------------------+------------------------+------------------------+
|row_count|min_date_hour      |max_date_hour      |min_processing_date_hour|max_processing_date_hour|
+---------+-------------------+-------------------+------------------------+------------------------+
|3326978  |2025-01-01 00:00:00|2025-01-31 23:00:00|2025-01-01 12:00:00     |2025-02-01 00:00:00     |
+---------+-------------------+-------------------+------------------------+------------------------+

Cached df_raw rows: 3326978
First processing_date_hour values:

+--------------------+---------+
|processing_date_hour|row_count|
+--------------------+---------+
|2025-01-01 12:00:00 |36464    |
|2025-01-02 00:00:00 |45227    |
|2025-01-02 12:00:00 |19740    |
|2025-01-03 00:00:00 |61896    |
|2025-01-03 12:00:00 |21563    |
|2025-01-04 00:00:00 |66523    |
|2025-01-04 12:00:00 |22995    |
|2025-01-05 00:00:00 |71531    |
|2025-01-05 12:00:00 |25047    |
|2025-01-06 00:00:00 |53406    |
+--------------------+---------+
only showing top 10 rows

Last processing_date_hour values:
+--------------------+---------+
|processing_date_hour|row_count|
+--------------------+---------+
|2025-02-01 00:00:00 |93156    |
|2025-01-31 12:00:00 |31944    |
|2025-01-31 00:00:00 |94242    |
|2025-01-30 12:00:00 |32929    |
|2025-01-30 00:00:00 |87625    |
|2025-01-29 12:00:00 |28139    |
|2025-01-29 00:00:00 |81639    |
|2025-01-28 12:00:00 |27793    |
|2025-01-28 00:00:00 |64075    |
|2025-01-27 12:00:00 |26096    |
+--------------------+---------+
only showing top 10 rows

## 6. Define target and comparison batches

- Target batch: `label = 1`.
- Comparison/history batches: `label = 0`.

In [6]:
def filter_processing_hour(source_df, processing_hour):
    """
    Lọc dữ liệu theo processing_date_hour.
    Cột processing_date_hour đã là timestamp chuẩn nên không cần format/cast lại.
    """
    return source_df.filter(
        F.col("processing_date_hour") == F.lit(processing_hour.to_pydatetime())
    )


def get_comparison_processing_hours(target_processing_hour):
    """
    Tạo danh sách các batch lịch sử để so sánh với target batch.
    """
    target_processing_hour = pd.Timestamp(target_processing_hour)

    comparison_hours = [target_processing_hour - PREVIOUS_BATCH_OFFSET]
    comparison_hours += [
        target_processing_hour - offset
        for offset in HISTORY_OFFSETS
    ]

    return sorted(set(comparison_hours))


# Target batch: label = 1
target_processing_hour = pd.Timestamp(TARGET_PROCESSING_DATE_HOUR)

# Historical batches: label = 0
comparison_processing_hours = get_comparison_processing_hours(
    target_processing_hour
)

target_count = filter_processing_hour(
    df_raw,
    target_processing_hour
).count()

print("Target processing hour, label = 1:")
print(f"- {target_processing_hour} | rows: {target_count:,}")

print("\nComparison processing hours, label = 0:")
for processing_hour in comparison_processing_hours:
    row_count = filter_processing_hour(
        df_raw,
        processing_hour
    ).count()

    print(f"- {processing_hour} | rows: {row_count:,}")

Target processing hour, label = 1:
- 2025-01-15 12:00:00 | rows: 32,738

Comparison processing hours, label = 0:
- 2025-01-01 12:00:00 | rows: 36,464
- 2025-01-08 12:00:00 | rows: 28,758
- 2025-01-14 12:00:00 | rows: 30,435
- 2025-01-15 00:00:00 | rows: 86,467

## 7. Optimized sampling by processing hour

Đây là tối ưu quan trọng nhất so với cách `orderBy(rand()).limit()` trực tiếp trên toàn bộ batch.

In [7]:
def sample_by_processing_hour(
    source_df,
    processing_hour,
    label,
    max_rows,
    random_state,
):
    part = filter_processing_hour(source_df, processing_hour)

    part = part.withColumn("label", F.lit(float(label)))

    total_rows = part.count()

    # Nếu batch nhỏ hơn hoặc bằng max_rows, lấy toàn bộ.
    if total_rows <= max_rows:
        return part

    # Nếu batch lớn hơn max_rows, random rồi lấy đúng max_rows dòng.
    return (
        part
        .orderBy(F.rand(int(random_state)))
        .limit(int(max_rows))
    )

## 8. Build training dataset: target vs history

In [8]:
# ============================================================
# 1. Target batch: label = 1
# ============================================================

positive_df = sample_by_processing_hour(
    source_df=df_raw,
    processing_hour=target_processing_hour,
    label=1,
    max_rows=TARGET_SAMPLE_PER_GROUP,
    random_state=RANDOM_STATE,
)

positive_count = positive_df.count()

print("Positive sample:")
print(f"- processing_hour = {target_processing_hour}")
print(f"- rows = {positive_count:,}")


# ============================================================
# 2. Historical/comparison batches: label = 0
# ============================================================

negative_parts = []

for i, compare_hour in enumerate(comparison_processing_hours):
    negative_part = sample_by_processing_hour(
        source_df=df_raw,
        processing_hour=compare_hour,
        label=0,
        max_rows=TARGET_SAMPLE_PER_GROUP,
        random_state=RANDOM_STATE + i + 1,
    )

    row_count = negative_part.count()

    if row_count < MIN_ROWS_PER_GROUP:
        print(
            f"Skipped comparison hour {compare_hour} "
            f"because rows = {row_count:,} < {MIN_ROWS_PER_GROUP:,}"
        )
        continue

    print(f"Negative sample: {compare_hour} | rows = {row_count:,}")
    negative_parts.append(negative_part)


if not negative_parts:
    raise ValueError("Không có đủ dữ liệu lịch sử để tạo label = 0.")


# Gộp tất cả negative batches thành một DataFrame duy nhất.
negative_df = negative_parts[0]

for negative_part in negative_parts[1:]:
    negative_df = negative_df.unionByName(
        negative_part,
        allowMissingColumns=True,
    )


negative_count = negative_df.count()

print(f"\nNegative sample total rows: {negative_count:,}")

negative_df.groupBy("processing_date_hour") \
    .count() \
    .withColumnRenamed("count", "row_count") \
    .orderBy("processing_date_hour") \
    .show(truncate=False)

Positive sample:
- processing_hour = 2025-01-15 12:00:00
- rows = 10,000
Negative sample: 2025-01-01 12:00:00 | rows = 10,000
Negative sample: 2025-01-08 12:00:00 | rows = 10,000
Negative sample: 2025-01-14 12:00:00 | rows = 10,000
Negative sample: 2025-01-15 00:00:00 | rows = 10,000

Negative sample total rows: 40,000

[Stage 103:=============================================>         (10 + 2) / 12]

+--------------------+---------+
|processing_date_hour|row_count|
+--------------------+---------+
|2025-01-01 12:00:00 |10000    |
|2025-01-08 12:00:00 |10000    |
|2025-01-14 12:00:00 |10000    |
|2025-01-15 00:00:00 |10000    |
+--------------------+---------+

In [9]:
# Gộp target batch label = 1 và history batches label = 0
work_df = positive_df.unionByName(
    negative_df,
    allowMissingColumns=True,
)

work_df = work_df.persist(StorageLevel.MEMORY_AND_DISK)

# Kích hoạt cache và kiểm tra kích thước dataset
row_count = work_df.count()
col_count = len(work_df.columns)

print("Work dataset shape:", (row_count, col_count))

# Kiểm tra số dòng theo từng label và từng processing batch
work_df.groupBy("label", "processing_date_hour") \
    .count() \
    .withColumnRenamed("count", "row_count") \
    .orderBy("label", "processing_date_hour") \
    .show(truncate=False)

Work dataset shape: (50000, 23)
+-----+--------------------+---------+
|label|processing_date_hour|row_count|
+-----+--------------------+---------+
|0.0  |2025-01-01 12:00:00 |10000    |
|0.0  |2025-01-08 12:00:00 |10000    |
|0.0  |2025-01-14 12:00:00 |10000    |
|0.0  |2025-01-15 00:00:00 |10000    |
|1.0  |2025-01-15 12:00:00 |10000    |
+-----+--------------------+---------+

## 9. Feature configuration

Không đưa các cột thời gian và label vào mô hình để tránh leakage. Mục tiêu là kiểm tra phân phối của các feature nghiệp vụ, không để mô hình học trực tiếp batch time.

In [10]:
# Không dùng các cột này làm feature.
EXCLUDE_COLS = [
    "label",
    "date_hour",
    "processing_date_hour",
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
]

# Categorical/code columns.
CATEGORICAL_COLS = [
    "vendorid",
    "ratecodeid",
    "store_and_fwd_flag",
    "payment_type",
]

# Numeric columns.
NUMERIC_COLS = [
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "pulocationid",
    "dolocationid",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee",
    "cbd_congestion_fee",
]

# Chỉ giữ cột thật sự tồn tại trong dataset.
CATEGORICAL_COLS = [c for c in CATEGORICAL_COLS if c in work_df.columns]
NUMERIC_COLS = [c for c in NUMERIC_COLS if c in work_df.columns]

print("Excluded columns:", [c for c in EXCLUDE_COLS if c in work_df.columns])
print("Categorical columns:", CATEGORICAL_COLS)
print("Numeric columns:", NUMERIC_COLS)

Excluded columns: ['label', 'date_hour', 'processing_date_hour', 'tpep_pickup_datetime', 'tpep_dropoff_datetime']
Categorical columns: ['vendorid', 'ratecodeid', 'store_and_fwd_flag', 'payment_type']
Numeric columns: ['passenger_count', 'trip_distance', 'fare_amount', 'pulocationid', 'dolocationid', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'cbd_congestion_fee']

In [11]:
# ============================================================
# Missing value summary for raw feature columns
# ============================================================

def build_missing_summary(input_df, feature_cols, numeric_cols):
    """
    Tính missing value cho các feature columns.

    Quy ước:
    - Numeric columns: missing nếu NULL hoặc NaN.
    - Non-numeric columns: missing nếu NULL.
    """

    # Chỉ giữ các cột thật sự tồn tại trong DataFrame
    existing_cols = [
        col for col in feature_cols
        if col in input_df.columns
    ]

    numeric_col_set = set(numeric_cols)

    total_rows = input_df.count()

    missing_exprs = []

    for col in existing_cols:
        if col in numeric_col_set:
            # Numeric: check cả NULL và NaN
            expr = F.sum(
                F.when(
                    F.col(col).isNull() | F.isnan(F.col(col).cast("double")),
                    1
                ).otherwise(0)
            ).alias(col)
        else:
            # Categorical/string: chỉ check NULL
            expr = F.sum(
                F.when(F.col(col).isNull(), 1).otherwise(0)
            ).alias(col)

        missing_exprs.append(expr)

    missing_row = input_df.select(missing_exprs).first().asDict()

    missing_summary_df = pd.DataFrame([
        {
            "column": col,
            "missing_count": int(missing_row[col]),
            "missing_rate_pct": (
                int(missing_row[col]) / total_rows * 100
                if total_rows > 0 else 0.0
            ),
        }
        for col in existing_cols
    ])

    missing_summary_df = missing_summary_df.sort_values(
        "missing_count",
        ascending=False,
    )

    return missing_summary_df


# Các cột raw feature cần kiểm tra missing
raw_feature_cols = CATEGORICAL_COLS + NUMERIC_COLS

missing_summary_df = build_missing_summary(
    input_df=work_df,
    feature_cols=raw_feature_cols,
    numeric_cols=NUMERIC_COLS,
)

display(missing_summary_df)

missing_path = f"{OUTPUT_DIR}/feature_missing_summary.csv"
missing_summary_df.to_csv(missing_path, index=False)

print("Saved:", missing_path)

                   column  missing_count  missing_rate_pct
4         passenger_count           7782            15.564
2      store_and_fwd_flag           7782            15.564
15   congestion_surcharge           7782            15.564
16            airport_fee           7782            15.564
1              ratecodeid              0             0.000
0                vendorid              0             0.000
6             fare_amount              0             0.000
7            pulocationid              0             0.000
3            payment_type              0             0.000
5           trip_distance              0             0.000
9                   extra              0             0.000
8            dolocationid              0             0.000
10                mta_tax              0             0.000
11             tip_amount              0             0.000
13  improvement_surcharge              0             0.000
12           tolls_amount              0             0.000
14           total_amount              0             0.000
17     cbd_congestion_fee              0             0.000

Saved: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/feature_missing_summary.csv

## 10. Stratified split utilities

Spark không có `train_test_split(..., stratify=y)` như sklearn. Vì vậy cell này tạo split gần tương đương:

- Tổng số dòng test ≈ `round(TEST_SIZE * total)`.
- Tổng số dòng validation ≈ `round(VALID_SIZE * total)`.
- Tỷ lệ label trong train/valid/test gần giống nhau.
- Dùng hash theo row id để random ổn định hơn `orderBy(rand())`.

In [12]:
# ============================================================
# Exact stratified train / valid / test split
# Gần giống logic train_test_split(stratify=y) của sklearn
# ============================================================

from pyspark.sql import Window
import pyspark.sql.functions as F
from pyspark.storagelevel import StorageLevel


def stratified_split_exact(
    input_df,
    label_col="label",
    test_size=TEST_SIZE,
    valid_size=VALID_SIZE,
    seed=RANDOM_STATE,
):
    """
    Chia dữ liệu thành train / valid / test có stratify theo label.

    Mục tiêu:
    - Giữ tỷ lệ label gần như chính xác trong từng split.
    - Số dòng valid/test ổn định hơn randomSplit().
    - Logic dễ hiểu hơn bản allocation phức tạp.

    Cách làm:
    1. Đếm số dòng của từng label.
    2. Với mỗi label, tính:
       - n_test_label  = round(test_size  * số dòng label đó)
       - n_valid_label = round(valid_size * số dòng label đó)
    3. Random thứ tự dữ liệu trong từng label.
    4. Lấy:
       - dòng 1 → n_test_label cho test
       - dòng tiếp theo → n_valid_label cho valid
       - phần còn lại cho train
    """
    # Ép label về double để thống nhất với SynapseML LightGBM
    base_df = input_df.withColumn(
        label_col,
        F.col(label_col).cast("double"),
    )

    # Đếm số dòng theo từng label và tính số dòng cần lấy cho test/valid
    label_count_df = (
        base_df
        .groupBy(label_col)
        .count()
        .withColumn("_n_test", F.round(F.col("count") * F.lit(test_size)).cast("long"))
        .withColumn("_n_valid", F.round(F.col("count") * F.lit(valid_size)).cast("long"))
        .drop("count")
    )

    labels = [row[label_col] for row in label_count_df.select(label_col).collect()]

    # Random thứ tự bên trong từng label
    window_by_label = Window.partitionBy(label_col).orderBy(F.rand(seed))

    split_df = (
        base_df
        .join(F.broadcast(label_count_df), on=label_col, how="left")
        .withColumn("_row_number", F.row_number().over(window_by_label))
        .withColumn(
            "_split",
            F.when(F.col("_row_number") <= F.col("_n_test"), F.lit("test"))
             .when(F.col("_row_number") <= F.col("_n_test") + F.col("_n_valid"), F.lit("valid"))
             .otherwise(F.lit("train"))
        )
        .drop("_row_number", "_n_test", "_n_valid")
    )

    train_df = split_df.filter(F.col("_split") == "train").drop("_split")
    valid_df = split_df.filter(F.col("_split") == "valid").drop("_split")
    test_df = split_df.filter(F.col("_split") == "test").drop("_split")

    return train_df, valid_df, test_df


def get_count_and_positive_rate(input_df, label_col="label"):
    """
    Trả về số dòng và tỷ lệ label = 1.
    """
    row = input_df.select(
        F.count("*").alias("row_count"),
        F.avg(F.col(label_col).cast("double")).alias("positive_rate"),
    ).first()

    return int(row["row_count"]), float(row["positive_rate"] or 0.0)


def print_split_report(train_df, valid_df, test_df, label_col="label"):
    """
    In báo cáo để kiểm tra kết quả split.
    """
    print("========== Split Report ==========")

    for split_name, split_df in [
        ("Train", train_df),
        ("Valid", valid_df),
        ("Test ", test_df),
    ]:
        row_count, positive_rate = get_count_and_positive_rate(
            split_df,
            label_col=label_col,
        )

        print(
            f"{split_name}: "
            f"rows={row_count:,} | "
            f"columns={len(split_df.columns)} | "
            f"positive_rate={positive_rate:.6f}"
        )

        split_df.groupBy(label_col) \
            .count() \
            .orderBy(label_col) \
            .show()

## 11. Feature pipeline

Cell này làm 3 việc:

1. Numeric columns → cast sang `double`.
2. String categorical columns → `StringIndexer`.
3. Ghép tất cả feature vào cột vector `features` để SynapseML LightGBM sử dụng.

In [13]:
class TaxiFeaturePipeline:
    """
    Feature pipeline cho Spark / SynapseML LightGBM.

    Mục tiêu:
    - Chuyển dữ liệu raw thành cột "features" để đưa vào LightGBM.
    - Giữ cách xử lý gần giống notebook LightGBM thường.
    - Không tự tạo thêm __isnull features.
    - Không fill missing numeric, vì LightGBM có thể xử lý missing value.
    - String categorical được encode bằng StringIndexer.
    - Numeric categorical được giữ dạng số và khai báo categoricalSlotIndexes.
    """

    def __init__(
        self,
        categorical_cols,
        numeric_cols,
        exclude_cols,
        label_col="label",
        features_col="features",
    ):
        self.categorical_cols = list(categorical_cols)
        self.numeric_cols = list(numeric_cols)
        self.exclude_cols = set(exclude_cols)
        self.label_col = label_col
        self.features_col = features_col

        # Các biến được xác định sau khi fit()
        self.numeric_feature_cols_ = []
        self.categorical_numeric_cols_ = []
        self.categorical_string_cols_ = []
        self.string_indexed_cols_ = []

        self.feature_cols_ = []
        self.categorical_slot_indexes_ = []

        self.string_indexer_model_ = None
        self.assembler_ = None

    def fit(self, train_df):
        """
        Fit pipeline trên train_df.

        Lưu ý:
        - Chỉ fit StringIndexer trên train set để tránh data leakage.
        - Valid/test chỉ transform bằng mapping đã học từ train.
        """

        available_cols = set(train_df.columns)
        schema_map = {
            field.name: field.dataType
            for field in train_df.schema.fields
        }

        categorical_set = set(self.categorical_cols)

        # ----------------------------------------------------
        # 1. Chọn numeric features
        # ----------------------------------------------------
        # Nếu một cột vừa nằm trong numeric_cols vừa nằm trong categorical_cols,
        # ưu tiên xem nó là categorical để tránh duplicate feature.
        self.numeric_feature_cols_ = [
            col
            for col in self.numeric_cols
            if col in available_cols
            and col not in self.exclude_cols
            and col not in categorical_set
        ]

        # ----------------------------------------------------
        # 2. Tách categorical thành:
        #    - string categorical: cần StringIndexer
        #    - numeric categorical: giữ dạng số, nhưng khai báo categoricalSlotIndexes
        # ----------------------------------------------------
        self.categorical_string_cols_ = []
        self.categorical_numeric_cols_ = []

        for col in self.categorical_cols:
            if col not in available_cols or col in self.exclude_cols:
                continue

            dtype = schema_map[col]

            if isinstance(dtype, T.StringType):
                self.categorical_string_cols_.append(col)
            else:
                self.categorical_numeric_cols_.append(col)

        # ----------------------------------------------------
        # 3. Fit StringIndexer cho các categorical dạng string
        # ----------------------------------------------------
        self.string_indexed_cols_ = [
            f"{col}__idx"
            for col in self.categorical_string_cols_
        ]

        if self.categorical_string_cols_:
            indexer = StringIndexer(
                inputCols=self.categorical_string_cols_,
                outputCols=self.string_indexed_cols_,
                handleInvalid="keep",
            )

            self.string_indexer_model_ = indexer.fit(train_df)
        else:
            self.string_indexer_model_ = None

        # ----------------------------------------------------
        # 4. Xác định thứ tự feature trong vector
        # ----------------------------------------------------
        self.feature_cols_ = (
            self.numeric_feature_cols_
            + self.categorical_numeric_cols_
            + self.string_indexed_cols_
        )

        if not self.feature_cols_:
            raise ValueError("Không có feature nào để đưa vào VectorAssembler.")

        # ----------------------------------------------------
        # 5. Xác định categorical slot indexes cho LightGBM
        # ----------------------------------------------------
        categorical_feature_cols = (
            self.categorical_numeric_cols_
            + self.string_indexed_cols_
        )

        self.categorical_slot_indexes_ = [
            self.feature_cols_.index(col)
            for col in categorical_feature_cols
        ]

        # ----------------------------------------------------
        # 6. Tạo VectorAssembler
        # ----------------------------------------------------
        self.assembler_ = VectorAssembler(
            inputCols=self.feature_cols_,
            outputCol=self.features_col,
            handleInvalid="keep",
        )

        return self

    def _clean_numeric_column(self, col_name):
        """
        Cast một cột sang double và chuyển NaN/inf thành null.

        Vì sao:
        - Spark ML vector dùng numeric/double.
        - LightGBM xử lý missing value tốt hơn là để inf.
        """

        x = F.col(col_name).cast("double")

        return (
            F.when(
                F.isnan(x)
                | (x == float("inf"))
                | (x == float("-inf")),
                F.lit(None).cast("double"),
            )
            .otherwise(x)
            .alias(col_name)
        )

    def transform(self, input_df):
        """
        Transform DataFrame thành DataFrame có cột features.

        Output:
        - Giữ các cột gốc cần thiết.
        - Thêm các cột indexed cho string categorical.
        - Thêm cột features.
        """

        if self.assembler_ is None:
            raise RuntimeError("Pipeline chưa được fit. Hãy gọi .fit(train_df) trước.")

        df = input_df

        # ----------------------------------------------------
        # 1. Cast numeric và numeric categorical sang double
        # ----------------------------------------------------
        cols_to_cast = set(
            self.numeric_feature_cols_
            + self.categorical_numeric_cols_
        )

        select_exprs = []

        for col in df.columns:
            if col in cols_to_cast:
                select_exprs.append(self._clean_numeric_column(col))
            else:
                select_exprs.append(F.col(col))

        df = df.select(*select_exprs)

        # ----------------------------------------------------
        # 2. Encode string categorical bằng StringIndexer model đã fit
        # ----------------------------------------------------
        if self.string_indexer_model_ is not None:
            df = self.string_indexer_model_.transform(df)

        # ----------------------------------------------------
        # 3. Ghép các feature thành vector features
        # ----------------------------------------------------
        df = self.assembler_.transform(df)

        return df

## 12. Split data and build features

In [14]:
# ============================================================
# Run exact stratified split
# ============================================================

train_df, valid_df, test_df = stratified_split_exact(
    input_df=work_df,
    label_col="label",
    test_size=TEST_SIZE,
    valid_size=VALID_SIZE,
    seed=RANDOM_STATE,
)

# Cache vì các DataFrame này sẽ dùng nhiều lần phía sau:
# feature pipeline, training, evaluation.
train_df = train_df.persist(StorageLevel.MEMORY_AND_DISK)
valid_df = valid_df.persist(StorageLevel.MEMORY_AND_DISK)
test_df = test_df.persist(StorageLevel.MEMORY_AND_DISK)

# Trigger cache
train_df.count()
valid_df.count()
test_df.count()

print_split_report(
    train_df=train_df,
    valid_df=valid_df,
    test_df=test_df,
    label_col="label",
)

26/05/05 23:21:03 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

========== Split Report ==========
Train: rows=35,000 | columns=23 | positive_rate=0.200000
+-----+-----+
|label|count|
+-----+-----+
|  0.0|28000|
|  1.0| 7000|
+-----+-----+

Valid: rows=7,500 | columns=23 | positive_rate=0.200000
+-----+-----+
|label|count|
+-----+-----+
|  0.0| 6000|
|  1.0| 1500|
+-----+-----+

Test : rows=7,500 | columns=23 | positive_rate=0.200000
+-----+-----+
|label|count|
+-----+-----+
|  0.0| 6000|
|  1.0| 1500|
+-----+-----+

In [15]:
# ============================================================
# Build feature vector for SynapseML LightGBM
# ============================================================

# Fit feature pipeline only on train set to avoid data leakage.
feature_pipeline = TaxiFeaturePipeline(
    categorical_cols=CATEGORICAL_COLS,
    numeric_cols=NUMERIC_COLS,
    exclude_cols=EXCLUDE_COLS,
    label_col="label",
    features_col="features",
)

feature_pipeline.fit(train_df)


# ============================================================
# Check selected features
# ============================================================

print("========== Feature Pipeline Summary ==========")
print("Numeric feature columns:")
print(feature_pipeline.numeric_feature_cols_)

print("\nCategorical numeric columns:")
print(feature_pipeline.categorical_numeric_cols_)

print("\nCategorical string columns:")
print(feature_pipeline.categorical_string_cols_)

print("\nString indexed columns:")
print(feature_pipeline.string_indexed_cols_)

print("\nFinal feature columns:")
print(feature_pipeline.feature_cols_)

print("\nCategorical slot indexes for LightGBM:")
print(feature_pipeline.categorical_slot_indexes_)

print("=============================================\n")


# ============================================================
# Transform train / valid / test into LightGBM input format
# ============================================================

train_features_df = (
    feature_pipeline
    .transform(train_df)
    .select("features", "label")
)

valid_features_df = (
    feature_pipeline
    .transform(valid_df)
    .select("features", "label")
)

test_features_df = (
    feature_pipeline
    .transform(test_df)
    .select("features", "label")
)

train_features_df = train_features_df.persist(StorageLevel.MEMORY_AND_DISK)
valid_features_df = valid_features_df.persist(StorageLevel.MEMORY_AND_DISK)
test_features_df = test_features_df.persist(StorageLevel.MEMORY_AND_DISK)


# Trigger cache and print row counts
train_feature_count = train_features_df.count()
valid_feature_count = valid_features_df.count()
test_feature_count = test_features_df.count()

print("Feature dataset rows:")
print(f"- Train: {train_feature_count:,}")
print(f"- Valid: {valid_feature_count:,}")
print(f"- Test : {test_feature_count:,}")


# ============================================================
# Quick sample check
# ============================================================

print("\nSample feature rows on train:")
train_features_df.show(5, truncate=False)

========== Feature Pipeline Summary ==========
Numeric feature columns:
['passenger_count', 'trip_distance', 'fare_amount', 'pulocationid', 'dolocationid', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'cbd_congestion_fee']

Categorical numeric columns:
['vendorid', 'ratecodeid', 'payment_type']

Categorical string columns:
['store_and_fwd_flag']

String indexed columns:
['store_and_fwd_flag__idx']

Final feature columns:
['passenger_count', 'trip_distance', 'fare_amount', 'pulocationid', 'dolocationid', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'cbd_congestion_fee', 'vendorid', 'ratecodeid', 'payment_type', 'store_and_fwd_flag__idx']

Categorical slot indexes for LightGBM:
[14, 15, 16, 17]
=============================================

Feature dataset rows:
- Train: 35,000
- Valid: 7,500
- Test : 7,500

Sample feature rows on train:
+----------------------------------------------------------------------------------+-----+
|features                                                                          |label|
+----------------------------------------------------------------------------------+-----+
|[1.0,9.85,38.7,132.0,196.0,0.0,0.5,0.0,0.0,1.0,41.95,0.0,1.75,0.0,2.0,1.0,2.0,0.0]|0.0  |
|[1.0,1.14,9.3,163.0,237.0,0.0,0.5,2.81,0.0,1.0,16.86,2.5,0.0,0.75,2.0,1.0,1.0,0.0]|0.0  |
|[1.0,2.6,15.6,236.0,161.0,3.25,0.5,4.05,0.0,1.0,24.4,2.5,0.0,0.75,1.0,1.0,1.0,0.0]|0.0  |
|[1.0,0.42,4.4,68.0,246.0,0.0,0.5,1.0,0.0,1.0,10.15,2.5,0.0,0.75,2.0,1.0,1.0,0.0]  |0.0  |
|[1.0,0.6,5.8,237.0,141.0,2.5,0.5,1.95,0.0,1.0,11.75,2.5,0.0,0.0,1.0,1.0,1.0,0.0]  |0.0  |
+----------------------------------------------------------------------------------+-----+
only showing top 5 rows

## 14. SynapseML LightGBM helper functions

Các hàm dưới đây giúp:

- Gộp train + valid cho SynapseML thông qua `validationIndicatorCol`.
- Chuẩn hóa params để tránh nhầm tên param giữa LightGBM Python và SynapseML.
- Train/evaluate AUC.

In [16]:
# ============================================================
# SynapseML LightGBM helper functions
# ============================================================

from synapse.ml.lightgbm import LightGBMClassifier
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.functions import vector_to_array
from pyspark.storagelevel import StorageLevel
import pyspark.sql.functions as F


# Evaluator dùng chung cho baseline, Optuna và final model
auc_evaluator = BinaryClassificationEvaluator(
    labelCol="label",
    rawPredictionCol="rawPrediction",
    metricName="areaUnderROC",
)


def build_lgbm_train_valid_df(
    train_features_df,
    valid_features_df,
    num_partitions=None,
    persist=True,
):
    """
    Gộp train + valid thành một DataFrame cho SynapseML LightGBM.

    Vì SynapseML LightGBM hỗ trợ early stopping bằng validationIndicatorCol:
    - is_validation = False  -> dòng train
    - is_validation = True   -> dòng validation

    Input:
    - train_features_df: DataFrame có cột features, label
    - valid_features_df: DataFrame có cột features, label

    Output:
    - DataFrame có cột features, label, is_validation
    """

    # Dữ liệu train
    train_part = (
        train_features_df
        .select(
            F.col("features"),
            F.col("label").cast("double").alias("label"),
        )
        .withColumn("is_validation", F.lit(False))
    )

    # Dữ liệu validation
    valid_part = (
        valid_features_df
        .select(
            F.col("features"),
            F.col("label").cast("double").alias("label"),
        )
        .withColumn("is_validation", F.lit(True))
    )

    # Gộp train + validation
    lgbm_train_df = train_part.unionByName(valid_part)

    # Với SynapseML LightGBM, số partition nên gần với số LightGBM tasks.
    # Ví dụ NUM_TASKS = 4 thì repartition(4) là hợp lý.
    if num_partitions is not None:
        lgbm_train_df = lgbm_train_df.repartition(int(num_partitions))

    # Cache vì DataFrame này có thể được dùng nhiều lần trong baseline/Optuna/final model.
    if persist:
        lgbm_train_df = lgbm_train_df.persist(StorageLevel.MEMORY_AND_DISK)
        lgbm_train_df.count()  # trigger cache

    return lgbm_train_df


def build_lgbm_params(overrides=None):
    """
    Tạo bộ tham số SynapseML LightGBM.

    overrides:
    - Dùng để truyền tham số từ baseline hoặc Optuna.
    - Ví dụ: {"learningRate": 0.05, "numLeaves": 31}

    Lưu ý:
    - Dùng tên tham số của SynapseML: learningRate, numLeaves, maxDepth...
    - Không dùng tên kiểu LightGBM Python: learning_rate, num_leaves...
    """

    params = {
        # Model objective / metric
        "objective": "binary",
        "metric": "auc",

        # Columns
        "featuresCol": "features",
        "labelCol": "label",
        "validationIndicatorCol": "is_validation",

        # Core LightGBM parameters
        "learningRate": 0.05,
        "numLeaves": 31,
        "maxDepth": -1,
        "minDataInLeaf": 20,
        "baggingFraction": 1.0,
        "baggingFreq": 0,
        "featureFraction": 1.0,
        "lambdaL1": 0.0,
        "lambdaL2": 0.0,
        "minGainToSplit": 0.0,
        "maxBin": 255,

        # Training control
        "numIterations": N_ESTIMATORS_MAX,
        "earlyStoppingRound": EARLY_STOPPING_ROUNDS,

        # Distributed LightGBM control
        "numTasks": LGBM_NUM_TASKS,
        "numThreads": LGBM_NUM_THREADS,
        "maxStreamingOMPThreads": LGBM_NUM_THREADS,

        # Stability/runtime options
        "timeout": 600,
        "useBarrierExecutionMode": True,
        "useSingleDatasetMode": True,
        "dataTransferMode": "streaming",
        "verbosity": -1,
    }

    if overrides:
        params.update(overrides)

    # Fixed ports giúp tránh conflict khi chạy notebook nhiều lần.
    # Nếu không dùng fixed ports thì để SynapseML tự chọn.
    if USE_FIXED_PORTS:
        params["driverListenPort"] = 12400
        params["defaultListenPort"] = 12401

    return params


def build_lgbm_classifier(
    params=None,
    categorical_slot_indexes=None,
    shap_col=None,
):
    """
    Tạo SynapseML LightGBMClassifier.

    categorical_slot_indexes:
    - Danh sách vị trí categorical features trong vector features.
    - Lấy từ feature_pipeline.categorical_slot_indexes_.

    shap_col:
    - Nếu truyền vào, SynapseML sẽ tạo thêm cột SHAP.
    - Chỉ bật khi cần giải thích final model vì transform sẽ chậm hơn.
    """

    lgbm_params = build_lgbm_params(params)

    if categorical_slot_indexes:
        lgbm_params["categoricalSlotIndexes"] = [
            int(x) for x in categorical_slot_indexes
        ]

    if shap_col:
        lgbm_params["featuresShapCol"] = shap_col

    return LightGBMClassifier(**lgbm_params)


def evaluate_auc(model, eval_df):
    """
    Tính AUC cho một DataFrame đã có features và label.

    Dùng cho:
    - baseline validation AUC
    - Optuna validation AUC
    - final test AUC
    """
    pred_df = model.transform(eval_df)
    auc = float(auc_evaluator.evaluate(pred_df))

    return auc


def predict_and_evaluate_auc(model, eval_df, persist_predictions=False):
    """
    Transform dữ liệu và tính AUC.

    Dùng khi bạn cần giữ lại prediction để:
    - tính classification report
    - lấy probability
    - phân tích lỗi
    - tính SHAP nếu model có bật featuresShapCol
    """
    pred_df = model.transform(eval_df)
    auc = float(auc_evaluator.evaluate(pred_df))

    keep_cols = [
        "features",
        "label",
        "rawPrediction",
        "probability",
        "prediction",
        "featuresShap",
    ]
    keep_cols = [col for col in keep_cols if col in pred_df.columns]
    pred_df = pred_df.select(*keep_cols)

    if persist_predictions:
        pred_df = pred_df.persist(StorageLevel.MEMORY_AND_DISK)
        pred_df.count()

    return auc, pred_df


def prediction_to_pandas(pred_df):
    """
    Chuyển prediction của Spark về pandas.

    Output gồm:
    - y_true: label thật
    - pred_score: xác suất model dự đoán label = 1

    Dùng để tính thêm metric ngoài Spark, ví dụ:
    - sklearn classification_report
    - confusion matrix
    - ROC curve
    """
    return (
        pred_df
        .select(
            F.col("label").cast("double").alias("y_true"),
            vector_to_array("probability")[1].cast("double").alias("pred_score"),
        )
        .toPandas()
    )


def _safe_model_call(model, method_name):
    """Gọi method của SynapseML model an toàn; lỗi thì trả về None."""
    try:
        fn = getattr(model, method_name, None)
        if fn is None:
            return None
        value = fn() if callable(fn) else fn
        return value
    except Exception:
        return None


def _to_optional_int(value):
    """Convert value sang int nếu hợp lệ; lỗi thì trả về None."""
    try:
        if value is None:
            return None
        return int(value)
    except Exception:
        return None


def get_lgbm_iteration_info(model):
    """
    Lấy thông tin iteration từ SynapseML LightGBM model.

    Quan trọng:
    - getBoosterBestIteration(): best iteration do early stopping chọn.
    - getBoosterNumTotalIterations(): tổng số iteration model đã train thật sự.

    Nếu best iteration không lấy được hoặc <= 0, notebook fallback về total iterations.
    Trường hợp này thường xảy ra khi early stopping không trigger hoặc SynapseML version
    không expose best iteration ổn định.
    """
    raw_best = None
    raw_best_method = None

    # SynapseML chính thức expose method này trên LightGBMModelMixin.
    # Các tên phía sau là fallback cho một số version/wrapper khác nhau.
    for method_name in [
        "getBoosterBestIteration",
        "getBestIteration",
        "bestIteration",
        "best_iteration",
    ]:
        value = _safe_model_call(model, method_name)
        value_int = _to_optional_int(value)
        if value_int is not None:
            raw_best = value_int
            raw_best_method = method_name
            break

    total_iterations = _to_optional_int(
        _safe_model_call(model, "getBoosterNumTotalIterations")
    )
    total_models = _to_optional_int(
        _safe_model_call(model, "getBoosterNumTotalModel")
    )

    if raw_best is not None and raw_best > 0:
        best_iteration = raw_best
        best_iteration_source = raw_best_method
    elif total_iterations is not None and total_iterations > 0:
        # Nếu early stopping không trigger, số iteration tốt nhất để dùng production
        # thường chính là số iteration đã train thực tế.
        best_iteration = total_iterations
        best_iteration_source = "fallback_getBoosterNumTotalIterations"
    else:
        best_iteration = None
        best_iteration_source = None

    return {
        "best_iteration": best_iteration,
        "best_iteration_source": best_iteration_source,
        "booster_best_iteration_raw": raw_best,
        "booster_best_iteration_method": raw_best_method,
        "booster_total_iterations": total_iterations,
        "booster_num_total_model": total_models,
    }


def get_best_iteration(model):
    """Backward-compatible wrapper: chỉ trả về best_iteration."""
    return get_lgbm_iteration_info(model)["best_iteration"]

## 15. Build reusable LightGBM train/eval DataFrames

DataFrame `lgbm_train_df` gồm cả train và validation, có cột `is_validation`. SynapseML LightGBM dùng cột này để early stopping.

In [17]:
lgbm_train_valid_df = build_lgbm_train_valid_df(
    train_features_df=train_features_df,
    valid_features_df=valid_features_df,
    num_partitions=LGBM_NUM_PARTITIONS,
    persist=True,
)

print("LightGBM train+valid rows:", lgbm_train_valid_df.count())

lgbm_train_valid_df.groupBy("is_validation", "label") \
    .count() \
    .orderBy("is_validation", "label") \
    .show()

LightGBM train+valid rows: 42500
+-------------+-----+-----+
|is_validation|label|count|
+-------------+-----+-----+
|        false|  0.0|28000|
|        false|  1.0| 7000|
|         true|  0.0| 6000|
|         true|  1.0| 1500|
+-------------+-----+-----+

## 16. Baseline SynapseML LightGBM

Baseline dùng params gần với LightGBM thường để có mốc so sánh với Optuna.

In [18]:
# ============================================================
# Baseline SynapseML LightGBM
# ============================================================

import time
import json
import gc


# Bộ tham số baseline, cố gắng khớp với LightGBM thường.
# Lưu ý:
# - Dùng tên tham số của SynapseML: learningRate, numLeaves, maxDepth...
# - Không dùng tên LightGBM Python như learning_rate, num_leaves.
baseline_params = {
    "learningRate": 0.05,
    "numLeaves": 31,
    "maxDepth": -1,
    "minDataInLeaf": 20,

    "baggingFraction": 1.0,
    "baggingFreq": 0,
    "featureFraction": 1.0,

    "lambdaL1": 1e-8,
    "lambdaL2": 1e-8,
    "minGainToSplit": 0.0,

    # 255 khớp LightGBM thường.
    # Nếu SynapseML/cluster hay lỗi native memory, có thể đổi về 127.
    "maxBin": 255,
}


def train_lgbm_baseline(
    params,
    train_valid_df,
    valid_df,
    test_df,
    categorical_slot_indexes,
    shap_col=None,
    keep_test_predictions=False,
):
    """
    Train baseline SynapseML LightGBM và đánh giá AUC trên valid/test.

    Input:
    - params:
        Bộ tham số LightGBM baseline hoặc Optuna.
    - train_valid_df:
        DataFrame đã gộp train + valid.
        Phải có cột:
        + features
        + label
        + is_validation
    - valid_df:
        DataFrame validation có features, label.
    - test_df:
        DataFrame test có features, label.
    - categorical_slot_indexes:
        Vị trí các categorical features trong vector features.
    - shap_col:
        Tên cột SHAP nếu muốn bật SHAP.
        Baseline thường để None cho nhanh.
    - keep_test_predictions:
        Nếu True, trả về thêm test prediction DataFrame.
        Nếu False, chỉ tính AUC để tiết kiệm memory.

    Output:
    - result: dict chứa valid_auc, test_auc, best_iteration, booster_total_iterations, fit_seconds
    - model: SynapseML LightGBM model đã train
    - test_pred_df: prediction trên test nếu keep_test_predictions=True, ngược lại None
    """

    # Tạo estimator từ params.
    estimator = build_lgbm_classifier(
        params=params,
        categorical_slot_indexes=categorical_slot_indexes,
        shap_col=shap_col,
    )

    # Train model.
    start_time = time.time()
    model = estimator.fit(train_valid_df)
    fit_seconds = time.time() - start_time

    # Đánh giá AUC trên validation set.
    valid_auc = evaluate_auc(
        model=model,
        eval_df=valid_df,
    )

    # Đánh giá AUC trên test set.
    if keep_test_predictions:
        test_auc, test_pred_df = predict_and_evaluate_auc(
            model=model,
            eval_df=test_df,
            persist_predictions=True,
        )
    else:
        test_auc = evaluate_auc(
            model=model,
            eval_df=test_df,
        )
        test_pred_df = None

    iteration_info = get_lgbm_iteration_info(model)

    result = {
        "valid_auc": float(valid_auc),
        "test_auc": float(test_auc),
        **iteration_info,
        "fit_seconds": float(fit_seconds),
    }

    return result, model, test_pred_df

In [19]:

# ============================================================
# Run baseline training
# ============================================================

baseline_result, baseline_model, baseline_test_pred_df = train_lgbm_baseline(
    params=baseline_params,
    train_valid_df=lgbm_train_valid_df,
    valid_df=valid_features_df,
    test_df=test_features_df,
    categorical_slot_indexes=feature_pipeline.categorical_slot_indexes_,
    shap_col=None,
    keep_test_predictions=False,
)

baseline_valid_auc = baseline_result["valid_auc"]
baseline_test_auc = baseline_result["test_auc"]

print("========== Baseline Result ==========")
print(json.dumps(baseline_result, indent=2, default=str))
print("=====================================")

gc.collect()

[LightGBM] [Info] Saving data reference to binary buffer

========== Baseline Result ==========
{
  "valid_auc": 0.6984623888888889,
  "test_auc": 0.7033909444444444,
  "best_iteration": 130,
  "best_iteration_source": "getBoosterBestIteration",
  "booster_best_iteration_raw": 130,
  "booster_best_iteration_method": "getBoosterBestIteration",
  "booster_total_iterations": 131,
  "booster_num_total_model": 131,
  "fit_seconds": 8.569045543670654
}
=====================================

577

## 17. Optuna tuning

Optuna chỉ tối ưu trên validation AUC. Không bật SHAP trong trial để tránh mỗi trial bị chậm quá nhiều.

In [20]:
# ============================================================
# Optuna tuning for SynapseML LightGBM
# ============================================================

import gc
import json
import optuna

from optuna.samplers import TPESampler
from optuna.pruners import NopPruner


def suggest_lgbm_params(trial):
    """
    Search space cho SynapseML LightGBM.

    Lưu ý:
    - Chỉ return các tham số cần tune.
    - Các tham số fixed như numTasks, numThreads, numIterations,
      earlyStoppingRound... sẽ được thêm trong build_lgbm_params().
    """

    params = {
        # Learning speed
        "learningRate": trial.suggest_float(
            "learningRate",
            0.01,
            0.20,
            log=True,
        ),

        # Tree complexity
        "numLeaves": trial.suggest_categorical(
            "numLeaves",
            [15, 31, 63, 127],
        ),
        "maxDepth": trial.suggest_categorical(
            "maxDepth",
            [-1, 4, 6, 8, 10, 12],
        ),
        "minDataInLeaf": trial.suggest_categorical(
            "minDataInLeaf",
            [10, 20, 50, 100, 200],
        ),

        # Row sampling
        "baggingFraction": trial.suggest_float(
            "baggingFraction",
            0.7,
            1.0,
        ),
        "baggingFreq": trial.suggest_categorical(
            "baggingFreq",
            [0, 1, 3, 5],
        ),

        # Feature sampling
        "featureFraction": trial.suggest_float(
            "featureFraction",
            0.7,
            1.0,
        ),

        # Regularization
        "lambdaL1": trial.suggest_float(
            "lambdaL1",
            1e-8,
            10.0,
            log=True,
        ),
        "lambdaL2": trial.suggest_float(
            "lambdaL2",
            1e-8,
            10.0,
            log=True,
        ),
        "minGainToSplit": trial.suggest_float(
            "minGainToSplit",
            0.0,
            1.0,
        ),

        # Histogram bins
        # 255 khớp LightGBM thường.
        # Nếu cluster hay lỗi native memory, 127 thường an toàn hơn.
        "maxBin": trial.suggest_categorical(
            "maxBin",
            [63, 127, 255],
        ),
    }

    return params


def objective(trial):
    """
    Optuna objective.

    Mục tiêu:
    - Train một SynapseML LightGBM model với params do Optuna đề xuất.
    - Tối ưu validation AUC.
    - Lưu thêm test AUC, best_iteration, fit_seconds để theo dõi.
    """

    params = suggest_lgbm_params(trial)

    try:
        result, model, _ = train_lgbm_baseline(
            params=params,
            train_valid_df=lgbm_train_valid_df,
            valid_df=valid_features_df,
            test_df=test_features_df,
            categorical_slot_indexes=feature_pipeline.categorical_slot_indexes_,
            shap_col=None,
            keep_test_predictions=False,
        )

        # Lưu thông tin phụ để xem lại sau khi tuning.
        # Các cột này sẽ xuất hiện trong optuna_synapseml_lgbm_trials.csv
        # với prefix user_attrs_...
        trial.set_user_attr("test_auc", result["test_auc"])
        trial.set_user_attr("best_iteration", result.get("best_iteration"))
        trial.set_user_attr("best_iteration_source", result.get("best_iteration_source"))
        trial.set_user_attr("booster_best_iteration_raw", result.get("booster_best_iteration_raw"))
        trial.set_user_attr("booster_best_iteration_method", result.get("booster_best_iteration_method"))
        trial.set_user_attr("booster_total_iterations", result.get("booster_total_iterations"))
        trial.set_user_attr("booster_num_total_model", result.get("booster_num_total_model"))
        trial.set_user_attr("fit_seconds", result["fit_seconds"])

        return float(result["valid_auc"])

    except Exception as e:
        print(f"[Trial {trial.number}] failed: {repr(e)}")

        if DEBUG_TRIAL_ERRORS:
            raise

        # 0.5 tương đương random classifier cho AUC
        return 0.5

    finally:
        try:
            del model
        except Exception:
            pass

        gc.collect()


# ============================================================
# Create Optuna study
# ============================================================

# SynapseML LightGBM không expose intermediate validation AUC từng boosting round
# về Python như LightGBM thường, nên MedianPruner không thật sự hữu ích ở đây.
# Early stopping vẫn được xử lý bên trong LightGBM bằng earlyStoppingRound.
study = optuna.create_study(
    direction="maximize",
    sampler=TPESampler(seed=RANDOM_STATE),
    pruner=NopPruner(),
)


# Enqueue baseline để Optuna luôn chạy baseline trước.
# baseline_params là dict đã khai báo ở cell baseline.
study.enqueue_trial(baseline_params)


# ============================================================
# Run Optuna
# ============================================================

if RUN_OPTUNA:
    study.optimize(
        objective,
        n_trials=N_TRIALS,
        show_progress_bar=True,
        gc_after_trial=True,
    )
else:
    # Nếu không muốn tuning lâu, chỉ chạy baseline trial đã enqueue.
    study.optimize(
        objective,
        n_trials=1,
        show_progress_bar=True,
        gc_after_trial=True,
    )


# ============================================================
# Optuna result
# ============================================================

print("========== Optuna Best Result ==========")
print("Best validation AUC:", study.best_value)

print("\nBest params:")
print(json.dumps(study.best_params, indent=2, default=str))

best_trial = study.best_trial

print("\nBest trial extra info:")
print("Trial number    :", best_trial.number)
print("Test AUC        :", best_trial.user_attrs.get("test_auc"))
print("Best iteration  :", best_trial.user_attrs.get("best_iteration"))
print("Best iter source:", best_trial.user_attrs.get("best_iteration_source"))
print("Total iterations:", best_trial.user_attrs.get("booster_total_iterations"))
print("Fit seconds     :", best_trial.user_attrs.get("fit_seconds"))
print("========================================")

[I 2026-05-05 23:22:24,557] A new study created in memory with name: no-name-4f07c148-3598-4322-a360-4dbe198df80e
  0%|          | 0/100 [00:00<?, ?it/s]

[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:   1%|          | 1/100 [00:10<16:53, 10.24s/it]

[I 2026-05-05 23:22:34,690] Trial 0 finished with value: 0.6984732222222221 and parameters: {'learningRate': 0.05, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 1.0, 'baggingFreq': 0, 'featureFraction': 1.0, 'lambdaL1': 1e-08, 'lambdaL2': 1e-08, 'minGainToSplit': 0.0, 'maxBin': 255}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:   2%|▏         | 2/100 [00:21<17:16, 10.57s/it]

[I 2026-05-05 23:22:45,500] Trial 1 finished with value: 0.6936525555555555 and parameters: {'learningRate': 0.030710573677773714, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 10, 'baggingFraction': 0.7912726728878613, 'baggingFreq': 5, 'featureFraction': 0.7418481581956126, 'lambdaL1': 4.258943089524393e-06, 'lambdaL2': 1.9826980964985924e-05, 'minGainToSplit': 0.45606998421703593, 'maxBin': 63}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:   3%|▎         | 3/100 [00:29<15:46,  9.75s/it]

[I 2026-05-05 23:22:54,276] Trial 2 finished with value: 0.6921747777777778 and parameters: {'learningRate': 0.05898602410432694, 'numLeaves': 31, 'maxDepth': 4, 'minDataInLeaf': 200, 'baggingFraction': 0.777633994480005, 'baggingFreq': 0, 'featureFraction': 0.7554563366576581, 'lambdaL1': 5.324289357128436, 'lambdaL2': 0.09466630153726856, 'minGainToSplit': 0.9394989415641891, 'maxBin': 255}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:23:01 WARN DAGScheduler: Broadcasting large task binary with size 1308.2 KiB
26/05/05 23:23:03 WARN DAGScheduler: Broadcasting large task binary with size 1308.2 KiB
Best trial: 0. Best value: 0.698473:   4%|▍         | 4/100 [00:40<15:53,  9.93s/it]

[I 2026-05-05 23:23:04,479] Trial 3 finished with value: 0.6923552222222222 and parameters: {'learningRate': 0.01303561122512888, 'numLeaves': 127, 'maxDepth': 4, 'minDataInLeaf': 50, 'baggingFraction': 0.7016566351370807, 'baggingFreq': 0, 'featureFraction': 0.7222133955202271, 'lambdaL1': 1.683416412018213e-05, 'lambdaL2': 1.1036250149900698e-07, 'minGainToSplit': 0.8631034258755935, 'maxBin': 63}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:23:12 WARN DAGScheduler: Broadcasting large task binary with size 1140.9 KiB
26/05/05 23:23:13 WARN DAGScheduler: Broadcasting large task binary with size 1140.9 KiB
Best trial: 0. Best value: 0.698473:   5%|▌         | 5/100 [00:49<15:40,  9.90s/it]

[I 2026-05-05 23:23:14,334] Trial 4 finished with value: 0.6967807222222224 and parameters: {'learningRate': 0.02538617845650057, 'numLeaves': 127, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.7094287557060203, 'baggingFreq': 5, 'featureFraction': 0.7747876687446624, 'lambdaL1': 4.9368087974032924e-05, 'lambdaL2': 0.06308995924905789, 'minGainToSplit': 0.22879816549162246, 'maxBin': 127}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:   6%|▌         | 6/100 [00:57<14:32,  9.28s/it]

[I 2026-05-05 23:23:22,387] Trial 5 finished with value: 0.6944300555555554 and parameters: {'learningRate': 0.16201847221720986, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 200, 'baggingFraction': 0.7020856391593572, 'baggingFreq': 0, 'featureFraction': 0.8012845514210883, 'lambdaL1': 3.0632845126552133, 'lambdaL2': 8.106369361161699e-06, 'minGainToSplit': 0.5187906217433661, 'maxBin': 255}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:   7%|▋         | 7/100 [01:05<13:44,  8.87s/it]

[I 2026-05-05 23:23:30,428] Trial 6 finished with value: 0.6931083333333332 and parameters: {'learningRate': 0.17871985357940612, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.9016406642217636, 'baggingFreq': 0, 'featureFraction': 0.8896917491780738, 'lambdaL1': 0.005032310118297565, 'lambdaL2': 0.000663700518115767, 'minGainToSplit': 0.0902897700544083, 'maxBin': 63}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:23:38 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/05 23:23:40 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 0. Best value: 0.698473:   8%|▊         | 8/100 [01:17<14:47,  9.65s/it]

[I 2026-05-05 23:23:41,755] Trial 7 finished with value: 0.6981718888888889 and parameters: {'learningRate': 0.011299251679907115, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.7773824883145466, 'baggingFreq': 1, 'featureFraction': 0.7725556872701355, 'lambdaL1': 6.885332382888648e-08, 'lambdaL2': 1.188343025435737, 'minGainToSplit': 0.9004180571633305, 'maxBin': 63}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:   9%|▉         | 9/100 [01:25<13:51,  9.14s/it]

[I 2026-05-05 23:23:49,773] Trial 8 finished with value: 0.6973173333333333 and parameters: {'learningRate': 0.08800150788211335, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.8955883778507802, 'baggingFreq': 1, 'featureFraction': 0.9239474215354072, 'lambdaL1': 0.007025804993039185, 'lambdaL2': 0.4395524392287042, 'minGainToSplit': 0.6576128923003434, 'maxBin': 63}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:  10%|█         | 10/100 [01:33<13:25,  8.96s/it]

[I 2026-05-05 23:23:58,313] Trial 9 finished with value: 0.6913386666666667 and parameters: {'learningRate': 0.022132793664325537, 'numLeaves': 31, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.9821375753058743, 'baggingFreq': 0, 'featureFraction': 0.9784955687763176, 'lambdaL1': 7.139327996351564e-05, 'lambdaL2': 5.010641965202524, 'minGainToSplit': 0.9636199770892528, 'maxBin': 63}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 0. Best value: 0.698473:  11%|█         | 11/100 [01:42<13:10,  8.89s/it]

[I 2026-05-05 23:24:07,044] Trial 10 finished with value: 0.6945894444444445 and parameters: {'learningRate': 0.06889556861408848, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 0.995156085765876, 'baggingFreq': 3, 'featureFraction': 0.9918969421053334, 'lambdaL1': 1.2534333684621333e-08, 'lambdaL2': 2.042213320965466e-08, 'minGainToSplit': 0.01231116956493733, 'maxBin': 255}. Best is trial 0 with value: 0.6984732222222221.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:24:15 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:24:16 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 11. Best value: 0.698544:  12%|█▏        | 12/100 [01:53<14:00,  9.55s/it]

[I 2026-05-05 23:24:18,118] Trial 11 finished with value: 0.6985436111111111 and parameters: {'learningRate': 0.010527912429507196, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 100, 'baggingFraction': 0.8117374700506187, 'baggingFreq': 1, 'featureFraction': 0.8356357762317824, 'lambdaL1': 1.0880883560577159e-08, 'lambdaL2': 0.0009294716775490714, 'minGainToSplit': 0.28087408671838654, 'maxBin': 127}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 11. Best value: 0.698544:  13%|█▎        | 13/100 [02:02<13:34,  9.36s/it]

[I 2026-05-05 23:24:27,022] Trial 12 finished with value: 0.6968567222222224 and parameters: {'learningRate': 0.04071922924925074, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 0.8443865478898067, 'baggingFreq': 1, 'featureFraction': 0.8542668769519566, 'lambdaL1': 3.49300767213645e-07, 'lambdaL2': 0.001385502475829992, 'minGainToSplit': 0.24746062408891994, 'maxBin': 127}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:24:35 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:24:37 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 11. Best value: 0.698544:  14%|█▍        | 14/100 [02:14<14:25, 10.06s/it]

[I 2026-05-05 23:24:38,719] Trial 13 finished with value: 0.6972885555555556 and parameters: {'learningRate': 0.016838189652010182, 'numLeaves': 31, 'maxDepth': 8, 'minDataInLeaf': 100, 'baggingFraction': 0.9302102038563679, 'baggingFreq': 3, 'featureFraction': 0.8248094400752193, 'lambdaL1': 6.064000335284586e-07, 'lambdaL2': 2.045032258890311e-06, 'minGainToSplit': 0.19982898700284257, 'maxBin': 127}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 11. Best value: 0.698544:  15%|█▌        | 15/100 [02:22<13:24,  9.46s/it]

[I 2026-05-05 23:24:46,780] Trial 14 finished with value: 0.697280888888889 and parameters: {'learningRate': 0.10305080157845938, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 50, 'baggingFraction': 0.8417371962335793, 'baggingFreq': 1, 'featureFraction': 0.9236540350587609, 'lambdaL1': 3.796503839126196e-08, 'lambdaL2': 0.009261607845107338, 'minGainToSplit': 0.37852092223324085, 'maxBin': 127}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 11. Best value: 0.698544:  16%|█▌        | 16/100 [02:30<12:44,  9.10s/it]

[I 2026-05-05 23:24:55,049] Trial 15 finished with value: 0.6920645555555556 and parameters: {'learningRate': 0.04374687013408061, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 20, 'baggingFraction': 0.8065381144143162, 'baggingFreq': 1, 'featureFraction': 0.867884767929035, 'lambdaL1': 9.560198294998334e-07, 'lambdaL2': 8.754460887635451e-05, 'minGainToSplit': 0.007962035489862518, 'maxBin': 255}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 11. Best value: 0.698544:  17%|█▋        | 17/100 [02:39<12:35,  9.10s/it]

[I 2026-05-05 23:25:04,161] Trial 16 finished with value: 0.6948439999999999 and parameters: {'learningRate': 0.03329512745346346, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 100, 'baggingFraction': 0.8895804535090898, 'baggingFreq': 3, 'featureFraction': 0.9370150875051599, 'lambdaL1': 0.0019775431591760903, 'lambdaL2': 4.4642468651243974e-07, 'minGainToSplit': 0.35387845130920104, 'maxBin': 127}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:25:11 WARN DAGScheduler: Broadcasting large task binary with size 1140.0 KiB
26/05/05 23:25:12 WARN DAGScheduler: Broadcasting large task binary with size 1140.0 KiB
Best trial: 11. Best value: 0.698544:  18%|█▊        | 18/100 [02:49<12:41,  9.28s/it]

[I 2026-05-05 23:25:13,866] Trial 17 finished with value: 0.6948269444444444 and parameters: {'learningRate': 0.01698176427705049, 'numLeaves': 15, 'maxDepth': 10, 'minDataInLeaf': 20, 'baggingFraction': 0.9573812901289941, 'baggingFreq': 5, 'featureFraction': 0.8202898712956748, 'lambdaL1': 0.07022576529008369, 'lambdaL2': 0.007446598681412434, 'minGainToSplit': 0.14269833529896003, 'maxBin': 255}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 11. Best value: 0.698544:  19%|█▉        | 19/100 [02:57<12:02,  8.92s/it]

[I 2026-05-05 23:25:21,934] Trial 18 finished with value: 0.6951748888888889 and parameters: {'learningRate': 0.06075645170322403, 'numLeaves': 127, 'maxDepth': 8, 'minDataInLeaf': 100, 'baggingFraction': 0.7441784079000389, 'baggingFreq': 1, 'featureFraction': 0.8873354198413935, 'lambdaL1': 1.1973401177564905e-07, 'lambdaL2': 8.976800229239037e-05, 'minGainToSplit': 0.6572415663875774, 'maxBin': 127}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 11. Best value: 0.698544:  20%|██        | 20/100 [03:05<11:30,  8.64s/it]

[I 2026-05-05 23:25:29,907] Trial 19 finished with value: 0.6942231111111111 and parameters: {'learningRate': 0.11953980299119342, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 50, 'baggingFraction': 0.826486985970287, 'baggingFreq': 0, 'featureFraction': 0.8249182172845623, 'lambdaL1': 1.4329321655479917e-08, 'lambdaL2': 1.5325207755717412e-08, 'minGainToSplit': 0.3067663162951827, 'maxBin': 255}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:25:38 WARN DAGScheduler: Broadcasting large task binary with size 1092.0 KiB
26/05/05 23:25:39 WARN DAGScheduler: Broadcasting large task binary with size 1092.0 KiB
Best trial: 11. Best value: 0.698544:  21%|██        | 21/100 [03:16<12:16,  9.32s/it]

[I 2026-05-05 23:25:40,829] Trial 20 finished with value: 0.6965628888888888 and parameters: {'learningRate': 0.0211824779485491, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 10, 'baggingFraction': 0.8793015147739095, 'baggingFreq': 0, 'featureFraction': 0.9587941530527748, 'lambdaL1': 3.419624887827877e-06, 'lambdaL2': 9.327682907032998e-07, 'minGainToSplit': 0.08710255089497025, 'maxBin': 255}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:25:49 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:25:50 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 11. Best value: 0.698544:  22%|██▏       | 22/100 [03:27<12:51,  9.89s/it]

[I 2026-05-05 23:25:52,046] Trial 21 finished with value: 0.6974406666666665 and parameters: {'learningRate': 0.010302631309335607, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.751085856276318, 'baggingFreq': 1, 'featureFraction': 0.7050243103415199, 'lambdaL1': 6.01665817531636e-08, 'lambdaL2': 6.214727400031298, 'minGainToSplit': 0.7552518921106084, 'maxBin': 63}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:25:59 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/05 23:26:01 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 11. Best value: 0.698544:  23%|██▎       | 23/100 [03:38<13:00, 10.14s/it]

[I 2026-05-05 23:26:02,762] Trial 22 finished with value: 0.6974423333333333 and parameters: {'learningRate': 0.010321915759551898, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.7670592782030842, 'baggingFreq': 1, 'featureFraction': 0.7803673589656656, 'lambdaL1': 1.3005949467567763e-07, 'lambdaL2': 0.29019950769397657, 'minGainToSplit': 0.5420957602128789, 'maxBin': 63}. Best is trial 11 with value: 0.6985436111111111.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:26:11 WARN DAGScheduler: Broadcasting large task binary with size 2.3 MiB
26/05/05 23:26:12 WARN DAGScheduler: Broadcasting large task binary with size 2.3 MiB
Best trial: 23. Best value: 0.699319:  24%|██▍       | 24/100 [03:49<13:18, 10.51s/it]

[I 2026-05-05 23:26:14,138] Trial 23 finished with value: 0.6993188888888888 and parameters: {'learningRate': 0.015130749402165562, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.8024646756450458, 'baggingFreq': 1, 'featureFraction': 0.7920184900504746, 'lambdaL1': 1.1235507380327156e-08, 'lambdaL2': 0.00661239534807973, 'minGainToSplit': 0.44137700803535024, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:26:23 WARN DAGScheduler: Broadcasting large task binary with size 3.3 MiB
26/05/05 23:26:25 WARN DAGScheduler: Broadcasting large task binary with size 3.3 MiB
Best trial: 23. Best value: 0.699319:  25%|██▌       | 25/100 [04:02<13:58, 11.18s/it]

[I 2026-05-05 23:26:26,899] Trial 24 finished with value: 0.6984069999999999 and parameters: {'learningRate': 0.014560438799103612, 'numLeaves': 31, 'maxDepth': -1, 'minDataInLeaf': 100, 'baggingFraction': 0.8208436176584369, 'baggingFreq': 1, 'featureFraction': 0.804427726648838, 'lambdaL1': 1.3756388053803676e-08, 'lambdaL2': 0.00942200835597734, 'minGainToSplit': 0.4635311947694988, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:26:35 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
26/05/05 23:26:36 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
Best trial: 23. Best value: 0.699319:  26%|██▌       | 26/100 [04:13<13:55, 11.29s/it]

[I 2026-05-05 23:26:38,424] Trial 25 finished with value: 0.6962946666666665 and parameters: {'learningRate': 0.01771657310152471, 'numLeaves': 31, 'maxDepth': 6, 'minDataInLeaf': 20, 'baggingFraction': 0.8555072743245488, 'baggingFreq': 1, 'featureFraction': 0.8854737752337823, 'lambdaL1': 1.5355097572449243e-06, 'lambdaL2': 0.002729084248946642, 'minGainToSplit': 0.39041903126293837, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:26:44 WARN DAGScheduler: Broadcasting large task binary with size 1044.6 KiB
26/05/05 23:26:45 WARN DAGScheduler: Broadcasting large task binary with size 1044.6 KiB
Best trial: 23. Best value: 0.699319:  27%|██▋       | 27/100 [04:22<12:39, 10.40s/it]

[I 2026-05-05 23:26:46,771] Trial 26 finished with value: 0.6942871666666668 and parameters: {'learningRate': 0.0308777616588778, 'numLeaves': 127, 'maxDepth': 10, 'minDataInLeaf': 100, 'baggingFraction': 0.8657421841741962, 'baggingFreq': 5, 'featureFraction': 0.8434918127355424, 'lambdaL1': 2.8692121017683875e-07, 'lambdaL2': 0.00022214421348035668, 'minGainToSplit': 0.5944451005305297, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:26:55 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:26:57 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 23. Best value: 0.699319:  28%|██▊       | 28/100 [04:34<13:05, 10.92s/it]

[I 2026-05-05 23:26:58,869] Trial 27 finished with value: 0.6976812222222221 and parameters: {'learningRate': 0.013069093759445722, 'numLeaves': 15, 'maxDepth': 8, 'minDataInLeaf': 100, 'baggingFraction': 0.9191965432724076, 'baggingFreq': 3, 'featureFraction': 0.7960090932373889, 'lambdaL1': 0.43692131736864886, 'lambdaL2': 0.036775568315919244, 'minGainToSplit': 0.29163870331555813, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  29%|██▉       | 29/100 [04:42<11:59, 10.14s/it]

[I 2026-05-05 23:27:07,212] Trial 28 finished with value: 0.6991960555555554 and parameters: {'learningRate': 0.04760125882543498, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.8096080186597443, 'baggingFreq': 1, 'featureFraction': 0.8475431967262901, 'lambdaL1': 1.1463420641390762e-05, 'lambdaL2': 1.2302976273912757e-05, 'minGainToSplit': 0.11067660865020254, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:27:14 WARN DAGScheduler: Broadcasting large task binary with size 1532.2 KiB
26/05/05 23:27:15 WARN DAGScheduler: Broadcasting large task binary with size 1532.2 KiB
Best trial: 23. Best value: 0.699319:  30%|███       | 30/100 [04:52<11:36,  9.95s/it]

[I 2026-05-05 23:27:16,726] Trial 29 finished with value: 0.6986614999999998 and parameters: {'learningRate': 0.03846630025290409, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.8059267999167011, 'baggingFreq': 1, 'featureFraction': 0.846571030580111, 'lambdaL1': 0.00033327626540650686, 'lambdaL2': 1.97386127066182e-05, 'minGainToSplit': 0.159551065758261, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  31%|███       | 31/100 [05:00<10:56,  9.52s/it]

[I 2026-05-05 23:27:25,221] Trial 30 finished with value: 0.6934050555555555 and parameters: {'learningRate': 0.0509584598057271, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.7366923809303959, 'baggingFreq': 1, 'featureFraction': 0.8626053318660325, 'lambdaL1': 0.0004166769039287125, 'lambdaL2': 1.8188496859630268e-05, 'minGainToSplit': 0.14557133801594704, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  32%|███▏      | 32/100 [05:10<10:42,  9.45s/it]

[I 2026-05-05 23:27:34,525] Trial 31 finished with value: 0.6983853333333333 and parameters: {'learningRate': 0.036014855655614283, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.8033835994321329, 'baggingFreq': 1, 'featureFraction': 0.841627891338377, 'lambdaL1': 0.0002896038864971527, 'lambdaL2': 0.00022082220657995268, 'minGainToSplit': 0.17131260028022696, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  33%|███▎      | 33/100 [05:18<10:10,  9.12s/it]

[I 2026-05-05 23:27:42,846] Trial 32 finished with value: 0.6943374444444447 and parameters: {'learningRate': 0.07166259053192588, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.8236131227001326, 'baggingFreq': 1, 'featureFraction': 0.8339277529325203, 'lambdaL1': 8.32913617215924e-06, 'lambdaL2': 4.40967894189024e-06, 'minGainToSplit': 0.08462826363965717, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:27:49 WARN DAGScheduler: Broadcasting large task binary with size 1323.7 KiB
26/05/05 23:27:50 WARN DAGScheduler: Broadcasting large task binary with size 1323.7 KiB
Best trial: 23. Best value: 0.699319:  34%|███▍      | 34/100 [05:27<10:03,  9.14s/it]

[I 2026-05-05 23:27:52,042] Trial 33 finished with value: 0.6953858333333331 and parameters: {'learningRate': 0.02443710579286278, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 10, 'baggingFraction': 0.7941485334367847, 'baggingFreq': 1, 'featureFraction': 0.8745081445598033, 'lambdaL1': 0.00038356461369328795, 'lambdaL2': 3.016507809573751e-05, 'minGainToSplit': 0.28835323445944766, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  35%|███▌      | 35/100 [05:36<09:46,  9.02s/it]

[I 2026-05-05 23:28:00,785] Trial 34 finished with value: 0.6989672222222222 and parameters: {'learningRate': 0.05066548842743558, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7636805819603821, 'baggingFreq': 1, 'featureFraction': 0.7378920003950243, 'lambdaL1': 7.496555274502449e-05, 'lambdaL2': 3.4169441302515226e-05, 'minGainToSplit': 0.40561600872263853, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:28:07 WARN DAGScheduler: Broadcasting large task binary with size 1002.4 KiB
26/05/05 23:28:08 WARN DAGScheduler: Broadcasting large task binary with size 1002.4 KiB
Best trial: 23. Best value: 0.699319:  36%|███▌      | 36/100 [05:45<09:35,  8.99s/it]

[I 2026-05-05 23:28:09,729] Trial 35 finished with value: 0.697595611111111 and parameters: {'learningRate': 0.04567252194651191, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7695463306933925, 'baggingFreq': 1, 'featureFraction': 0.7444744989785417, 'lambdaL1': 2.7555879834303313e-05, 'lambdaL2': 3.4621711735786047e-07, 'minGainToSplit': 0.38855484330792717, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  37%|███▋      | 37/100 [05:53<09:16,  8.83s/it]

[I 2026-05-05 23:28:18,162] Trial 36 finished with value: 0.6952397777777776 and parameters: {'learningRate': 0.054419446495194285, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7874060688340648, 'baggingFreq': 5, 'featureFraction': 0.7268333799821014, 'lambdaL1': 0.00010299129653716969, 'lambdaL2': 4.382257420762977e-05, 'minGainToSplit': 0.4596894043462893, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  38%|███▊      | 38/100 [06:01<08:54,  8.63s/it]

[I 2026-05-05 23:28:26,318] Trial 37 finished with value: 0.6967457777777777 and parameters: {'learningRate': 0.07731736625282898, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.723503237131314, 'baggingFreq': 1, 'featureFraction': 0.7565883426684039, 'lambdaL1': 0.002011546911908809, 'lambdaL2': 9.273346147344897e-06, 'minGainToSplit': 0.5633144337617284, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:28:33 WARN DAGScheduler: Broadcasting large task binary with size 1286.6 KiB
26/05/05 23:28:34 WARN DAGScheduler: Broadcasting large task binary with size 1286.6 KiB
Best trial: 23. Best value: 0.699319:  39%|███▉      | 39/100 [06:11<09:06,  8.96s/it]

[I 2026-05-05 23:28:36,046] Trial 38 finished with value: 0.6969887222222222 and parameters: {'learningRate': 0.0283834964700984, 'numLeaves': 63, 'maxDepth': 4, 'minDataInLeaf': 200, 'baggingFraction': 0.7667655409438797, 'baggingFreq': 1, 'featureFraction': 0.790693952425008, 'lambdaL1': 1.2489965469419288e-05, 'lambdaL2': 3.036818362531206e-06, 'minGainToSplit': 0.8000920381375523, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  40%|████      | 40/100 [06:20<08:51,  8.86s/it]

[I 2026-05-05 23:28:44,669] Trial 39 finished with value: 0.6981003888888888 and parameters: {'learningRate': 0.037438633323494834, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 50, 'baggingFraction': 0.7883361749508798, 'baggingFreq': 1, 'featureFraction': 0.809967393980995, 'lambdaL1': 0.052861655112594996, 'lambdaL2': 0.0004362135807002188, 'minGainToSplit': 0.3429056274431588, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  41%|████      | 41/100 [06:28<08:26,  8.59s/it]

[I 2026-05-05 23:28:52,627] Trial 40 finished with value: 0.6943914444444445 and parameters: {'learningRate': 0.060182097129894835, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 20, 'baggingFraction': 0.7511015139358164, 'baggingFreq': 5, 'featureFraction': 0.7639710307328613, 'lambdaL1': 8.856482602778121e-05, 'lambdaL2': 1.6335981954654447e-07, 'minGainToSplit': 0.4324720023189693, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:29:00 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:29:01 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 23. Best value: 0.699319:  42%|████▏     | 42/100 [06:38<08:50,  9.15s/it]

[I 2026-05-05 23:29:03,060] Trial 41 finished with value: 0.6984821666666666 and parameters: {'learningRate': 0.012117415831573714, 'numLeaves': 127, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.810850166973222, 'baggingFreq': 1, 'featureFraction': 0.903030660073581, 'lambdaL1': 5.218324598093336e-06, 'lambdaL2': 0.0018405840334951402, 'minGainToSplit': 0.24326317397469233, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:29:10 WARN DAGScheduler: Broadcasting large task binary with size 1481.8 KiB
26/05/05 23:29:11 WARN DAGScheduler: Broadcasting large task binary with size 1481.8 KiB
Best trial: 23. Best value: 0.699319:  43%|████▎     | 43/100 [06:48<09:01,  9.50s/it]

[I 2026-05-05 23:29:13,420] Trial 42 finished with value: 0.6974067222222222 and parameters: {'learningRate': 0.01519199339859971, 'numLeaves': 15, 'maxDepth': 12, 'minDataInLeaf': 100, 'baggingFraction': 0.8285475729728388, 'baggingFreq': 1, 'featureFraction': 0.7287705983689681, 'lambdaL1': 0.0010093873166701947, 'lambdaL2': 1.3072515759860206e-05, 'minGainToSplit': 0.1971683459461939, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 23. Best value: 0.699319:  44%|████▍     | 44/100 [06:56<08:18,  8.90s/it]

[I 2026-05-05 23:29:20,900] Trial 43 finished with value: 0.6937375555555557 and parameters: {'learningRate': 0.13760040462156853, 'numLeaves': 63, 'maxDepth': 4, 'minDataInLeaf': 20, 'baggingFraction': 0.7973745487941502, 'baggingFreq': 1, 'featureFraction': 0.8546474149933267, 'lambdaL1': 3.966695939299284e-05, 'lambdaL2': 7.640311486380622e-05, 'minGainToSplit': 0.11771095623341013, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:29:28 WARN DAGScheduler: Broadcasting large task binary with size 1828.5 KiB
26/05/05 23:29:29 WARN DAGScheduler: Broadcasting large task binary with size 1828.5 KiB
Best trial: 23. Best value: 0.699319:  45%|████▌     | 45/100 [07:06<08:27,  9.23s/it]

[I 2026-05-05 23:29:30,904] Trial 44 finished with value: 0.6990044444444444 and parameters: {'learningRate': 0.01948717096062587, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7766395114359904, 'baggingFreq': 1, 'featureFraction': 0.7054519124122138, 'lambdaL1': 0.014860681271070401, 'lambdaL2': 0.0005859052194646419, 'minGainToSplit': 0.27028501847842273, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:29:37 WARN DAGScheduler: Broadcasting large task binary with size 1201.3 KiB
26/05/05 23:29:38 WARN DAGScheduler: Broadcasting large task binary with size 1201.3 KiB
Best trial: 23. Best value: 0.699319:  46%|████▌     | 46/100 [07:15<08:13,  9.14s/it]

[I 2026-05-05 23:29:39,831] Trial 45 finished with value: 0.6992896111111112 and parameters: {'learningRate': 0.022163414381337808, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7778704491999829, 'baggingFreq': 1, 'featureFraction': 0.7050700394263489, 'lambdaL1': 0.026964556731308698, 'lambdaL2': 0.00019999418660354544, 'minGainToSplit': 0.050633814807863, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:29:47 WARN DAGScheduler: Broadcasting large task binary with size 1765.6 KiB
26/05/05 23:29:48 WARN DAGScheduler: Broadcasting large task binary with size 1765.6 KiB
Best trial: 23. Best value: 0.699319:  47%|████▋     | 47/100 [07:25<08:13,  9.31s/it]

[I 2026-05-05 23:29:49,541] Trial 46 finished with value: 0.698843111111111 and parameters: {'learningRate': 0.02038138691752215, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7204902333429104, 'baggingFreq': 1, 'featureFraction': 0.7044550140632366, 'lambdaL1': 0.016585518795469465, 'lambdaL2': 0.027718834373616264, 'minGainToSplit': 0.04862832030643597, 'maxBin': 127}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:29:56 WARN DAGScheduler: Broadcasting large task binary with size 1433.1 KiB
26/05/05 23:29:57 WARN DAGScheduler: Broadcasting large task binary with size 1433.1 KiB
Best trial: 23. Best value: 0.699319:  48%|████▊     | 48/100 [07:34<08:06,  9.35s/it]

[I 2026-05-05 23:29:58,971] Trial 47 finished with value: 0.6982207222222221 and parameters: {'learningRate': 0.027226904123618046, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7828790477833851, 'baggingFreq': 3, 'featureFraction': 0.7161990634451905, 'lambdaL1': 0.8940099852361608, 'lambdaL2': 0.00023585378179174593, 'minGainToSplit': 0.4971485815766372, 'maxBin': 63}. Best is trial 23 with value: 0.6993188888888888.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:30:06 WARN DAGScheduler: Broadcasting large task binary with size 1788.2 KiB
26/05/05 23:30:07 WARN DAGScheduler: Broadcasting large task binary with size 1788.2 KiB
Best trial: 48. Best value: 0.700544:  49%|████▉     | 49/100 [07:44<08:02,  9.47s/it]

[I 2026-05-05 23:30:08,729] Trial 48 finished with value: 0.7005439444444443 and parameters: {'learningRate': 0.01917473458326452, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7717311032776671, 'baggingFreq': 1, 'featureFraction': 0.7403795868190902, 'lambdaL1': 0.019711688182947277, 'lambdaL2': 0.0037087051123223017, 'minGainToSplit': 0.21457892947376855, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:30:15 WARN DAGScheduler: Broadcasting large task binary with size 1703.0 KiB
26/05/05 23:30:17 WARN DAGScheduler: Broadcasting large task binary with size 1703.0 KiB
Best trial: 48. Best value: 0.700544:  50%|█████     | 50/100 [07:53<07:54,  9.48s/it]

[I 2026-05-05 23:30:18,241] Trial 49 finished with value: 0.6972048333333332 and parameters: {'learningRate': 0.019729353091365007, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 200, 'baggingFraction': 0.7775543902152586, 'baggingFreq': 0, 'featureFraction': 0.7427048263727625, 'lambdaL1': 0.10743808281903405, 'lambdaL2': 0.005357400949494036, 'minGainToSplit': 0.05088321208465888, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:30:25 WARN DAGScheduler: Broadcasting large task binary with size 1675.6 KiB
26/05/05 23:30:26 WARN DAGScheduler: Broadcasting large task binary with size 1675.6 KiB
Best trial: 48. Best value: 0.700544:  51%|█████     | 51/100 [08:03<07:44,  9.48s/it]

[I 2026-05-05 23:30:27,732] Trial 50 finished with value: 0.6988375 and parameters: {'learningRate': 0.024045072808390418, 'numLeaves': 127, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.8369302016224537, 'baggingFreq': 1, 'featureFraction': 0.7112767520297457, 'lambdaL1': 0.1855786243714495, 'lambdaL2': 0.15024487200639355, 'minGainToSplit': 0.2015607399023667, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:30:36 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
26/05/05 23:30:37 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
Best trial: 48. Best value: 0.700544:  52%|█████▏    | 52/100 [08:14<08:04, 10.10s/it]

[I 2026-05-05 23:30:39,281] Trial 51 finished with value: 0.7002790555555555 and parameters: {'learningRate': 0.01427846054422471, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7676837229527753, 'baggingFreq': 1, 'featureFraction': 0.733114160419319, 'lambdaL1': 0.01754298946504257, 'lambdaL2': 0.0007026999349310694, 'minGainToSplit': 0.25504165344341806, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:30:47 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/05/05 23:30:48 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
Best trial: 48. Best value: 0.700544:  53%|█████▎    | 53/100 [08:25<08:05, 10.33s/it]

[I 2026-05-05 23:30:50,153] Trial 52 finished with value: 0.6993798888888888 and parameters: {'learningRate': 0.014890554630541291, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7539871925443348, 'baggingFreq': 1, 'featureFraction': 0.7219008445237824, 'lambdaL1': 0.017300449577740958, 'lambdaL2': 0.000677371993967787, 'minGainToSplit': 0.25522303915220135, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:30:58 WARN DAGScheduler: Broadcasting large task binary with size 1551.2 KiB
26/05/05 23:30:59 WARN DAGScheduler: Broadcasting large task binary with size 1551.2 KiB
Best trial: 48. Best value: 0.700544:  54%|█████▍    | 54/100 [08:35<07:54, 10.31s/it]

[I 2026-05-05 23:31:00,418] Trial 53 finished with value: 0.6995800555555554 and parameters: {'learningRate': 0.014238211951125807, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7572863365900451, 'baggingFreq': 1, 'featureFraction': 0.7544754433953268, 'lambdaL1': 0.023110343418000088, 'lambdaL2': 0.01791427065163, 'minGainToSplit': 0.3371751677517666, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:31:08 WARN DAGScheduler: Broadcasting large task binary with size 1862.0 KiB
26/05/05 23:31:09 WARN DAGScheduler: Broadcasting large task binary with size 1862.0 KiB
Best trial: 48. Best value: 0.700544:  55%|█████▌    | 55/100 [08:46<07:46, 10.36s/it]

[I 2026-05-05 23:31:10,879] Trial 54 finished with value: 0.6986613333333332 and parameters: {'learningRate': 0.015020776788552492, 'numLeaves': 63, 'maxDepth': 8, 'minDataInLeaf': 200, 'baggingFraction': 0.7326325727047575, 'baggingFreq': 1, 'featureFraction': 0.7535712929132043, 'lambdaL1': 0.026926770678282877, 'lambdaL2': 0.017177069830589843, 'minGainToSplit': 0.3351455664694489, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:31:19 WARN DAGScheduler: Broadcasting large task binary with size 1994.1 KiB
26/05/05 23:31:21 WARN DAGScheduler: Broadcasting large task binary with size 1994.1 KiB
Best trial: 48. Best value: 0.700544:  56%|█████▌    | 56/100 [08:58<08:01, 10.94s/it]

[I 2026-05-05 23:31:23,189] Trial 55 finished with value: 0.6989414444444444 and parameters: {'learningRate': 0.01329382569456121, 'numLeaves': 15, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7520869063355327, 'baggingFreq': 1, 'featureFraction': 0.7698025626977557, 'lambdaL1': 0.005534915112421448, 'lambdaL2': 0.00311187531574168, 'minGainToSplit': 0.22729818720609032, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:31:32 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
26/05/05 23:31:34 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
Best trial: 48. Best value: 0.700544:  57%|█████▋    | 57/100 [09:11<08:09, 11.38s/it]

[I 2026-05-05 23:31:35,590] Trial 56 finished with value: 0.6981837777777778 and parameters: {'learningRate': 0.011895525082770274, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.7128292910541026, 'baggingFreq': 3, 'featureFraction': 0.730083026736665, 'lambdaL1': 2.4845369984416337, 'lambdaL2': 0.0009348746544747791, 'minGainToSplit': 0.3207088734950459, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:31:43 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/05 23:31:45 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 48. Best value: 0.700544:  58%|█████▊    | 58/100 [09:22<07:51, 11.23s/it]

[I 2026-05-05 23:31:46,454] Trial 57 finished with value: 0.6994727222222221 and parameters: {'learningRate': 0.01700059549585453, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7578237270848736, 'baggingFreq': 1, 'featureFraction': 0.7843671812533369, 'lambdaL1': 0.28988742909186155, 'lambdaL2': 0.11455509702578807, 'minGainToSplit': 0.4325614163721657, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:31:52 WARN DAGScheduler: Broadcasting large task binary with size 1005.8 KiB
26/05/05 23:31:54 WARN DAGScheduler: Broadcasting large task binary with size 1005.8 KiB
Best trial: 48. Best value: 0.700544:  59%|█████▉    | 59/100 [09:31<07:13, 10.58s/it]

[I 2026-05-05 23:31:55,531] Trial 58 finished with value: 0.6934992222222223 and parameters: {'learningRate': 0.01758833732481386, 'numLeaves': 63, 'maxDepth': 4, 'minDataInLeaf': 10, 'baggingFraction': 0.7553636910649488, 'baggingFreq': 0, 'featureFraction': 0.7768851812039618, 'lambdaL1': 9.01702128468746, 'lambdaL2': 1.8704694827494255, 'minGainToSplit': 0.3555086826411014, 'maxBin': 127}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:32:03 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:32:05 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 48. Best value: 0.700544:  60%|██████    | 60/100 [09:42<07:13, 10.84s/it]

[I 2026-05-05 23:32:06,981] Trial 59 finished with value: 0.7005053333333332 and parameters: {'learningRate': 0.015935352811212323, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7432305751388728, 'baggingFreq': 1, 'featureFraction': 0.7835199404044981, 'lambdaL1': 0.26195468332914457, 'lambdaL2': 0.06787486391680105, 'minGainToSplit': 0.4997612559571577, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:32:14 WARN DAGScheduler: Broadcasting large task binary with size 1819.4 KiB
26/05/05 23:32:16 WARN DAGScheduler: Broadcasting large task binary with size 1819.4 KiB
Best trial: 48. Best value: 0.700544:  61%|██████    | 61/100 [09:53<07:00, 10.78s/it]

[I 2026-05-05 23:32:17,632] Trial 60 finished with value: 0.6977261666666666 and parameters: {'learningRate': 0.013901479468715266, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 200, 'baggingFraction': 0.7015550475055516, 'baggingFreq': 5, 'featureFraction': 0.7556393141845796, 'lambdaL1': 0.3036229246985016, 'lambdaL2': 0.7912289197699394, 'minGainToSplit': 0.47865959777238354, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:32:26 WARN DAGScheduler: Broadcasting large task binary with size 2.0 MiB
26/05/05 23:32:27 WARN DAGScheduler: Broadcasting large task binary with size 2.0 MiB
Best trial: 48. Best value: 0.700544:  62%|██████▏   | 62/100 [10:04<06:53, 10.87s/it]

[I 2026-05-05 23:32:28,702] Trial 61 finished with value: 0.7002843333333333 and parameters: {'learningRate': 0.01586955833161513, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7394229335197237, 'baggingFreq': 1, 'featureFraction': 0.7856510927932844, 'lambdaL1': 1.5654177780373602, 'lambdaL2': 0.0835506950365893, 'minGainToSplit': 0.43138289991011936, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:32:38 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:32:39 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 48. Best value: 0.700544:  63%|██████▎   | 63/100 [10:16<06:56, 11.25s/it]

[I 2026-05-05 23:32:40,839] Trial 62 finished with value: 0.7002342777777778 and parameters: {'learningRate': 0.01647692571305467, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7355464393331277, 'baggingFreq': 1, 'featureFraction': 0.783506408872927, 'lambdaL1': 1.6811163183604887, 'lambdaL2': 0.08568584650176149, 'minGainToSplit': 0.6151223933239566, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:32:49 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:32:50 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 48. Best value: 0.700544:  64%|██████▍   | 64/100 [10:27<06:43, 11.20s/it]

[I 2026-05-05 23:32:51,935] Trial 63 finished with value: 0.6993357777777778 and parameters: {'learningRate': 0.01622497200768146, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7362331951916534, 'baggingFreq': 1, 'featureFraction': 0.8155738676891635, 'lambdaL1': 1.5991890269528493, 'lambdaL2': 0.05577384284955093, 'minGainToSplit': 0.6852537812254369, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:33:01 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
26/05/05 23:33:03 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
Best trial: 48. Best value: 0.700544:  65%|██████▌   | 65/100 [10:40<06:48, 11.66s/it]

[I 2026-05-05 23:33:04,668] Trial 64 finished with value: 0.6999274444444442 and parameters: {'learningRate': 0.011623525122966471, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7237916526965971, 'baggingFreq': 1, 'featureFraction': 0.7854443136904757, 'lambdaL1': 0.705131676190206, 'lambdaL2': 0.14493780443059018, 'minGainToSplit': 0.5244065839524518, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:33:13 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
26/05/05 23:33:14 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
Best trial: 48. Best value: 0.700544:  66%|██████▌   | 66/100 [10:51<06:36, 11.65s/it]

[I 2026-05-05 23:33:16,259] Trial 65 finished with value: 0.6992489999999997 and parameters: {'learningRate': 0.011749061556660648, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7244436376298113, 'baggingFreq': 1, 'featureFraction': 0.7653904387573339, 'lambdaL1': 0.9271222511701543, 'lambdaL2': 0.2365338802868275, 'minGainToSplit': 0.6153404211916632, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:33:25 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
26/05/05 23:33:27 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
Best trial: 48. Best value: 0.700544:  67%|██████▋   | 67/100 [11:04<06:34, 11.95s/it]

[I 2026-05-05 23:33:28,916] Trial 66 finished with value: 0.6990899444444443 and parameters: {'learningRate': 0.011271981602645698, 'numLeaves': 63, 'maxDepth': 8, 'minDataInLeaf': 50, 'baggingFraction': 0.7126283528453274, 'baggingFreq': 1, 'featureFraction': 0.7996786863642403, 'lambdaL1': 4.44980062186277, 'lambdaL2': 0.016694873951636973, 'minGainToSplit': 0.5382883478444391, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:33:36 WARN DAGScheduler: Broadcasting large task binary with size 1861.4 KiB
26/05/05 23:33:37 WARN DAGScheduler: Broadcasting large task binary with size 1861.4 KiB
Best trial: 48. Best value: 0.700544:  68%|██████▊   | 68/100 [11:14<06:07, 11.48s/it]

[I 2026-05-05 23:33:39,300] Trial 67 finished with value: 0.6992150555555556 and parameters: {'learningRate': 0.018256734172149226, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7423346864113267, 'baggingFreq': 1, 'featureFraction': 0.7498411991158604, 'lambdaL1': 0.7802214489949665, 'lambdaL2': 0.05949010951378406, 'minGainToSplit': 0.5962205936051587, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:33:47 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/05/05 23:33:49 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
Best trial: 48. Best value: 0.700544:  69%|██████▉   | 69/100 [11:25<05:52, 11.36s/it]

[I 2026-05-05 23:33:50,408] Trial 68 finished with value: 0.6993584444444447 and parameters: {'learningRate': 0.012927334951352756, 'numLeaves': 127, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7295357567528991, 'baggingFreq': 1, 'featureFraction': 0.782592133262954, 'lambdaL1': 0.11755727790961598, 'lambdaL2': 0.3276364814390368, 'minGainToSplit': 0.7042892995925399, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:33:58 WARN DAGScheduler: Broadcasting large task binary with size 1992.1 KiB
26/05/05 23:34:00 WARN DAGScheduler: Broadcasting large task binary with size 1992.1 KiB
Best trial: 48. Best value: 0.700544:  70%|███████   | 70/100 [11:37<05:41, 11.39s/it]

[I 2026-05-05 23:34:01,861] Trial 69 finished with value: 0.6953473888888889 and parameters: {'learningRate': 0.010188108456761616, 'numLeaves': 15, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.7409777215946143, 'baggingFreq': 0, 'featureFraction': 0.7355580311000509, 'lambdaL1': 0.05360524533634011, 'lambdaL2': 0.8161786678977424, 'minGainToSplit': 0.5112125674615489, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:34:09 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
26/05/05 23:34:11 WARN DAGScheduler: Broadcasting large task binary with size 2.2 MiB
Best trial: 48. Best value: 0.700544:  71%|███████   | 71/100 [11:48<05:23, 11.16s/it]

[I 2026-05-05 23:34:12,496] Trial 70 finished with value: 0.6990613333333331 and parameters: {'learningRate': 0.01599739837567302, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7181801004652735, 'baggingFreq': 3, 'featureFraction': 0.7631772622558586, 'lambdaL1': 0.5549719924061658, 'lambdaL2': 0.01635717301610611, 'minGainToSplit': 0.6319525427419742, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:34:19 WARN DAGScheduler: Broadcasting large task binary with size 1711.2 KiB
26/05/05 23:34:20 WARN DAGScheduler: Broadcasting large task binary with size 1711.2 KiB
Best trial: 48. Best value: 0.700544:  72%|███████▏  | 72/100 [11:57<04:59, 10.69s/it]

[I 2026-05-05 23:34:22,074] Trial 71 finished with value: 0.6997613888888887 and parameters: {'learningRate': 0.018220511804059883, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7461543210110346, 'baggingFreq': 1, 'featureFraction': 0.7903411070339647, 'lambdaL1': 0.2509627972249707, 'lambdaL2': 0.1203114454170266, 'minGainToSplit': 0.42212165359073733, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:34:29 WARN DAGScheduler: Broadcasting large task binary with size 1911.9 KiB
26/05/05 23:34:31 WARN DAGScheduler: Broadcasting large task binary with size 1911.9 KiB
Best trial: 48. Best value: 0.700544:  73%|███████▎  | 73/100 [12:08<04:46, 10.61s/it]

[I 2026-05-05 23:34:32,504] Trial 72 finished with value: 0.6992073333333334 and parameters: {'learningRate': 0.02237553893652342, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7454117819128211, 'baggingFreq': 1, 'featureFraction': 0.7751285778262144, 'lambdaL1': 9.490362881886874, 'lambdaL2': 0.16287032340875482, 'minGainToSplit': 0.5621443302448874, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:34:39 WARN DAGScheduler: Broadcasting large task binary with size 1720.3 KiB
26/05/05 23:34:41 WARN DAGScheduler: Broadcasting large task binary with size 1720.3 KiB
Best trial: 48. Best value: 0.700544:  74%|███████▍  | 74/100 [12:17<04:29, 10.36s/it]

[I 2026-05-05 23:34:42,288] Trial 73 finished with value: 0.699639 and parameters: {'learningRate': 0.01882669619427544, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7077178664980431, 'baggingFreq': 1, 'featureFraction': 0.7881720396702682, 'lambdaL1': 1.8173388619234023, 'lambdaL2': 2.008706134757477, 'minGainToSplit': 0.376870598001838, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:34:49 WARN DAGScheduler: Broadcasting large task binary with size 1750.7 KiB
26/05/05 23:34:51 WARN DAGScheduler: Broadcasting large task binary with size 1750.7 KiB
Best trial: 48. Best value: 0.700544:  75%|███████▌  | 75/100 [12:27<04:16, 10.25s/it]

[I 2026-05-05 23:34:52,290] Trial 74 finished with value: 0.6986952222222222 and parameters: {'learningRate': 0.018704956585517827, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7063873142415501, 'baggingFreq': 1, 'featureFraction': 0.7908488247025715, 'lambdaL1': 1.6388419404876442, 'lambdaL2': 2.9068213283220565, 'minGainToSplit': 0.40536487696770845, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:35:00 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
26/05/05 23:35:02 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
Best trial: 48. Best value: 0.700544:  76%|███████▌  | 76/100 [12:39<04:15, 10.63s/it]

[I 2026-05-05 23:35:03,780] Trial 75 finished with value: 0.6994097777777776 and parameters: {'learningRate': 0.012506970789155358, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7313587804757727, 'baggingFreq': 1, 'featureFraction': 0.8096742278244887, 'lambdaL1': 3.8079771397764595, 'lambdaL2': 0.521402409111582, 'minGainToSplit': 0.5306238806986718, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:35:13 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
26/05/05 23:35:14 WARN DAGScheduler: Broadcasting large task binary with size 3.0 MiB
Best trial: 48. Best value: 0.700544:  77%|███████▋  | 77/100 [12:51<04:17, 11.18s/it]

[I 2026-05-05 23:35:16,267] Trial 76 finished with value: 0.6988651666666665 and parameters: {'learningRate': 0.011077326504562997, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 10, 'baggingFraction': 0.7112674076231045, 'baggingFreq': 1, 'featureFraction': 0.8030940875136836, 'lambdaL1': 2.3146567834490384, 'lambdaL2': 9.893692262200574, 'minGainToSplit': 0.484301262849809, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:35:24 WARN DAGScheduler: Broadcasting large task binary with size 2.3 MiB
26/05/05 23:35:25 WARN DAGScheduler: Broadcasting large task binary with size 2.3 MiB
Best trial: 48. Best value: 0.700544:  78%|███████▊  | 78/100 [13:02<04:02, 11.03s/it]

[I 2026-05-05 23:35:26,955] Trial 77 finished with value: 0.6997250555555554 and parameters: {'learningRate': 0.016139705764310175, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7242398446349527, 'baggingFreq': 1, 'featureFraction': 0.7909958367210735, 'lambdaL1': 0.23855195843113142, 'lambdaL2': 0.0441072284295206, 'minGainToSplit': 0.36339382273849813, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:35:34 WARN DAGScheduler: Broadcasting large task binary with size 1234.5 KiB
26/05/05 23:35:35 WARN DAGScheduler: Broadcasting large task binary with size 1234.5 KiB
Best trial: 48. Best value: 0.700544:  79%|███████▉  | 79/100 [13:11<03:41, 10.53s/it]

[I 2026-05-05 23:35:36,314] Trial 78 finished with value: 0.6947874999999999 and parameters: {'learningRate': 0.01346277472266563, 'numLeaves': 63, 'maxDepth': 10, 'minDataInLeaf': 50, 'baggingFraction': 0.726804007425707, 'baggingFreq': 5, 'featureFraction': 0.82634466104543, 'lambdaL1': 0.18420426732015194, 'lambdaL2': 0.0747526693574385, 'minGainToSplit': 0.5576679100127333, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:35:43 WARN DAGScheduler: Broadcasting large task binary with size 1520.1 KiB
26/05/05 23:35:44 WARN DAGScheduler: Broadcasting large task binary with size 1520.1 KiB
Best trial: 48. Best value: 0.700544:  80%|████████  | 80/100 [13:21<03:27, 10.37s/it]

[I 2026-05-05 23:35:46,321] Trial 79 finished with value: 0.6972854444444444 and parameters: {'learningRate': 0.016355651259567342, 'numLeaves': 63, 'maxDepth': 4, 'minDataInLeaf': 200, 'baggingFraction': 0.7447653655218601, 'baggingFreq': 1, 'featureFraction': 0.8162247243054718, 'lambdaL1': 0.25971938800202354, 'lambdaL2': 0.035639441968781334, 'minGainToSplit': 0.41119277354158257, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

Best trial: 48. Best value: 0.700544:  81%|████████  | 81/100 [13:29<03:02,  9.59s/it]

[I 2026-05-05 23:35:54,069] Trial 80 finished with value: 0.6949997777777778 and parameters: {'learningRate': 0.19946565348751222, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7621009786029638, 'baggingFreq': 1, 'featureFraction': 0.7695190375096375, 'lambdaL1': 0.5010850841666898, 'lambdaL2': 0.10265625860723382, 'minGainToSplit': 0.4540482524756159, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:36:01 WARN DAGScheduler: Broadcasting large task binary with size 1604.6 KiB
26/05/05 23:36:02 WARN DAGScheduler: Broadcasting large task binary with size 1604.6 KiB
Best trial: 48. Best value: 0.700544:  82%|████████▏ | 82/100 [13:39<02:52,  9.59s/it]

[I 2026-05-05 23:36:03,627] Trial 81 finished with value: 0.6986767777777777 and parameters: {'learningRate': 0.02067329806109386, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7008528779211756, 'baggingFreq': 1, 'featureFraction': 0.7870315401028727, 'lambdaL1': 1.3827932231159406, 'lambdaL2': 0.19998669324008456, 'minGainToSplit': 0.3716071082931409, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:36:11 WARN DAGScheduler: Broadcasting large task binary with size 1957.2 KiB
26/05/05 23:36:12 WARN DAGScheduler: Broadcasting large task binary with size 1957.2 KiB
Best trial: 48. Best value: 0.700544:  83%|████████▎ | 83/100 [13:49<02:44,  9.70s/it]

[I 2026-05-05 23:36:13,611] Trial 82 finished with value: 0.6994421111111109 and parameters: {'learningRate': 0.01856942152447936, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7156985604335359, 'baggingFreq': 1, 'featureFraction': 0.795200358422449, 'lambdaL1': 0.08770267002598221, 'lambdaL2': 2.304905136365132, 'minGainToSplit': 0.3024424956297424, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:36:22 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
26/05/05 23:36:23 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
Best trial: 48. Best value: 0.700544:  84%|████████▍ | 84/100 [14:00<02:44, 10.27s/it]

[I 2026-05-05 23:36:25,205] Trial 83 finished with value: 0.6983987777777776 and parameters: {'learningRate': 0.015545014762587728, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7207765764593852, 'baggingFreq': 1, 'featureFraction': 0.8072557180664154, 'lambdaL1': 0.49576869490608305, 'lambdaL2': 0.4432891849040406, 'minGainToSplit': 0.3646331770276804, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:36:32 WARN DAGScheduler: Broadcasting large task binary with size 1128.4 KiB
26/05/05 23:36:33 WARN DAGScheduler: Broadcasting large task binary with size 1128.4 KiB
Best trial: 48. Best value: 0.700544:  85%|████████▌ | 85/100 [14:10<02:30, 10.02s/it]

[I 2026-05-05 23:36:34,663] Trial 84 finished with value: 0.6993297777777778 and parameters: {'learningRate': 0.023706034873922765, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 200, 'baggingFraction': 0.7375723711503902, 'baggingFreq': 1, 'featureFraction': 0.7797338251235473, 'lambdaL1': 1.0961360086125471, 'lambdaL2': 0.0042590972226593474, 'minGainToSplit': 0.42579971306706405, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:36:42 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/05 23:36:43 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 48. Best value: 0.700544:  86%|████████▌ | 86/100 [14:20<02:22, 10.15s/it]

[I 2026-05-05 23:36:45,127] Trial 85 finished with value: 0.7001338333333335 and parameters: {'learningRate': 0.017419140817845905, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7687983931833006, 'baggingFreq': 1, 'featureFraction': 0.831304457752793, 'lambdaL1': 2.27081615443576, 'lambdaL2': 0.00994439025866402, 'minGainToSplit': 0.5108683005906214, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:36:53 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/05/05 23:36:55 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
Best trial: 48. Best value: 0.700544:  87%|████████▋ | 87/100 [14:32<02:16, 10.52s/it]

[I 2026-05-05 23:36:56,499] Trial 86 finished with value: 0.6989281111111112 and parameters: {'learningRate': 0.014303772739429727, 'numLeaves': 127, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7710768241376377, 'baggingFreq': 1, 'featureFraction': 0.8280543730240857, 'lambdaL1': 4.8424853004495505, 'lambdaL2': 0.008423369005024536, 'minGainToSplit': 0.5837435210192925, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:37:04 WARN DAGScheduler: Broadcasting large task binary with size 1431.4 KiB
26/05/05 23:37:05 WARN DAGScheduler: Broadcasting large task binary with size 1431.4 KiB
Best trial: 48. Best value: 0.700544:  88%|████████▊ | 88/100 [14:42<02:06, 10.58s/it]

[I 2026-05-05 23:37:07,217] Trial 87 finished with value: 0.6976816666666666 and parameters: {'learningRate': 0.017212779680601826, 'numLeaves': 15, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7447844832033428, 'baggingFreq': 1, 'featureFraction': 0.7469602086454481, 'lambdaL1': 0.002712930528047476, 'lambdaL2': 0.0019523033725672868, 'minGainToSplit': 0.4977685806632587, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:37:14 WARN DAGScheduler: Broadcasting large task binary with size 1206.9 KiB
26/05/05 23:37:15 WARN DAGScheduler: Broadcasting large task binary with size 1206.9 KiB
Best trial: 48. Best value: 0.700544:  89%|████████▉ | 89/100 [14:51<01:51, 10.14s/it]

[I 2026-05-05 23:37:16,328] Trial 88 finished with value: 0.6950748888888888 and parameters: {'learningRate': 0.02598631470987207, 'numLeaves': 63, 'maxDepth': 8, 'minDataInLeaf': 10, 'baggingFraction': 0.7619776312168106, 'baggingFreq': 1, 'featureFraction': 0.8373485397584535, 'lambdaL1': 0.04794938157818334, 'lambdaL2': 0.027754128657250424, 'minGainToSplit': 0.4711507680669997, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:37:24 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
26/05/05 23:37:25 WARN DAGScheduler: Broadcasting large task binary with size 2.1 MiB
Best trial: 48. Best value: 0.700544:  90%|█████████ | 90/100 [15:02<01:42, 10.20s/it]

[I 2026-05-05 23:37:26,667] Trial 89 finished with value: 0.6997490555555553 and parameters: {'learningRate': 0.012639747032666203, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7709999944154051, 'baggingFreq': 1, 'featureFraction': 0.7618672074909263, 'lambdaL1': 0.007306739860669754, 'lambdaL2': 0.048935516504496276, 'minGainToSplit': 0.6455491938246313, 'maxBin': 255}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:37:35 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
26/05/05 23:37:37 WARN DAGScheduler: Broadcasting large task binary with size 3.1 MiB
Best trial: 48. Best value: 0.700544:  91%|█████████ | 91/100 [15:14<01:37, 10.78s/it]

[I 2026-05-05 23:37:38,813] Trial 90 finished with value: 0.6997702222222221 and parameters: {'learningRate': 0.010951464581852033, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7718647686928702, 'baggingFreq': 3, 'featureFraction': 0.760522707860183, 'lambdaL1': 0.00967939894166232, 'lambdaL2': 0.010545481698102791, 'minGainToSplit': 0.6363827866424735, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:37:47 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
26/05/05 23:37:48 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
Best trial: 48. Best value: 0.700544:  92%|█████████▏| 92/100 [15:25<01:27, 10.95s/it]

[I 2026-05-05 23:37:50,164] Trial 91 finished with value: 0.6990132222222221 and parameters: {'learningRate': 0.010940054997387214, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7742645499488887, 'baggingFreq': 3, 'featureFraction': 0.763912097363148, 'lambdaL1': 0.010599440586519264, 'lambdaL2': 0.010580078503371868, 'minGainToSplit': 0.7408423839368606, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:37:58 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
26/05/05 23:37:59 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
Best trial: 48. Best value: 0.700544:  93%|█████████▎| 93/100 [15:36<01:16, 10.93s/it]

[I 2026-05-05 23:38:01,048] Trial 92 finished with value: 0.6993257777777776 and parameters: {'learningRate': 0.012471667507696241, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7874007321899277, 'baggingFreq': 3, 'featureFraction': 0.7384220430258069, 'lambdaL1': 0.009199671302465939, 'lambdaL2': 0.004122541796366289, 'minGainToSplit': 0.6430033623107699, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:38:09 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
26/05/05 23:38:10 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
Best trial: 48. Best value: 0.700544:  94%|█████████▍| 94/100 [15:47<01:05, 11.00s/it]

[I 2026-05-05 23:38:12,197] Trial 93 finished with value: 0.699330611111111 and parameters: {'learningRate': 0.013671226501272098, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7840365732909964, 'baggingFreq': 3, 'featureFraction': 0.7731232347893973, 'lambdaL1': 0.0031875204599047416, 'lambdaL2': 0.0955368290961366, 'minGainToSplit': 0.7032618715292597, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:38:20 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/05/05 23:38:21 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
Best trial: 48. Best value: 0.700544:  95%|█████████▌| 95/100 [15:58<00:55, 11.03s/it]

[I 2026-05-05 23:38:23,287] Trial 94 finished with value: 0.7002282777777777 and parameters: {'learningRate': 0.011717976433341621, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7975663669448365, 'baggingFreq': 3, 'featureFraction': 0.7582359671133642, 'lambdaL1': 0.0008173183820218274, 'lambdaL2': 0.0013525145892015662, 'minGainToSplit': 0.6817864958730215, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:38:31 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
26/05/05 23:38:32 WARN DAGScheduler: Broadcasting large task binary with size 2.6 MiB
Best trial: 48. Best value: 0.700544:  96%|█████████▌| 96/100 [16:09<00:43, 10.99s/it]

[I 2026-05-05 23:38:34,211] Trial 95 finished with value: 0.6981586111111112 and parameters: {'learningRate': 0.01013567602843236, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 50, 'baggingFraction': 0.7483763776476685, 'baggingFreq': 3, 'featureFraction': 0.7597044207619391, 'lambdaL1': 0.0015293013643435667, 'lambdaL2': 0.002135965923421125, 'minGainToSplit': 0.678389544404277, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:38:42 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
26/05/05 23:38:44 WARN DAGScheduler: Broadcasting large task binary with size 2.4 MiB
Best trial: 48. Best value: 0.700544:  97%|█████████▋| 97/100 [16:21<00:33, 11.12s/it]

[I 2026-05-05 23:38:45,619] Trial 96 finished with value: 0.6985942777777775 and parameters: {'learningRate': 0.01181961414623397, 'numLeaves': 63, 'maxDepth': 6, 'minDataInLeaf': 200, 'baggingFraction': 0.763352858569603, 'baggingFreq': 3, 'featureFraction': 0.7504948258626852, 'lambdaL1': 0.15485470227347312, 'lambdaL2': 0.0013978877444064978, 'minGainToSplit': 0.7841556436132361, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:38:53 WARN DAGScheduler: Broadcasting large task binary with size 1805.0 KiB
26/05/05 23:38:54 WARN DAGScheduler: Broadcasting large task binary with size 1805.0 KiB
Best trial: 48. Best value: 0.700544:  98%|█████████▊| 98/100 [16:30<00:21, 10.70s/it]

[I 2026-05-05 23:38:55,362] Trial 97 finished with value: 0.6981330555555555 and parameters: {'learningRate': 0.015086417300825898, 'numLeaves': 63, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.8006170364344128, 'baggingFreq': 3, 'featureFraction': 0.7342116658927388, 'lambdaL1': 0.0005971056974480225, 'lambdaL2': 0.01080881138122476, 'minGainToSplit': 0.5922100464350452, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:39:02 WARN DAGScheduler: Broadcasting large task binary with size 1302.6 KiB
26/05/05 23:39:03 WARN DAGScheduler: Broadcasting large task binary with size 1302.6 KiB
Best trial: 48. Best value: 0.700544:  99%|█████████▉| 99/100 [16:40<00:10, 10.45s/it]

[I 2026-05-05 23:39:05,213] Trial 98 finished with value: 0.6988160000000001 and parameters: {'learningRate': 0.021215804988944847, 'numLeaves': 31, 'maxDepth': 12, 'minDataInLeaf': 200, 'baggingFraction': 0.7371517498829694, 'baggingFreq': 3, 'featureFraction': 0.8001151462008784, 'lambdaL1': 0.034037340276343156, 'lambdaL2': 0.000377447828461474, 'minGainToSplit': 0.6100232078015764, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
[LightGBM] [Info] Saving data reference to binary buffer

26/05/05 23:39:14 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
26/05/05 23:39:15 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
Best trial: 48. Best value: 0.700544: 100%|██████████| 100/100 [16:52<00:00, 10.13s/it]

[I 2026-05-05 23:39:17,316] Trial 99 finished with value: 0.6985932222222222 and parameters: {'learningRate': 0.011061446732513795, 'numLeaves': 63, 'maxDepth': -1, 'minDataInLeaf': 200, 'baggingFraction': 0.7941194098967049, 'baggingFreq': 3, 'featureFraction': 0.743382764425543, 'lambdaL1': 0.00017262867734172248, 'lambdaL2': 0.001199043237096902, 'minGainToSplit': 0.5212733465993994, 'maxBin': 63}. Best is trial 48 with value: 0.7005439444444443.
========== Optuna Best Result ==========
Best validation AUC: 0.7005439444444443

Best params:
{
  "learningRate": 0.01917473458326452,
  "numLeaves": 63,
  "maxDepth": 12,
  "minDataInLeaf": 200,
  "baggingFraction": 0.7717311032776671,
  "baggingFreq": 1,
  "featureFraction": 0.7403795868190902,
  "lambdaL1": 0.019711688182947277,
  "lambdaL2": 0.0037087051123223017,
  "minGainToSplit": 0.21457892947376855,
  "maxBin": 127
}

Best trial extra info:
Trial number    : 48
Test AUC        : 0.7027919999999998
Best iteration  : 244
Best iter source: getBoosterBestIteration
Total iterations: 245
Fit seconds     : 7.026308298110962
========================================

In [21]:
# ============================================================
# Save and review Optuna tuning results
# ============================================================

from pathlib import Path
import pandas as pd

# Đảm bảo output directory tồn tại
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)


# ============================================================
# 1. Save all Optuna trials
# ============================================================

trials_df = study.trials_dataframe()

trials_path = f"{OUTPUT_DIR}/optuna_synapseml_lgbm_trials.csv"
trials_df.to_csv(trials_path, index=False)

print("Saved Optuna trials:", trials_path)


# ============================================================
# 2. Show top trials by validation AUC
# ============================================================

# value = validation AUC vì objective() return valid_auc
top_trials_df = (
    trials_df
    .dropna(subset=["value"])
    .sort_values("value", ascending=False)
    .head(10)
)

print("\nTop 10 trials by validation AUC:")
display(top_trials_df)


# ============================================================
# 3. Parameter importance
# ============================================================

try:
    from optuna.importance import get_param_importances

    complete_trials = [
        trial for trial in study.trials
        if trial.state == optuna.trial.TrialState.COMPLETE
        and trial.value is not None
    ]

    if len(complete_trials) < 2:
        print(
            "\nParam importance skipped: "
            "cần ít nhất 2 completed trials để tính importance."
        )
    else:
        param_importance = get_param_importances(study)

        param_importance_df = (
            pd.DataFrame(
                {
                    "parameter": list(param_importance.keys()),
                    "importance": list(param_importance.values()),
                }
            )
            .sort_values("importance", ascending=False)
        )

        param_importance_path = (
            f"{OUTPUT_DIR}/optuna_synapseml_param_importance.csv"
        )

        param_importance_df.to_csv(param_importance_path, index=False)

        print("\nSaved parameter importance:", param_importance_path)
        display(param_importance_df)

except Exception as e:
    print("\nParam importance skipped:", repr(e))

Saved Optuna trials: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/optuna_synapseml_lgbm_trials.csv

Top 10 trials by validation AUC:

,number,value,datetime_start,datetime_complete,duration,params_baggingFraction,params_baggingFreq,params_featureFraction,params_lambdaL1,params_lambdaL2,...,user_attrs_best_iteration,user_attrs_best_iteration_source,user_attrs_booster_best_iteration_method,user_attrs_booster_best_iteration_raw,user_attrs_booster_num_total_model,user_attrs_booster_total_iterations,user_attrs_fit_seconds,user_attrs_test_auc,system_attrs_fixed_params,state
48,48,0.700544,2026-05-05 23:29:59.081235,2026-05-05 23:30:08.729031,0 days 00:00:09.647796,0.771731,1,0.740380,0.019712,0.003709,...,244,getBoosterBestIteration,getBoosterBestIteration,244,245,245,7.026308,0.702792,NaN,COMPLETE
59,59,0.700505,2026-05-05 23:31:55.639593,2026-05-05 23:32:06.981181,0 days 00:00:11.341588,0.743231,1,0.783520,0.261955,0.067875,...,328,getBoosterBestIteration,getBoosterBestIteration,328,329,329,8.127074,0.701539,NaN,COMPLETE
61,61,0.700284,2026-05-05 23:32:17.737939,2026-05-05 23:32:28.702433,0 days 00:00:10.964494,0.739423,1,0.785651,1.565418,0.083551,...,291,getBoosterBestIteration,getBoosterBestIteration,291,292,292,8.135273,0.701527,NaN,COMPLETE
51,51,0.700279,2026-05-05 23:30:27.835331,2026-05-05 23:30:39.281658,0 days 00:00:11.446327,0.767684,1,0.733114,0.017543,0.000703,...,396,getBoosterBestIteration,getBoosterBestIteration,396,397,397,8.391499,0.703151,NaN,COMPLETE
62,62,0.700234,2026-05-05 23:32:28.806860,2026-05-05 23:32:40.839781,0 days 00:00:12.032921,0.735546,1,0.783506,1.681116,0.085686,...,317,getBoosterBestIteration,getBoosterBestIteration,317,318,318,9.059222,0.702589,NaN,COMPLETE
94,94,0.700228,2026-05-05 23:38:12.300077,2026-05-05 23:38:23.287357,0 days 00:00:10.987280,0.797566,3,0.758236,0.000817,0.001353,...,374,getBoosterBestIteration,getBoosterBestIteration,374,375,375,7.910875,0.702417,NaN,COMPLETE
85,85,0.700134,2026-05-05 23:36:34.766391,2026-05-05 23:36:45.127084,0 days 00:00:10.360693,0.768798,1,0.831304,2.270816,0.009944,...,309,getBoosterBestIteration,getBoosterBestIteration,309,310,310,7.551841,0.702104,NaN,COMPLETE
64,64,0.699927,2026-05-05 23:32:52.044822,2026-05-05 23:33:04.668461,0 days 00:00:12.623639,0.723792,1,0.785444,0.705132,0.144938,...,471,getBoosterBestIteration,getBoosterBestIteration,471,472,472,9.262883,0.703419,NaN,COMPLETE
90,90,0.699770,2026-05-05 23:37:26.774225,2026-05-05 23:37:38.812956,0 days 00:00:12.038731,0.771865,3,0.760523,0.009679,0.010545,...,458,getBoosterBestIteration,getBoosterBestIteration,458,459,459,8.666776,0.703277,NaN,COMPLETE
71,71,0.699761,2026-05-05 23:34:12.600664,2026-05-05 23:34:22.074133,0 days 00:00:09.473469,0.746154,1,0.790341,0.250963,0.120311,...,235,getBoosterBestIteration,getBoosterBestIteration,235,236,236,6.941692,0.701667,NaN,COMPLETE

Saved parameter importance: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/optuna_synapseml_param_importance.csv

          parameter  importance
0       baggingFreq    0.184161
1      learningRate    0.167624
2     minDataInLeaf    0.157942
3    minGainToSplit    0.137119
4          maxDepth    0.128324
5   featureFraction    0.104135
6         numLeaves    0.064541
7            maxBin    0.028833
8          lambdaL1    0.012984
9   baggingFraction    0.008237
10         lambdaL2    0.006100

## 18. Select best params and train final model

Nếu Optuna tốt hơn baseline theo validation AUC thì dùng Optuna; ngược lại giữ baseline.

In [22]:
# ============================================================
# Select best parameters: Optuna vs Baseline
# ============================================================

# Nếu Optuna tốt hơn hoặc bằng baseline trên validation AUC,
# dùng best params từ Optuna.
# Ngược lại, quay về baseline params.
if float(study.best_value) >= float(baseline_valid_auc):
    selected_params = dict(study.best_params)
    selected_param_source = "optuna"
    selected_valid_auc = float(study.best_value)
else:
    selected_params = dict(baseline_params)
    selected_param_source = "baseline"
    selected_valid_auc = float(baseline_valid_auc)


# Build full SynapseML params:
# - selected_params chỉ chứa model params cần tune
# - build_lgbm_params() sẽ thêm các fixed params như:
#   numIterations, earlyStoppingRound, numTasks, numThreads, timeout...
selected_lgbm_params = build_lgbm_params(selected_params)


print("========== Selected LightGBM Parameters ==========")
print("Selected param source:", selected_param_source)
print("Selected validation AUC:", selected_valid_auc)

print("\nSelected tunable params:")
print(json.dumps(selected_params, indent=2, default=str))

print("\nSelected full SynapseML params:")
print(json.dumps(selected_lgbm_params, indent=2, default=str))

print("==================================================")

========== Selected LightGBM Parameters ==========
Selected param source: optuna
Selected validation AUC: 0.7005439444444443

Selected tunable params:
{
  "learningRate": 0.01917473458326452,
  "numLeaves": 63,
  "maxDepth": 12,
  "minDataInLeaf": 200,
  "baggingFraction": 0.7717311032776671,
  "baggingFreq": 1,
  "featureFraction": 0.7403795868190902,
  "lambdaL1": 0.019711688182947277,
  "lambdaL2": 0.0037087051123223017,
  "minGainToSplit": 0.21457892947376855,
  "maxBin": 127
}

Selected full SynapseML params:
{
  "objective": "binary",
  "metric": "auc",
  "featuresCol": "features",
  "labelCol": "label",
  "validationIndicatorCol": "is_validation",
  "learningRate": 0.01917473458326452,
  "numLeaves": 63,
  "maxDepth": 12,
  "minDataInLeaf": 200,
  "baggingFraction": 0.7717311032776671,
  "baggingFreq": 1,
  "featureFraction": 0.7403795868190902,
  "lambdaL1": 0.019711688182947277,
  "lambdaL2": 0.0037087051123223017,
  "minGainToSplit": 0.21457892947376855,
  "maxBin": 127,
  "numIterations": 2000,
  "earlyStoppingRound": 100,
  "numTasks": 4,
  "numThreads": 3,
  "maxStreamingOMPThreads": 3,
  "timeout": 600,
  "useBarrierExecutionMode": true,
  "useSingleDatasetMode": true,
  "dataTransferMode": "streaming",
  "verbosity": -1
}
==================================================

In [23]:
# ============================================================
# Train final SynapseML LightGBM model
# ============================================================

final_shap_col = "featuresShap" if RUN_FINAL_SHAP else None

final_result, final_model, final_test_pred_df = train_lgbm_baseline(
    params=selected_params,
    train_valid_df=lgbm_train_valid_df,
    valid_df=valid_features_df,
    test_df=test_features_df,
    categorical_slot_indexes=feature_pipeline.categorical_slot_indexes_,
    shap_col=final_shap_col,
    keep_test_predictions=True,
)

final_valid_auc = final_result["valid_auc"]
final_test_auc = final_result["test_auc"]
final_best_iteration = final_result["best_iteration"]

print("========== Final Model Result ==========")
print(json.dumps(final_result, indent=2, default=str))

print("\nRUN_FINAL_SHAP:", RUN_FINAL_SHAP)
print("Final prediction columns:")
print(final_test_pred_df.columns)
print("========================================")

[LightGBM] [Info] Saving data reference to binary buffer

26/05/06 00:49:24 WARN DAGScheduler: Broadcasting large task binary with size 1788.2 KiB
26/05/06 00:49:26 WARN DAGScheduler: Broadcasting large task binary with size 1788.2 KiB
26/05/06 00:49:27 WARN DAGScheduler: Broadcasting large task binary with size 1809.9 KiB
26/05/06 00:49:51 WARN DAGScheduler: Broadcasting large task binary with size 1814.3 KiB

========== Final Model Result ==========
{
  "valid_auc": 0.7005318333333335,
  "test_auc": 0.702794888888889,
  "best_iteration": 244,
  "best_iteration_source": "getBoosterBestIteration",
  "booster_best_iteration_raw": 244,
  "booster_best_iteration_method": "getBoosterBestIteration",
  "booster_total_iterations": 245,
  "booster_num_total_model": 245,
  "fit_seconds": 7.704510688781738
}

RUN_FINAL_SHAP: True
Final prediction columns:
['features', 'label', 'rawPrediction', 'probability', 'prediction', 'featuresShap']
========================================

In [24]:
# ============================================================
# Save AUC + best_iteration summary
# ============================================================

from pathlib import Path
import pandas as pd

Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

# Lấy thông tin phụ của best Optuna trial nếu có
optuna_best_test_auc = study.best_trial.user_attrs.get("test_auc")
optuna_best_iteration = study.best_trial.user_attrs.get("best_iteration")
optuna_best_iteration_source = study.best_trial.user_attrs.get("best_iteration_source")
optuna_booster_total_iterations = study.best_trial.user_attrs.get("booster_total_iterations")
optuna_fit_seconds = study.best_trial.user_attrs.get("fit_seconds")

auc_summary_df = pd.DataFrame([
    {
        "case": "baseline",
        "valid_auc": float(baseline_valid_auc),
        "test_auc": float(baseline_test_auc),
        "best_iteration": baseline_result.get("best_iteration"),
        "best_iteration_source": baseline_result.get("best_iteration_source"),
        "booster_total_iterations": baseline_result.get("booster_total_iterations"),
        "fit_seconds": baseline_result.get("fit_seconds"),
        "param_source": "baseline",
    },
    {
        "case": "optuna_best",
        "valid_auc": float(study.best_value),
        "test_auc": (
            float(optuna_best_test_auc)
            if optuna_best_test_auc is not None
            else None
        ),
        "best_iteration": (
            int(optuna_best_iteration)
            if optuna_best_iteration is not None
            else None
        ),
        "best_iteration_source": optuna_best_iteration_source,
        "booster_total_iterations": (
            int(optuna_booster_total_iterations)
            if optuna_booster_total_iterations is not None
            else None
        ),
        "fit_seconds": (
            float(optuna_fit_seconds)
            if optuna_fit_seconds is not None
            else None
        ),
        "param_source": "optuna",
    },
    {
        "case": "final_selected",
        "valid_auc": float(final_valid_auc),
        "test_auc": float(final_test_auc),
        "best_iteration": final_result.get("best_iteration"),
        "best_iteration_source": final_result.get("best_iteration_source"),
        "booster_total_iterations": final_result.get("booster_total_iterations"),
        "fit_seconds": final_result.get("fit_seconds"),
        "param_source": selected_param_source,
    },
])

auc_summary_path = f"{OUTPUT_DIR}/auc_summary.csv"
auc_summary_df.to_csv(auc_summary_path, index=False)

# File riêng để copy nhanh số numIterations nên dùng khi production không bật early stopping.
production_iteration_df = pd.DataFrame([
    {
        "recommended_source": "final_selected.best_iteration",
        "production_num_iterations": final_result.get("best_iteration"),
        "source_detail": final_result.get("best_iteration_source"),
        "note": (
            "Use this as fixed numIterations in production when earlyStoppingRound is disabled. "
            "If this value is missing, keep validation + early stopping or rerun offline tuning."
        ),
    }
])

production_iteration_path = f"{OUTPUT_DIR}/production_num_iterations_recommendation.csv"
production_iteration_df.to_csv(production_iteration_path, index=False)

print("Saved AUC summary:", auc_summary_path)
print("Saved production iteration recommendation:", production_iteration_path)
display(auc_summary_df)
display(production_iteration_df)

Saved AUC summary: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/auc_summary.csv
Saved production iteration recommendation: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/production_num_iterations_recommendation.csv

,case,valid_auc,test_auc,best_iteration,best_iteration_source,booster_total_iterations,fit_seconds,param_source
0,baseline,0.698462,0.703391,130,getBoosterBestIteration,131,8.569046,baseline
1,optuna_best,0.700544,0.702792,244,getBoosterBestIteration,245,7.026308,optuna
2,final_selected,0.700532,0.702795,244,getBoosterBestIteration,245,7.704511,optuna

,recommended_source,production_num_iterations,source_detail,note
0,final_selected.best_iteration,244,getBoosterBestIteration,Use this as fixed numIterations in production ...

In [25]:
# ============================================================
# Save best SynapseML LightGBM configuration
# ============================================================

from pathlib import Path
import json

Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

# Full params dùng để train SynapseML LightGBM.
# selected_params chỉ là tunable params, còn build_lgbm_params()
# sẽ bổ sung fixed params như numIterations, numTasks, numThreads...
selected_lgbm_params = build_lgbm_params(selected_params)

# Lấy test AUC của best Optuna trial nếu có
optuna_best_test_auc = study.best_trial.user_attrs.get("test_auc")
optuna_best_iteration = study.best_trial.user_attrs.get("best_iteration")
optuna_best_iteration_source = study.best_trial.user_attrs.get("best_iteration_source")
optuna_booster_best_iteration_raw = study.best_trial.user_attrs.get("booster_best_iteration_raw")
optuna_booster_best_iteration_method = study.best_trial.user_attrs.get("booster_best_iteration_method")
optuna_booster_total_iterations = study.best_trial.user_attrs.get("booster_total_iterations")
optuna_booster_num_total_model = study.best_trial.user_attrs.get("booster_num_total_model")
optuna_fit_seconds = study.best_trial.user_attrs.get("fit_seconds")

# Trong TaxiFeaturePipeline phiên bản mới,
# categorical features gồm:
# - categorical numeric columns
# - string columns sau khi StringIndexer
categorical_feature_cols = (
    feature_pipeline.categorical_numeric_cols_
    + feature_pipeline.string_indexed_cols_
)

best_config = {
    "model": "SynapseML LightGBM",
    "task": "current_batch_vs_historical_batches",
    "target_processing_date_hour": str(TARGET_PROCESSING_DATE_HOUR),
    "comparison_processing_date_hours": [
        str(h) for h in comparison_processing_hours
    ],

    # Main metric
    "metric": "auc",

    # Baseline result
    "baseline": {
        "valid_auc": float(baseline_valid_auc),
        "test_auc": float(baseline_test_auc),
        "best_iteration": baseline_result.get("best_iteration"),
        "best_iteration_source": baseline_result.get("best_iteration_source"),
        "booster_best_iteration_raw": baseline_result.get("booster_best_iteration_raw"),
        "booster_best_iteration_method": baseline_result.get("booster_best_iteration_method"),
        "booster_total_iterations": baseline_result.get("booster_total_iterations"),
        "booster_num_total_model": baseline_result.get("booster_num_total_model"),
        "fit_seconds": baseline_result.get("fit_seconds"),
        "params": baseline_params,
    },

    # Optuna result
    "optuna_best": {
        "valid_auc": float(study.best_value),
        "test_auc": (
            float(optuna_best_test_auc)
            if optuna_best_test_auc is not None
            else None
        ),
        "best_iteration": (
            int(optuna_best_iteration)
            if optuna_best_iteration is not None
            else None
        ),
        "best_iteration_source": optuna_best_iteration_source,
        "booster_best_iteration_raw": (
            int(optuna_booster_best_iteration_raw)
            if optuna_booster_best_iteration_raw is not None
            else None
        ),
        "booster_best_iteration_method": optuna_booster_best_iteration_method,
        "booster_total_iterations": (
            int(optuna_booster_total_iterations)
            if optuna_booster_total_iterations is not None
            else None
        ),
        "booster_num_total_model": (
            int(optuna_booster_num_total_model)
            if optuna_booster_num_total_model is not None
            else None
        ),
        "fit_seconds": (
            float(optuna_fit_seconds)
            if optuna_fit_seconds is not None
            else None
        ),
        "params": study.best_params,
    },

    # Final selected result
    "final_selected": {
        "selected_param_source": selected_param_source,
        "selected_valid_auc": float(selected_valid_auc),
        "selected_tunable_params": selected_params,
        "selected_full_lgbm_params": selected_lgbm_params,
        "final_valid_auc": float(final_valid_auc),
        "final_test_auc": float(final_test_auc),
        "final_best_iteration": (
            int(final_best_iteration)
            if final_best_iteration is not None
            else None
        ),
        "best_iteration_source": final_result.get("best_iteration_source"),
        "booster_best_iteration_raw": final_result.get("booster_best_iteration_raw"),
        "booster_best_iteration_method": final_result.get("booster_best_iteration_method"),
        "booster_total_iterations": final_result.get("booster_total_iterations"),
        "booster_num_total_model": final_result.get("booster_num_total_model"),
        "fit_seconds": final_result.get("fit_seconds"),
        "production_num_iterations_recommendation": final_result.get("best_iteration"),
    },

    # Feature information
    "features": {
        "numeric_feature_cols": feature_pipeline.numeric_feature_cols_,
        "categorical_numeric_cols": feature_pipeline.categorical_numeric_cols_,
        "categorical_string_cols": feature_pipeline.categorical_string_cols_,
        "string_indexed_cols": feature_pipeline.string_indexed_cols_,
        "final_feature_cols": feature_pipeline.feature_cols_,
        "categorical_feature_cols": categorical_feature_cols,
        "categorical_slot_indexes": feature_pipeline.categorical_slot_indexes_,
    },

    # Fixed experiment config
    "fixed_training_config": {
        "random_state": RANDOM_STATE,
        "target_sample_per_group": TARGET_SAMPLE_PER_GROUP,
        "min_rows_per_group": MIN_ROWS_PER_GROUP,
        "previous_batch_offset": str(PREVIOUS_BATCH_OFFSET),
        "history_offsets": [
            str(offset) for offset in HISTORY_OFFSETS
        ],
        "n_estimators_max": N_ESTIMATORS_MAX,
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "production_rule": "If production uses train/test only, set earlyStoppingRound=0 and numIterations=production_num_iterations_recommendation.",
        "lgbm_num_tasks": LGBM_NUM_TASKS,
        "lgbm_num_threads": LGBM_NUM_THREADS,
        "spark_sql_shuffle_partitions": SPARK_SQL_SHUFFLE_PARTITIONS,
        "run_optuna": RUN_OPTUNA,
        "n_trials": N_TRIALS,
        "run_final_shap": RUN_FINAL_SHAP,
        "use_fixed_ports": USE_FIXED_PORTS,
    },
}

best_config_path = f"{OUTPUT_DIR}/best_synapseml_lightgbm_config.json"

with open(best_config_path, "w", encoding="utf-8") as f:
    json.dump(
        best_config,
        f,
        indent=2,
        ensure_ascii=False,
        default=str,
    )

print("Saved best config:", best_config_path)

Saved best config: /opt/spark/workspace/output/synapseml_experiment_silver_yellow_tripdata/best_synapseml_lightgbm_config.json

## 19. Classification report on test set

AUC là metric chính cho drift detection. Classification report chỉ để xem thêm tại một threshold cụ thể.

In [ ]:
THRESHOLD = 0.5

score_pdf = extract_probability_label_df(final_test_pred_df)
score_pdf["y_pred"] = (score_pdf["pred_score"] >= THRESHOLD).astype(int)

print("Test AUC from Spark:", final_test_auc)
print("Test AUC from pandas:", roc_auc_score(score_pdf["y_true"], score_pdf["pred_score"]))
print("Threshold:", THRESHOLD)
print(classification_report(score_pdf["y_true"], score_pdf["y_pred"], digits=4))

score_path = f"{OUTPUT_DIR}/final_test_predictions_scores.csv"
score_pdf.to_csv(score_path, index=False)
print("Saved:", score_path)

## 20. Feature importance and optional SHAP

- Native feature importance nhẹ hơn SHAP.
- SHAP trong SynapseML nặng hơn nhiều, nên chỉ bật bằng `RUN_FINAL_SHAP=True`.

In [ ]:
def get_synapseml_feature_importance_df(model, feature_cols):
    """Đọc feature importance từ SynapseML model nếu version hiện tại hỗ trợ."""
    importances = None

    # SynapseML versions khác nhau có thể expose importance khác nhau.
    for expr in [
        "model.getFeatureImportances()",
        "model.getLightGBMBooster().getFeatureImportances()",
    ]:
        try:
            importances = eval(expr)
            break
        except Exception:
            pass

    if importances is None:
        print("Could not read native feature_importances from SynapseML model.")
        return pd.DataFrame({"feature": feature_cols, "importance": np.nan})

    importances = list(importances)
    n = min(len(importances), len(feature_cols))

    if len(importances) != len(feature_cols):
        print("Warning: importance length mismatch:", len(importances), len(feature_cols))

    return pd.DataFrame({
        "feature": feature_cols[:n],
        "importance": importances[:n],
    }).sort_values("importance", ascending=False)


importance_df = get_synapseml_feature_importance_df(final_model, feature_pipeline.feature_cols_)
importance_path = f"{OUTPUT_DIR}/final_synapseml_feature_importance.csv"
importance_df.to_csv(importance_path, index=False)

print("Saved:", importance_path)
display(importance_df.head(30))

In [ ]:
import matplotlib.pyplot as plt

plot_df = importance_df.dropna().head(20).sort_values("importance")

if len(plot_df) > 0:
    plt.figure(figsize=(8, 6))
    plt.barh(plot_df["feature"], plot_df["importance"])
    plt.xlabel("Importance")
    plt.ylabel("Feature")
    plt.title("Top SynapseML LightGBM Feature Importance")
    plt.show()
else:
    print("Native feature importance not available or empty.")

In [ ]:
def compute_top_shap_from_predictions(pred_df, feature_cols, shap_col="featuresShap", top_n=20, sample_size=None, seed=42):
    """Tính mean(|SHAP|) cho từng feature từ prediction DataFrame."""
    if shap_col not in pred_df.columns:
        raise ValueError(
            f"Column {shap_col!r} không tồn tại. "
            "Hãy bật RUN_FINAL_SHAP=True hoặc estimator phải có featuresShapCol."
        )

    shap_source_df = pred_df

    if sample_size is not None:
        total = pred_df.count()
        if total > sample_size:
            frac = min(1.0, float(sample_size) / float(total) * 1.5)
            shap_source_df = pred_df.sample(False, frac, seed=seed).limit(int(sample_size))

    shap_df = shap_source_df.withColumn("shap_array", vector_to_array(shap_col))
    shap_size = shap_df.select(F.size("shap_array").alias("shap_size")).first()["shap_size"]

    shap_long_df = shap_df.select(
        F.posexplode("shap_array").alias("feature_index", "shap_value")
    )

    # Một số version có bias/base value ở cuối vector SHAP. Nếu có, bỏ phần đó.
    if shap_size == len(feature_cols) + 1:
        shap_long_df = shap_long_df.filter(F.col("feature_index") < len(feature_cols))

    feature_mapping_df = spark.createDataFrame(
        [(i, name) for i, name in enumerate(feature_cols)],
        ["feature_index", "feature"],
    )

    shap_all_df = (
        shap_long_df
        .groupBy("feature_index")
        .agg(F.avg(F.abs("shap_value")).alias("mean_abs_shap"))
        .join(F.broadcast(feature_mapping_df), on="feature_index", how="left")
        .orderBy(F.desc("mean_abs_shap"))
    )

    return shap_all_df.limit(top_n), shap_all_df


if RUN_FINAL_SHAP and final_test_pred_df is not None and "featuresShap" in final_test_pred_df.columns:
    shap_top_df_spark, shap_all_df_spark = compute_top_shap_from_predictions(
        pred_df=final_test_pred_df,
        feature_cols=feature_pipeline.feature_cols_,
        shap_col="featuresShap",
        top_n=20,
        sample_size=SHAP_SAMPLE_SIZE,
        seed=RANDOM_STATE,
    )

    shap_top_pdf = shap_top_df_spark.toPandas()
    shap_path = f"{OUTPUT_DIR}/final_synapseml_shap_top_features.csv"
    shap_top_pdf.to_csv(shap_path, index=False)

    print("Saved:", shap_path)
    display(shap_top_pdf)
else:
    shap_top_pdf = pd.DataFrame(columns=["feature_index", "mean_abs_shap", "feature"])
    print("Final SHAP skipped. Set RUN_FINAL_SHAP=True to compute SynapseML featuresShap.")

In [ ]:
if len(shap_top_pdf) > 0:
    plot_df = shap_top_pdf.sort_values("mean_abs_shap")

    plt.figure(figsize=(8, 6))
    plt.barh(plot_df["feature"], plot_df["mean_abs_shap"])
    plt.xlabel("Mean absolute SHAP value")
    plt.ylabel("Feature")
    plt.title("Top SynapseML SHAP Features")
    plt.show()
else:
    print("No SHAP plot because SHAP was skipped or unavailable.")

## 21. Optional: Synthetic anomaly experiment

Phần này chỉ chạy khi `RUN_SYNTHETIC_EXPERIMENTS=True`. Mục tiêu là kiểm tra detector có nhạy hơn khi ta cố tình inject anomaly vào target batch hay không.

In [ ]:
ANOMALY_LEVELS = [0.0, 0.05, 0.10, 0.20, 0.30, 0.50, 0.75]
ANOMALY_RANDOM_STATE = 2025


def inject_synthetic_anomalies_spark(target_df, anomaly_fraction=0.30, random_state=42):
    """
    Inject anomaly đơn giản vào một phần target rows.

    Đây chỉ là synthetic test, không dùng để clean dữ liệu thật.
    """
    data = (
        target_df
        .withColumn("_r_anom", F.rand(int(random_state)))
        .withColumn("synthetic_anomaly", (F.col("_r_anom") < float(anomaly_fraction)).cast("int"))
        .withColumn("_anom_group", (F.rand(int(random_state) + 1) * 5).cast("int"))
    )

    is_anom = F.col("synthetic_anomaly") == 1

    if "trip_distance" in data.columns:
        data = data.withColumn(
            "trip_distance",
            F.when(is_anom & (F.col("_anom_group") == 0), F.col("trip_distance") * F.lit(5.0))
             .otherwise(F.col("trip_distance"))
        )

    if "total_amount" in data.columns:
        data = data.withColumn(
            "total_amount",
            F.when(is_anom & (F.col("_anom_group") == 1), F.col("total_amount") * F.lit(4.0))
             .otherwise(F.col("total_amount"))
        )

    if "fare_amount" in data.columns:
        data = data.withColumn(
            "fare_amount",
            F.when(is_anom & (F.col("_anom_group") == 2), F.col("fare_amount") * F.lit(4.0))
             .otherwise(F.col("fare_amount"))
        )

    if "store_and_fwd_flag" in data.columns:
        data = data.withColumn(
            "store_and_fwd_flag",
            F.when(is_anom & (F.col("_anom_group") == 3), F.lit("ANOM"))
             .otherwise(F.col("store_and_fwd_flag"))
        )

    for loc_col in ["pulocationid", "dolocationid"]:
        if loc_col in data.columns:
            data = data.withColumn(
                loc_col,
                F.when(is_anom & (F.col("_anom_group") == 4), F.lit(999))
                 .otherwise(F.col(loc_col))
            )

    return data.drop("_r_anom", "_anom_group")


def train_synapseml_on_work_df(batch_work_df, synapseml_params, random_state=42, shap_col=None, return_artifacts=False):
    """
    Train/evaluate trọn gói trên một work_df bất kỳ.

    Dùng cho:
    - Synthetic experiments.
    - Batch monitoring loop.
    """
    local_split_df = None
    local_lgbm_train_df = None
    local_train_features_df = None
    local_valid_features_df = None
    local_test_features_df = None
    local_test_pred_df = None

    try:
        local_train_raw_df, local_valid_raw_df, local_test_raw_df, local_split_df = stratified_split_sklearn_like_spark(
            input_df=batch_work_df,
            label_col="label",
            test_size=TEST_SIZE,
            valid_size=VALID_SIZE,
            seed=random_state,
            cache_result=True,
            return_split_df=True,
        )

        local_pipeline = SparkTaxiFeaturePipeline(
            categorical_cols=CATEGORICAL_COLS,
            numeric_cols=NUMERIC_COLS,
            exclude_cols=EXCLUDE_COLS,
            label_col="label",
        ).fit(local_train_raw_df)

        local_train_features_df = local_pipeline.transform(local_train_raw_df).select("features", "label").persist(StorageLevel.MEMORY_AND_DISK)
        local_valid_features_df = local_pipeline.transform(local_valid_raw_df).select("features", "label").persist(StorageLevel.MEMORY_AND_DISK)
        local_test_features_df = local_pipeline.transform(local_test_raw_df).select("features", "label").persist(StorageLevel.MEMORY_AND_DISK)

        local_train_features_df.count()
        local_valid_features_df.count()
        local_test_features_df.count()

        local_lgbm_train_df = build_lgbm_train_df(
            train_df=local_train_features_df,
            valid_df=local_valid_features_df,
            num_partitions=LGBM_NUM_PARTITIONS,
            persist=True,
        )

        estimator = build_synapseml_lgbm_classifier(
            synapseml_params=synapseml_params,
            categorical_slot_indexes=local_pipeline.categorical_slot_indexes_,
            shap_col=shap_col,
            validation_col="is_validation",
        )

        start = time.time()
        model = estimator.fit(local_lgbm_train_df)
        fit_seconds = time.time() - start

        valid_auc, _ = evaluate_auc(model, local_valid_features_df.select("features", "label"), return_predictions=False)
        test_auc, local_test_pred_df = evaluate_auc(
            model,
            local_test_features_df.select("features", "label"),
            return_predictions=return_artifacts,
            persist_predictions=return_artifacts,
        )

        result = {
            "valid_auc": float(valid_auc),
            "test_auc": float(test_auc),
            "best_iteration": safe_get_best_iteration(model),
            "fit_seconds": float(fit_seconds),
            "feature_count": len(local_pipeline.feature_cols_),
        }

        artifacts = None
        if return_artifacts:
            artifacts = {
                "model": model,
                "pipeline": local_pipeline,
                "test_pred_df": local_test_pred_df,
                "feature_cols": local_pipeline.feature_cols_,
            }

        return result, artifacts

    finally:
        if not return_artifacts:
            for obj in [
                local_test_pred_df,
                local_lgbm_train_df,
                local_train_features_df,
                local_valid_features_df,
                local_test_features_df,
                local_split_df,
            ]:
                try:
                    if obj is not None:
                        obj.unpersist()
                except Exception:
                    pass
        gc.collect()


if RUN_SYNTHETIC_EXPERIMENTS:
    synthetic_results = []

    for frac in ANOMALY_LEVELS:
        print("Running synthetic anomaly fraction:", frac)

        temp_positive = inject_synthetic_anomalies_spark(
            positive_df,
            anomaly_fraction=frac,
            random_state=ANOMALY_RANDOM_STATE,
        )

        temp_negative = negative_df.withColumn("synthetic_anomaly", F.lit(0))

        temp_work_df = (
            temp_positive
            .unionByName(temp_negative, allowMissingColumns=True)
            .repartition(SPARK_SQL_SHUFFLE_PARTITIONS)
            .persist(StorageLevel.MEMORY_AND_DISK)
        )
        temp_work_df.count()

        try:
            result, _ = train_synapseml_on_work_df(
                temp_work_df,
                synapseml_params=selected_synapseml_params,
                random_state=RANDOM_STATE,
                shap_col=None,
                return_artifacts=False,
            )

            result["anomaly_fraction"] = float(frac)
            result["n_rows"] = int(temp_work_df.count())
            result["n_synthetic_anomaly"] = int(temp_work_df.filter(F.col("synthetic_anomaly") == 1).count())
            synthetic_results.append(result)

            print(result)
        finally:
            temp_work_df.unpersist()

    synthetic_df = pd.DataFrame(synthetic_results)
    synthetic_path = f"{OUTPUT_DIR}/synthetic_anomaly_sweep.csv"
    synthetic_df.to_csv(synthetic_path, index=False)

    print("Saved:", synthetic_path)
    display(synthetic_df)
else:
    print("Synthetic experiments skipped. Set RUN_SYNTHETIC_EXPERIMENTS=True to run.")

## 22. Optional: Batch AUC monitoring

Phần này chạy nhiều target batches liên tiếp để tạo chuỗi AUC. Chỉ chạy khi `RUN_BATCH_MONITORING=True`.

In [ ]:
def build_dataset_for_target_batch_spark(
    source_df,
    target_processing_hour,
    min_rows_per_group=MIN_ROWS_PER_GROUP,
    max_rows_per_group=TARGET_SAMPLE_PER_GROUP,
    random_state=RANDOM_STATE,
):
    """Build work_df cho một target batch cụ thể."""
    positive = sample_by_processing_hour_spark(
        source_df=source_df,
        processing_hour=target_processing_hour,
        label=1,
        max_rows=max_rows_per_group,
        random_state=random_state,
        oversample_factor=OVERSAMPLE_FACTOR,
    )

    positive_rows = positive.count()
    if positive_rows < min_rows_per_group:
        return None, {
            "status": "skipped",
            "reason": "positive_rows_too_few",
            "target_processing_date_hour": str(target_processing_hour),
            "positive_rows": int(positive_rows),
        }

    comparison_hours = get_comparison_processing_hours(target_processing_hour)

    negative_parts = []
    negative_info = []

    for i, compare_hour in enumerate(comparison_hours):
        part = sample_by_processing_hour_spark(
            source_df=source_df,
            processing_hour=compare_hour,
            label=0,
            max_rows=max_rows_per_group,
            random_state=random_state + i + 100,
            oversample_factor=OVERSAMPLE_FACTOR,
        )

        rows = part.count()
        negative_info.append({"comparison_hour": str(compare_hour), "rows": int(rows)})

        if rows >= min_rows_per_group:
            negative_parts.append(part)

    if len(negative_parts) == 0:
        return None, {
            "status": "skipped",
            "reason": "negative_rows_too_few",
            "target_processing_date_hour": str(target_processing_hour),
            "positive_rows": int(positive_rows),
            "negative_info": negative_info,
        }

    negative = negative_parts[0]
    for p in negative_parts[1:]:
        negative = negative.unionByName(p, allowMissingColumns=True)

    work = positive.unionByName(negative, allowMissingColumns=True)
    work = work.repartition(SPARK_SQL_SHUFFLE_PARTITIONS).persist(StorageLevel.MEMORY_AND_DISK)
    work.count()

    label_counts = {
        float(r["label"]): int(r["count"])
        for r in work.groupBy("label").count().collect()
    }

    meta = {
        "status": "ok",
        "target_processing_date_hour": str(target_processing_hour),
        "positive_rows": int(label_counts.get(1.0, 0)),
        "negative_rows": int(label_counts.get(0.0, 0)),
        "total_rows": int(sum(label_counts.values())),
        "comparison_hours": [str(h) for h in comparison_hours],
        "negative_info": negative_info,
    }

    return work, meta

In [ ]:
if RUN_BATCH_MONITORING:
    target_batch_list = pd.date_range(start=BATCH_START, end=BATCH_END, freq=BATCH_FREQ).tolist()

    print("Number of target batches:", len(target_batch_list))
    print("First target batch:", target_batch_list[0])
    print("Last target batch :", target_batch_list[-1])

    batch_auc_results = []

    for i, batch_hour in enumerate(target_batch_list):
        print("\n" + "=" * 80)
        print(f"[{i+1}/{len(target_batch_list)}] Target batch: {batch_hour}")

        batch_df = None
        artifacts = None

        try:
            batch_df, meta = build_dataset_for_target_batch_spark(
                source_df=df_raw,
                target_processing_hour=batch_hour,
                random_state=RANDOM_STATE + i,
            )

            if meta.get("status") != "ok":
                print("Skipped:", meta)
                batch_auc_results.append(meta)
                continue

            need_shap = bool(RUN_BATCH_SHAP)
            result, artifacts = train_synapseml_on_work_df(
                batch_df,
                synapseml_params=selected_synapseml_params,
                random_state=RANDOM_STATE + i,
                shap_col=("featuresShap" if need_shap else None),
                return_artifacts=need_shap,
            )

            row = {**meta, **result}
            batch_auc_results.append(row)
            print("Result:", row)

            # Optional SHAP per batch nếu cần.
            if need_shap and artifacts is not None:
                shap_top_df_spark, _ = compute_top_shap_from_predictions(
                    artifacts["test_pred_df"],
                    feature_cols=artifacts["feature_cols"],
                    shap_col="featuresShap",
                    top_n=10,
                    sample_size=1000,
                    seed=RANDOM_STATE + i,
                )
                shap_top_pdf = shap_top_df_spark.toPandas()
                shap_top_pdf["target_processing_date_hour"] = str(batch_hour)
                display(shap_top_pdf)

        except Exception as e:
            print("Failed:", repr(e))
            batch_auc_results.append({
                "status": "failed",
                "target_processing_date_hour": str(batch_hour),
                "reason": repr(e),
            })

        finally:
            try:
                if batch_df is not None:
                    batch_df.unpersist()
            except Exception:
                pass
            gc.collect()

    auc_series_df = pd.DataFrame(batch_auc_results)
    auc_series_path = f"{OUTPUT_DIR}/batch_auc_series.csv"
    auc_series_df.to_csv(auc_series_path, index=False)

    print("Saved:", auc_series_path)
    display(auc_series_df)
else:
    auc_series_df = pd.DataFrame()
    print("Batch monitoring skipped. Set RUN_BATCH_MONITORING=True to run.")

## 23. Empirical p-value for AUC monitoring

Nếu đã có chuỗi AUC theo batch, ta dùng empirical p-value để xem AUC hiện tại có thuộc vùng cao bất thường so với lịch sử trước đó hay không.

In [ ]:
def add_empirical_auc_anomaly_score(
    auc_df,
    auc_col="test_auc",
    time_col="target_processing_date_hour",
    min_history_points=20,
    rolling_window=None,
    alpha=0.05,
):
    """
    Tính empirical p-value theo lịch sử trước thời điểm hiện tại.

    Công thức:
    p_value = (số AUC lịch sử >= AUC hiện tại + 1) / (số điểm lịch sử + 1)

    Nếu p_value <= alpha, AUC hiện tại nằm ở vùng cao bất thường so với lịch sử.
    """
    data = auc_df.copy()

    if data.empty or auc_col not in data.columns:
        return data

    data = data.sort_values(time_col).reset_index(drop=True)

    p_values = []
    percentile_ranks = []
    history_means = []
    history_medians = []
    history_qs = []
    history_sizes = []
    anomaly_flags = []
    anomaly_reasons = []

    for i, row in data.iterrows():
        current_auc = row.get(auc_col, np.nan)
        history = data.loc[:i-1, auc_col].dropna()

        if rolling_window is not None:
            history = history.tail(int(rolling_window))

        history_size = len(history)
        history_sizes.append(history_size)

        if history_size < min_history_points or pd.isna(current_auc):
            p_values.append(np.nan)
            percentile_ranks.append(np.nan)
            history_means.append(np.nan)
            history_medians.append(np.nan)
            history_qs.append(np.nan)
            anomaly_flags.append(False)
            anomaly_reasons.append("warmup_not_enough_history")
            continue

        p_value = (np.sum(history >= current_auc) + 1) / (history_size + 1)
        percentile_rank = (np.sum(history <= current_auc) + 1) / (history_size + 1)

        history_mean = history.mean()
        history_median = history.median()
        history_q = history.quantile(1 - alpha)

        is_anomaly = p_value <= alpha

        p_values.append(float(p_value))
        percentile_ranks.append(float(percentile_rank))
        history_means.append(float(history_mean))
        history_medians.append(float(history_median))
        history_qs.append(float(history_q))
        anomaly_flags.append(bool(is_anomaly))

        if is_anomaly:
            anomaly_reasons.append(f"auc_is_in_top_{int(alpha * 100)}pct_tail_of_history")
        else:
            anomaly_reasons.append("normal_vs_history")

    q_col = f"history_auc_q{int((1-alpha)*100)}"
    data["history_size"] = history_sizes
    data["history_auc_mean"] = history_means
    data["history_auc_median"] = history_medians
    data[q_col] = history_qs
    data["auc_empirical_p_value"] = p_values
    data["auc_percentile_rank"] = percentile_ranks
    data["is_auc_anomaly"] = anomaly_flags
    data["auc_anomaly_reason"] = anomaly_reasons

    return data


if len(auc_series_df) > 0:
    auc_monitoring_df = add_empirical_auc_anomaly_score(
        auc_series_df,
        auc_col="test_auc",
        time_col="target_processing_date_hour",
        min_history_points=MIN_HISTORY_POINTS,
        rolling_window=ROLLING_WINDOW,
        alpha=ALPHA,
    )

    auc_monitoring_path = f"{OUTPUT_DIR}/batch_auc_empirical_pvalue_monitoring.csv"
    auc_monitoring_df.to_csv(auc_monitoring_path, index=False)

    print("Saved:", auc_monitoring_path)
    display(auc_monitoring_df)
else:
    print("No AUC series available. Run batch monitoring first.")

In [ ]:
if "auc_monitoring_df" in globals() and len(auc_monitoring_df) > 0:
    plot_df = auc_monitoring_df.copy()
    plot_df["target_processing_date_hour"] = pd.to_datetime(plot_df["target_processing_date_hour"])
    plot_df = plot_df.sort_values("target_processing_date_hour")

    plt.figure(figsize=(12, 5))
    plt.plot(plot_df["target_processing_date_hour"], plot_df["test_auc"], marker="o", label="test_auc")

    q_col = f"history_auc_q{int((1-ALPHA)*100)}"
    if q_col in plot_df.columns:
        plt.plot(plot_df["target_processing_date_hour"], plot_df[q_col], linestyle="--", label=q_col)

    if "is_auc_anomaly" in plot_df.columns:
        anomalies = plot_df[plot_df["is_auc_anomaly"] == True]
        if len(anomalies) > 0:
            plt.scatter(anomalies["target_processing_date_hour"], anomalies["test_auc"], s=80, label="anomaly")

    plt.xlabel("target_processing_date_hour")
    plt.ylabel("AUC")
    plt.title("Batch AUC Monitoring")
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
else:
    print("No AUC monitoring plot.")

## 24. Cleanup

Chạy cell này sau khi đã lưu xong kết quả để giải phóng cache Spark.

In [ ]:
# Chỉ cleanup khi bạn đã hoàn tất train/evaluate/monitoring.
for obj_name in [
    "final_test_pred_df",
    "lgbm_train_df",
    "train_features_df",
    "valid_features_df",
    "test_features_df",
    "main_split_df",
    "work_df",
    "df_raw",
]:
    try:
        obj = globals().get(obj_name)
        if obj is not None:
            obj.unpersist()
            print("Unpersisted:", obj_name)
    except Exception as e:
        print("Skip cleanup for", obj_name, ":", repr(e))

gc.collect()
print("Cleanup completed.")